import * as v from 'valibot';
/** Only completed events are included in this explicitly labelled preview deck. */
export const SpiritEventKeySchema = v.picklist(['NEW_SPECIES', 'LITTLE_RAIN', 'SEEKING_INTERIOR', 'RECONNAISSANCE', 'DISCOVERIES', 'STRANGE_TALES', 'TIGHT_KNIT', 'WELL_PREPARED', 'ROOTS', 'NEW_LANDS', 'SURGE_INLAND', 'POPULATION', 'URBAN_DEVELOPMENT', 'HEAVY_FARMING', 'CULTURAL_ASSIMILATION', 'DISTANT_EXPLORATION', 'MISSIONARIES', 'RISING_INTEREST', 'FARMERS', 'FARMLAND', 'INVESTIGATION', 'OUTPACED', 'MADNESS']);
export type SpiritEventKey = v.InferOutput<typeof SpiritEventKeySchema>;
export const SPIRIT_EVENTS = {
 NEW_SPECIES: { type:'CHOICE', title: '새로운 종의 확산', name: 'New Species Spread', artwork: 'KEEPER', element: 'MOON', free: '외래종의 번성을 지켜본다', paid: '위험한 종을 변화시킨다', main: '무료: 보드마다 보조 덱 맨 위 카드를 버립니다. 빠른 능력이면 건물이 있는 지역에 오염 1개를 추가합니다. 해결 후 이 이벤트를 덱 위에서 세 번째에 돌려놓습니다. 지원: 인원당 비용 4, 달 원소 지원. 인원당 공포 1, 보드마다 건물이 있는 지역에 야수 1개를 추가합니다.', token: '새 질병 · 보드 절반(올림)을 골라, 침략자와 다한이 함께 있는 지역에 질병 1개와 다한 피해 2를 줍니다.', dahan: '춤과 무늬의 공물 · 자기 현신이 있는 지역들에 다한이 합계 2개 이상인 정령은 에너지 1을 얻습니다.' },
 LITTLE_RAIN: { type:'CHOICE', title: '비가 적은 해', name: 'Years of Little Rain', artwork: 'OCEAN', element: 'WATER', free: '가뭄을 감수한다', paid: '가뭄을 누그러뜨린다', main: '무료: 보드마다 보조 덱 맨 위 카드를 버립니다. 물 원소가 없으면 모래 지역에 오염 1개를 추가합니다. 이번 라운드 마을·도시·다한의 체력이 1 감소합니다(최소 1). 지원: 인원당 비용 4, 물 원소 지원. 각 정령은 자기 현신과 다한이 있는 지역에 현신 1개를 추가할 수 있습니다.', token: '야수의 공격 · 야수마다 차례로 침략자에게 피해 2. 마을이나 도시를 파괴한 야수만 제거합니다.', dahan: '노련한 방어 · 이번 라운드 파괴 행동에서 다한마다 방어 1을 제공합니다.' },
 SEEKING_INTERIOR: { type:'STAGE', title:'내륙을 향한 발걸음', name:'Seeking the Interior / Local Diaspora', artwork:'RIVER', element:null, free:null, paid:null, early:'내륙을 찾아서', late:'인근으로 흩어지다', main:'침략 I: 각 해안 지역에서 탐험가 1개를 인접한 내륙으로 밉니다. 침략 II·III: 섬 전체에서 침략자가 가장 많은 한 지역을 골라, 각 인접 지역으로 탐험가 또는 마을 1개씩 밉니다.', token:'야수의 배회 · 야수마다 침략자가 있는 지역이면 공포 1. 없다면 인접 지역으로 이동합니다.', dahan:'메마른 땅을 떠나다 · 보드마다 오염된 한 지역의 다한 2개를 오염 없는 인접한 한 지역으로 밉니다. 2개가 불가능하면 가능한 1개를 옮깁니다.' },
 RECONNAISSANCE: { type:'STAGE', title:'밀려오는 정찰대', name:'Wave of Reconnaissance / Urbanization', artwork:'LIGHTNING', element:null, free:null, paid:null, early:'정찰의 물결', late:'도시화', main:'침략 I: 이번 라운드 탐험에 성공한 지역마다 탐험가 1개를 더 추가합니다. 침략 II·III: 마을이 2개 이상인 각 지역에서 마을 절반(올림)을 도시로 교체합니다.', token:'병든 침략자 · 이번 라운드 질병 또는 분쟁이 있는 지역에서는 파괴 행동을 생략합니다. 질병·분쟁은 이 생략으로 소모되지 않습니다.', dahan:'후퇴 · 보드마다 도시가 있는 한 지역의 다한 2개를 도시 없는 인접한 한 지역으로 밉니다. 2개가 불가능하면 가능한 1개를 옮깁니다.' },
 DISCOVERIES: { type:'STAGE', title:'흥미로운 발견', name:'Interesting Discoveries / Increasing Aggression', artwork:'KEEPER', element:null, free:null, paid:null, early:'흥미로운 발견', late:'거세지는 침략', main:'침략 I: 보드마다 성소 하나를 골라 탐험가 1개를 모으고 탐험가 1개를 추가합니다. 침략 II·III: 이번 라운드 파괴 행동에서 침략자 피해가 지역마다 1 증가합니다.', token:'폐 질환의 확산 · 보드마다 밀림·습지 중 마을과 도시 합계가 가장 많은 지역에 질병 1개를 놓습니다. 건물이 적어도 1개 있어야 합니다.', dahan:'땅을 돌보다 · 보드마다 다한이 2개 이상인 지역에서 오염 1개를 제거합니다.' },
 STRANGE_TALES: { type:'STAGE', title:'낯선 섬의 소문', name:'Strange Tales Attract Explorers / Fortification', artwork:'SHADOW', element:null, free:null, paid:null, early:'소문을 따라오는 탐험가', late:'요새화', main:'침략 I: 성소가 있는 정령마다 공포 1. 침략 카드를 전진시킨 뒤 성소가 있는 각 지역에 탐험가 1개를 추가합니다. 침략 II·III: 침략 카드를 전진시킨 뒤 침략자 행동 칸에 표시되지 않은 지형 하나에서 정상 건설을 진행합니다. 가능한 지형이 없으면 생략합니다.', token:'야수의 공격 · 야수마다 차례로 침략자에게 피해 2. 마을이나 도시를 파괴한 야수만 제거합니다.', dahan:'성장하는 다한 · 보드마다 다한이 있는 산 또는 모래 지역에 다한 1개를 추가합니다.' },
 TIGHT_KNIT: { type:'ISLAND', title:'단단히 뭉친 공동체', name:'Tight-Knit Communities / Blight Spreads', artwork:'KEEPER', healthy:'단단히 뭉친 공동체', blighted:'퍼져가는 오염', main:'건강한 섬: 이번 라운드 마을·도시 체력 +1. 오염된 섬: 보드마다 오염 지역에 인접한 지역에 오염 1개를 추가합니다. 해당 보드의 현신 합계 2개를 파괴하여 그 보드를 보호할 수 있습니다.', token:'방심한 탐험가를 사냥하다 · 야수마다 같은 지역의 탐험가 1개를 파괴합니다. 이후 야수가 없는 보드 하나에 야수 1개를 추가합니다.', dahan:'성장하는 다한 · 보드마다 다한이 있는 해안 지역에 다한 1개를 추가합니다.' },
 WELL_PREPARED: { type:'ISLAND', title:'철저히 준비한 탐험가', name:'Well-Prepared Explorers / Blight Spreads', artwork:'RIVER', healthy:'철저히 준비한 탐험가', blighted:'퍼져가는 오염', main:'건강한 섬: 이번 라운드 탐험가 체력 +1. 오염된 섬: 보드마다 오염 지역에 인접한 지역에 오염 1개를 추가합니다. 해당 보드의 현신 합계 2개를 파괴하여 그 보드를 보호할 수 있습니다.', token:'야수의 배회 · 야수마다 침략자가 있는 지역이면 공포 1. 없다면 인접 지역으로 이동합니다.', dahan:'성장하는 다한 · 보드마다 다한이 있는 내륙 지역에 다한 1개를 추가합니다.' },
 ROOTS: {type:'ISLAND',title:'내륙에 뿌리내리다',name:'Putting Down Roots / The Center Crumbles',artwork:'KEEPER',healthy:'내륙에 뿌리내리다',blighted:'무너지는 중심',main:'건강한 섬: 보드마다 내륙의 탐험가 1개를 마을로 교체합니다. 오염된 섬: 침략자가 있는 보드마다 내륙에 오염 1개를 추가합니다. 해당 보드의 현신 3개를 파괴해 막을 수 있습니다.',token:'병든 침략자 · 이번 라운드 질병 또는 분쟁이 있는 지역에서는 파괴를 생략합니다.',dahan:'침입자를 몰아내다 · 각 정령은 다한이 있는 지역에서 탐험가 또는 마을 1개를 인접 지역으로 밀 수 있습니다.'},
 NEW_LANDS: {type:'ISLAND',title:'새 땅을 찾아서',name:'Search for New Lands / Devastated Shores',artwork:'RIVER',healthy:'새 땅을 찾아서',blighted:'황폐해진 해안',main:'건강한 섬: 탐험가가 2개 이상인 지역마다 탐험가 1개를 침략자 없는 인접 지역으로 밉니다. 오염된 섬: 침략자가 있는 보드마다 해안에 오염 1개를 추가합니다. 해당 보드의 현신 2개를 파괴해 막을 수 있습니다.',token:'먼 곳의 사냥 · 보드마다 야수 1개를 오염 없는 인접 지역으로 밀고 그곳에 침략자 피해 1을 줍니다.',dahan:'노련한 방어 · 이번 라운드 파괴 시 다한마다 방어 1을 제공합니다.'},
 SURGE_INLAND: {type:'ISLAND',title:'내륙으로 밀려드는 침략자',name:'Invaders Surge Inland / Widening Destruction',artwork:'SHADOW',healthy:'내륙으로 밀려드는 침략자',blighted:'넓어지는 파괴',main:'건강한 섬: 보드마다 해안의 마을 1개를 한 번 또는 두 번 이동합니다. 매번 해안에서 더 멀어지는 인접 지역으로 이동하며 중간 지역에도 실제로 들어갑니다. 오염된 섬: 보드마다 마을·도시가 있거나 그에 인접한 지역에 오염 1개를 추가합니다. 해당 보드의 현신 2개를 파괴해 막을 수 있습니다.',token:'질병의 대가 · 보드마다 질병 지역 하나에서 침략자와 다한에게 각각 피해 2를 줍니다.',dahan:'노련한 방어 · 이번 라운드 파괴 시 다한마다 방어 1을 제공합니다.'},
 POPULATION: {type:'ISLAND',title:'늘어나는 인구',name:'Population Rises / Power Fades',artwork:'KEEPER',healthy:'늘어나는 인구',blighted:'희미해지는 힘',main:'건강한 섬: 보드마다 탐험가 또는 마을이 있는 지역에 마을 1개를 추가합니다. 오염된 섬: 각 정령은 자기 현신 2개 파괴, 능력 2장 망각, 오염 카드의 오염 1개를 게임에서 제거 중 하나를 선택합니다.',token:'모래 열병 · 보드마다 산·모래 중 건물 수가 가장 많은 지역에 질병 1개를 놓습니다. 건물이 적어도 1개 있어야 합니다.',dahan:'춤과 무늬의 공물 · 자기 현신 지역들에 다한이 합계 2개 이상인 정령은 에너지 1을 얻습니다.'},
 URBAN_DEVELOPMENT: {type:'ISLAND',title:'도시 개발',name:'Urban Development / Festering Pits of Blight',artwork:'SHADOW',healthy:'도시 개발',blighted:'곪아가는 오염 지대',main:'건강한 섬: 다음 정상 파괴에서 도시마다 피해 +2. 파괴 카드가 비어 있으면 효과가 대기합니다. 오염된 섬: 침략자가 있는 보드마다 오염이 2개 이상인 지역에 오염 1개를 추가합니다. 연쇄는 발생하지 않지만 현신은 파괴됩니다.',token:'오래 남는 역병 · 보드마다 질병 1개를 추가합니다. 이번 침략자 단계에는 질병이 건설을 막지 않으며 소모되지 않습니다.',dahan:'위압적인 기세 · 침략자가 있고 다한 수가 마을·도시 합계보다 많은 지역마다 공포 1을 생성합니다.'},
 HEAVY_FARMING: {type:'ISLAND',title:'집약적 농업',name:'Heavy Farming / Overcrowded Cities',artwork:'KEEPER',healthy:'집약적 농업',blighted:'과밀한 도시',main:'건강한 섬: 다음 정상 파괴에서 마을마다 피해 +1. 파괴 카드가 비어 있으면 효과가 대기합니다. 오염된 섬: 도시가 있는 보드마다 도시 지역에 오염 1개를 추가합니다. 해당 보드의 현신 2개를 파괴해 막을 수 있습니다.',token:'방심한 탐험가를 사냥하다 · 야수마다 같은 지역의 탐험가 1개를 파괴합니다. 이후 야수가 없는 보드 하나에 야수 1개를 추가합니다.',dahan:'성장하는 다한 · 보드마다 다한이 있는 밀림·습지 지역에 다한 1개를 추가합니다.'},
 CULTURAL_ASSIMILATION: {type:'TERROR',title:'문화적 동화',name:'Cultural Assimilation / Reprisal Against the Dahan',artwork:'EARTH',lateFrom:3,early:'문화적 동화',late:'다한을 향한 보복',main:'공포 I·II: 보드마다 다한이 정확히 1개이며 도시가 있거나 도시에 인접한 지역에서 다한을 마을로 교체합니다. 공포 III: 보드마다 다한과 마을·도시가 함께 있는 지역에서 다한에게 피해 3을 줍니다. 방어는 무시합니다.',token:'야수의 공격 · 야수마다 침략자에게 피해 2. 건물을 파괴한 야수만 제거합니다.',dahan:'무모한 공세 · 보드마다 다한과 건물이 각각 2개 이상인 지역을 고릅니다. 다한마다 건물 1개를 파괴한 뒤 오염 1개를 추가합니다.'},
 DISTANT_EXPLORATION: {type:'TERROR',title:'먼 곳의 탐험',name:'Distant Exploration / Fearful Mobs',artwork:'RIVER',lateFrom:2,early:'먼 곳의 탐험',late:'겁에 질린 군중',main:'공포 I: 이번 라운드 탐험은 마을·도시·바다에서 거리 2까지 가능합니다. 지형과 탐험 차단 조건은 유지합니다. 공포 II·III: 이번 라운드 파괴 시 침략자가 3개 이상인 지역마다 피해 +3.',token:'질병의 대가 · 보드마다 질병 지역 하나에서 침략자와 다한에게 각각 피해 2를 줍니다.',dahan:'위압적인 기세 · 침략자가 있고 다한 수가 마을·도시 합계보다 많은 지역마다 공포 1을 생성합니다.'},
 MISSIONARIES: {type:'CHOICE',title:'선교사의 도착',name:'Missionaries Arrive',artwork:'EARTH',element:'SUN',free:'다한과의 접촉을 지켜본다',paid:'낯선 이들의 말을 저주한다',main:'무료: 보드마다 보조 카드 1장을 버립니다. 태양 원소가 있으면 다한 지역의 탐험가 1개를 밀고, 없으면 다한 1개를 마을로 교체합니다. 해결 후 이 이벤트를 덱 위에서 세 번째에 반환합니다. 지원: 인원당 비용 4, 태양 원소 지원. 각 정령은 도시 지역에 질병 1개를 놓고 인원당 공포 2를 생성합니다. 다음 정상 파괴에서 도시마다 피해 +3.',token:'방심한 탐험가를 사냥하다 · 야수마다 탐험가 1개를 파괴합니다. 이후 야수 없는 보드 하나에 야수 1개를 추가합니다.',dahan:null},
 RISING_INTEREST: {type:'CHOICE',title:'섬에 쏠리는 관심',name:'Rising Interest in the Island',artwork:'SHADOW',element:'AIR',free:'호기심을 내버려 둔다',paid:'관찰자의 마음에 거짓을 심는다',main:'무료: 침략 덱 위의 일반 카드 1장을 게임에서 제거합니다. 준비 때 별도 배치한 카드는 건너뜁니다. 보드마다 마을 없는 지역에 마을 1개를 추가합니다. 지원: 인원당 비용 4, 바람 원소 지원. 공포 덱 위 카드 1장을 해결 없이 게임에서 제거하고, 다음 정상 파괴에서 마을·도시마다 피해 +1.',token:'밀림의 야수 · 보드마다 오염 없는 밀림에 야수 1개를 놓습니다. 침략자가 있으면 공포 1.',dahan:'덫과 올가미 · 보드마다 다한이 있는 지역에 야생 1개를 놓습니다.'},
 FARMERS: {type:'DECISION',title:'다한에게 도움을 청하는 농부들',name:'Farmers Seek the Dahan for Aid',artwork:'RIVER',main:'거절: 보드마다 다한·건물이 있는 지역의 다한에게 피해 2, 건물 2개 이상인 지역에 오염 1개. 이번 라운드 마을·도시 체력 −1(최소 1). 가르치기: 보드마다 다한 지역에 마을 1개를 놓습니다. 다음 정상 파괴를 건설로 바꾸며 파괴 카드가 비어 있으면 대기합니다. 두 선택 모두 에너지 비용은 없습니다.',token:'새 질병 · 서로 다른 보드 절반(올림)을 골라 침략자·다한이 함께 있는 지역에 질병 1개와 다한 피해 2를 줍니다.',dahan:null},
 FARMLAND: {type:'ISLAND',title:'비옥한 농경지',name:'Promising Farmland / New Cash Crops Take Hold',artwork:'KEEPER',healthy:'비옥한 농경지',blighted:'새 환금 작물의 정착',main:'건강: 이번 라운드 탐험 중 보드마다 한 번 탐험가 1개 대신 마을 1개를 놓습니다. 실제 탐험 지역 중에서 선택합니다. 오염: 침략자 행동 칸에 표시되지 않은 지형 하나에서 즉시 추가 파괴합니다. 각 보드의 현신 2개를 희생해 그 보드를 보호할 수 있습니다.',token:'자극받은 야수 · 보드마다 오염 없고 마을 있는 지역에 야수 1개를 놓습니다.',dahan:'영리한 방어 · 이번 라운드 다한마다 방어 1. 위의 추가 파괴를 끝낸 뒤 적용합니다.'},
 INVESTIGATION: {type:'TERROR',title:'위험 조사',name:'Investigation of Dangers / Destroy the Unnatural',artwork:'SHADOW',lateFrom:2,early:'위험 조사',late:'부자연스러운 것을 파괴하라',main:'공포 I: 보드마다 침략자·다한이 없는 지역에 탐험가 1개를 추가합니다. 공포 II·III: 이번 라운드 현신이 있는 지역에서 파괴 피해 +3.',token:'방심한 탐험가를 사냥하다 · 야수마다 탐험가 1개를 파괴한 뒤 야수 없는 보드 하나에 야수 1개를 추가합니다.',dahan:'정령을 깨우다 · 자기 현신 지역들의 다한 합계가 3개 이상인 정령은 느린 능력 하나를 지금 사용할 수 있습니다. 속도는 바뀌지 않으며 사용 기록과 반복 권한을 적용합니다.'},
 OUTPACED: {type:'PERSONAL',title:'뒤처진 정령들',name:'Outpaced',artwork:'LIGHTNING',main:'정령마다 사용 중인 느린 카드의 처리 순서를 고릅니다. 버리기: 인쇄 비용+1 에너지를 얻고 원소를 잃습니다. 유지하기: 자기 에너지 3 또는 자기 현신 2개를 지불합니다. 유지한 카드는 지금 사용하거나 느린 단계에 사용할 수 있습니다. 정령끼리 비용을 대신 낼 수 없습니다.',token:'오래 남는 역병 · 보드마다 질병 1개를 추가합니다. 이번 침략자 단계에는 질병이 건설을 막지 않고 소모되지 않습니다.',dahan:'대규모 습격 · 정령마다 서로 다른 지역을 고릅니다. 다한 수가 마을·도시 합계보다 많은 지역에서 다한마다 피해 1.'},
 MADNESS: {type:'CHOICE',title:'야수들 사이의 기이한 광기',name:'A Strange Madness Among the Beasts',artwork:'FANGS',element:'ANIMAL',free:'광기가 다할 때까지 내버려 둔다',paid:'광기를 이끈다',main:'무료: 야수마다 다한 1개를 파괴한 뒤 보드마다 야수 1개를 제거합니다. 지원: 제거할 야수를 고르고 남길 야수마다 비용 3(최소 3)을 동물 원소로 지원합니다. 확정 후 정령마다 야수 1개를 인접 지역으로 밀 수 있습니다. 같은 야수를 다시 밀어도 됩니다.',token:'사나운 광란 · 본문 해결 후 남은 야수마다 탐험가 1개를 파괴하고 침략자 피해 2를 줍니다. 건물을 파괴해도 야수는 소모하지 않습니다.',dahan:'더 안전한 보금자리 · 보드마다 야수·질병·야생이 있는 한 지역의 다한 2개를 그 세 토큰이 모두 없는 인접한 한 지역으로 밉니다. 2개가 불가능하면 가능한 1개를 옮깁니다.'},
} as const;
export const SPIRIT_EVENT_KEYS = SpiritEventKeySchema.options;
export const SPIRIT_EVENT_COUNT = SPIRIT_EVENT_KEYS.length;
