import { useState } from 'react';
import { spiritPower, SPIRIT_SCENARIOS, SPIRIT_SCENARIO_HELP, type SpiritAction, type SpiritProjection } from '@hangul-rummikub/shared';
const names=['빈 표식','불타는 비늘','청동 고리','물 떨어지는 이빨','얼어붙은 갈비뼈','빛나는 잉걸불','바람으로 엮은 밧줄','햇빛 기둥','가죽 주머니'];
const spiritBenefits=['','불 원소를 주는 피해 능력에 총 피해 +1','모래 사이에서 현신을 자유롭게 전환','카드를 회수하지 않은 정령 단계에 에너지 +2','다음 정상 파괴: 침략자 피해 −3 / 지역','주요 능력 획득 시 카드 망각 면제','모든 능력의 사거리 +1','공포 카드 2장 획득 · 한 지역의 다한당 피해 2','한 지역의 모든 기물·현신·오염·토큰 영구 제거'];
const invaderBenefits=['','불 원소 능력의 피해·파괴에 추가 에너지 1 필요','탐험·건설에서 모든 모래 지역의 침략자를 공유','습지 탐험 직후 추가 건설','다음 라운드 카드 준비 한도 1장','건물이 없던 밀림·습지에 건물이 추가되면 오염','침략자 밀기·모으기에 능력당 추가 에너지 1 필요','보드마다 최대 건물 지역의 다한·토큰 파괴 후 오염','발견 지역을 능력 대상으로 선택할 수 없음'];
export function ScenarioPanel({game:g,disabled,onAction}:{game:SpiritProjection;disabled:boolean;onAction(a:SpiritAction):void}){
 const [card,setCard]=useState(''),[at,setAt]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const me=g.playerStates.find(p=>p.playerId===g.privateState.playerId)!;
 if(!['WARD','FLAME','FORGOTTEN','SECOND_WAVE'].includes(g.settings.scenario)||g.stage==='SELECT')return null;
 const fire=[...me.hand,...me.played,...me.discard].filter(c=>spiritPower(c.key).elements.includes('FIRE'));
 const own=g.lands.filter(l=>l.presence.some(p=>p.playerId===me.playerId&&p.count>0));
 return <section className={`si-scenario-panel si-scenario-${g.settings.scenario.toLowerCase()}`} aria-label="시나리오 진행"><div><span className="si-eyebrow">SCENARIO</span><h2>{SPIRIT_SCENARIOS[g.settings.scenario]}</h2><p>{SPIRIT_SCENARIO_HELP[g.settings.scenario]}</p></div>
 {g.settings.scenario==='SECOND_WAVE'?<div className="si-scenario-markers"><strong>{g.waveNumber}번째 물결{g.waveWon?' · 방어 성공':''}</strong><p>{g.waveStageThree?'이전 정령의 능력을 정령 단계에 준비할 수 있습니다.':'침략 III단계에 진입하면 이전 정령의 능력을 준비할 수 있습니다.'}</p>{g.wavePowers.map(w=><article key={w.card.cardId}><p>{spiritPower(w.card.key).title} · {w.spirit}의 유산</p><button disabled={disabled||g.stage!=='PREPARE'||!g.waveStageThree||w.played||w.resolved||w.controller!==me.playerId||!!g.pending} onClick={()=>onAction({kind:'PLAY_LEGACY',cardId:w.card.cardId})}>{w.resolved?'사용 완료':w.played?'준비 완료':'무료로 준비 · 원소 없음'}</button></article>)}</div>:null}
 {g.settings.scenario==='WARD'?<div className="si-scenario-markers"><strong>◇ 수호 표식 {g.wards.length} / {4*g.playerStates.length}</strong><p>{g.wards.length?g.wards.join(' · '):'카드 준비에서 수호 능력으로 뒤집을 카드를 고르세요.'}</p><p>공포 II 이상 · 모든 해안의 수호 표식이 승리 조건입니다.</p></div>:null}
 {g.settings.scenario==='FLAME'?<><div className="si-scenario-markers"><strong>♨ 영구 불꽃 {g.flames.length}개</strong><p>{g.flames.join(' · ')||'아직 불꽃이 없습니다.'}</p></div>{g.stage==='PREPARE'?<fieldset disabled={disabled||!!g.pending||me.ready||!g.playerStates.every(p=>p.grown)}><legend>불꽃 의식 · 모든 정령의 성장 후</legend><label>망각할 불 원소 카드<select value={card} onChange={e=>setCard(e.target.value)}><option value="">카드 선택</option>{fire.map(c=><option key={c.cardId} value={c.cardId}>{spiritPower(c.key).title}</option>)}</select></label><label>내 현신이 있는 의식 지역<select value={at} onChange={e=>setAt(e.target.value)}><option value="">지역 선택</option>{own.map(l=><option key={l.id} value={l.id}>{l.id} · 오염 {l.blight} · 다한 {l.pieces.filter(p=>p.kind==='DAHAN').length}</option>)}</select></label><p>카드 영구 망각 · 오염 추가로 현신 파괴 및 연쇄가 발생할 수 있습니다.</p><button disabled={!fire.some(c=>c.cardId===card)||!own.some(l=>l.id===at)} onClick={()=>onAction({kind:'FLAME_RITUAL',cardId:card,landId:at})}>불꽃 의식 실행</button></fieldset>:null}</>:null}
 {g.settings.scenario==='FORGOTTEN'?<><div className="si-scenario-relics">{g.relics.map(r=><article key={`${r.land}-${r.number}`}><strong>{r.side==='HIDDEN'?'? 숨은 표식':names[r.number??0]}</strong>{r.number?<p>{r.side==='INVADER'?invaderBenefits[r.number]:spiritBenefits[r.number]}</p>:null}<span>{r.land} · {r.side==='HIDDEN'?'미탐색':r.side==='INVADER'?'침략자 발견':r.active?'정령 사용 중':'정령 발견 · 보류'}</span>{r.side==='SPIRIT'&&!r.active&&r.number?<button disabled={disabled} onClick={()=>{if(r.number)onAction({kind:'USE_RELIC',number:r.number});}}>효과 사용</button>:null}</article>)}</div>{g.relicIceRound===g.round?<p>얼어붙은 갈비뼈 · 이번 라운드는 카드 1장만 준비할 수 있습니다.</p>:null}{g.relicRavage?<p>다음 정상 파괴의 침략자 피해가 지역마다 3 줄어듭니다.</p>:null}{g.relics.some(r=>r.side==='SPIRIT'&&r.number===2&&r.active)?<fieldset disabled={disabled}><legend>청동 고리 · 모래 사이 현신 전환</legend><label>출발<select value={from} onChange={e=>setFrom(e.target.value)}><option value="">모래 선택</option>{own.filter(l=>l.terrain==='SANDS').map(l=><option key={l.id}>{l.id}</option>)}</select></label><label>도착<select value={to} onChange={e=>setTo(e.target.value)}><option value="">모래 선택</option>{g.lands.filter(l=>l.terrain==='SANDS'&&l.id!==from).map(l=><option key={l.id}>{l.id}</option>)}</select></label><button disabled={!from||!to||from===to} onClick={()=>onAction({kind:'SHIFT_SANDS',from,to})}>현신 1개 전환</button></fieldset>:null}</>:null}
 </section>;
}
