import {ArkNovaHousingChoices} from './ArkNovaHousingChoices.js';
import {ArkNovaConditionGuide} from './ArkNovaConditionGuide.js';
import {ArkNovaBreakTrack} from './ArkNovaBreakTrack.js';
import {ArkNovaActionGuide} from './ArkNovaActionGuide.js';
import {ArkNovaScoreBoard} from './ArkNovaScoreBoard.js';
import {ArkNovaHistory} from './ArkNovaHistory.js';
import {arkFeedback,type ArkFeedback} from './feedback.js';
import {ArkAnimalArt} from './animal-art.js';
import {arkCardName,arkZooIcons} from '@hangul-rummikub/shared';
import {useEffect,useRef,useState} from 'react';
import {ARK_UNIQUE_BUILDINGS,arkUniqueShape,ARK_ACTION_LABELS,ARK_BUILDINGS,arkCellKey,arkShape,type ArkCell,type ArkSoloView,type ArkSoloCommand} from '@hangul-rummikub/shared';
import {arkBuildOptionAdvice,arkMapBonusAdvice,arkFreeBuildPlacementHint,arkWazaSelectionAdvice,arkSponsorSelectionAdvice,arkAnimalSelectionAdvice,arkActionControls,arkBuildPlacementHint,arkDisplayedStrength,arkZooSelectionHint,arkReachableDisplayCards} from './action-controls.js';
import {ArkNovaResult} from './ArkNovaResult.js';
import {ArkNovaBoard} from './ArkNovaBoard.js';
import {ArkNovaCardRow,ArkNovaDisplay} from './ArkNovaCards.js';
import {ArkNovaEffects,arkEffectSummary} from './ArkNovaEffects.js';
import {ArkNovaAssociation} from './ArkNovaAssociation.js';
import {ArkNovaRewards} from './ArkNovaRewards.js';
import type {ArkCue} from './sound.js';

type Props={state:ArkSoloView;disabled:boolean;onCommand(command:ArkSoloCommand):void;onCue(cue:ArkCue):void;onRematch?():void};
const rotations=[0,1,2,3,4,5] as const;
/** The table emits intents; costs, legal targets and transitions stay authoritative on the server. */
export function ArkNovaTable({state:s,disabled,onCommand:send,onCue,onRematch}:Props) {
  const [associationOpen,setAssociationOpen]=useState(false);
  const associationPanel=useRef<HTMLDivElement>(null);
  const toggleAssociation=()=>setAssociationOpen(open=>!open);
  useEffect(()=>{if(associationOpen)associationPanel.current?.scrollIntoView({block:'start'});},[associationOpen]);
  const [chosen,setChosen]=useState<string[]>([]),[market,setMarket]=useState<string|null>(null),[x,setX]=useState(0);
  const [anchor,setAnchor]=useState<ArkCell|null>(null),[building,setBuilding]=useState('ENCLOSURE_1'),[rotation,setRotation]=useState<typeof rotations[number]>(0),[reflected,setReflected]=useState(false);
  const [effectUnique,setEffectUnique]=useState<string|null>(null);
  const [effectAnimal,setEffectAnimal]=useState<{revision:number;cardId:string}|null>(null);
  const buildPanel=useRef<HTMLElement>(null);
  const [buildMode,setBuildMode]=useState(false),[gainReputation,setGainReputation]=useState(true);
  useEffect(()=>{if(buildMode){buildPanel.current?.scrollIntoView({block:'start'});buildPanel.current?.focus({preventScroll:true});}},[buildMode]);
  useEffect(()=>{setChosen([]);setMarket(null);setAnchor(null);setX(0);setBuildMode(false);setEffectUnique(null);setEffectAnimal(null);},[s.revision]);
  const previous=useRef(s),[feedback,setFeedback]=useState<ArkFeedback|null>(null);
  useEffect(()=>{const event=arkFeedback(previous.current,s);previous.current=s;if(event){setFeedback(event);onCue(event.conservation?'CONSERVATION':event.animals.length?'ARRIVAL':'PLACE');}},[s,onCue]);
  useEffect(()=>{if(!feedback)return;const timer=setTimeout(()=>setFeedback(null),3000);return()=>clearTimeout(timer);},[feedback]);
  const pending=s.pending;
  const actionAvailable=!disabled&&s.phase==='PLAYING'&&s.progress.stage==='ACTION'&&!pending&&!s.activeBuild&&!s.associationWork&&!s.zooWork;
  const associationAvailable=actionAvailable&&arkActionControls(s,'ASSOCIATION').regular||!disabled&&s.phase==='PLAYING'&&!!s.associationWork?.upgraded&&!pending;
  const selectedBuilding=anchor?s.buildings.find(b=>b.cells.some(c=>arkCellKey(c)===arkCellKey(anchor))):undefined;
  const rotate=()=>{setRotation(r=>rotations[(r+1)%6]!);onCue('ROTATE');};
  const reflect=()=>{setReflected(f=>!f);onCue('ROTATE');};
  const placement=anchor?{building,anchor,rotation,reflected}:null;
  const placementHint=s.activeEffect?.kind==='FREE_BUILD'?arkFreeBuildPlacementHint(s,placement):placement&&(buildMode||s.activeBuild)?arkBuildPlacementHint(s,placement,x):null;
  const selectedCard=[...s.hand,...s.display.filter(c=>c!==null)].find(c=>c.cardId===(market??chosen[0]));
  const zooCanPlay=!!s.zooWork&&s.zooWork.stage==='PLAYING'&&s.zooWork.remaining>0&&(s.zooWork.action!=='SPONSORS'||s.zooWork.upgraded||s.zooWork.playedCount===0);
  const animalAdvice=zooCanPlay&&s.zooWork?.action==='ANIMALS'?arkAnimalSelectionAdvice(s,market??(chosen.length===1?chosen[0]!:null)):null;
  const effectAnimalAdvice=s.activeEffect?.kind==='WAZA_PLAY'&&effectAnimal?.revision===s.revision?arkWazaSelectionAdvice(s,effectAnimal.cardId,selectedBuilding?.id??null):null;
  const sponsorAdvice=zooCanPlay&&s.zooWork?.action==='SPONSORS'?arkSponsorSelectionAdvice(s,market??(chosen.length===1?chosen[0]!:null),anchor?{anchor,rotation}:null):null;
  const housingHint=animalAdvice&&!animalAdvice.issues.length&&!(selectedBuilding?animalAdvice.housingIds.includes(selectedBuilding.id):animalAdvice.flock)?'강조된 입주 가능한 우리를 선택하세요.':null;
  const zooHint=arkZooSelectionHint(s,market??(chosen.length===1?chosen[0]!:null));
  const uniqueKey=effectUnique??(zooCanPlay&&selectedCard&&Object.hasOwn(ARK_UNIQUE_BUILDINGS,selectedCard.key)?selectedCard.key:null);
  const select=(id:string)=>{setMarket(null);setChosen(ids=>ids.includes(id)?ids.filter(x=>x!==id):s.zooWork&&!pending?[id]:[...ids,id]);if(s.zooWork&&!pending)setAnchor(null);onCue('CARD');};
  return <div className="ark-live-table">
    <div className="ark-live-status" aria-label="내 동물원 자원"><span>돈 <b>{s.money}</b></span><span>매력 <b>{s.appeal}</b></span><span>보전 <b>{s.conservation}</b></span><span>평판 <b>{s.reputation}</b></span><span title="보유 대학과 사용한 카드의 연구 아이콘 합계. 카드 조건에 쓰이며 소모되지 않습니다.">연구 <b>{arkZooIcons(s.played,s.partners,s.universities).Science??0}</b>개</span><span>X <b>{s.x}</b></span><span>직원 <b>{s.workers-s.busyWorkers}/{s.workers}</b></span></div>
    <ArkNovaBreakTrack progress={s.progress}/>
    <ArkNovaScoreBoard state={s}/>
    <ArkNovaResult state={s} disabled={disabled} {...(onRematch?{onRematch}:{})}/>
    <ArkNovaHistory entries={s.history}/>
    <div className="ark-feedback-host" role="status" aria-live="polite" aria-atomic="true">{feedback&&<div key={feedback.revision} className={`ark-feedback ${feedback.conservation?'is-conservation':feedback.animals.length?'is-arrival':'is-construction'}`}>
      {feedback.animals[0]&&<ArkAnimalArt cardKey={feedback.animals[0]} eager/>}
      <div><strong>{feedback.conservation?'보전 성과 달성':feedback.animals.length?'새로운 동물이 도착했어요':'동물원이 자라납니다'}</strong>
      {feedback.built.length>0&&<p>시설 {feedback.built.length}개 건설 완료</p>}{feedback.animals.map(key=><p key={key}>{arkCardName(key)} 입주</p>)}{feedback.conservation>0&&<p>보전 +{feedback.conservation}</p>}</div>
    </div>}</div>
    {s.progress.stage==='SETUP'&&<section className="ark-live-setup-hand"><h2>시작 손패 선택 · 8장 중 4장</h2><ArkNovaCardRow cards={s.hand} selected={chosen} disabled={disabled} onSelect={select}/></section>}
    <div id="ark-zoo-placement-area" className="ark-live-layout"><ArkNovaBoard eligibleBonusCells={s.activeEffect?.kind==='ARCHAEOLOGIST'?arkMapBonusAdvice(s,anchor).available:[]} eligibleHousingIds={(s.activeEffect?.kind==='WAZA_PLAY'?effectAnimalAdvice:animalAdvice)?.housingIds??[]} feedback={feedback} invalid={placementHint!==null} buildings={s.buildings} selected={anchor} ghost={anchor&&uniqueKey?arkUniqueShape(uniqueKey,anchor,rotation):placement&&(buildMode||s.activeBuild||s.activeEffect?.kind==='FREE_BUILD')?arkShape(building,anchor!,rotation,reflected):[]} disabled={disabled||s.phase==='FINISHED'} onSelect={cell=>{setAnchor(cell);onCue('SELECT');}} onRotate={rotate} {...(uniqueKey?{}:{onReflect:reflect})} onCancel={()=>setAnchor(null)}/>
      <section id="ark-current-action" tabIndex={-1} className="ark-live-controls" aria-label="현재 행동">
        {s.progress.stage==='SETUP'&&<><h2>동물원의 첫 계획</h2><p>위 카드 8장 중 시작 손패로 남길 4장을 선택하세요.</p><button disabled={disabled||chosen.length!==4} onClick={()=>send({kind:'INITIAL_HAND',keep:chosen})}>선택한 {chosen.length}/4장으로 시작</button></>}
        {(pending?.kind==='BREAK_DISCARD'||pending?.kind==='DRAW_DISCARD')&&<><h2>{pending.kind==='BREAK_DISCARD'?'휴식 · 손패 정리':'카드 버리기'}</h2><p>버릴 카드 {pending.count}장을 선택하세요.</p><button disabled={disabled||chosen.length!==pending.count} onClick={()=>send({kind:'DISCARD',choiceId:pending.choiceId,cards:chosen})}>{chosen.length}/{pending.count}장 버리기</button></>}
        {pending?.kind==='FINAL_GOAL'&&<><h2>최종 목표 선택</h2><p>목표 카드 중 버릴 1장을 선택하세요.</p><ArkNovaCardRow cards={s.goals} selected={chosen} disabled={disabled} onSelect={id=>setChosen([id])}/><button disabled={disabled||chosen.length!==1} onClick={()=>send({kind:'FINAL_GOAL',choiceId:pending.choiceId,discard:chosen[0]!})}>선택한 목표 버리기</button></>}
        {pending?.kind==='DRAW_PICK'&&<><h2>카드 가져오기 · {pending.remaining}장 남음</h2><button disabled={disabled} onClick={()=>send({kind:'PICK_CARD',choiceId:pending.choiceId,cardId:null})}>덱에서 뽑기</button><button disabled={disabled||!arkReachableDisplayCards(s).some(c=>c.cardId===market)} onClick={()=>send({kind:'PICK_CARD',choiceId:pending.choiceId,cardId:market})}>선택한 공개 카드 가져오기</button></>}
        {actionAvailable&&!buildMode&&<>{s.extraAction&&!s.extraAction.started&&<p role="status">추가 행동: {s.extraAction.action==='TAKE_X'?'X 토큰 받기':ARK_ACTION_LABELS[s.extraAction.action]}</p>}{s.repeatedAction&&<p role="status">{ARK_ACTION_LABELS[s.repeatedAction.action]} 반복 · 남은 {s.repeatedAction.remaining}회 · 기본 행동력 {s.repeatedAction.baseStrength}</p>}<label>X 토큰 추가 <select value={x} onChange={e=>setX(Number(e.target.value))}>{Array.from({length:s.x+1},(_,i)=><option key={i} value={i}>{i}개</option>)}</select></label>
          <label><input type="checkbox" checked={gainReputation} onChange={e=>setGainReputation(e.target.checked)}/> 동물 II · 행동력 5 이상일 때 평판 받기</label><div className="ark-live-actions">{s.actions.map((a,i)=><div key={a.kind}><strong>{i+1} · {ARK_ACTION_LABELS[a.kind]} {a.upgraded?'II':'I'}</strong><ArkNovaActionGuide kind={a.kind} upgraded={a.upgraded} strength={arkDisplayedStrength(s,a.kind,x)}/>
            <fieldset className="ark-live-action-options" disabled={!arkActionControls(s,a.kind).regular}>{a.kind==='CARDS'?<><button onClick={()=>send({kind:'DRAW',x})}>카드 뽑기</button><button disabled={!market||arkDisplayedStrength(s,a.kind,x)<(a.upgraded?3:5)} onClick={()=>send({kind:'SNAP',x,cardId:market!})}>공개 카드 낚아채기</button></>:a.kind==='BUILD'?<button onClick={()=>{setAnchor(null);setBuilding('ENCLOSURE_1');setBuildMode(true);}}>건물 배치</button>:a.kind==='ANIMALS'||a.kind==='SPONSORS'?<><button disabled={a.kind==='ANIMALS'&&arkDisplayedStrength(s,a.kind,x)<2} onClick={()=>send({kind:'BEGIN_ZOO',action:a.kind==='ANIMALS'?'ANIMALS':'SPONSORS',x,gainReputation})}>{ARK_ACTION_LABELS[a.kind]} 카드 사용</button>{a.kind==='SPONSORS'&&<button onClick={()=>send({kind:'FUNDRAISE',x})}>모금</button>}</>:<button className="ark-association-link" aria-controls="ark-association-content" aria-expanded={associationOpen} onClick={toggleAssociation}>{associationOpen?'협회판 접기 ↑':'협회판에서 업무 선택 ↓'}</button>}</fieldset>
            <button disabled={!arkActionControls(s,a.kind).takeX||s.x>=5} onClick={()=>send({kind:'TAKE_X',action:a.kind})}>X 토큰 받기</button></div>)}</div></>}
        {(buildMode||s.activeBuild)&&!pending&&<section ref={buildPanel} tabIndex={-1} className="ark-build-panel" aria-label="건설 조작"><h2>건물 배치</h2><p>① 시설 선택 → ② 동물원 지도에서 칸 선택 → ③ 배치 확정</p><p>건설 행동력 {s.activeBuild?.remaining??arkDisplayedStrength(s,'BUILD',x)} · 보유 돈 {s.money} · 기본 비용 칸당 돈 2</p>{!s.activeBuild&&<button type="button" onClick={()=>{setBuildMode(false);setAnchor(null);}}>건설 취소 · 행동 선택으로</button>}<label>시설 <select value={building} disabled={disabled} onChange={e=>setBuilding(e.target.value)}>{Object.entries(ARK_BUILDINGS).map(([id,b])=>{const reason=arkBuildOptionAdvice(s,id,x);return <option key={id} value={id} disabled={reason!==null}>{b.name} · 돈 {b.shape.length*2}{reason?` — ${reason}`:''}</option>;})}</select></label><p role="status">{arkBuildOptionAdvice(s,building,x)??placementHint??'지도에서 기준 칸을 고르고 모양을 확인하세요.'}</p><button disabled={disabled} onClick={rotate}>회전 ↻</button><button disabled={disabled} onClick={reflect}>반전 ↔</button><button disabled={disabled||!placement||placementHint!==null||arkBuildOptionAdvice(s,building,x)!==null} onClick={()=>{if(placement)send(s.activeBuild?{kind:'BUILD_MORE',placement}:{kind:'BUILD',x,placement});}}>배치 확정</button><button type="button" onClick={()=>document.getElementById('ark-zoo-placement-area')?.scrollIntoView({block:'start'})}>동물원 지도에서 위치 선택 ↑</button>{s.activeBuild&&<button disabled={disabled} onClick={()=>send({kind:'END_BUILD'})}>건설 마치기</button>}</section>}
        {s.zooWork&&!pending&&<><h2>{ARK_ACTION_LABELS[s.zooWork.action]} 카드 사용</h2><p>{s.zooWork.action==='ANIMALS'?`남은 동물 ${s.zooWork.remaining}장`:`남은 후원 행동력 ${s.zooWork.remaining}`}</p>{zooCanPlay&&selectedCard&&<p className="ark-selected-card-name">선택한 카드: <b>{arkCardName(selectedCard.key)}</b></p>}{zooCanPlay&&<p>{s.zooWork.upgraded?'손패 또는 평판 범위 안의 공개 카드':'손패'} 1장을 선택하세요.{s.zooWork.action==='ANIMALS'?' 동물은 지도에서 입주할 우리를 고르세요.':''}</p>}{zooHint&&<p role="status">{zooHint}</p>}{animalAdvice&&<div className="ark-admission-guide" aria-label="동물 입주 조건"><strong>실제 비용 {animalAdvice.price} · 보유 {s.money}</strong><p>할인과 공개 카드 추가 비용을 반영했습니다.</p>{animalAdvice.issues.map(text=><p className="ark-admission-missing" key={text}>{text}</p>)}{animalAdvice.housingIds.length>0&&<p>지도에서 테두리가 강조된 우리 {animalAdvice.housingIds.length}개에 입주할 수 있습니다.</p>}{housingHint&&<p role="status">{housingHint}</p>}<ArkNovaHousingChoices buildings={s.buildings} eligibleIds={animalAdvice.housingIds} selected={anchor} disabled={disabled} onChoose={cell=>{setAnchor(cell);onCue('SELECT');}}/>{animalAdvice.flock&&<button disabled={disabled} onClick={()=>setAnchor(null)}>무리 생활 · 새 우리 없이 입주{anchor===null?' ✓':''}</button>}</div>}{sponsorAdvice&&<div className="ark-admission-guide" aria-label="후원자 사용 조건"><strong>지불할 돈 {sponsorAdvice.price} · 보유 {s.money}</strong>{sponsorAdvice.issues.map(text=><p className="ark-admission-missing" key={text}>{text}</p>)}</div>}{zooCanPlay&&<ArkNovaConditionGuide state={s} cardId={market??(chosen.length===1?chosen[0]!:null)}/>}{uniqueKey&&<><p>지도에서 고유 건물 위치를 선택하세요.</p><button disabled={disabled} onClick={rotate}>고유 건물 회전 ↻</button></>}{zooCanPlay&&s.zooWork.action==='ANIMALS'&&<p>선택한 우리: {selectedBuilding?ARK_BUILDINGS[selectedBuilding.kind]?.name??'특수 시설':'없음'}</p>}<button disabled={disabled||zooHint!==null||!!animalAdvice?.issues.length||!!sponsorAdvice?.issues.length||housingHint!==null||chosen.length+(market?1:0)!==1} onClick={()=>send({kind:'PLAY_ZOO',card:{cardId:market??chosen[0]!,housingId:s.zooWork?.action==='ANIMALS'?selectedBuilding?.id??null:null,...(uniqueKey&&anchor?{uniquePlacement:{anchor,rotation}}:{})}})}>카드 사용</button><button disabled={disabled} onClick={()=>send({kind:'END_ZOO'})}>카드 사용 마치기</button>{s.zooWork.playedCount===0&&s.zooWork.cancelX!=null?<><button disabled={disabled} onClick={()=>send({kind:'CANCEL_ZOO'})}>카드 사용 취소 · 행동 선택으로</button><p>턴을 소비하지 않고 돌아갑니다. 사용한 X 토큰 {s.zooWork.cancelX}개도 돌려받습니다.</p></>:<p>카드를 사용했거나 시작 보상·특수 행동이 진행되어 취소할 수 없습니다. ‘카드 사용 마치기’는 남은 카드 사용을 포기하고 행동을 마칩니다.</p>}</>}
        {s.associationWork&&!pending&&<><h2>협회 활동</h2><p>남은 행동력 {s.associationWork.remaining}</p><button aria-controls="ark-association-content" aria-expanded={associationOpen} onClick={toggleAssociation}>{associationOpen?'협회판 접기 ↑':'협회판에서 추가 업무·기부 선택 ↓'}</button><button disabled={disabled} onClick={()=>send({kind:'END_ASSOCIATION'})}>협회 활동 마치기</button></>}
        <ArkNovaRewards state={s} disabled={disabled} onCommand={send}/>
        {pending?.kind==='EFFECT'&&<section aria-label="효과 선택"><h2>카드 효과</h2>{s.effectOptions.map(e=><button key={e.id} disabled={disabled} onClick={()=>send({kind:'SELECT_EFFECT',choiceId:pending.choiceId,effectId:e.id})}>{arkEffectSummary(e.kind,e.guide)}</button>)}{s.activeEffect&&<ArkNovaEffects key={s.revision} state={s} disabled={disabled} onSelect={selection=>send({kind:'EFFECT',choiceId:pending.choiceId,effectId:s.activeEffect!.id,selection})} placement={placement} cell={anchor} housingId={selectedBuilding?.id??null} onAnimalCard={cardId=>{setEffectAnimal({revision:s.revision,cardId});setAnchor(null);onCue('CARD');}} onClearHousing={()=>setAnchor(null)} onChooseHousing={id=>setAnchor(s.buildings.find(b=>b.id===id)?.cells[0]??null)} selectedBuildingKind={building} onUniqueCard={setEffectUnique} onBuilding={setBuilding} onRotate={rotate} onReflect={reflect}/>}</section>}
        {s.repeatedAction&&actionAvailable&&<button onClick={()=>send({kind:'END_REPEAT'})}>반복 행동 마치기</button>}
        {s.extraAction&&!s.extraAction.started&&actionAvailable&&<button onClick={()=>send({kind:'CANCEL_EXTRA'})}>추가 행동 포기</button>}
      </section></div>
    {s.progress.stage!=='SETUP'&&<div id="ark-association-area" ref={associationPanel} className="ark-association-fold"><button className="ark-association-peek" aria-controls="ark-association-content" aria-expanded={associationOpen} onClick={toggleAssociation}><strong>협회판</strong><span>직원 {s.workers}명 · 제휴 {s.partners.length}곳 · 대학 {s.universities.length}곳</span><b>{associationOpen?'접기 ↑':'업무 선택 · 펼치기 ↓'}</b></button><div id="ark-association-content" hidden={!associationOpen}><ArkNovaAssociation state={s} x={x} disabled={!associationAvailable} onTask={task=>send(s.associationWork?{kind:'ASSOCIATION_MORE',task}:{kind:'ASSOCIATION',x,task})} onDonate={()=>send({kind:'DONATE'})}/></div></div>}
    <section><h2>공개 카드 <small>덱 {s.deckCount}장</small></h2><ArkNovaDisplay reputation={s.reputation} cardsUpgraded={s.actions.some(a=>a.kind==='CARDS'&&a.upgraded)} cards={s.display} selected={market} disabled={disabled||s.phase==='FINISHED'||s.progress.stage==='SETUP'||pending?.kind==='FINAL_GOAL'} onSelect={id=>{setChosen([]);setMarket(m=>m===id?null:id);if(s.zooWork&&!pending)setAnchor(null);onCue('CARD');}}/></section>
    {s.progress.stage!=='SETUP'&&<section><h2>내 손패 · {s.hand.length}장</h2><ArkNovaCardRow cards={s.hand} selected={chosen} disabled={disabled||s.phase==='FINISHED'||pending?.kind==='FINAL_GOAL'} onSelect={select}/></section>}
    <details><summary>내 동물과 후원자 · {s.played.length}장</summary><ArkNovaCardRow cards={s.played}/></details>
    <details><summary>최종 목표와 보전 프로젝트</summary><ArkNovaCardRow cards={[...s.goals,...s.baseProjects,...s.playedProjects]}/></details>
  </div>;
}
