import assert from 'node:assert/strict';
import test from 'node:test';
import * as v from 'valibot';
import {GameIdSchema,PlayerIdSchema,TileIdSchema,TurnIdSchema,ServerTimeSchema,ARNAK_CARDS,arnakResources,ArnakPlayingProjectionSchema,type ArnakOffer} from '@hangul-rummikub/shared';
import {createArnakGame,applyArnakAction,arnakOffers,parseArnakState,type ArnakState} from './games/arnak/domain/game.js';
import {projectArnak} from './games/arnak/compatibility/projector.js';
let serial=0;
function rng(seed:number){return {nextInt(max:number){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed%max;}};}
const now=v.parse(ServerTimeSchema,1000),random=rng(42);
function create(n=2,seed=42){return createArnakGame({generateTileId:()=>v.parse(TileIdSchema,'arnak-card-'+(++serial)),gameId:v.parse(GameIdSchema,'arnak-game'),playerIds:Array.from({length:n},(_,i)=>v.parse(PlayerIdSchema,'arnak-player-'+i)),now,turnId:v.parse(TurnIdSchema,'arnak-turn-0'),random:rng(seed)});}
function act(s:ArnakState,predicate:(o:ArnakOffer)=>boolean){const offer=arnakOffers(s,s.activePlayerId).find(predicate);assert.ok(offer,'Expected legal offer');const next=applyArnakAction(s,s.activePlayerId,{type:'TAKE',actionId:offer.id},now,v.parse(TurnIdSchema,'arnak-turn-'+(++serial)),random);assert.ok(next.ok);return next.state;}
function settle(s:ArnakState){for(let i=0;s.jobs.length&&i<100;i++)s=act(s,o=>o.kind==='EFFECT'||o.kind==='PASS');assert.equal(s.jobs.length,0);return s;}
function give(s:ArnakState,id:string){const p=s.players.find(p=>p.playerId===s.activePlayerId)!;for(const source of [s.itemDeck,s.artifactDeck,s.market]){const i=source.findIndex(c=>c.definitionId===id);if(i>=0){p.hand.push(...source.splice(i,1));p.handCount=p.hand.length;return;}}throw new Error('Card missing');}
test('Arnak base catalog and 2–4 player setup have conserved opaque cards, correct sites, blocking and private projection',()=>{
 assert.equal(ARNAK_CARDS.filter(c=>c.type==='item').length,40);assert.equal(ARNAK_CARDS.filter(c=>c.type==='artifact').length,35);
 for(const n of [2,3,4]){const s=create(n);assert.equal(s.sites.length,17);assert.equal(s.sites.reduce((a,b)=>a+b.blocked.filter(Boolean).length,0),n===2?5:n===3?3:0);assert.equal(s.market.length,6);assert.equal(s.inventory.length,94+n*4);for(const p of s.players){assert.equal(p.hand.length,5);assert.equal(p.deck.length,1);const g=projectArnak({gameId:s.gameId,gameRevision:s.revision,startedAt:s.startedAt,finishedAt:null,state:s},p.playerId);assert.ok(g);v.parse(ArnakPlayingProjectionSchema,g);const wire=JSON.stringify(g);for(const other of s.players.filter(o=>o!==p))for(const card of [...other.hand,...other.deck])assert.equal(wire.includes(JSON.stringify(card.tileId)),false);assert.equal(wire.includes(JSON.stringify(s.itemDeck[0]!.tileId)),false);}}
});
test('Arnak rejects forged offers and out-of-turn commands without mutations',()=>{const s=create(),before=structuredClone(s);assert.deepEqual(applyArnakAction(s,s.players[1]!.playerId,{type:'TAKE',actionId:'action-0'},now,s.transitionId,random),{ok:false,reason:'NOT_YOUR_TURN'});assert.equal(applyArnakAction(s,s.activePlayerId,{type:'TAKE',actionId:'forged'},now,s.transitionId,random).ok,false);assert.deepEqual(s,before);const corrupt=structuredClone(s);corrupt.players[0]!.hand.push(corrupt.players[0]!.hand[0]!);assert.throws(()=>parseArnakState(corrupt));});
test('Arnak free cards produce resources, digging spends a card and a worker, only one main action',()=>{let s=create();const p=s.players[0]!,card=p.hand.find(c=>c.definitionId.startsWith('funding'));assert.ok(card);s=act(s,o=>o.kind==='CARD'&&o.targetId===card.tileId);assert.equal(s.mainActionUsed,false);s=settle(s);assert.equal(s.players[0]!.resources.coin,3);const hand=s.players[0]!.hand.length;s=act(s,o=>o.kind==='DIG'&&o.targetId==='base-0'&&o.cards.length===1);s=settle(s);assert.equal(s.players[0]!.resources.coin,5);assert.equal(s.players[0]!.hand.length,hand-1);assert.equal(s.players[0]!.workers,1);assert.equal(arnakOffers(s,s.activePlayerId).some(o=>o.kind==='DIG'),false);s=act(s,o=>o.kind==='END');assert.notEqual(s.activePlayerId,p.playerId);});
test('Arnak pass card is an alternative, not a bonus on an already-used card',()=>{let s=create();give(s,'0108');s=act(s,o=>o.kind==='CARD'&&o.label.includes('패스 보상'));s=settle(s);assert.equal(s.stage,'CLEANUP');assert.equal(s.players[0]!.resources.coin,5);});
test('Arnak notebook cannot overtake magnifier and research obtains assistants',()=>{let s=create();s.players[0]!.resources=arnakResources({coin:20,compass:20,tablet:20,arrow:20,jewel:20});assert.equal(arnakOffers(s,s.activePlayerId).some(o=>o.label.startsWith('수첩')),false);s=act(s,o=>o.kind==='RESEARCH'&&o.targetId==='1L');s=settle(s);s.mainActionUsed=false;s=act(s,o=>o.label.startsWith('수첩')&&o.targetId==='1L');s=settle(s);assert.equal(s.players[0]!.assistants.length,1);});
test('Arnak each base card can be used and its pending selections resolve without corrupting inventory',()=>{for(const card of ARNAK_CARDS.filter(c=>c.type==='item'||c.type==='artifact')){let s=create();give(s,card.id);s.players[0]!.resources=arnakResources({coin:30,compass:30,tablet:30,arrow:30,jewel:30});const c=s.players[0]!.hand.find(c=>c.definitionId===card.id)!;s=act(s,o=>o.kind==='CARD'&&o.targetId===c.tileId);try{s=settle(s);parseArnakState(s);}catch(error){throw new Error(card.name+' '+String(error));}}});
test('Arnak seeded complete games terminate after five rounds and preserve every physical card',()=>{for(const n of [2,3,4])for(let seed=1;seed<=4;seed++){let s=create(n,seed);const r=rng(seed),types=new Set<string>();for(let steps=0;s.phase==='PLAYING'&&steps<1600;steps++){const all=arnakOffers(s,s.activePlayerId);assert.ok(all.length,'No deadlock');let candidates=all.filter(o=>s.jobs.length?o.kind==='EFFECT'||o.kind==='PASS':s.stage==='CLEANUP'?o.kind==='PASS':o.kind==='CARD'||o.kind==='DIG'||o.kind==='DISCOVER'||o.kind==='RESEARCH'||o.kind==='GUARDIAN'||o.kind==='BUY'||o.kind==='END');if(!candidates.length)candidates=all.filter(o=>o.kind==='PASS');const choice=candidates[r.nextInt(candidates.length)]!;types.add(choice.kind);s=act(s,o=>o.id===choice.id);}assert.equal(s.phase,'FINISHED');assert.equal(s.round,5);assert.equal(s.result?.scores.length,n);assert.ok(types.has('DIG'));}});
test('Arnak private peek choices never publish the selected hidden card in public history',()=>{let s=create();give(s,'0214');s.players[0]!.resources.tablet=1;const source=s.players[0]!.hand.find(c=>c.definitionId==='0214')!;s=act(s,o=>o.kind==='CARD'&&o.targetId===source.tileId);s=act(s,o=>o.kind==='EFFECT'&&o.label==='카드 1장 확인');assert.equal(s.peek.length,1);const hidden=s.peek[0]!;const other=s.players[1]!;const wire=JSON.stringify(projectArnak({gameId:s.gameId,gameRevision:s.revision,startedAt:s.startedAt,finishedAt:null,state:s},other.playerId));assert.equal(wire.includes(JSON.stringify(hidden.tileId)),false);s=act(s,o=>o.targetId===hidden.tileId);assert.equal(s.history.at(-1)!.text,'확인한 카드의 배치를 마쳤습니다');});
