import assert from 'node:assert/strict';
import test from 'node:test';
import {parse,safeParse} from 'valibot';
import {GameIdSchema,PlayerIdSchema,ServerTimeSchema,TileIdSchema,TurnIdSchema,PANDEMIC_CITIES,PANDEMIC_CITY_INFO,PANDEMIC_COLORS,PANDEMIC_EDGES,PANDEMIC_ROLES,PandemicActionSchema,PandemicPlayingProjectionSchema,PandemicFinishedProjectionSchema,pandemicNeighbors,pandemicProjectionIsConsistent,type PandemicAction,type PandemicCard,type PandemicCity,type PandemicColor,type PandemicEvent,type PandemicRole} from '@hangul-rummikub/shared';
import {createPandemicGame,makePandemicCards,applyPandemicAction,parsePandemicState,infectPandemic,type PandemicState} from './games/pandemic/domain/game.js';
import {boardCity} from './games/pandemic/domain/state.js';
import {projectPandemic} from './games/pandemic/compatibility/projector.js';
let sequence=0;
const now=parse(ServerTimeSchema,1000),turn=()=>parse(TurnIdSchema,`turn-${++sequence}`);
function rng(seed=13){let x=seed;return {nextInt(max:number){x=(Math.imul(x,1664525)+1013904223)>>>0;return x%max;}};}
function setup(n=2,seed=13){return createPandemicGame({gameId:parse(GameIdSchema,`pd-${++sequence}`),playerIds:Array.from({length:n},(_,i)=>parse(PlayerIdSchema,`p${i}`)),now,turnId:turn(),random:rng(seed),cards:makePandemicCards(()=>parse(TileIdSchema,`opaque-${++sequence}`))});}
function apply(s:PandemicState,a:PandemicAction,index=s.activeIndex){const before=structuredClone(s),r=applyPandemicAction(s,s.players[index]!.playerId,a,now,turn(),rng(),s.players[0]!.playerId);assert.deepEqual(s,before,'input must remain immutable');assert.ok(r.ok,JSON.stringify(a));return r.state;}
function game(n=2,seed=13){return apply(setup(n,seed),{type:'BEGIN'},0);}
function role(s:PandemicState,index:number,r:PandemicRole){const other=s.players.findIndex(p=>p.role===r);if(other>=0)s.players[other]!.role=s.players[index]!.role;s.players[index]!.role=r;}
function active(s:PandemicState,index=0){s.activeIndex=index;s.phase='ACTIONS';s.actionsLeft=4;return s.players[index]!;}
function clear(s:PandemicState){for(const b of s.board)for(const c of PANDEMIC_COLORS){s.supply[c]+=b.cubes[c];b.cubes[c]=0;}}
function cubes(s:PandemicState,city:PandemicCity,c:PandemicColor,n:number){const b=boardCity(s,city);s.supply[c]+=b.cubes[c]-n;b.cubes[c]=n;}
function take(s:PandemicState,predicate:(c:PandemicCard)=>boolean,index=0){let card:PandemicCard|undefined;for(const pile of [s.playerDeck,s.discard,s.removed,...s.players.map(p=>p.hand)]){const i=pile.findIndex(predicate);if(i>=0){card=pile.splice(i,1)[0];break;}}assert.ok(card);s.players[index]!.hand.push(card);return card;}
function cityCard(s:PandemicState,c:PandemicCity,index=0){return take(s,x=>x.kind==='CITY'&&x.city===c,index);}
function event(s:PandemicState,e:PandemicEvent,index=0){return take(s,c=>c.kind==='EVENT'&&c.event===e,index);}
function emptyHands(s:PandemicState){for(const p of s.players){s.discard.push(...p.hand);p.hand=[];}}
function rejected(s:PandemicState,a:PandemicAction,index=s.activeIndex){const before=structuredClone(s);assert.equal(applyPandemicAction(s,s.players[index]!.playerId,a,now,turn(),rng(),s.players[0]!.playerId).ok,false);assert.deepEqual(s,before);}
function boundary(s:PandemicState){for(let i=0;i<s.players.length;i++)s=apply(s,{type:'CONTINUE'},i);return s;}
function project(s:PandemicState,index=0){return projectPandemic({gameId:s.gameId,gameRevision:s.revision,startedAt:s.startedAt,finishedAt:s.finishedAt,state:s},s.players[index]!.playerId)!;}

test('Pandemic map: 48 cities, 12 per color, 93 unique undirected routes, Pacific connections and connected graph',()=>{assert.equal(PANDEMIC_CITIES.length,48);for(const c of PANDEMIC_COLORS)assert.equal(PANDEMIC_CITIES.filter(id=>PANDEMIC_CITY_INFO[id].color===c).length,12);assert.equal(PANDEMIC_EDGES.length,93);assert.equal(new Set(PANDEMIC_EDGES.map(e=>[...e].sort().join(':'))).size,93);assert.ok(pandemicNeighbors('SAN_FRANCISCO').includes('MANILA'));assert.ok(pandemicNeighbors('SYDNEY').includes('LOS_ANGELES'));const seen=new Set<PandemicCity>(['ATLANTA']);for(let i=0;i<48;i++)for(const c of seen)for(const n of pandemicNeighbors(c))seen.add(n);assert.equal(seen.size,48);});
for(const n of [2,3,4])for(const epidemics of [4,5,6] as const)test(`Pandemic setup ${n} players / ${epidemics} epidemics: inventory, deal, role uniqueness and stratified deck`,()=>{let s=setup(n);s=apply(s,{type:'CONFIGURE',epidemics,openHands:true},0);s=apply(s,{type:'BEGIN'},0);assert.equal(new Set(s.players.map(p=>p.role)).size,n);assert.equal(s.infectionDiscard.length,9);assert.equal(s.infectionDeck.length,39);assert.equal(s.board.reduce((n,b)=>n+Object.values(b.cubes).reduce((a,b)=>a+b,0),0),18);assert.ok(s.players.every(p=>p.hand.length===(n===2?4:n===3?3:2)));assert.equal(s.playerDeck.filter(c=>c.kind==='EPIDEMIC').length,epidemics);const deckCity=s.playerDeck.length-epidemics,base=Math.floor(deckCity/epidemics),extra=deckCity%epidemics;let pos=0;for(let i=0;i<epidemics;i++){const size=base+(i<extra?1:0)+1;assert.equal(s.playerDeck.slice(pos,pos+size).filter(c=>c.kind==='EPIDEMIC').length,1);pos+=size;}assert.ok(pandemicProjectionIsConsistent(project(s)));});
test('Pandemic invalid payload, wrong player, foreign card and illegal route leave original unchanged',()=>{const s=game();active(s);rejected(s,{type:'TREAT',color:'BLUE'},1);rejected(s,{type:'MOVE',playerId:s.players[0]!.playerId,destination:'SYDNEY',mode:'DRIVE',cardId:null});rejected(s,{type:'MOVE',playerId:s.players[0]!.playerId,destination:'SYDNEY',mode:'DIRECT',cardId:parse(TileIdSchema,'not-a-card')});assert.equal(safeParse(PandemicActionSchema,{type:'TREAT',color:'BLUE',supply:999}).success,false);});
test('Pandemic move costs: drive, direct, charter and shuttle',()=>{for(const mode of ['DRIVE','DIRECT','CHARTER','SHUTTLE'] as const){let s=game();const p=active(s);emptyHands(s);const destination=mode==='DRIVE'?'CHICAGO':'SYDNEY',c=mode==='DIRECT'?cityCard(s,'SYDNEY'):mode==='CHARTER'?cityCard(s,'ATLANTA'):null;if(mode==='SHUTTLE')s.stations.push('SYDNEY');s=apply(s,{type:'MOVE',playerId:p.playerId,destination,mode,cardId:c?.cardId??null});assert.equal(s.players[0]!.city,destination);assert.equal(s.actionsLeft,3);if(c)assert.ok(s.discard.some(x=>x.cardId===c.cardId));}});
test('Pandemic outbreak chain: triangle never repeats cities, color follows original infection',()=>{const s=game();clear(s);for(const p of s.players)p.role=p===s.players[0]?'SCIENTIST':'RESEARCHER';for(const c of ['ALGIERS','CAIRO','ISTANBUL'] as const)cubes(s,c,'BLACK',3);infectPandemic(s,'ALGIERS','BLACK',1,now);assert.equal(s.outbreaks,3);assert.equal(boardCity(s,'MADRID').cubes.BLACK,1);assert.equal(boardCity(s,'MADRID').cubes.BLUE,0);assert.ok(s.board.every(b=>b.cubes.BLACK<=3));parsePandemicState(s);infectPandemic(s,'ALGIERS','BLACK',1,now);assert.equal(s.outbreaks,7);assert.ok(s.history.some(l=>l.sound==='OUTBREAK'&&l.city==='BAGHDAD'));});
test('Pandemic losses: eighth outbreak and actual cube shortage terminate immediately',()=>{for(const why of ['OUTBREAKS','CUBES'] as const){const s=game();clear(s);role(s,0,'SCIENTIST');role(s,1,'RESEARCHER');if(why==='OUTBREAKS'){s.outbreaks=7;cubes(s,'ATLANTA','BLUE',3);}else for(const city of PANDEMIC_CITIES.filter(c=>c!=='ATLANTA').slice(0,8))cubes(s,city,'BLUE',3);infectPandemic(s,'ATLANTA','BLUE',1,now);assert.equal(s.result?.reason,why);assert.equal(s.phase,'FINISHED');parsePandemicState(s);}});
test('Pandemic quarantine blocks infection and outbreaks in own and adjacent city',()=>{const s=game();clear(s);role(s,0,'QUARANTINE');s.players[0]!.city='ATLANTA';cubes(s,'CHICAGO','BLUE',3);infectPandemic(s,'CHICAGO','BLUE',1,now);infectPandemic(s,'ATLANTA','BLACK',3,now,true);assert.equal(s.outbreaks,0);assert.equal(boardCity(s,'ATLANTA').cubes.BLACK,0);infectPandemic(s,'TOKYO','RED',1,now);assert.equal(boardCity(s,'TOKYO').cubes.RED,1);});
test('Pandemic medic treats all, auto-clears cured diseases after dispatcher consent and prevents cured infection',()=>{let s=game();clear(s);role(s,0,'DISPATCHER');role(s,1,'MEDIC');active(s);cubes(s,'ATLANTA','BLUE',3);s=apply(s,{type:'END_ACTIONS'});active(s,1);s=apply(s,{type:'TREAT',color:'BLUE'},1);assert.equal(boardCity(s,'ATLANTA').cubes.BLUE,0);active(s);s.cures.BLUE='CURED';cubes(s,'CHICAGO','BLUE',2);const action:PandemicAction={type:'MOVE',playerId:s.players[1]!.playerId,destination:'CHICAGO',mode:'DRIVE',cardId:null};s=apply(s,action);assert.equal(s.players[1]!.city,'ATLANTA');assert.equal(s.actionsLeft,4);s=apply(s,{type:'CONSENT',accept:true},1);assert.equal(s.players[1]!.city,'CHICAGO');assert.equal(boardCity(s,'CHICAGO').cubes.BLUE,0);assert.equal(s.cures.BLUE,'ERADICATED');infectPandemic(s,'TOKYO','BLUE',3,now,true);assert.equal(boardCity(s,'TOKYO').cubes.BLUE,0);});
test('Pandemic operations expert builds without card and may special-fly only once per turn',()=>{let s=game();active(s);emptyHands(s);role(s,0,'OPERATIONS');s.players[0]!.city='SYDNEY';s=apply(s,{type:'BUILD',replace:null});const c=cityCard(s,'TOKYO');s=apply(s,{type:'MOVE',playerId:s.players[0]!.playerId,destination:'ATLANTA',mode:'OPERATIONS',cardId:c.cardId});assert.equal(s.operationsUsed,true);const c2=cityCard(s,'SEOUL');rejected(s,{type:'MOVE',playerId:s.players[0]!.playerId,destination:'TOKYO',mode:'OPERATIONS',cardId:c2.cardId});});
test('Pandemic dispatcher pays own flight card; cannot borrow operations ability',()=>{let s=game();active(s);emptyHands(s);role(s,0,'DISPATCHER');role(s,1,'OPERATIONS');const c=cityCard(s,'SYDNEY');s=apply(s,{type:'MOVE',playerId:s.players[1]!.playerId,destination:'SYDNEY',mode:'DIRECT',cardId:c.cardId});s=apply(s,{type:'CONSENT',accept:true},1);assert.equal(s.players[1]!.city,'SYDNEY');assert.equal(s.players[0]!.hand.length,0);const c2=cityCard(s,'ATLANTA');rejected(s,{type:'MOVE',playerId:s.players[1]!.playerId,destination:'TOKYO',mode:'OPERATIONS',cardId:c2.cardId});});
test('Pandemic researcher giving exception applies on either turn, refusal costs nothing, receiving exception forbidden',()=>{let s=game();active(s);emptyHands(s);role(s,0,'SCIENTIST');role(s,1,'RESEARCHER');const c=cityCard(s,'TOKYO',1);s=apply(s,{type:'SHARE',from:s.players[1]!.playerId,to:s.players[0]!.playerId,cardId:c.cardId});s=apply(s,{type:'CONSENT',accept:false},1);assert.equal(s.actionsLeft,4);s=apply(s,{type:'SHARE',from:s.players[1]!.playerId,to:s.players[0]!.playerId,cardId:c.cardId});s=apply(s,{type:'CONSENT',accept:true},1);assert.ok(s.players[0]!.hand.some(x=>x.cardId===c.cardId));rejected(s,{type:'SHARE',from:s.players[0]!.playerId,to:s.players[1]!.playerId,cardId:c.cardId});});
test('Pandemic cure: scientist four, regular five, last cure wins with cubes remaining',()=>{for(const scientist of [false,true]){let s=game();active(s);emptyHands(s);role(s,0,scientist?'SCIENTIST':'RESEARCHER');for(const c of ['YELLOW','BLACK','RED'] as const)s.cures[c]='CURED';const cards=PANDEMIC_CITIES.filter(c=>PANDEMIC_CITY_INFO[c].color==='BLUE').slice(0,scientist?4:5).map(c=>cityCard(s,c).cardId);s=apply(s,{type:'CURE',color:'BLUE',cards});assert.equal(s.result?.reason,'CURED');assert.equal(s.result.winnerPlayerIds.length,2);assert.equal(s.phase,'FINISHED');assert.ok(s.board.some(b=>Object.values(b.cubes).some(n=>n>0)));}});
test('Pandemic cure rejects duplicate cards, wrong colors and missing station',()=>{const s=game();active(s);emptyHands(s);role(s,0,'SCIENTIST');const ids=(['ATLANTA','CHICAGO','NEW_YORK','WASHINGTON'] as const).map(c=>cityCard(s,c).cardId);rejected(s,{type:'CURE',color:'BLUE',cards:[ids[0]!,ids[0]!,ids[1]!,ids[2]!]});s.stations=[];rejected(s,{type:'CURE',color:'BLUE',cards:ids});});
test('Pandemic airlift: off-turn event, consent and zero action cost',()=>{let s=game();active(s);const c=event(s,'AIRLIFT',1);s=apply(s,{type:'EVENT',cardId:c.cardId,target:s.players[0]!.playerId,city:'TOKYO',replace:null},1);assert.equal(s.pending?.kind,'CONSENT');s=apply(s,{type:'CONSENT',accept:true},0);assert.equal(s.players[0]!.city,'TOKYO');assert.equal(s.actionsLeft,4);assert.ok(s.discard.some(x=>x.cardId===c.cardId));});
test('Pandemic government grant: six stations forces explicit relocation; no city card cost',()=>{let s=game();active(s);s.stations=['ATLANTA','TOKYO','SEOUL','MADRID','PARIS','LIMA'];const c=event(s,'GRANT');const action:PandemicAction={type:'EVENT',cardId:c.cardId,target:null,city:'SYDNEY',replace:null};rejected(s,action);s=apply(s,{...action,replace:'LIMA'});assert.equal(s.stations.length,6);assert.ok(!s.stations.includes('LIMA'));assert.ok(s.stations.includes('SYDNEY'));assert.equal(s.actionsLeft,4);});
test('Pandemic forecast: only chooser sees top six, invalid permutation is atomic, sorted order is preserved',()=>{let s=game();active(s);const c=event(s,'FORECAST',1),top=s.infectionDeck.slice(0,6);s=apply(s,{type:'EVENT',cardId:c.cardId,target:null,city:null,replace:null},1);assert.equal(project(s,0).privateState.forecast,null);assert.deepEqual(project(s,1).privateState.forecast,top);rejected(s,{type:'FORECAST_ORDER',cities:[top[0]!,top[0]!]},1);rejected(s,{type:'FORECAST_ORDER',cities:top},0);s=apply(s,{type:'FORECAST_ORDER',cities:[...top].reverse()},1);assert.deepEqual(s.infectionDeck.slice(0,6),[...top].reverse());assert.equal(s.pending,null);});
test('Pandemic resilient population can intervene between epidemic infection and intensification',()=>{let s=game();active(s);const c=event(s,'RESILIENT');s.phase='DRAW';const ep=s.playerDeck.find(x=>x.kind==='EPIDEMIC')!;s.playerDeck=s.playerDeck.filter(x=>x!==ep);s.playerDeck.unshift(ep);s=boundary(s);assert.equal(s.phase,'INTENSIFY');const removed=s.lastInfected!;s=apply(s,{type:'EVENT',cardId:c.cardId,target:null,city:removed,replace:null});assert.ok(s.infectionRemoved.includes(removed));s=boundary(s);assert.ok(!s.infectionDeck.includes(removed));parsePandemicState(s);});
test('Pandemic quiet night skips the next infection step, not remaining cards of a started step',()=>{let s=game();active(s);const c=event(s,'QUIET_NIGHT');s.phase='INFECTION_READY';const before=s.infectionDeck.length;s=apply(s,{type:'EVENT',cardId:c.cardId,target:null,city:null,replace:null});s=boundary(s);assert.equal(s.phase,'TURN_END');assert.equal(s.infectionDeck.length,before);assert.equal(s.quietNight,false);});
test('Pandemic contingency planner stores one event outside hand, then removes it after use',()=>{let s=game();active(s);emptyHands(s);role(s,0,'PLANNER');const c=event(s,'QUIET_NIGHT');s.players[0]!.hand=[];s.discard.push(c);s=apply(s,{type:'STORE',cardId:c.cardId});assert.equal(s.players[0]!.stored?.cardId,c.cardId);assert.equal(s.players[0]!.hand.length,0);assert.equal(s.actionsLeft,3);s=apply(s,{type:'EVENT',cardId:c.cardId,target:null,city:null,replace:null});assert.equal(s.players[0]!.stored,null);assert.ok(s.removed.some(x=>x.cardId===c.cardId));assert.ok(!s.discard.some(x=>x.cardId===c.cardId));});
test('Pandemic hand limit interrupts card sharing immediately; overflow owner must discard',()=>{let s=game();active(s);emptyHands(s);role(s,0,'SCIENTIST');role(s,1,'RESEARCHER');const c=cityCard(s,'ATLANTA');for(const city of PANDEMIC_CITIES.slice(6,13))cityCard(s,city,1);s=apply(s,{type:'SHARE',from:s.players[0]!.playerId,to:s.players[1]!.playerId,cardId:c.cardId});s=apply(s,{type:'CONSENT',accept:true},1);assert.equal(s.players[1]!.hand.length,8);rejected(s,{type:'END_ACTIONS'});s=apply(s,{type:'DISCARD',cardId:c.cardId},1);assert.equal(s.players[1]!.hand.length,7);s=apply(s,{type:'END_ACTIONS'});assert.equal(s.phase,'DRAW');});
test('Pandemic deck exhaustion is checked before drawing either card',()=>{let s=game();active(s);s.discard.push(...s.playerDeck.filter(c=>c.kind!=='EPIDEMIC'));s.removed.push(...s.playerDeck.filter(c=>c.kind==='EPIDEMIC'));s.playerDeck=[];s.phase='DRAW';s=boundary(s);assert.equal(s.result?.reason,'DECK');});
test('Pandemic two epidemics resolve individually, both intensify, no replacement player cards',()=>{let s=game();active(s);clear(s);role(s,0,'SCIENTIST');role(s,1,'RESEARCHER');const eps=s.playerDeck.filter(c=>c.kind==='EPIDEMIC').slice(0,2);s.playerDeck=[...eps,...s.playerDeck.filter(c=>!eps.some(e=>e.cardId===c.cardId))];s.phase='DRAW';const n=s.players[0]!.hand.length;s=boundary(s);assert.equal(s.phase,'INTENSIFY');assert.equal(s.epidemicsRemaining,2);const first=s.lastInfected;s=boundary(s);assert.equal(s.phase,'EPIDEMIC_NEXT');s=boundary(s);assert.equal(s.phase,'INTENSIFY');assert.notEqual(s.lastInfected,first);s=boundary(s);assert.equal(s.epidemicsRemaining,0);assert.equal(s.rateIndex,2);assert.equal(s.players[0]!.hand.length,n);});
test('Pandemic event opportunity acknowledgements reset after an event and cannot double advance',()=>{let s=game();active(s);const c=event(s,'QUIET_NIGHT',1);s.phase='DRAW';s=apply(s,{type:'CONTINUE'},0);assert.equal(s.phase,'DRAW');rejected(s,{type:'CONTINUE'},0);s=apply(s,{type:'EVENT',cardId:c.cardId,target:null,city:null,replace:null},1);assert.deepEqual(s.continueReady,[]);});
test('Pandemic projection is allowlisted; hidden hands and deck order never serialize',()=>{const s=game();s.settings.openHands=false;const p=project(s);assert.equal(p.playerStates[1]!.hand,null);assert.equal(p.playerStates[0]!.hand?.length,s.players[0]!.hand.length);assert.equal('playerDeck' in p,false);assert.equal('infectionDeck' in p,false);assert.ok(pandemicProjectionIsConsistent(p));assert.equal(safeParse(PandemicPlayingProjectionSchema,{...p,playerDeck:s.playerDeck}).success,false);const card=s.players[1]!.hand[0]!;assert.equal(JSON.stringify(p).includes(card.cardId),false);});
test('Pandemic state validation rejects lost cards, duplicate infection entries and cube tampering',()=>{const s=game();for(const corrupt of [(g:PandemicState)=>g.playerDeck.pop(),(g:PandemicState)=>g.infectionDeck.push(g.infectionDeck[0]!),(g:PandemicState)=>g.supply.BLUE++]){const c=structuredClone(s);corrupt(c);assert.throws(()=>parsePandemicState(c));}});
test('Pandemic all seven roles have distinct setup selection and cannot take a teammate role',()=>{assert.equal(PANDEMIC_ROLES.length,7);let s=setup();const other=s.players[1]!.role;rejected(s,{type:'ROLE',role:other},0);for(const role of PANDEMIC_ROLES.filter(r=>r!==other))s=apply(s,{type:'ROLE',role},0);});
for(const n of [2,3,4])for(const seed of [1,23,157])test(`Pandemic deterministic complete game ${n} players seed ${seed}: transitions conserve inventory through terminal loss`,()=>{
 let s=game(n,seed),steps=0;
 while(s.phase!=='FINISHED'&&steps++<600){
  if(s.epidemicsRemaining===0&&s.players.some(p=>p.hand.length>7)){const i=s.players.findIndex(p=>p.hand.length>7);s=apply(s,{type:'DISCARD',cardId:s.players[i]!.hand[0]!.cardId},i);}
  else if(s.phase==='ACTIONS')s=apply(s,{type:'END_ACTIONS'});
  else s=boundary(s);
  parsePandemicState(s);assert.ok(pandemicProjectionIsConsistent(project(s)));
 }
 assert.equal(s.phase,'FINISHED');assert.ok(s.result&&s.result.reason!=='CURED');assert.ok(safeParse(PandemicFinishedProjectionSchema,project(s)).success);
});

test('Pandemic private sharing: owner selects an eligible card, outsiders cannot approve, and no hidden hand leaks',()=>{
 let s=game(3);active(s);emptyHands(s);role(s,0,'SCIENTIST');role(s,1,'RESEARCHER');s.settings.openHands=false;
 const offered=cityCard(s,'TOKYO',1),secret=cityCard(s,'SEOUL',1);
 s=apply(s,{type:'REQUEST_SHARE',from:s.players[1]!.playerId});
 assert.equal(s.pending?.kind,'SHARE_PICK');assert.equal(s.actionsLeft,4);
 const before=JSON.stringify(project(s,0));assert.ok(!before.includes(offered.cardId));assert.ok(!before.includes(secret.cardId));
 rejected(s,{type:'OFFER_CARD',cardId:offered.cardId},2);
 s=apply(s,{type:'OFFER_CARD',cardId:offered.cardId},1);
 assert.equal(s.pending,null);assert.equal(s.actionsLeft,3);assert.ok(s.players[0]!.hand.some(c=>c.cardId===offered.cardId));
 assert.ok(!JSON.stringify(project(s,0)).includes(secret.cardId));parsePandemicState(s);
});
test('Pandemic private sharing: refusal is free and a non-researcher cannot offer a different city',()=>{
 let s=game();active(s);emptyHands(s);role(s,0,'SCIENTIST');role(s,1,'MEDIC');s.settings.openHands=false;
 const wrong=cityCard(s,'TOKYO',1);s=apply(s,{type:'REQUEST_SHARE',from:s.players[1]!.playerId});
 rejected(s,{type:'OFFER_CARD',cardId:wrong.cardId},1);
 s=apply(s,{type:'OFFER_CARD',cardId:null},1);assert.equal(s.pending,null);assert.equal(s.actionsLeft,4);assert.equal(s.players[1]!.hand[0]?.cardId,wrong.cardId);
});
