import assert from 'node:assert/strict';
import test from 'node:test';
import * as v from 'valibot';
import {GameIdSchema,PlayerIdSchema,TileIdSchema,TurnIdSchema,ServerTimeSchema,TerrorscapeActionSchema,TERROR_CHARACTERS,TERROR_DOORS,TERROR_SKILL_INFO,terrorEdge,terrorAdjacent,type TerrorscapeAction,type TerrorCharacter,type TerrorItem,type TerrorSkill} from '@hangul-rummikub/shared';
import {createTerrorscapeGame,makeTerrorscapeCards,applyTerrorscapeAction,parseTerrorscapeState,cancelTerrorscape,type TerrorscapeState} from './games/terrorscape/domain/game.js';
import {projectTerrorscape} from './games/terrorscape/compatibility/projector.js';
const now=v.parse(ServerTimeSchema,1000);let seq=0;
const id=()=>v.parse(TurnIdSchema,'turn-'+(++seq));
function rng(seed=13){return {nextInt(max:number){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed%max;}};}
function game(n=2){return createTerrorscapeGame({gameId:v.parse(GameIdSchema,'terror-'+(++seq)),playerIds:Array.from({length:n},(_,i)=>v.parse(PlayerIdSchema,'p'+i)),cards:makeTerrorscapeCards(()=>v.parse(TileIdSchema,'opaque-'+(++seq))),now,turnId:id(),random:rng()});}
function act(s:TerrorscapeState,a:TerrorscapeAction,actor=s.killerPlayerId,random={nextInt:(max:number)=>max-1}){const result=applyTerrorscapeAction(s,actor,a,now,id(),random);assert.ok(result.ok,JSON.stringify(a));return result.state;}
function teamAct(s:TerrorscapeState,a:TerrorscapeAction,c:TerrorCharacter='ANNA',random={nextInt:(max:number)=>max-1}){return act(s,a,s.survivors.find(p=>p.character===c)!.playerId,random);}
function begun(n=2){return act(game(n),{type:'BEGIN_HUNT'});}
function basic(character:TerrorCharacter,kind:Extract<TerrorscapeAction,{type:'BASIC'}>['kind']='CALM'):Extract<TerrorscapeAction,{type:'BASIC'}>{return {type:'BASIC',character,kind,path:[],edge:'',cardId:null};}
function projection(s:TerrorscapeState,i:number){return projectTerrorscape({gameId:s.gameId,gameRevision:s.revision,startedAt:s.startedAt,finishedAt:s.finishedAt,state:s},s.players[i]!.playerId);}
function rejected(s:TerrorscapeState,a:TerrorscapeAction,actor=s.killerPlayerId){const before=JSON.stringify(s);assert.deepEqual(applyTerrorscapeAction(s,actor,a,now,id(),rng()),{ok:false,reason:'INVALID_ACTION'});assert.equal(JSON.stringify(s),before);}
function give(s:TerrorscapeState,c:TerrorCharacter,key:TerrorItem){for(const pool of [s.searchDeck,s.discoverDeck,s.discard,...s.survivors.map(p=>p.hand)]){const index=pool.findIndex(c=>c.key===key);if(index>=0){const card=pool.splice(index,1)[0]!;s.survivors.find(p=>p.character===c)!.hand.push(card);return card;}}throw new Error('Missing '+key);}
function handSkill(s:TerrorscapeState,key:TerrorSkill){const existing=s.hand.find(c=>c.key===key);if(existing)return existing;const i=s.killerDeck.findIndex(c=>c.key===key);assert.ok(i>=0);const c=s.killerDeck.splice(i,1)[0]!;if(s.hand.length===5)s.killerDiscard.push(s.hand.pop()!);s.hand.push(c);return c;}
function skill(s:TerrorscapeState,key:TerrorSkill):Extract<TerrorscapeAction,{type:'KILLER_CARD'}>{const card=handSkill(s,key);while(s.hand.length<TERROR_SKILL_INFO[key].cost+1)s.hand.push(s.killerDeck.pop()!);return {type:'KILLER_CARD',cardId:card.cardId,cost:s.hand.filter(c=>c!==card).slice(0,TERROR_SKILL_INFO[key].cost).map(c=>c.cardId),path:[],zone:'R',edge:'',replaces:[]};}
function endTeam(s:TerrorscapeState){for(const c of TERROR_CHARACTERS){if(!s.survivors.find(p=>p.character===c)!.acted)s=teamAct(s,basic(c),c);s=teamAct(s,{type:'READY',character:c,ready:true},c);}s=teamAct(s,{type:'DISCOVER',character:'ANNA'});if(s.phase==='LOOT')s=teamAct(s,{type:'KEEP',cardId:null});return s;}
test('Terrorscape: 2/3/4 players conserve 44 items and 13 skills, bottom key, strict commands',()=>{for(const n of [2,3,4])for(let i=0;i<10;i++){const s=game(n);assert.equal(s.searchDeck.length,11);assert.equal(s.searchDeck[0]!.key,'KEY');assert.equal(s.discoverDeck.length,32);assert.equal(s.hand.length,2);assert.deepEqual(parseTerrorscapeState(s),s);for(let j=0;j<n;j++)assert.doesNotThrow(()=>projection(s,j));}assert.equal(v.safeParse(TerrorscapeActionSchema,{type:'BEGIN_HUNT',hack:true}).success,false);assert.equal(v.safeParse(TerrorscapeActionSchema,{...basic('ANNA','MOVE'),path:['invalid']}).success,false);});
test('Terrorscape: hidden team moves do not alter killer projection, scoped revision or turn ID',()=>{let s=begun(4);const before=projection(s,0),id=s.killerTurnId;s=teamAct(s,{...basic('ANNA','MOVE'),path:['R2']});assert.equal(s.survivors[0]!.location,'R2');assert.deepEqual(projection(s,0),before);assert.equal(s.killerTurnId,id);assert.equal(s.survivorRevision,2);const json=JSON.stringify(projection(s,0));for(const c of [...s.searchDeck,...s.discoverDeck,...s.survivors.flatMap(p=>p.hand)])assert.equal(json.includes(c.cardId),false);assert.ok(!('team' in projection(s,0).privateState));for(const c of [...s.hand,...s.killerDeck])assert.equal(JSON.stringify(projection(s,1)).includes(c.cardId),false);});
test('Terrorscape: actor authority, route walls, blocked paths, basic action reuse reject atomically',()=>{let s=begun(4);const a={...basic('ANNA','MOVE'),path:['R2' as const]};rejected(s,a);rejected(s,a,s.survivors[1]!.playerId);rejected(s,{...a,path:['G5']},s.survivors[0]!.playerId);s.blocks=['R1-R2'];rejected(s,a,s.survivors[0]!.playerId);s.blocks=[];s=teamAct(s,a);rejected(s,basic('ANNA'),s.survivors[0]!.playerId);assert.equal(terrorAdjacent('R3','R4'),false);assert.equal(terrorAdjacent('B2','R3'),false);});
test('Terrorscape: role assignment is host-only and all non-killer players must own characters',()=>{let s=game(4);rejected(s,{type:'SET_ROLES',killerPlayerId:s.players[1]!.playerId,owners:[s.players[0]!.playerId,s.players[0]!.playerId,s.players[0]!.playerId]});const owners=[s.players[0]!.playerId,s.players[2]!.playerId,s.players[3]!.playerId];s=act(s,{type:'SET_ROLES',killerPlayerId:s.players[1]!.playerId,owners},s.players[0]!.playerId);for(let i=0;i<4;i++)projection(s,i);rejected(s,{type:'BEGIN_HUNT'},s.players[1]!.playerId);s=act(s,{type:'BEGIN_HUNT'},s.players[0]!.playerId);assert.equal(s.phase,'SURVIVORS');});
test('Terrorscape: search and discovery have different Anna noise behavior; key pools immediately',()=>{let s=begun();s.survivors[0]!.location='R2';const key=s.searchDeck.find(c=>c.key==='KEY')!;s.searchDeck=s.searchDeck.filter(c=>c!==key);s.searchDeck.push(key);s=teamAct(s,basic('ANNA','SEARCH'));assert.deepEqual(s.pendingNoises,[]);s=teamAct(s,{type:'KEEP',cardId:key.cardId});assert.equal(s.keys.length,1);assert.equal(s.survivors[0]!.hand.length,0);const noisy=s.discoverDeck.find(c=>c.key==='KEY')!;s.discoverDeck=s.discoverDeck.filter(c=>c!==noisy);s.discoverDeck.push(noisy);s=endTeam(s);assert.ok(s.noises.includes('R2'));assert.equal(s.phase,'FAST');});
test('Terrorscape: discovery overflow waits for owner discard before starting killer',()=>{let s=begun();for(const k of ['HATCHET','HERBS','POWDER'] as const)give(s,'ANNA',k);for(const c of TERROR_CHARACTERS){s=teamAct(s,basic(c),c);s=teamAct(s,{type:'READY',character:c,ready:true},c);}s=teamAct(s,{type:'DISCOVER',character:'ANNA'});const keep=s.loot!.cards.find(c=>c.key!=='KEY')!;s=teamAct(s,{type:'KEEP',cardId:keep.cardId});assert.equal(s.phase,'SURVIVORS');assert.equal(s.survivors[0]!.hand.length,4);rejected(s,{type:'DISCOVER',character:'ANNA'},s.survivors[0]!.playerId);s=teamAct(s,{type:'DISCARD',character:'ANNA',cardId:keep.cardId});assert.equal(s.phase,'FAST');});
test('Terrorscape: toolbox repairs twice, once per round; rescue countdown starts next survivor turn',()=>{let s=begun();s.survivors[0]!.location='B1';s.survivors[1]!.location='B1';s.repair=3;const c=give(s,'ANNA','TOOLBOX');s=teamAct(s,{type:'ITEM',character:'ANNA',cardId:c.cardId,target:'ANNA',destination:'B1',edge:''});assert.equal(s.rescue,5);rejected(s,basic('WILLIAM','REPAIR'),s.survivors[1]!.playerId);s=endTeam(s);s.phase='SLOW';s=act(s,{type:'KILLER_NEXT'});assert.equal(s.rescue,4);});
test('Terrorscape: winning exits are checked at survivor start, secret map required for garden',()=>{for(const garden of [false,true]){let s=begun();for(let i=0;i<5;i++){const c=s.searchDeck.find(c=>c.key==='KEY')!;s.searchDeck=s.searchDeck.filter(x=>x!==c);s.keys.push(c);}for(const p of s.survivors)p.location=garden?'G5':'R1';if(garden)give(s,'ANNA','SECRET_MAP');s.phase='SLOW';s=act(s,{type:'KILLER_NEXT'});assert.equal(s.result?.reason,'ESCAPED');assert.deepEqual(s.result?.winnerPlayerIds,[s.players[1]!.playerId]);}let s=begun();s.rescue=1;s.phase='SLOW';s=act(s,{type:'KILLER_NEXT'});assert.equal(s.result?.reason,'RESCUED');});
test('Terrorscape: exhausted discovery loses except during rescue',()=>{for(const rescue of [null,3]){let s=begun();s.discard.push(...s.discoverDeck);s.discoverDeck=[];s.rescue=rescue;s=endTeam(s);assert.equal(s.phase,rescue===null?'FINISHED':'FAST');if(rescue===null)assert.equal(s.result?.reason,'EXHAUSTED');}});
test('Terrorscape: survivor card trades, recipient overflow, flashlight and Marco medicine preserve cards',()=>{let s=begun(4);const c=give(s,'ANNA','FLASHLIGHT');s=teamAct(s,{type:'TRADE',character:'ANNA',target:'WILLIAM',cardId:c.cardId});s.survivors[1]!.location='B1';s=teamAct(s,{type:'ITEM',character:'WILLIAM',cardId:c.cardId,target:'WILLIAM',destination:'G2',edge:''},'WILLIAM');assert.equal(s.survivors[1]!.location,'G2');assert.ok(s.survivors[1]!.hand.some(x=>x.cardId===c.cardId));s.survivors[0]!.injuries=1;s.survivors[0]!.fear=2;const med=s.survivors[2]!.hand.find(c=>c.key==='MEDKIT')!;s=teamAct(s,{type:'ITEM',character:'MARCO',cardId:med.cardId,target:'ANNA',destination:'R1',edge:''},'MARCO');assert.equal(s.survivors[0]!.injuries,0);assert.equal(s.survivors[0]!.fear,0);parseTerrorscapeState(s);});
test('Terrorscape: killer fast/main/slow timing, cost uniqueness, sense immunity and block movement',()=>{let s=begun();s.phase='FAST';s=act(s,skill(s,'SENSE'));assert.deepEqual(s.sensed.map(p=>p.character),['WILLIAM','MARCO']);s=act(s,{type:'KILLER_NEXT'});rejected(s,skill(s,'SENSE'));s.killerLocation='R1';s.blocks=['R1-R2'];s=act(s,{type:'KILLER_BASIC',kind:'MOVE',destination:'R2'});assert.equal(s.blocks.length,0);assert.equal(s.actionsLeft,1);assert.equal(s.phase,'MAIN');s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R2'});assert.equal(s.phase,'SLOW');const b=skill(s,'BARRICADE');s=act(s,{...b,edge:'R1-R2'});assert.ok(s.blocks.includes('R1-R2'));rejected(s,skill(s,'BARRICADE'));s=act(s,{type:'KILLER_NEXT'});assert.equal(s.phase,'SURVIVORS');assert.ok(s.hand.length<=5);});
test('Terrorscape: chainsaw causes fear before movement and direct injury without defense',()=>{let s=begun();s.phase='MAIN';s.killerLocation='R2';s.survivors[0]!.fear=2;const a=skill(s,'CHAINSAW');rejected(s,{...a,cost:[a.cost[0]!,a.cost[0]!]});s=act(s,{...a,path:['R1']});assert.equal(s.phase,'SLOW');assert.ok(s.survivors.every(p=>p.injuries===1));assert.ok(s.noises.includes('R1'));assert.equal(s.encounter,null);assert.equal(s.survivors[0]!.fear,2);});
test('Terrorscape: failed defense rotates survivors, successful defense discards deck and permits individual flee',()=>{let s=begun(4);s.phase='MAIN';s.killerLocation='R1';s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});assert.equal(s.phase,'DEFENDER');rejected(s,{type:'DEFENDER',character:'ANNA'});s=teamAct(s,{type:'DEFENDER',character:'ANNA'});s=teamAct(s,{type:'DEFEND',cardId:null},'ANNA',{nextInt:()=>0});assert.equal(s.survivors[0]!.injuries,1);assert.equal(s.phase,'DEFENDER');s=teamAct(s,{type:'DEFENDER',character:'WILLIAM'},'WILLIAM');const before=s.killerDeck.length;s=teamAct(s,{type:'DEFEND',cardId:null},'WILLIAM');assert.equal(s.defenseTotal,13);assert.equal(s.killerDeck.length,before-2);assert.equal(s.phase,'FLEE');s=teamAct(s,{type:'FLEE',character:'ANNA',destination:'R2'});s=teamAct(s,{type:'FLEE',character:'WILLIAM',destination:'R1'},'WILLIAM');s=teamAct(s,{type:'FLEE',character:'MARCO',destination:'R3'},'MARCO');assert.equal(s.phase,'SURVIVORS');assert.equal(s.survivors[0]!.location,'R2');});
test('Terrorscape: second injury and level-five opening injury finish immediately',()=>{for(const level of [1,5]){let s=begun();s.survivors[0]!.injuries=1;s.level=level;s.phase='MAIN';s.killerLocation='R1';s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});if(level===1){s=teamAct(s,{type:'DEFENDER',character:'ANNA'});s=teamAct(s,{type:'DEFEND',cardId:null},'ANNA',{nextInt:()=>0});}assert.equal(s.result?.reason,'KILLED');assert.deepEqual(s.result?.winnerPlayerIds,[s.killerPlayerId]);}});
test('Terrorscape: level-up happens before reshuffle, rage unlock at full hand pauses and resumes drawing',()=>{let s=begun();s.phase='SLOW';s.level=2;while(s.hand.length<5)s.hand.push(s.killerDeck.pop()!);s.killerDiscard.push(...s.killerDeck);s.killerDeck=[];s=act(s,{type:'KILLER_NEXT'});assert.equal(s.phase,'UNLOCK');assert.equal(s.level,3);assert.equal(s.hand.length,6);assert.equal(s.pendingDraw?.remaining,3);s=act(s,{type:'UNLOCK_DISCARD',cardId:s.hand.find(c=>c.key==='RAGE')!.cardId});assert.equal(s.phase,'SURVIVORS');assert.equal(s.hand.length,5);assert.equal(s.level,3);parseTerrorscapeState(s);});
test('Terrorscape: long sword draws and levels BEFORE defense roll, retaining encounter continuation',()=>{let s=begun();s.phase='MAIN';s.killerLocation='R1';give(s,'ANNA','LONGSWORD');s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});s=teamAct(s,{type:'DEFENDER',character:'ANNA'});s.level=2;while(s.hand.length<5)s.hand.push(s.killerDeck.pop()!);s.killerDiscard.push(...s.killerDeck);s.killerDeck=[];s=teamAct(s,{type:'DEFEND',cardId:s.survivors[0]!.hand.find(c=>c.key==='LONGSWORD')!.cardId});assert.equal(s.phase,'UNLOCK');assert.equal(s.dice.length,0);s=act(s,{type:'UNLOCK_DISCARD',cardId:s.hand[0]!.cardId});assert.equal(s.phase,'FLEE');assert.equal(s.defenseTotal,15);assert.equal(s.encounter?.attacked[0],'ANNA');});
test('Terrorscape: rage repeats only after breaking a block without finding anyone',()=>{let s=begun();s.phase='MAIN';s.level=3;assert.ok(s.locked);s.hand.push(s.locked);s.locked=null;const a=skill(s,'RAGE');s.blocks=[terrorEdge('G5','B4')];s=act(s,{...a,path:['B4']});assert.equal(s.phase,'RAGE');s=act(s,{type:'RAGE_MOVE',path:['B3']});assert.equal(s.phase,'SLOW');});
test('Terrorscape: seven-block cap needs exact explicit reallocation; outdoor paths cannot be blocked',()=>{let s=begun();s.phase='SLOW';s.killerLocation='B1';s.blocks=TERROR_DOORS.filter(([a,b])=>a!=='B1'&&b!=='B1').slice(0,7).map(([a,b])=>terrorEdge(a,b));const a=skill(s,'BARRICADE');rejected(s,{...a,edge:'B1-B2'});s=act(s,{...a,edge:'B1-B2',replaces:[s.blocks[0]!]});assert.equal(s.blocks.length,7);assert.ok(s.blocks.includes('B1-B2'));});
test('Terrorscape: corrupt conservation rejects, cancellation is idempotent with scoped revisions',()=>{const s=begun();const broken=structuredClone(s);broken.discoverDeck.push(broken.searchDeck[0]!);assert.throws(()=>parseTerrorscapeState(broken));const cancelled=cancelTerrorscape(s,now);assert.equal(cancelled.result?.reason,'CANCELLED');assert.ok(cancelled.killerRevision>s.killerRevision);assert.deepEqual(cancelTerrorscape(cancelled,now),cancelled);});
test('Terrorscape: explicitly chosen paths can return through an opened door, respecting step count',()=>{let s=begun();s.phase='MAIN';s.level=3;s.hand.push(s.locked!);s.locked=null;s.blocks=['B4-G5'];const a=skill(s,'RAGE');s=act(s,{...a,path:['B4','G5']});assert.equal(s.killerLocation,'G5');assert.equal(s.blocks.length,0);assert.equal(s.phase,'RAGE');});

test('Terrorscape: assigning roles before the hunt never exposes the initial killer hand',()=>{let s=game(3);const secretIds=s.hand.map(c=>c.cardId);for(let i=0;i<3;i++)for(const id of secretIds)assert.equal(JSON.stringify(projection(s,i)).includes(id),false);s=act(s,{type:'SET_ROLES',killerPlayerId:s.players[1]!.playerId,owners:[s.players[0]!.playerId,s.players[2]!.playerId,s.players[0]!.playerId]},s.players[0]!.playerId);for(let i=0;i<3;i++)for(const id of secretIds)assert.equal(JSON.stringify(projection(s,i)).includes(id),false);s=act(s,{type:'BEGIN_HUNT'},s.players[0]!.playerId);assert.ok(secretIds.every(id=>JSON.stringify(projection(s,1)).includes(id)));assert.ok(secretIds.every(id=>!JSON.stringify(projection(s,0)).includes(id)));});
