import assert from 'node:assert/strict';
import test from 'node:test';
import * as v from 'valibot';
import {GameIdSchema,PlayerIdSchema,TileIdSchema,TurnIdSchema,ServerTimeSchema,TerrorscapeActionSchema,TERROR_TRAITS,TERROR_TRAIT_INFO,TERROR_PLANS,TERROR_PLAN_INFO,type TerrorTrait,type TerrorPlan,type TerrorKiller,type TerrorMap,terrorBoard,TERROR_CHARACTERS,TERROR_ROOMS,TERROR_DOORS,TERROR_SKILL_INFO,terrorEdge,terrorAdjacent,terrorPaths,type TerrorscapeAction,type TerrorCharacter,type TerrorItem,type TerrorSkill} from '@hangul-rummikub/shared';
import {createTerrorscapeGame,makeTerrorscapeCards,applyTerrorscapeAction,parseTerrorscapeState,cancelTerrorscape,type TerrorscapeState} from './games/terrorscape/domain/game.js';
import {projectTerrorscape} from './games/terrorscape/compatibility/projector.js';
const now=v.parse(ServerTimeSchema,1000);let seq=0;
const id=()=>v.parse(TurnIdSchema,'turn-'+(++seq));
function rng(seed=13){return {nextInt(max:number){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed%max;}};}
function game(n=2){return createTerrorscapeGame({gameId:v.parse(GameIdSchema,'terror-'+(++seq)),playerIds:Array.from({length:n},(_,i)=>v.parse(PlayerIdSchema,'p'+i)),cards:makeTerrorscapeCards(()=>v.parse(TileIdSchema,'opaque-'+(++seq))),now,turnId:id(),random:rng()});}
function act(s:TerrorscapeState,a:TerrorscapeAction,actor=s.killerPlayerId,random={nextInt:(max:number)=>max-1}){const result=applyTerrorscapeAction(s,actor,a,now,id(),random);assert.ok(result.ok,JSON.stringify(a));return result.state;}
function teamAct(s:TerrorscapeState,a:TerrorscapeAction,c:TerrorCharacter='ANNA',random={nextInt:(max:number)=>max-1}){return act(s,a,s.survivors.find(p=>p.character===c)!.playerId,random);}
function begun(n=2){return act(game(n),{type:'BEGIN_HUNT'});}
function basic(character:TerrorCharacter,kind:Extract<TerrorscapeAction,{type:'BASIC'}>['kind']='CALM'):Extract<TerrorscapeAction,{type:'BASIC'}>{return {type:'BASIC',character,kind,path:[],edge:'',cardId:null};}
function projection(s:TerrorscapeState,i:number){return projectTerrorscape({gameId:s.gameId,gameRevision:s.revision,startedAt:s.startedAt,finishedAt:s.finishedAt,state:s},s.players[i]!.playerId);}
function rejected(s:TerrorscapeState,a:TerrorscapeAction,actor=s.killerPlayerId){const before=JSON.stringify(s);assert.deepEqual(applyTerrorscapeAction(s,actor,a,now,id(),rng()),{ok:false,reason:'INVALID_ACTION'});assert.equal(JSON.stringify(s),before);}
function give(s:TerrorscapeState,c:TerrorCharacter,key:TerrorItem){for(const pool of [s.searchDeck,s.discoverDeck,s.discard,...s.survivors.map(p=>p.hand)]){const index=pool.findIndex(c=>c.key===key);if(index>=0){const card=pool.splice(index,1)[0]!;s.survivors.find(p=>p.character===c)!.hand.push(card);return card;}}throw new Error('Missing '+key);}
function handSkill(s:TerrorscapeState,key:TerrorSkill){const existing=s.hand.find(c=>c.key===key);if(existing)return existing;const i=s.killerDeck.findIndex(c=>c.key===key);assert.ok(i>=0);const c=s.killerDeck.splice(i,1)[0]!;if(s.hand.length===5)s.killerDiscard.push(s.hand.pop()!);s.hand.push(c);return c;}
function skill(s:TerrorscapeState,key:TerrorSkill):Extract<TerrorscapeAction,{type:'KILLER_CARD'}>{const card=handSkill(s,key);while(s.hand.length<TERROR_SKILL_INFO[key].cost+1)s.hand.push(s.killerDeck.pop()!);return {type:'KILLER_CARD',cardId:card.cardId,cost:s.hand.filter(c=>c!==card).slice(0,TERROR_SKILL_INFO[key].cost).map(c=>c.cardId),path:[],zone:'R',edge:'',replaces:[]};}
function endTeam(s:TerrorscapeState){for(const c of TERROR_CHARACTERS.slice(0,3)){if(!s.survivors.find(p=>p.character===c)!.acted)s=teamAct(s,basic(c),c);s=teamAct(s,{type:'READY',character:c,ready:true},c);}s=teamAct(s,{type:'DISCOVER',character:'ANNA'});if(s.phase==='LOOT')s=teamAct(s,{type:'KEEP',cardId:null});return s;}
test('Terrorscape: 2/3/4 players conserve 44 items and 13 skills, bottom key, strict commands',()=>{for(const n of [2,3,4])for(let i=0;i<10;i++){const s=game(n);assert.equal(s.searchDeck.length,11);assert.equal(s.searchDeck[0]!.key,'KEY');assert.equal(s.discoverDeck.length,32);assert.equal(s.hand.length,2);assert.deepEqual(parseTerrorscapeState(s),s);for(let j=0;j<n;j++)assert.doesNotThrow(()=>projection(s,j));}assert.equal(v.safeParse(TerrorscapeActionSchema,{type:'BEGIN_HUNT',hack:true}).success,false);assert.equal(v.safeParse(TerrorscapeActionSchema,{...basic('ANNA','MOVE'),path:['invalid']}).success,false);});
test('Terrorscape: hidden team moves do not alter killer projection, scoped revision or turn ID',()=>{let s=begun(4);const before=projection(s,0),id=s.killerTurnId;s=teamAct(s,{...basic('ANNA','MOVE'),path:['R2']});assert.equal(s.survivors[0]!.location,'R2');assert.deepEqual(projection(s,0),before);assert.equal(s.killerTurnId,id);assert.equal(s.survivorRevision,2);const json=JSON.stringify(projection(s,0));for(const c of [...s.searchDeck,...s.discoverDeck,...s.survivors.flatMap(p=>p.hand)])assert.equal(json.includes(c.cardId),false);assert.ok(!('team' in projection(s,0).privateState));for(const c of [...s.hand,...s.killerDeck])assert.equal(JSON.stringify(projection(s,1)).includes(c.cardId),false);});
test('Terrorscape: actor authority, route walls, blocked paths, basic action reuse reject atomically',()=>{let s=begun(4);const a={...basic('ANNA','MOVE'),path:['R2' as const]};rejected(s,a);rejected(s,a,s.survivors[1]!.playerId);rejected(s,{...a,path:['G5']},s.survivors[0]!.playerId);s.blocks=['R1-R2'];rejected(s,a,s.survivors[0]!.playerId);s.blocks=[];s=teamAct(s,a);rejected(s,basic('ANNA'),s.survivors[0]!.playerId);assert.equal(terrorAdjacent('R3','R4'),false);assert.equal(terrorAdjacent('B2','R3'),false);});
test('Terrorscape: role assignment is host-only and all non-killer players must own characters',()=>{let s=game(4);rejected(s,{type:'SET_ROLES',killerPlayerId:s.players[1]!.playerId,owners:[s.players[0]!.playerId,s.players[0]!.playerId,s.players[0]!.playerId]});const owners=[s.players[0]!.playerId,s.players[2]!.playerId,s.players[3]!.playerId];s=act(s,{type:'SET_ROLES',killerPlayerId:s.players[1]!.playerId,owners},s.players[0]!.playerId);for(let i=0;i<4;i++)projection(s,i);rejected(s,{type:'BEGIN_HUNT'},s.players[1]!.playerId);s=act(s,{type:'BEGIN_HUNT'},s.players[0]!.playerId);assert.equal(s.phase,'SURVIVORS');});
test('Terrorscape: search and discovery have different Anna noise behavior; key pools immediately',()=>{let s=begun();s.survivors[0]!.location='R2';const key=s.searchDeck.find(c=>c.key==='KEY')!;s.searchDeck=s.searchDeck.filter(c=>c!==key);s.searchDeck.push(key);s=teamAct(s,basic('ANNA','SEARCH'));assert.deepEqual(s.pendingNoises,[]);s=teamAct(s,{type:'KEEP',cardId:key.cardId});assert.equal(s.keys.length,1);assert.equal(s.survivors[0]!.hand.length,0);const noisy=s.discoverDeck.find(c=>c.key==='KEY')!;s.discoverDeck=s.discoverDeck.filter(c=>c!==noisy);s.discoverDeck.push(noisy);s=endTeam(s);assert.ok(s.noises.includes('R2'));assert.equal(s.phase,'FAST');});
test('Terrorscape: discovery overflow waits for owner discard before starting killer',()=>{let s=begun();for(const k of ['HATCHET','HERBS','POWDER'] as const)give(s,'ANNA',k);for(const c of TERROR_CHARACTERS.slice(0,3)){s=teamAct(s,basic(c),c);s=teamAct(s,{type:'READY',character:c,ready:true},c);}s=teamAct(s,{type:'DISCOVER',character:'ANNA'});const keep=s.loot!.cards.find(c=>c.key!=='KEY')!;s=teamAct(s,{type:'KEEP',cardId:keep.cardId});assert.equal(s.phase,'SURVIVORS');assert.equal(s.survivors[0]!.hand.length,4);rejected(s,{type:'DISCOVER',character:'ANNA'},s.survivors[0]!.playerId);s=teamAct(s,{type:'DISCARD',character:'ANNA',cardId:keep.cardId});assert.equal(s.phase,'FAST');});
test('Terrorscape: toolbox repairs twice, once per round; rescue countdown starts next survivor turn',()=>{let s=begun();s.survivors[0]!.location='B1';s.survivors[1]!.location='B1';s.repair=3;const c=give(s,'ANNA','TOOLBOX');s=teamAct(s,{type:'ITEM',character:'ANNA',cardId:c.cardId,target:'ANNA',destination:'B1',edge:''});assert.equal(s.rescue,5);rejected(s,basic('WILLIAM','REPAIR'),s.survivors[1]!.playerId);s=endTeam(s);s.phase='SLOW';s=act(s,{type:'KILLER_NEXT'});assert.equal(s.rescue,4);});
test('Terrorscape: winning exits are checked at survivor start, secret map required for garden',()=>{for(const garden of [false,true]){let s=begun();for(let i=0;i<5;i++){const c=s.searchDeck.find(c=>c.key==='KEY')!;s.searchDeck=s.searchDeck.filter(x=>x!==c);s.keys.push(c);}for(const p of s.survivors)p.location=garden?'G5':'R1';if(garden)give(s,'ANNA','SECRET_MAP');s.phase='SLOW';s=act(s,{type:'KILLER_NEXT'});assert.equal(s.result?.reason,'ESCAPED');assert.deepEqual(s.result?.winnerPlayerIds,[s.players[1]!.playerId]);}let s=begun();s.rescue=1;s.phase='SLOW';s=act(s,{type:'KILLER_NEXT'});assert.equal(s.result?.reason,'RESCUED');});
test('Terrorscape: exhausted discovery loses except during rescue',()=>{for(const rescue of [null,3]){let s=begun();s.discard.push(...s.discoverDeck);s.discoverDeck=[];s.rescue=rescue;s=endTeam(s);assert.equal(s.phase,rescue===null?'FINISHED':'FAST');if(rescue===null)assert.equal(s.result?.reason,'EXHAUSTED');}});
test('Terrorscape: survivor card trades, recipient overflow, flashlight and Marco medicine preserve cards',()=>{let s=begun(4);const c=give(s,'ANNA','FLASHLIGHT');s=teamAct(s,{type:'TRADE',character:'ANNA',target:'WILLIAM',cardId:c.cardId});s.survivors[1]!.location='B1';s=teamAct(s,{type:'ITEM',character:'WILLIAM',cardId:c.cardId,target:'WILLIAM',destination:'G2',edge:''},'WILLIAM');assert.equal(s.survivors[1]!.location,'G2');assert.ok(s.survivors[1]!.hand.some(x=>x.cardId===c.cardId));s.survivors[0]!.injuries=1;s.survivors[0]!.fear=2;const med=s.survivors[2]!.hand.find(c=>c.key==='MEDKIT')!;s=teamAct(s,{type:'ITEM',character:'MARCO',cardId:med.cardId,target:'ANNA',destination:'R1',edge:''},'MARCO');assert.equal(s.survivors[0]!.injuries,0);assert.equal(s.survivors[0]!.fear,0);parseTerrorscapeState(s);});
test('Terrorscape: killer fast/main/slow timing, cost uniqueness, sense immunity and block movement',()=>{let s=begun();s.phase='FAST';s=act(s,skill(s,'SENSE'));assert.deepEqual(s.sensed.map(p=>p.character),['WILLIAM','MARCO']);s=act(s,{type:'KILLER_NEXT'});rejected(s,skill(s,'SENSE'));s.killerLocation='R1';s.blocks=['R1-R2'];s=act(s,{type:'KILLER_BASIC',kind:'MOVE',destination:'R2'});assert.equal(s.blocks.length,0);assert.equal(s.actionsLeft,1);assert.equal(s.phase,'MAIN');s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R2'});assert.equal(s.phase,'SLOW');const b=skill(s,'BARRICADE');s=act(s,{...b,edge:'R1-R2'});assert.ok(s.blocks.includes('R1-R2'));rejected(s,skill(s,'BARRICADE'));s=act(s,{type:'KILLER_NEXT'});assert.equal(s.phase,'SURVIVORS');assert.ok(s.hand.length<=5);});
test('Terrorscape: chainsaw causes fear before movement and direct injury without defense',()=>{let s=begun();s.phase='MAIN';s.killerLocation='R2';s.survivors[0]!.fear=2;const a=skill(s,'CHAINSAW');rejected(s,{...a,cost:[a.cost[0]!,a.cost[0]!]});s=act(s,{...a,path:['R1']});assert.equal(s.phase,'SLOW');assert.ok(s.survivors.every(p=>p.injuries===1));assert.ok(s.noises.includes('R1'));assert.equal(s.encounter,null);assert.equal(s.survivors[0]!.fear,2);});
test('Terrorscape: failed defense rotates survivors, successful defense discards deck and permits individual flee',()=>{let s=begun(4);s.phase='MAIN';s.killerLocation='R1';s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});assert.equal(s.phase,'DEFENDER');rejected(s,{type:'DEFENDER',character:'ANNA'});s=teamAct(s,{type:'DEFENDER',character:'ANNA'});s=teamAct(s,{type:'DEFEND',cardId:null},'ANNA',{nextInt:()=>0});assert.equal(s.survivors[0]!.injuries,1);assert.equal(s.phase,'DEFENDER');s=teamAct(s,{type:'DEFENDER',character:'WILLIAM'},'WILLIAM');const before=s.killerDeck.length;s=teamAct(s,{type:'DEFEND',cardId:null},'WILLIAM');assert.equal(s.defenseTotal,13);assert.equal(s.killerDeck.length,before-2);assert.equal(s.phase,'FLEE');s=teamAct(s,{type:'FLEE',character:'ANNA',destination:'R2'});s=teamAct(s,{type:'FLEE',character:'WILLIAM',destination:'R1'},'WILLIAM');s=teamAct(s,{type:'FLEE',character:'MARCO',destination:'R3'},'MARCO');assert.equal(s.phase,'SURVIVORS');assert.equal(s.survivors[0]!.location,'R2');});
test('Terrorscape: second injury and level-five opening injury finish immediately',()=>{for(const level of [1,5]){let s=begun();s.survivors[0]!.injuries=1;s.level=level;s.phase='MAIN';s.killerLocation='R1';s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});if(level===1){s=teamAct(s,{type:'DEFENDER',character:'ANNA'});s=teamAct(s,{type:'DEFEND',cardId:null},'ANNA',{nextInt:()=>0});}assert.equal(s.result?.reason,'KILLED');assert.deepEqual(s.result?.winnerPlayerIds,[s.killerPlayerId]);}});
test('Terrorscape: level-up happens before reshuffle, rage unlock at full hand pauses and resumes drawing',()=>{let s=begun();s.phase='SLOW';s.level=2;while(s.hand.length<5)s.hand.push(s.killerDeck.pop()!);s.killerDiscard.push(...s.killerDeck);s.killerDeck=[];s=act(s,{type:'KILLER_NEXT'});assert.equal(s.phase,'UNLOCK');assert.equal(s.level,3);assert.equal(s.hand.length,6);assert.equal(s.pendingDraw?.remaining,3);s=act(s,{type:'UNLOCK_DISCARD',cardId:s.hand.find(c=>c.key==='RAGE')!.cardId});assert.equal(s.phase,'SURVIVORS');assert.equal(s.hand.length,5);assert.equal(s.level,3);parseTerrorscapeState(s);});
test('Terrorscape: long sword draws and levels BEFORE defense roll, retaining encounter continuation',()=>{let s=begun();s.phase='MAIN';s.killerLocation='R1';give(s,'ANNA','LONGSWORD');s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});s=teamAct(s,{type:'DEFENDER',character:'ANNA'});s.level=2;while(s.hand.length<5)s.hand.push(s.killerDeck.pop()!);s.killerDiscard.push(...s.killerDeck);s.killerDeck=[];s=teamAct(s,{type:'DEFEND',cardId:s.survivors[0]!.hand.find(c=>c.key==='LONGSWORD')!.cardId});assert.equal(s.phase,'UNLOCK');assert.equal(s.dice.length,0);s=act(s,{type:'UNLOCK_DISCARD',cardId:s.hand[0]!.cardId});assert.equal(s.phase,'FLEE');assert.equal(s.defenseTotal,15);assert.equal(s.encounter?.attacked[0],'ANNA');});
test('Terrorscape: rage repeats only after breaking a block without finding anyone',()=>{let s=begun();s.phase='MAIN';s.level=3;assert.ok(s.locked);s.hand.push(s.locked);s.locked=null;const a=skill(s,'RAGE');s.blocks=[terrorEdge('G5','B4')];s=act(s,{...a,path:['B4']});assert.equal(s.phase,'RAGE');s=act(s,{type:'RAGE_MOVE',path:['B3']});assert.equal(s.phase,'SLOW');});
test('Terrorscape: seven-block cap needs exact explicit reallocation; outdoor paths cannot be blocked',()=>{let s=begun();s.phase='SLOW';s.killerLocation='B1';s.blocks=TERROR_DOORS.filter(([a,b])=>a!=='B1'&&b!=='B1').slice(0,7).map(([a,b])=>terrorEdge(a,b));const a=skill(s,'BARRICADE');rejected(s,{...a,edge:'B1-B2'});s=act(s,{...a,edge:'B1-B2',replaces:[s.blocks[0]!]});assert.equal(s.blocks.length,7);assert.ok(s.blocks.includes('B1-B2'));});
test('Terrorscape: corrupt conservation rejects, cancellation is idempotent with scoped revisions',()=>{const s=begun();const broken=structuredClone(s);broken.discoverDeck.push(broken.searchDeck[0]!);assert.throws(()=>parseTerrorscapeState(broken));const cancelled=cancelTerrorscape(s,now);assert.equal(cancelled.result?.reason,'CANCELLED');assert.ok(cancelled.killerRevision>s.killerRevision);assert.deepEqual(cancelTerrorscape(cancelled,now),cancelled);});
test('Terrorscape: explicitly chosen paths can return through an opened door, respecting step count',()=>{let s=begun();s.phase='MAIN';s.level=3;s.hand.push(s.locked!);s.locked=null;s.blocks=['B4-G5'];const a=skill(s,'RAGE');s=act(s,{...a,path:['B4','G5']});assert.equal(s.killerLocation,'G5');assert.equal(s.blocks.length,0);assert.equal(s.phase,'RAGE');});

test('Terrorscape: assigning roles before the hunt never exposes the initial killer hand',()=>{let s=game(3);const secretIds=s.hand.map(c=>c.cardId);for(let i=0;i<3;i++)for(const id of secretIds)assert.equal(JSON.stringify(projection(s,i)).includes(id),false);s=act(s,{type:'SET_ROLES',killerPlayerId:s.players[1]!.playerId,owners:[s.players[0]!.playerId,s.players[2]!.playerId,s.players[0]!.playerId]},s.players[0]!.playerId);for(let i=0;i<3;i++)for(const id of secretIds)assert.equal(JSON.stringify(projection(s,i)).includes(id),false);s=act(s,{type:'BEGIN_HUNT'},s.players[0]!.playerId);assert.ok(secretIds.every(id=>JSON.stringify(projection(s,1)).includes(id)));assert.ok(secretIds.every(id=>!JSON.stringify(projection(s,0)).includes(id)));});

test('Terrorscape: sense reports a zone and names without exposing exact rooms in either projection',()=>{
 let s=begun();s.phase='FAST';s.survivors[0]!.location='R2';s.survivors[1]!.location='R3';s.survivors[2]!.location='B1';
 s=act(s,skill(s,'SENSE'));
 const expected=[{kind:'ZONE',character:'WILLIAM',zone:'R'}];
 assert.deepEqual(s.sensed,expected);
 for(const i of [0,1])assert.deepEqual(projection(s,i).sensed,expected);
 assert.equal(JSON.stringify(projection(s,0).sensed).includes('R3'),false);
});
test('Terrorscape: toolbox draw noise respects Anna search immunity but not discovery',()=>{
 for(const character of ['ANNA','WILLIAM'] as const){
  let s=begun();const p=s.survivors.find(p=>p.character===character)!;p.location='R2';
  const card=s.searchDeck.find(c=>c.key==='TOOLBOX')!;s.searchDeck=s.searchDeck.filter(c=>c!==card);s.searchDeck.push(card);
  s=teamAct(s,basic(character,'SEARCH'),character);
  assert.deepEqual(s.pendingNoises,character==='ANNA'?[]:['R2']);
 }
 let s=begun();const cards=s.discoverDeck.filter(c=>c.key==='TOOLBOX');assert.equal(cards.length,2);s.discoverDeck=s.discoverDeck.filter(c=>c.key!=='TOOLBOX');s.discoverDeck.push(...cards);
 s=endTeam(s);assert.deepEqual(s.noises,['R1']);
});
test('Terrorscape: killer may forfeit one or both basic actions without drawing until slow phase ends',()=>{
 for(const remaining of [1,2]){
  let s=begun();s.phase='MAIN';s.actionsLeft=remaining;const before=s.killerDeck.length;
  rejected(s,{type:'KILLER_NEXT'},s.survivors[0]!.playerId);
  s=act(s,{type:'KILLER_NEXT'});assert.equal(s.phase,'SLOW');assert.equal(s.actionsLeft,0);assert.equal(s.killerDeck.length,before);
  rejected(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:s.killerLocation});
  s=act(s,{type:'KILLER_NEXT'});assert.equal(s.phase,'SURVIVORS');assert.equal(s.killerDeck.length,before-3);
 }
});

function castGame(killer:TerrorKiller,characters:TerrorCharacter[]=['ANNA','WILLIAM','MARCO'],n=2,map:TerrorMap='MANOR'){let s=game(n);if(map!=='MANOR')s=act(s,{type:'SET_MAP',map});s=act(s,{type:'SET_CAST',killer,characters});if(killer==='HUNTRESS'){const rooms=TERROR_ROOMS.filter(r=>terrorBoard(map).rooms[r].search||r===terrorBoard(map).radio);s=act(s,{type:'SET_TRAPS',placements:([{trap:'NET_A',room:rooms[0]!},{trap:'NET_B',room:rooms[1]!},{trap:'SKULL',room:rooms[2]!},{trap:'BEAR',room:rooms[3]!}])});}return act(s,{type:'BEGIN_HUNT'});}
test('Terrorscape base: all killer and survivor combinations preserve cards and setup hides reserves',()=>{
 for(const killer of ['BUTCHER','SPECTRE','MURDERER'] as const)for(let i=0;i<3;i++)for(let j=i+1;j<4;j++)for(let k=j+1;k<5;k++){
  const s=castGame(killer,[TERROR_CHARACTERS[i]!,TERROR_CHARACTERS[j]!,TERROR_CHARACTERS[k]!],4);
  assert.equal(s.survivors.length,3);assert.equal(s.hand.length+s.killerDeck.length+Number(Boolean(s.locked)),13);parseTerrorscapeState(s);
  assert.equal(projection(s,0).strength,killer==='SPECTRE'?2:killer==='BUTCHER'?5:4);
  for(let viewer=0;viewer<4;viewer++)for(const card of [...s.reserveItems,...s.reserveSkills])assert.equal(JSON.stringify(projection(s,viewer)).includes(card.cardId),false);
 }
 const s=game(4);rejected(s,{type:'SET_CAST',killer:'SPECTRE',characters:['ANNA','ANNA','MARCO']});rejected(s,{type:'SET_CAST',killer:'SPECTRE',characters:['ANNA','SOPHIA','JOHNSON']},s.players[1]!.playerId);
});
test('Terrorscape base: Sophia passages and one-use camera, Johnson unrestricted inventory and toolbox bonus',()=>{
 let s=castGame('BUTCHER',['SOPHIA','JOHNSON','MARCO']);s.survivors[0]!.location='B1';
 const camera=s.survivors[0]!.hand[0]!;s=teamAct(s,{type:'ITEM',character:'SOPHIA',cardId:camera.cardId,target:'SOPHIA',destination:'B1',edge:''},'SOPHIA');assert.ok(s.discard.some(c=>c.cardId===camera.cardId));assert.equal(s.survivors[0]!.acted,false);
 s=teamAct(s,{type:'PASSAGE',character:'SOPHIA'},'SOPHIA');assert.equal(s.survivors[0]!.location,'G2');assert.equal(s.survivors[0]!.acted,true);rejected(s,{type:'PASSAGE',character:'SOPHIA'},s.survivors[0]!.playerId);
 give(s,'SOPHIA','FLASHLIGHT');s=teamAct(s,{type:'PASSAGE',character:'SOPHIA'},'SOPHIA');assert.equal(s.survivors[0]!.location,'B1');
 for(const key of ['TOOLBOX','WHISKEY','HERBS','HATCHET','POWDER'] as const)give(s,'JOHNSON',key);s.survivors[1]!.location='B1';const toolbox=s.survivors[1]!.hand.find(c=>c.key==='TOOLBOX')!;
 s=teamAct(s,{type:'ITEM',character:'JOHNSON',cardId:toolbox.cardId,target:'JOHNSON',destination:'B1',edge:''},'JOHNSON');assert.equal(s.repair,3);assert.equal(s.survivors[1]!.hand.length,4);
});
test('Terrorscape base: stealth preserves blocks and hides both path and destination until reappearance',()=>{
 let s=castGame('MURDERER');s.phase='SLOW';s.killerLocation='B1';s.blocks=['B1-B2'];const card=skill(s,'STALK');
 const left=act(s,{...card,path:['B2']}),right=act(s,{...card,path:[]});const leftView=projection(left,1),rightView=projection(right,1);assert.deepEqual({...leftView,turnId:"same-transition"},{...rightView,turnId:"same-transition"});assert.equal(projection(left,1).killerLocation,null);assert.equal(left.killerLocation,'B2');assert.deepEqual(left.blocks,['B1-B2']);
 s=act(left,{type:'KILLER_NEXT'});s.survivors[0]!.location='B1';s=teamAct(s,basic('ANNA','REPAIR'));assert.equal(s.repair,1);
 s=endTeam(s);assert.equal(s.killerLocation,'B2');assert.equal(s.stealth,null);assert.equal(s.phase,'FAST');
});
test('Terrorscape base: reappearance encounter skips normal actions, Stalk only strengthens one attack',()=>{
 let s=castGame('MURDERER');s.phase='SLOW';s.level=2;s.killerLocation='R1';s=act(s,{...skill(s,'STALK'),path:[]});s=act(s,{type:'KILLER_NEXT'});s=endTeam(s);assert.equal(s.phase,'ATTACK');assert.equal(projection(s,0).strength,7);
 const stalk=handSkill(s,'STALK');s=act(s,{type:'ATTACK_CARD',cardId:stalk.cardId});assert.equal(projection(s,0).strength,8);s=teamAct(s,{type:'DEFENDER',character:'ANNA'});s=teamAct(s,{type:'DEFEND',cardId:null},'ANNA',{nextInt:()=>0});assert.equal(s.phase,'ATTACK');assert.equal(projection(s,0).strength,7);
 s=act(s,{type:'ATTACK_CARD',cardId:null});s=teamAct(s,{type:'DEFENDER',character:'WILLIAM'},'WILLIAM');s=teamAct(s,{type:'DEFEND',cardId:null},'WILLIAM');assert.equal(s.phase,'FLEE');rejected(s,{type:'KILLER_NEXT'});
});
test('Terrorscape base: Spectre overflow reaction resolves before level-five encounter injury',()=>{
 let s=castGame('SPECTRE');s.level=5;s.phase='MAIN';s.killerLocation='R1';s.survivors[0]!.fear=2;give(s,'ANNA','AMULET');while(s.hand.length<3)s.hand.push(s.killerDeck.pop()!);
 s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});assert.equal(s.phase,'REACTION');assert.equal(s.survivors[0]!.injuries,0);
 s=act(s,{type:'FEAR_REACTION',cost:s.hand.slice(0,3).map(c=>c.cardId)});assert.equal(s.phase,'DEFENDER');assert.equal(s.survivors[0]!.injuries,1);assert.ok(s.discard.some(c=>c.key==='AMULET'));
});
test('Terrorscape base: Whizz optional search, exact Trail and location-pair Deduction',()=>{
 let s=castGame('SPECTRE');s.phase='MAIN';s.level=2;s.killerLocation='G5';s=act(s,{...skill(s,'WHIZZ'),path:['B4','B3','B2','B1']});assert.equal(s.phase,'WHIZZ');s=act(s,{type:'SPECTRE_SEARCH',cost:[]});assert.equal(s.phase,'SLOW');
 s.phase='FAST';s.survivors[0]!.fear=1;s=act(s,skill(s,'TRAIL'));assert.deepEqual(s.sensed,[{kind:'LOCATION',character:'ANNA',location:'R1'}]);
 s=castGame('MURDERER');s.phase='FAST';s.survivors[1]!.location='R2';s.survivors[2]!.location='B1';s=act(s,{...skill(s,'DEDUCTION'),path:['R1','R2']});assert.deepEqual(s.sensed,[{kind:'PAIR',character:'WILLIAM',rooms:['R1','R2']}]);
});
test('Terrorscape base: Amulet blocks direct chainsaw injury but not Death Blossom',()=>{
 let s=begun();s.phase='MAIN';s.killerLocation='R1';give(s,'ANNA','AMULET');s=act(s,skill(s,'CHAINSAW'));assert.equal(s.survivors[0]!.injuries,0);assert.equal(s.survivors[1]!.injuries,1);
 s=castGame('MURDERER');give(s,'ANNA','AMULET');s.phase='SLOW';s.level=3;s.hand.push(s.locked!);s.locked=null;s.killerLocation='R1';s=act(s,skill(s,'BLOSSOM'));s=act(s,{type:'KILLER_NEXT'});s=endTeam(s);assert.equal(s.result?.reason,'KILLED');
});

function grantTrait(s:TerrorscapeState,t:TerrorTrait,c:TerrorCharacter|null=null){if(c){s.survivorTraits.find(p=>p.character===c)!.chosen=t;}else s.killerTraits.push(t);}
function traitAction(trait:TerrorTrait,character:TerrorCharacter|null=null,options:Partial<Extract<TerrorscapeAction,{type:'TRAIT_USE'}>>={}):Extract<TerrorscapeAction,{type:'TRAIT_USE'}>{return {type:'TRAIT_USE',trait,character,target:'ANNA',path:[],room:'R1',zone:'R',choice:'FEAR',cost:[],edges:[],replaces:[],...options};}
function completePlan(s:TerrorscapeState,plan:TerrorPlan){s.plansEnabled=true;s.plan={cards:[plan],active:plan,progress:TERROR_PLAN_INFO[plan].steps.length,complete:true,used:false,location:null,chooser:'ANNA'};}
function planAction(character:TerrorCharacter='ANNA',options:Partial<Extract<TerrorscapeAction,{type:'PLAN_USE'}>>={}):Extract<TerrorscapeAction,{type:'PLAN_USE'}>{return {type:'PLAN_USE',character,target:character,path:[],destination:'R1',cards:[],...options};}
test('Terrorscape variants: all 16 plans progress one step at a time, remain private and lock alternatives',()=>{
 for(const plan of TERROR_PLANS){let s=begun();s.plansEnabled=true;s.plan.cards=[plan];s.plan.chooser='ANNA';for(const step of TERROR_PLAN_INFO[plan].steps){s.phase='PLAN';for(const p of s.survivors)p.location='R1';if(step==='APART'){s.survivors[1]!.location='R2';s.survivors[2]!.location='R3';}else if(step!=='TOGETHER')s.survivors[0]!.location=step==='KILLER'?s.killerLocation:step==='BOOK'?'R5':step==='TOOLS'?'G3':step==='OCCULT'?'G2':step==='RADIO'?'B1':'G5';const before=s.plan.progress;s=teamAct(s,{type:'PLAN_PROGRESS',plan,target:'ANNA'});assert.equal(s.plan.progress,before+1,plan);if(s.phase==='LOOT')s=teamAct(s,{type:'KEEP',cardId:null});assert.equal(JSON.stringify(projection(s,0)).includes(plan),false,plan);}assert.equal(s.plan.complete,true,plan);parseTerrorscapeState(s);}
 let s=begun();s.plansEnabled=true;s.plan.cards=['BLUEPRINT','MYSTIC_HERBS'];s.plan.chooser='ANNA';s.phase='PLAN';s.survivors[0]!.location='R5';s=teamAct(s,{type:'PLAN_PROGRESS',plan:'BLUEPRINT',target:'ANNA'});s.phase='PLAN';rejected(s,{type:'PLAN_PROGRESS',plan:'MYSTIC_HERBS',target:'ANNA'},s.survivors[0]!.playerId);s.survivors[0]!.location='G2';s=teamAct(s,{type:'PLAN_PROGRESS',plan:'MYSTIC_HERBS',target:'ANNA'});assert.equal(s.plan.active,'MYSTIC_HERBS');assert.equal(s.plan.progress,1);
});
test('Terrorscape variants: plans cannot observe a stealth location; skipped progress ends discovery',()=>{
 let s=castGame('MURDERER');s.plansEnabled=true;s.plan.cards=['EXPLOSIVE'];s.plan.chooser='ANNA';s.phase='PLAN';s.stealth={origin:'G5',effect:'NONE'};s.survivors[0]!.location=s.killerLocation;
 rejected(s,{type:'PLAN_PROGRESS',plan:'EXPLOSIVE',target:'ANNA'},s.survivors[0]!.playerId);s.survivors[0]!.location='R1';s=teamAct(s,{type:'PLAN_PROGRESS',plan:null,target:'ANNA'});assert.equal(s.plan.progress,0);assert.equal(s.phase,'FAST');
});
test('Terrorscape variants: blueprint, careful repair and DIY radio apply exact repair and noise rules',()=>{
 for(const plan of ['BLUEPRINT','CAREFUL_REPAIR','DIY_RADIO'] as const){let s=begun();completePlan(s,plan);s.survivors[0]!.location='B1';const card=give(s,'ANNA','TOOLBOX');if(plan==='DIY_RADIO'){const cards=[card,give(s,'ANNA','TOOLBOX'),give(s,'ANNA','TOOLBOX')];s=teamAct(s,planAction('ANNA',{cards:cards.map(c=>c.cardId)}));assert.equal(s.repair,5);assert.equal(s.rescue,5);}else{s=teamAct(s,{type:'ITEM',character:'ANNA',cardId:card.cardId,target:'ANNA',destination:'B1',edge:''});assert.equal(s.repair,plan==='BLUEPRINT'?3:2);assert.deepEqual(s.pendingNoises,plan==='CAREFUL_REPAIR'?[]:['B1']);}}
});
test('Terrorscape variants: active plans enforce costs, once-only limits and connected secret passages',()=>{
 for(const plan of ['EXPLOSIVE','BUZZER','SKELETON_KEY'] as const){let s=begun();completePlan(s,plan);const card=give(s,'ANNA','TOOLBOX');rejected(s,planAction(),s.survivors[0]!.playerId);s=teamAct(s,planAction('ANNA',{cards:[card.cardId]}));assert.equal(s.plan.used,true);assert.ok(s.discard.some(c=>c.cardId===card.cardId));if(plan==='SKELETON_KEY')assert.equal(s.keys.length,1);else assert.equal(s.plan.location,'R1');if(plan==='BUZZER'){s=teamAct(s,planAction());assert.ok(s.pendingNoises.includes('R1'));}else rejected(s,planAction(),s.survivors[0]!.playerId);}
 let s=begun();completePlan(s,'SITE_STUDY');s=teamAct(s,planAction('ANNA',{path:['R2','R5']}));assert.equal(s.survivors[0]!.acted,false);assert.equal(s.survivors[0]!.location,'R5');rejected(s,planAction('ANNA',{path:['R2']}),s.survivors[0]!.playerId);
 s=begun();completePlan(s,'TUNNELS');s.survivors[0]!.location='B1';s=teamAct(s,planAction('ANNA',{destination:'G5'}));assert.equal(s.survivors[0]!.location,'G5');assert.equal(s.survivors[0]!.acted,true);
 s=begun();completePlan(s,'MYSTIC_HERBS');s.survivors[0]!.location='G2';s.survivors[1]!.location='G2';s.survivors[1]!.injuries=1;s.survivors[1]!.fear=2;s=teamAct(s,planAction('ANNA',{target:'WILLIAM'}));assert.equal(s.survivors[1]!.injuries,0);assert.equal(s.survivors[1]!.fear,0);
 s=begun();completePlan(s,'ANCIENT_CHEST');const amulet=give(s,'ANNA','AMULET');const before=s.searchDeck.length;s=teamAct(s,planAction('ANNA',{cards:[amulet.cardId]}));assert.equal(s.phase,'LOOT');assert.equal(s.loot?.cards.length,3);rejected(s,{type:'TRADE',character:'ANNA',target:'WILLIAM',cardId:s.loot!.cards[0]!.cardId},s.survivors[0]!.playerId);s=teamAct(s,{type:'KEEP',cardId:null});assert.equal(s.searchDeck.length,before-3);parseTerrorscapeState(s);
});
test('Terrorscape variants: strike-back victories and Molotov combine with ordinary defense correctly',()=>{
 let s=begun();completePlan(s,'EXPLOSIVE');s.plan.location='B1';s.phase='MAIN';s.killerLocation='B1';s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'B1'});assert.equal(s.result?.reason,'STRIKE_BACK');
 for(const plan of ['AMBUSH','SEAL'] as const){s=begun();completePlan(s,plan);const room=plan==='SEAL'?'G2':'R1';s.plan.location=room;s.phase='MAIN';s.killerLocation=room;for(const p of s.survivors)p.location=room;s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:room});s=teamAct(s,{type:'DEFENDER',character:'ANNA'});s=teamAct(s,{type:'DEFEND',cardId:null});assert.equal(s.result?.reason,'STRIKE_BACK');}
 s=begun();completePlan(s,'ROCKET');s.killerLocation='R2';s.phase='SLOW';s=act(s,{type:'KILLER_NEXT'});assert.equal(s.result?.reason,'STRIKE_BACK');
 s=begun();completePlan(s,'PORTAL');for(const p of s.survivors)p.location='G2';for(const item of ['SECRET_MAP','FLASHLIGHT','AMULET'] as const)give(s,'ANNA',item);s.phase='SLOW';s=act(s,{type:'KILLER_NEXT'});assert.equal(s.result?.reason,'ESCAPED');
 s=begun();completePlan(s,'MOLOTOV');give(s,'ANNA','WHISKEY');const powder=give(s,'ANNA','POWDER');s.phase='MAIN';s.killerLocation='R1';s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});s=teamAct(s,{type:'DEFENDER',character:'ANNA'});s=teamAct(s,{type:'DEFEND',cardId:powder.cardId,molotov:true},'ANNA',{nextInt:()=>0});assert.equal(s.defenseTotal,4);assert.equal(s.survivors[0]!.injuries,1);assert.ok(s.discard.some(c=>c.key==='WHISKEY'));
});
function separate(){let s=game(4);s=act(s,{type:'SET_SEPARATE',enabled:true});return act(s,{type:'BEGIN_HUNT'});}
test('Terrorscape separate ways: only four players, rotation, corpse items/keys and independent winners',()=>{
 rejected(game(3),{type:'SET_SEPARATE',enabled:true});let s=separate();const first=s.firstDiscover;assert.ok(first);for(const c of TERROR_CHARACTERS.slice(0,3)){s=teamAct(s,basic(c),c);s=teamAct(s,{type:'READY',character:c,ready:true},c);}const other=s.survivors.find(p=>p.character!==first)!;rejected(s,{type:'DISCOVER',character:other.character},other.playerId);s=teamAct(s,{type:'DISCOVER',character:first},first);s=teamAct(s,{type:'KEEP',cardId:null},first);assert.notEqual(s.firstDiscover,first);
 s=separate();const item=give(s,'ANNA','WHISKEY');const key=s.searchDeck.find(c=>c.key==='KEY')!;s.searchDeck=s.searchDeck.filter(c=>c!==key);s.keys.push(key);s.keyOwners.push({cardId:key.cardId,character:'ANNA'});s.survivors[0]!.outcome='DEAD';s.survivors[0]!.injuries=2;s=teamAct(s,{type:'CORPSE_LOOT',character:'WILLIAM',target:'ANNA',cardId:item.cardId},'WILLIAM');s=teamAct(s,{type:'CORPSE_LOOT',character:'WILLIAM',target:'ANNA',cardId:key.cardId},'WILLIAM');assert.equal(s.keyOwners[0]!.character,'WILLIAM');for(let i=0;i<2;i++){const k=s.searchDeck.find(c=>c.key==='KEY')!;s.searchDeck=s.searchDeck.filter(c=>c!==k);s.keys.push(k);s.keyOwners.push({cardId:k.cardId,character:'WILLIAM'});}s.phase='SLOW';s=act(s,{type:'KILLER_NEXT'});assert.equal(s.survivors[1]!.outcome,'ESCAPED');assert.equal(s.result,null);rejected(s,basic('WILLIAM'),s.survivors[1]!.playerId);s.survivors[2]!.injuries=1;s.phase='MAIN';s.killerLocation='R1';s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});s=teamAct(s,{type:'DEFENDER',character:'MARCO'},'MARCO');s=teamAct(s,{type:'DEFEND',cardId:null},'MARCO',{nextInt:()=>0});assert.equal(s.result?.reason,'SEPARATE_WAYS');assert.deepEqual(new Set(s.result?.winnerPlayerIds),new Set([s.killerPlayerId,s.survivors[1]!.playerId]));
});
test('Terrorscape separate ways: capped repair rewards and death-level unlock resume the encounter',()=>{
 let s=separate();s.repair=4;s.survivors[0]!.location='B1';const toolbox=give(s,'ANNA','TOOLBOX');s=teamAct(s,{type:'ITEM',character:'ANNA',cardId:toolbox.cardId,target:'ANNA',destination:'B1',edge:''});assert.equal(s.loot?.source,'REWARD');assert.equal(s.loot?.cards.length,1);s=teamAct(s,{type:'KEEP',cardId:null});assert.equal(s.round,1);assert.equal(s.repair,5);
 s=separate();s.level=2;s.phase='MAIN';s.killerLocation='R1';s.survivors[0]!.injuries=1;while(s.hand.length<5)s.hand.push(s.killerDeck.pop()!);s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});s=teamAct(s,{type:'DEFENDER',character:'ANNA'});s=teamAct(s,{type:'DEFEND',cardId:null},'ANNA',{nextInt:()=>0});assert.equal(s.phase,'UNLOCK');assert.equal(s.level,3);const deck=s.killerDeck.map(c=>c.cardId);s=act(s,{type:'UNLOCK_DISCARD',cardId:s.hand[0]!.cardId});assert.equal(s.phase,'DEFENDER');assert.deepEqual(s.killerDeck.map(c=>c.cardId),deck);assert.equal(s.survivors[0]!.outcome,'DEAD');
});

test('Terrorscape traits: all difficulties draft unique private choices and publish only chosen killer traits',()=>{
 for(const difficulty of ['EASY','NORMAL','HARD','NIGHTMARE'] as const){let s=game(4);s=act(s,{type:'SET_DIFFICULTY',difficulty});s=act(s,{type:'BEGIN_HUNT'});assert.equal(s.phase,'TRAIT_DRAFT');assert.equal(new Set(s.survivorTraits.flatMap(p=>p.offered)).size,6);for(const offer of s.survivorTraits)for(const t of offer.offered)assert.equal(JSON.stringify(projection(s,0)).includes('"'+t+'"'),false);assert.equal(projection(s,1).killerTraits.length,0);const chosen=s.killerTraitOffer.slice(0,s.killerTraitOffer.length/2);if(chosen.length)s=act(s,{type:'CHOOSE_TRAITS',character:null,traits:chosen});for(const p of s.survivorTraits)s=teamAct(s,{type:'CHOOSE_TRAITS',character:p.character,traits:[p.offered[0]!]},p.character);assert.notEqual(s.phase,'TRAIT_DRAFT');assert.deepEqual(projection(s,1).killerTraits,chosen);parseTerrorscapeState(s);}
 assert.equal(TERROR_TRAITS.filter(t=>TERROR_TRAIT_INFO[t].side==='SURVIVOR').length,20);assert.equal(TERROR_TRAITS.filter(t=>TERROR_TRAIT_INFO[t].side==='KILLER').length,20);
});
test('Terrorscape traits: survivor passive movement, healing and defense effects',()=>{
 let s=begun();grantTrait(s,'HURRIED','ANNA');s.killerLocation='R2';s=teamAct(s,{...basic('ANNA','MOVE'),path:['R2','R5','G4']});assert.equal(s.survivors[0]!.location,'G4');
 s=begun();grantTrait(s,'INTREPID','ANNA');s.survivors[0]!.fear=2;s=teamAct(s,{...basic('ANNA','MOVE'),path:['R2']});assert.equal(s.survivors[0]!.fear,1);
 s=begun();grantTrait(s,'HERBOLOGY','ANNA');s.survivors[1]!.injuries=1;const herb=give(s,'ANNA','HERBS');s=teamAct(s,{type:'ITEM',character:'ANNA',cardId:herb.cardId,target:'WILLIAM',destination:'R1',edge:''});assert.deepEqual(s.pendingNoises,[]);
 s=begun();grantTrait(s,'VIGILANT','WILLIAM');s.killerLocation='R1';const whiskey=give(s,'WILLIAM','WHISKEY');s=teamAct(s,{type:'ITEM',character:'WILLIAM',cardId:whiskey.cardId,target:'WILLIAM',destination:'R2',edge:''},'WILLIAM');assert.deepEqual(s.pendingNoises,[]);
});
test('Terrorscape traits: Martial Arts, luck, secret weapon, ammo bonus and improved flee',()=>{
 for(const t of ['MARTIAL','LUCK','SECRET_WEAPON','MARKSMAN','SURVIVAL_INSTINCT'] as const){let s=begun();grantTrait(s,t,'ANNA');s.phase='MAIN';s.killerLocation='R1';if(t==='MARKSMAN'){give(s,'ANNA','REVOLVER');give(s,'ANNA','AMMO');}s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});s=teamAct(s,{type:'DEFENDER',character:'ANNA'});if(t==='SECRET_WEAPON')s=teamAct(s,traitAction(t,'ANNA'), 'ANNA',{nextInt:()=>0});else s=teamAct(s,{type:'DEFEND',cardId:t==='MARKSMAN'?s.survivors[0]!.hand.find(c=>c.key==='AMMO')!.cardId:null},'ANNA',t==='SURVIVAL_INSTINCT'?{nextInt:()=>5}:{nextInt:()=>0});if(t==='MARTIAL')assert.equal(s.defenseTotal,1);if(t==='LUCK')assert.equal(s.phase,'FLEE');if(t==='SECRET_WEAPON'){assert.equal(s.defenseTotal,4);assert.ok(s.usedTraits.includes(t));}if(t==='MARKSMAN'){assert.equal(s.defenseTotal,5);assert.equal(s.phase,'FLEE');}if(t==='SURVIVAL_INSTINCT'){s.survivors[0]!.fear=2;s=teamAct(s,{type:'FLEE',character:'ANNA',destination:'R5',path:['R2','R5']});assert.equal(s.survivors[0]!.fear,0);assert.equal(s.survivors[0]!.location,'R5');}}
});
test('Terrorscape traits: survivor active effects enforce costs, turn consumption and once-only use',()=>{
 for(const t of ['FIRST_AID','MORALE','DECOY','JUDICIOUS','PROMPT','BURST'] as const){let s=begun();grantTrait(s,t,'ANNA');s.survivors[1]!.injuries=1;s.survivors[1]!.fear=2;s.survivors[0]!.fear=2;const a=traitAction(t,'ANNA',{target:'WILLIAM',room:'G5',path:t==='PROMPT'?['R2']:t==='BURST'?['R2','R5']:[]});s=teamAct(s,a);if(t==='FIRST_AID')assert.equal(s.survivors[1]!.injuries,0);if(t==='MORALE')assert.equal(s.survivors[1]!.fear,1);if(t==='DECOY')assert.ok(s.pendingNoises.includes('G5'));if(t==='JUDICIOUS')assert.equal(s.survivors[0]!.fear,0);if(t==='PROMPT')assert.equal(s.survivors[0]!.location,'R2');if(t==='BURST'){assert.equal(s.survivors[0]!.location,'R5');assert.ok(s.pendingNoises.includes('R1'));}assert.equal(s.survivors[0]!.acted,['FIRST_AID','MORALE','BURST'].includes(t));if(TERROR_TRAIT_INFO[t].once)rejected(s,a,s.survivors[0]!.playerId);}
 let s=begun();grantTrait(s,'TAUNT','ANNA');const before=s.killerDeck.length;s=teamAct(s,traitAction('TAUNT','ANNA'));assert.equal(s.round,1);assert.equal(s.killerDeck.length,before-4);assert.equal(s.hand.length,3);assert.equal(s.phase,'SURVIVORS');
});
test('Terrorscape traits: discovery can keep both cards or cancel only newly added discovery noise',()=>{
 for(const t of ['SLEIGHT','SILENT_RETRIEVAL'] as const){let s=begun();grantTrait(s,t,'ANNA');const boxes=s.discoverDeck.filter(c=>c.key==='TOOLBOX');s.discoverDeck=s.discoverDeck.filter(c=>c.key!=='TOOLBOX');s.discoverDeck.push(...boxes);for(const c of TERROR_CHARACTERS.slice(0,3)){s=teamAct(s,basic(c),c);s=teamAct(s,{type:'READY',character:c,ready:true},c);}s=teamAct(s,{type:'DISCOVER',character:'ANNA'});assert.ok(s.pendingNoises.includes('R1'));s=teamAct(s,traitAction(t,'ANNA'));assert.ok(s.usedTraits.includes(t));if(t==='SLEIGHT'){assert.equal(s.survivors[0]!.hand.length,2);assert.equal(s.phase,'FAST');}else {assert.deepEqual(s.pendingNoises,[]);s=teamAct(s,{type:'KEEP',cardId:null});assert.deepEqual(s.noises,[]);}}
});
test('Terrorscape traits: coordinator preserves hidden phase; heroic save moves only other controlled survivors',()=>{
 let s=begun(4);grantTrait(s,'COORDINATOR','ANNA');const before=projection(s,0);s=teamAct(s,traitAction('COORDINATOR','ANNA'));assert.equal(s.phase,'GROUP_MOVE');assert.deepEqual(projection(s,0),before);rejected(s,{type:'GROUP_MOVE',character:'WILLIAM',path:['R2']},s.survivors[0]!.playerId);s=teamAct(s,{type:'GROUP_MOVE',character:'WILLIAM',path:['R2','R5']},'WILLIAM');s=teamAct(s,{type:'GROUP_MOVE',character:'MARCO',path:[]},'MARCO');assert.equal(s.phase,'SURVIVORS');assert.deepEqual(projection(s,0),before);
 s=begun(4);grantTrait(s,'HEROIC_SAVE','ANNA');s.phase='MAIN';s.killerLocation='R1';s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});assert.equal(s.phase,'HEROIC');s=teamAct(s,traitAction('HEROIC_SAVE','ANNA'));s=teamAct(s,{type:'GROUP_MOVE',character:'WILLIAM',path:['R2']},'WILLIAM');s=teamAct(s,{type:'GROUP_MOVE',character:'MARCO',path:['R3']},'MARCO');assert.equal(s.phase,'DEFENDER');assert.deepEqual(s.encounter?.targets,['ANNA']);assert.ok(s.usedTraits.includes('HEROIC_SAVE'));
});
test('Terrorscape traits: killer start and sensing reactions never expose exact rooms',()=>{
 for(const t of ['SWIFT','ACUTE','ENHANCED'] as const){let s=begun();grantTrait(s,t);s.phase='KILLER_START';s.killerLocation='R2';s.noises=['R1'];s=act(s,traitAction(t,null,{path:['R1'],room:'R1',cost:s.hand.slice(0,t==='SWIFT'?2:1).map(c=>c.cardId)}));assert.equal(s.killerLocation,t==='SWIFT'?'R1':'R2');if(t!=='SWIFT'){assert.equal(s.sensed.length,2);assert.ok(s.sensed.every(p=>p.kind!=='LOCATION'));}rejected(s,traitAction(t));}
 for(const t of ['MURDEROUS','HEIGHTENED','IMMEDIATE'] as const){let s=begun();grantTrait(s,t);s.phase='FAST';const card=skill(s,'SENSE');s=act(s,card);assert.equal(s.phase,'SENSE_REACTION');if(!s.hand.length)s.hand.push(s.killerDeck.pop()!);s=act(s,traitAction(t,null,{cost:t==='HEIGHTENED'?[]:[s.hand[0]!.cardId],path:['B4'],zone:'B'}));if(t==='MURDEROUS')assert.deepEqual(s.survivors.map(p=>p.fear),[0,1,1]);if(t==='IMMEDIATE')assert.equal(s.killerLocation,'B4');if(t==='HEIGHTENED')assert.equal(s.sensed.length,0);s=act(s,{type:'TRAIT_PASS'});assert.equal(s.phase,'FAST');}
});
test('Terrorscape traits: end ambush, encirclement, aura, entrapment and encounter cancellation',()=>{
 for(const t of ['PERILOUS','ENCIRCLE','AURA'] as const){let s=begun();grantTrait(s,t);s.phase='KILLER_END';s.killerLocation='R1';s=act(s,traitAction(t,null,{cost:t==='AURA'?[]:s.hand.map(c=>c.cardId),edges:['R1-R2'],path:['R2']}));if(t==='PERILOUS')assert.equal(s.stealth?.origin,'R1');if(t==='ENCIRCLE')assert.ok(s.blocks.includes('R1-R2'));if(t==='AURA')assert.ok(s.survivors.every(p=>p.fear===1));s=act(s,{type:'KILLER_NEXT'});assert.equal(s.phase,'SURVIVORS');if(t==='AURA')assert.ok(s.survivors.every(p=>p.fear===1));}
 let s=begun();grantTrait(s,'ENTRAPMENT');s.phase='FAST';s=act(s,traitAction('ENTRAPMENT',null,{edges:['B1-B2','R1-R2']}));assert.equal(s.blocks.length,2);assert.ok(s.usedTraits.includes('ENTRAPMENT'));
 s=begun();grantTrait(s,'TOYING');s.phase='MAIN';s.killerLocation='R1';const before=s.killerDeck.length;s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});assert.equal(s.phase,'TOYING');s=act(s,traitAction('TOYING'));assert.equal(s.phase,'SURVIVORS');assert.equal(s.killerDeck.length,before-6);assert.ok(s.survivors.every(p=>p.injuries===0));
});
test('Terrorscape traits: level triggers and Devious overflow resume drawing without double-leveling',()=>{
 let s=begun();grantTrait(s,'DETERRENCE');grantTrait(s,'SLY');grantTrait(s,'SELF_CHALLENGE');s.level=2;s.phase='SLOW';s.killerDiscard.push(...s.killerDeck);s.killerDeck=[];s=act(s,{type:'KILLER_NEXT'});assert.equal(s.level,4);assert.equal(s.phase,'LEVEL_TRAIT');assert.deepEqual(s.levelTraitQueue,['DETERRENCE','SLY','DETERRENCE']);while(s.phase==='LEVEL_TRAIT'){const t=s.levelTraitQueue[0]!;s=act(s,traitAction(t,null,{target:'ANNA',edges:['R1-R2']}));}assert.equal(s.phase,'SURVIVORS');assert.equal(s.level,4);assert.equal(s.survivors[0]!.fear,2);assert.ok(s.blocks.includes('R1-R2'));
 s=begun();grantTrait(s,'DEVIOUS');s.phase='SLOW';while(s.hand.length<5)s.hand.push(s.killerDeck.pop()!);const before=s.killerDeck.length;s=act(s,{type:'KILLER_NEXT'});let pauses=0;while(s.phase==='UNLOCK'){pauses++;s=act(s,{type:'UNLOCK_DISCARD',cardId:s.hand[0]!.cardId});}assert.equal(pauses,3);assert.equal(s.level,1);assert.equal(s.killerDeck.length,before-3);assert.equal(s.hand.length,5);
});
test('Terrorscape traits: Fatal and Suppressed strength, Terrorising damage fear, inactive trait rejection',()=>{
 let s=begun();grantTrait(s,'FATAL');grantTrait(s,'SUPPRESSED');assert.equal(projection(s,0).strength,5);s.phase='SLOW';s.killerDiscard.push(...s.killerDeck);s.killerDeck=[];s=act(s,{type:'KILLER_NEXT'});assert.equal(projection(s,0).strength,7);
 s=begun();grantTrait(s,'TERRORISING');s.phase='MAIN';s.killerLocation='R1';s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});s=teamAct(s,{type:'DEFENDER',character:'ANNA'});s=teamAct(s,{type:'DEFEND',cardId:null},'ANNA',{nextInt:()=>0});assert.ok(s.survivors.every(p=>p.fear===1));rejected(s,traitAction('SWIFT',null,{cost:s.hand.map(c=>c.cardId),path:['R2']}));
});
test('Terrorscape traits: starting abilities use the actual decks and Lie in Wait skips its entire first turn',()=>{
 let s=game();s=act(s,{type:'SET_DIFFICULTY',difficulty:'NIGHTMARE'});s=act(s,{type:'BEGIN_HUNT'});s.killerTraitOffer=['LIE_WAIT','NIGHTMARE','DEVIOUS','FATAL','SWIFT','ACUTE'];s.survivorTraits[0]!.offered=['MARKSMAN','FIRST_AID'];s.survivorTraits[1]!.offered=['MARTIAL','PROMPT'];s.survivorTraits[2]!.offered=['INTREPID','DECOY'];s=act(s,{type:'CHOOSE_TRAITS',character:null,traits:['LIE_WAIT','NIGHTMARE','DEVIOUS']});for(const p of s.survivorTraits)s=teamAct(s,{type:'CHOOSE_TRAITS',character:p.character,traits:[p.offered[0]!]},p.character);assert.equal(s.level,2);assert.equal(s.hand.length,3);assert.ok(s.survivors.every(p=>p.fear===1));assert.ok(s.survivors[0]!.hand.some(c=>c.key==='REVOLVER'));const count=s.killerDeck.length;s=endTeam(s);assert.equal(s.round,2);assert.equal(s.phase,'SURVIVORS');assert.equal(s.killerDeck.length,count);
});
test('Terrorscape traits: heightened sensing preserves its original start-of-turn continuation',()=>{
 let s=begun();grantTrait(s,'ENHANCED');grantTrait(s,'HEIGHTENED');s.phase='KILLER_START';s.killerLocation='R2';s=act(s,traitAction('ENHANCED',null,{cost:[s.hand[0]!.cardId]}));assert.equal(s.phase,'SENSE_REACTION');s=act(s,traitAction('HEIGHTENED',null,{zone:'B'}));s=act(s,{type:'TRAIT_PASS'});assert.equal(s.phase,'KILLER_START');
});

test('Terrorscape: trap waits for the actual roll across unlock and cancellation preserves six cards',()=>{
 let s=begun();s.phase='MAIN';s.killerLocation='R1';s.trap='R1';const sword=give(s,'ANNA','LONGSWORD');s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});s=teamAct(s,{type:'DEFENDER',character:'ANNA'});s.level=2;while(s.hand.length<5)s.hand.push(s.killerDeck.pop()!);s.killerDiscard.push(...s.killerDeck);s.killerDeck=[];s=teamAct(s,{type:'DEFEND',cardId:sword.cardId});assert.equal(s.phase,'UNLOCK');assert.equal(s.trap,'R1');assert.equal(s.dice.length,0);assert.equal(cancelTerrorscape(s,now).result?.reason,'CANCELLED');s=act(s,{type:'UNLOCK_DISCARD',cardId:s.hand[0]!.cardId});assert.equal(s.trap,null);assert.equal(s.defenseTotal,17);
});
test('Terrorscape: dead survivors cannot receive mandatory plan rewards or healing',()=>{
 let s=separate();s.survivors[1]!.outcome='DEAD';s.survivors[1]!.injuries=2;completePlan(s,'MYSTIC_HERBS');s.survivors[0]!.location='G2';s.survivors[1]!.location='G2';rejected(s,planAction('ANNA',{target:'WILLIAM'}),s.survivors[0]!.playerId);
 s=separate();s.survivors[1]!.outcome='DEAD';s.survivors[1]!.injuries=2;s.phase='PLAN';s.plansEnabled=true;s.plan.cards=['INTEL'];s.plan.active='INTEL';s.plan.progress=TERROR_PLAN_INFO.INTEL.steps.length-1;s.plan.chooser='ANNA';const step=TERROR_PLAN_INFO.INTEL.steps.at(-1);for(const p of s.survivors)p.location=step==='BOOK'?'R5':step==='TOOLS'?'G3':step==='OCCULT'?'G2':step==='RADIO'?'B1':step==='EXIT'?'G5':s.killerLocation;rejected(s,{type:'PLAN_PROGRESS',plan:'INTEL',target:'WILLIAM'},s.survivors[0]!.playerId);
});
test('Terrorscape: paid skills discard costs before the played card and Molotov suppresses Martial Arts',()=>{
 let s=begun();s.phase='MAIN';const command=skill(s,'CHAINSAW');s=act(s,command);assert.deepEqual(s.killerDiscard.slice(-3).map(c=>c.cardId),[...command.cost,command.cardId]);
 s=begun();grantTrait(s,'MARTIAL','ANNA');completePlan(s,'MOLOTOV');give(s,'ANNA','WHISKEY');s.phase='MAIN';s.killerLocation='R1';s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});s=teamAct(s,{type:'DEFENDER',character:'ANNA'});s=teamAct(s,{type:'DEFEND',cardId:null,molotov:true},'ANNA',{nextInt:()=>0});assert.equal(s.defenseTotal,2);
});

test('Terrorscape: connected tunnels apply to flashlights and Sophia retains her extra action',()=>{
 let s=castGame('SPECTRE',['SOPHIA','JOHNSON','WILLIAM']);completePlan(s,'TUNNELS');const flash=give(s,'SOPHIA','FLASHLIGHT');s.survivors[0]!.location='B1';s.survivors[0]!.acted=true;s=teamAct(s,{type:'ITEM',character:'SOPHIA',cardId:flash.cardId,target:'SOPHIA',destination:'G5',edge:''},'SOPHIA');assert.equal(s.survivors[0]!.location,'G5');s=teamAct(s,planAction('SOPHIA',{destination:'G2'}),'SOPHIA');assert.equal(s.survivors[0]!.location,'G2');assert.ok(s.survivors[0]!.hand.some(c=>c.cardId===flash.cardId));
});

// Runs complete games using legal commands only; no canonical state is patched.
test('Terrorscape full play: every base and Feral cast on both maps with 2–4 players reaches a legal ending and preserves viewer privacy',()=>{
 for(const map of ['MANOR','CABIN'] as const)for(const killer of ['BUTCHER','SPECTRE','MURDERER','WEREWOLF','HUNTRESS'] as const)for(const players of [2,3,4])for(let i=0;i<3;i++)for(let j=i+1;j<4;j++)for(let k=j+1;k<5;k++){
  let s=castGame(killer,[TERROR_CHARACTERS[i]!,TERROR_CHARACTERS[j]!,TERROR_CHARACTERS[k]!],players,map),commands=0;
  const step=(action:TerrorscapeAction,character?:TerrorCharacter)=>{const before=s;s=character?teamAct(s,action,character,{nextInt:()=>0}):act(s,action,s.killerPlayerId,{nextInt:()=>0});commands++;assert.ok(s.revision>before.revision);assert.deepEqual(parseTerrorscapeState(s),s);for(let viewer=0;viewer<players;viewer++){const view=projection(s,viewer),json=JSON.stringify(view);if(view.privateState.role==='KILLER'){assert.ok(!('team' in view.privateState));for(const card of [...s.searchDeck,...s.discoverDeck,...s.survivors.flatMap(p=>p.hand)])assert.equal(json.includes(card.cardId),false);}else for(const card of [...s.hand,...s.killerDeck])assert.equal(json.includes(card.cardId),false);}};
  while(!s.result&&commands<160){
   switch(s.phase){
    case 'SURVIVORS':{const unacted=s.survivors.find(p=>!p.acted);if(unacted){step(basic(unacted.character),unacted.character);break;}const unready=s.survivors.find(p=>!p.ready);if(unready){step({type:'READY',character:unready.character,ready:true},unready.character);break;}const p=s.survivors[0]!;step({type:'DISCOVER',character:p.character},p.character);break;}
    case 'LOOT':step({type:'KEEP',cardId:null},s.loot!.character);break;
    case 'FAST':case 'SLOW':case 'KILLER_END':step({type:'KILLER_NEXT'});break;
    case 'MAIN':{const next=terrorPaths(s.killerLocation,15,[],map,true).get('R1')?.[0];step({type:'KILLER_BASIC',kind:s.killerLocation==='R1'?'SEARCH':'MOVE',destination:next??'R1'});break;}
    case 'ATTACK':step({type:'ATTACK_CARD',cardId:null});break;
    case 'DEFENDER':{const c=s.encounter!.targets.find(c=>!s.encounter!.attacked.includes(c))!;step({type:'DEFENDER',character:c},c);break;}
    case 'DEFEND':step({type:'DEFEND',cardId:null},s.encounter!.defender!);break;
    case 'FLEE':{const c=s.encounter!.fleePending[0]!;step({type:'FLEE',character:c,destination:s.survivors.find(p=>p.character===c)!.location},c);break;}
    case 'REACTION':step({type:'FEAR_REACTION',cost:[]});break;
    case 'UNLOCK':step({type:'UNLOCK_DISCARD',cardId:s.hand[0]!.cardId});break;
    default:assert.fail(`Unhandled full-play phase: ${s.phase}`);
   }
  }
  assert.equal(s.result?.reason,'KILLED',`${killer}/${players}/${i}${j}${k} after ${commands} commands`);assert.deepEqual(s.result.winnerPlayerIds,[s.killerPlayerId]);
 }
});

test('Terrorscape full play: repair and rescue finish legally across all base killers and player counts',()=>{
 for(const killer of ['BUTCHER','SPECTRE','MURDERER'] as const)for(const players of [2,3,4]){
  let s=castGame(killer,['SOPHIA','JOHNSON','WILLIAM'],players),commands=0;
  const step=(a:TerrorscapeAction,c?:TerrorCharacter)=>{s=c?teamAct(s,a,c):act(s,a);commands++;parseTerrorscapeState(s);for(let viewer=0;viewer<players;viewer++)projection(s,viewer);};
  while(!s.result&&commands<220){switch(s.phase){
   case 'SURVIVORS':{const p=s.survivors.find(p=>!p.acted);if(p){step(p.location!=='B1'?{...basic(p.character,'MOVE'),path:['B1']}:basic(p.character,!s.repaired&&s.repair<5?'REPAIR':'CALM'),p.character);break;}const unready=s.survivors.find(p=>!p.ready);if(unready){step({type:'READY',character:unready.character,ready:true},unready.character);break;}step({type:'DISCOVER',character:'JOHNSON'},'JOHNSON');break;}
   case 'LOOT':step({type:'KEEP',cardId:null},s.loot!.character);break;
   case 'FAST':case 'MAIN':case 'SLOW':step({type:'KILLER_NEXT'});break;
   case 'UNLOCK':step({type:'UNLOCK_DISCARD',cardId:s.hand[0]!.cardId});break;
   case 'LEVEL_BLOCK':{const edge=TERROR_DOORS.map(([a,b])=>terrorEdge(a,b)).find(e=>!s.blocks.includes(e))!;step({type:'LEVEL_BLOCK',edge,replaces:s.blocks.length===7?[s.blocks[0]!]:[]});break;}
   default:assert.fail(`Unhandled rescue phase: ${s.phase}`);
  }}
  assert.equal(s.result?.reason,'RESCUED');assert.equal(s.repair,5);assert.deepEqual(s.result.winnerPlayerIds,s.players.filter(p=>p.playerId!==s.killerPlayerId).map(p=>p.playerId));
 }
});

function feral(killer:'WEREWOLF'|'HUNTRESS',map:'MANOR'|'CABIN'='CABIN',begin=true){let s=game(4);s=act(s,{type:'SET_MAP',map});s=act(s,{type:'SET_CAST',killer,characters:['ANNA','WILLIAM','SOPHIA']});if(killer==='HUNTRESS')s=act(s,{type:'SET_TRAPS',placements:map==='CABIN'?[{trap:'NET_A',room:'R3'},{trap:'NET_B',room:'G4'},{trap:'SKULL',room:'B2'},{trap:'BEAR',room:'B3'}]:[{trap:'NET_A',room:'R2'},{trap:'NET_B',room:'G4'},{trap:'SKULL',room:'B4'},{trap:'BEAR',room:'B1'}]});return begin?act(s,{type:'BEGIN_HUNT'}):s;}
test('Feral: setup conserves 114 unique cards, all map/killer combinations remain independent',()=>{
 for(const map of ['MANOR','CABIN'] as const)for(const killer of ['WEREWOLF','HUNTRESS'] as const){const s=feral(killer,map);parseTerrorscapeState(s);assert.equal(s.rulesVersion,'terrorscape-feral-v2');assert.equal(s.hand.length+s.killerDeck.length+Number(!!s.locked),13);assert.equal(s.specialDeck.length,killer==='WEREWOLF'?4:0);assert.equal(s.huntTraps.length,killer==='HUNTRESS'?4:0);for(let i=0;i<4;i++){const json=JSON.stringify(projection(s,i));for(const c of [...s.reserveItems,...s.reserveSkills,...s.specialDeck])assert.equal(json.includes(c.cardId),false);}}
 let s=game(4);s=act(s,{type:'SET_CAST',killer:'HUNTRESS',characters:['ANNA','WILLIAM','MARCO']});rejected(s,{type:'BEGIN_HUNT'});rejected(s,{type:'SET_TRAPS',placements:[{trap:'NET_A',room:'R2'},{trap:'NET_A',room:'B4'},{trap:'SKULL',room:'G4'},{trap:'BEAR',room:'B1'}]});
});
test('Feral Cabin: killer-only passage affects movement but not range; survivors cannot cross',()=>{
 let s=feral('WEREWOLF');s.survivors[0]!.location='G2';rejected(s,{...basic('ANNA','MOVE'),path:['R5']},s.survivors[0]!.playerId);s.phase='MAIN';s.killerLocation='G2';s=act(s,{type:'KILLER_BASIC',kind:'MOVE',destination:'R5'});assert.equal(s.killerLocation,'R5');
 s.phase='FAST';s.survivors[0]!.location='G2';s=act(s,{...skill(s,'HOWL'),path:['R3']});assert.equal(s.survivors[0]!.fear,0,'killer passage must not shorten fear range');
 s=feral('WEREWOLF');s.survivors[2]!.location='R5';s=teamAct(s,{type:'PASSAGE',character:'SOPHIA'},'SOPHIA');assert.equal(s.survivors[2]!.location,'B2');
});
test('Feral Cabin: suitcase extra action, noisy card, key pooling, reuse and repair symbol',()=>{
 let s=feral('WEREWOLF');s.survivors[0]!.location='R4';const key=s.discoverDeck.find(c=>c.key==='KEY')!;s.discoverDeck=s.discoverDeck.filter(c=>c!==key);s.discoverDeck.push(key);s=teamAct(s,{type:'OPEN_CACHE',character:'ANNA',kind:'SUITCASE'});assert.equal(s.keys.length,1);assert.equal(s.suitcase,false);assert.equal(s.survivors[0]!.acted,false);assert.ok(s.pendingNoises.includes('R4'));rejected(s,{type:'OPEN_CACHE',character:'ANNA',kind:'SUITCASE'},s.survivors[0]!.playerId);
 s.survivors[0]!.location='B1';rejected(s,basic('ANNA','REPAIR'),s.survivors[0]!.playerId);s.survivors[0]!.location='B3';s=teamAct(s,basic('ANNA','REPAIR'));assert.equal(s.repair,1);s.phase='SLOW';s=act(s,{type:'KILLER_NEXT'});assert.equal(s.suitcase,true);
});
test('Feral Werewolf: treasure collection and silver weapons are private and conserve cards',()=>{
 let s=feral('WEREWOLF');s.survivors[0]!.location='R5';const before=projection(s,0);s=teamAct(s,{type:'OPEN_CACHE',character:'ANNA',kind:'TREASURE'});assert.equal(s.survivors[0]!.hand.length,1);assert.equal(s.survivors[0]!.acted,false);assert.equal(s.specialDeck.length,3);assert.deepEqual(projection(s,0),before);rejected(s,{type:'OPEN_CACHE',character:'ANNA',kind:'TREASURE'},s.survivors[0]!.playerId);
 for(const key of ['SILVER_DAGGER','SILVER_BULLETS'] as const){s=feral('WEREWOLF');const c=s.specialDeck.find(c=>c.key===key)!;s.specialDeck=s.specialDeck.filter(x=>x!==c);s.survivors[0]!.hand.push(c);if(key==='SILVER_BULLETS')give(s,'ANNA','REVOLVER');s.phase='MAIN';s.killerLocation='R1';s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});s=act(s,{type:'ATTACK_CARD',cardId:null});s=teamAct(s,{type:'DEFENDER',character:'ANNA'});s=teamAct(s,{type:'DEFEND',cardId:c.cardId},'ANNA',{nextInt:()=>1});assert.equal(s.defenseTotal,key==='SILVER_DAGGER'?9:20);assert.equal(s.survivors[0]!.hand.some(x=>x.cardId===c.cardId),key==='SILVER_DAGGER');}
});
test('Feral Werewolf: hyper-hearing nearest noise, current noise, mandatory howl and blood hunt movement',()=>{
 let s=feral('WEREWOLF','MANOR');s.level=2;s.hand.push(s.locked!);s.locked=null;s.phase='FAST';s.killerLocation='B3';s.noises=['B4','B2'];const a=skill(s,'HYPER_HEARING');rejected(s,{...a,path:['B2','R1']});s=act(s,{...a,path:['B4']});assert.equal(s.killerLocation,'B4');assert.equal(s.phase,'FAST');
 s=feral('WEREWOLF','MANOR');s.level=2;s.hand.push(s.locked!);s.locked=null;s.phase='FAST';s.noises=['G5','B4'];const hearing=skill(s,'HYPER_HEARING');rejected(s,{...hearing,path:['B4']});s=act(s,hearing);assert.equal(s.killerLocation,'G5');
 s=feral('WEREWOLF');s.phase='FAST';rejected(s,{...skill(s,'HOWL'),path:[]});const blood=skill(s,'BLOOD_HUNT');rejected(s,{...blood,path:['B4','B3']});s.survivors[0]!.injuries=1;s=act(s,{...blood,path:['B4','B3']});assert.equal(s.killerLocation,'B3');
});
test('Feral Huntress: initial types remain secret, net interrupts sprint and blocks all further movement until next round',()=>{
 let s=feral('HUNTRESS');s.survivors[1]!.location='R4';const secret=projection(s,1);assert.equal(JSON.stringify(secret).includes('NET_A'),false);assert.deepEqual(new Set(secret.huntingTrapRooms),new Set(['R3','G4','B2','B3']));s=teamAct(s,{...basic('WILLIAM','SPRINT'),path:['R3','B4','B5']},'WILLIAM');assert.equal(s.survivors[1]!.location,'R3');assert.equal(s.survivors[1]!.immobilized,true);assert.ok(s.pendingNoises.includes('R3'));assert.equal(projection(s,0).trapReveal?.room,'R3');const adrenaline=give(s,'WILLIAM','ADRENALINE');rejected(s,{type:'ITEM',character:'WILLIAM',cardId:adrenaline.cardId,target:'WILLIAM',destination:'B4',edge:''},s.survivors[1]!.playerId);s.phase='SLOW';s=act(s,{type:'KILLER_NEXT'});assert.equal(s.survivors[1]!.immobilized,false);
});
test('Feral Huntress: skull and bear traps resolve mid-route, amulet prevents direct injury, second injury stops flee terminally',()=>{
 let s=feral('HUNTRESS');s.survivors[0]!.location='B2';s=teamAct(s,{...basic('ANNA','MOVE'),path:['B3','B4']});assert.equal(s.survivors[0]!.injuries,1);assert.equal(s.survivors[0]!.location,'B4');assert.equal(s.huntTraps.some(t=>t.trap==='BEAR'),false);
 s=feral('HUNTRESS');s.survivors[0]!.location='B3';s=teamAct(s,{...basic('ANNA','MOVE'),path:['B2','B3']});assert.equal(s.survivors[0]!.fear,2);assert.equal(s.survivors[0]!.injuries,1);assert.equal(s.survivors[0]!.location,'B3');
 s=feral('HUNTRESS');s.survivors[0]!.location='B2';give(s,'ANNA','AMULET');s=teamAct(s,{...basic('ANNA','MOVE'),path:['B3']});assert.equal(s.survivors[0]!.injuries,0);assert.equal(s.survivors[0]!.hand.some(c=>c.key==='AMULET'),false);
 s=feral('HUNTRESS');s.survivors[0]!.location='B2';s.survivors[0]!.injuries=1;s.phase='FLEE';s.encounter={location:'B2',targets:['ANNA'],attacked:['ANNA'],defender:null,fleePending:['ANNA']};s=teamAct(s,{type:'FLEE',character:'ANNA',destination:'B3'});assert.equal(s.result?.reason,'KILLED');assert.equal(s.survivors[0]!.location,'B3');assert.equal(s.pendingDraw,null);
});
test('Feral Huntress: attack discount, tracking skips later effects on encounter, and reset neither reveals types nor triggers occupied traps',()=>{
 let s=feral('HUNTRESS');s.level=3;s.phase='MAIN';s.killerLocation='R1';s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});const axe=handSkill(s,'AXE_THROW');s=act(s,{type:'ATTACK_CARD',cardId:axe.cardId,cost:[]});assert.equal(projection(s,0).strength,7);
 s=feral('HUNTRESS');s.phase='FAST';s.level=4;s.killerLocation='R1';s=act(s,{...skill(s,'TRACKING'),cost:[],target:'ANNA',path:['G1']});assert.equal(s.phase,'ATTACK');assert.equal(s.tracking,null);assert.equal(s.killerLocation,'R1');
 s=feral('HUNTRESS');s.level=2;s.hand.push(s.locked!);s.locked=null;s.phase='MAIN';s=act(s,{...skill(s,'TRAPS_RESET'),path:['R5']});assert.equal(s.phase,'RESET_TRAPS');assert.equal(projection(s,1).killerLocation,null);s=act(s,{type:'SET_TRAPS',placements:[{trap:'BEAR',room:'R1'},{trap:'SKULL',room:'R3'},{trap:'NET_A',room:'B1'},{trap:'NET_B',room:'G5'}]});assert.equal(s.phase,'SLOW');assert.equal(s.survivors[0]!.injuries,0);assert.equal(projection(s,1).trapReveal,null);assert.equal(JSON.stringify(projection(s,1)).includes('BEAR'),false);
});
test('Feral Huntress: Bated Breath preserves a validated continuation through level-up and its bonus lasts through next turn',()=>{
 let s=feral('HUNTRESS');s.phase='MAIN';const action=skill(s,'BATED_BREATH');s.killerDiscard.push(...s.killerDeck);s.killerDeck=[];rejected(s,{...action,path:['R1']});s=act(s,{...action,path:['G5']});assert.equal(s.level,2);assert.equal(s.stealth?.origin,'B5');assert.equal(s.killerLocation,'G5');assert.equal(projection(s,0).strength,6);s=act(s,{type:'KILLER_NEXT'});assert.equal(projection(s,0).strength,6);s.phase='SLOW';s=act(s,{type:'KILLER_NEXT'});assert.equal(projection(s,0).strength,3);
});

test('Feral: attack skills cannot bypass encounter timing through KILLER_CARD, silver bullets require a revolver',()=>{
 let s=feral('WEREWOLF');s.phase='MAIN';s.killerLocation='R1';s=act(s,{type:'KILLER_BASIC',kind:'SEARCH',destination:'R1'});rejected(s,{...skill(s,'SAVAGE_BITE'),path:['G1']});const bite=handSkill(s,'SAVAGE_BITE');s=act(s,{type:'ATTACK_CARD',cardId:bite.cardId});assert.equal(projection(s,0).strength,8);const c=s.specialDeck.find(c=>c.key==='SILVER_BULLETS')!;s.specialDeck=s.specialDeck.filter(x=>x!==c);s.survivors[0]!.hand.push(c);s=teamAct(s,{type:'DEFENDER',character:'ANNA'});rejected(s,{type:'DEFEND',cardId:c.cardId},s.survivors[0]!.playerId);
});
test('Feral: territorial sensing reports a candidate set, tracking reports only distance and wolf aura resolves once',()=>{
 let s=feral('WEREWOLF');s.phase='FAST';s.survivors[0]!.location='R3';s.survivors[1]!.location='R3';s.survivors[2]!.location='G4';s=act(s,skill(s,'TERRITORIAL'));assert.deepEqual(s.sensed.map(x=>x.character),['WILLIAM','SOPHIA']);for(const x of s.sensed){assert.equal(x.kind,'PAIR');if(x.kind==='PAIR')assert.deepEqual(new Set(x.rooms),new Set(['R3','B2','G4']));}
 s=feral('HUNTRESS');s.level=4;s.phase='FAST';s.killerLocation='B5';s=act(s,{...skill(s,'TRACKING'),cost:[],target:'ANNA',path:['B4']});assert.equal(s.tracking?.origin,'B5');assert.ok(s.tracking!.distance>0);assert.equal(s.killerLocation,'B4');assert.equal(s.sensed.length,0);assert.deepEqual(Object.keys(s.tracking!).sort(),['character','distance','origin']);
 s=feral('WEREWOLF');s.level=4;s.phase='SLOW';s.killerLocation='R3';s.survivors[0]!.location='R5';s=act(s,{type:'KILLER_NEXT'});assert.equal(s.phase,'KILLER_END');s=act(s,{type:'KILLER_NEXT'});assert.equal(s.phase,'SURVIVORS');assert.equal(s.survivors[0]!.fear,1);
});
