import {CABIN_ROOMS,CABIN_DOORS,CABIN_OUTDOOR} from './cabin-layout.js';
import {HUNT_TRAP_NAME} from './feral.js';
import {useId,useState} from 'react';
import {terrorBoard,TERROR_ROOMS,terrorEdge,type TerrorRoom,type TerrorscapeProjection} from '@hangul-rummikub/shared';
import {MANOR_ROOMS as BASE_ROOMS,MANOR_DOORS as BASE_DOORS,MANOR_OUTDOOR as BASE_OUTDOOR,type Point} from './manor-layout.js';
import type {TerrorFeedback} from './feedback.js';
import {Portrait} from './art.js';

type Props={feedback?:readonly TerrorFeedback[];game:TerrorscapeProjection;start:TerrorRoom;path:readonly TerrorRoom[];destination:TerrorRoom|null;activeRooms:readonly TerrorRoom[];notes:readonly TerrorRoom[];edge:string;disabled:boolean;onRoom(room:TerrorRoom):void;onDoor(edge:string):void};
export function ManorMap({feedback=[],game:g,start,path,destination,activeRooms,notes,edge,disabled,onRoom,onDoor}:Props){
 const board=terrorBoard(g.map),TERROR_ROOM_INFO=board.rooms,TERROR_DOORS=board.doors,cabin=g.map==='CABIN',MANOR_ROOMS=cabin?CABIN_ROOMS:BASE_ROOMS,MANOR_DOORS=cabin?CABIN_DOORS:BASE_DOORS,MANOR_OUTDOOR=cabin?CABIN_OUTDOOR:BASE_OUTDOOR,width=cabin?1606:1290,height=cabin?1004:910;
 const id=useId().replaceAll(':',''),[zoom,setZoom]=useState(false),team=g.privateState.role==='SURVIVOR'?g.privateState.team:null;
 const route:Point[]=[];let previous=start;
 for(const room of path){if(!route.length)route.push(MANOR_ROOMS[previous].furniture);const gate=MANOR_DOORS[terrorEdge(previous,room)]?.at??MANOR_OUTDOOR[terrorEdge(previous,room)];if(gate)route.push(gate);route.push(MANOR_ROOMS[room].furniture);previous=room;}
 return <><div className="tsc-floor-tools"><span>방을 눌러 이동 · 문을 눌러 봉쇄 대상 선택</span><button aria-pressed={zoom} onClick={()=>setZoom(!zoom)}>{zoom?'지도 전체 보기':'지도 확대'}</button></div><div className="tsc-map-scroll"><svg viewBox={`-35 -35 ${width} ${height}`} className={'tsc-floorplan'+(cabin?' tsc-cabin-map':'')+(zoom?' tsc-floor-zoom':'')} aria-label={cabin?'오두막 평면도':'저택 평면도'}>
 <defs>
 {TERROR_ROOMS.map(r=><clipPath key={r} id={`${id}-${r}`}><polygon points={MANOR_ROOMS[r].polygon}/></clipPath>)}
 </defs>
 <rect x="-35" y="-35" width={width} height={height} rx="24" fill="#1d2b27"/>
 <image className="tsc-floor-art" href={cabin?'/images/terrorscape/cabin-floorplan.webp':'/images/terrorscape/manor-floorplan.webp'} x="-35" y="-35" width={width} height={height} preserveAspectRatio="none" aria-hidden="true" pointerEvents="none"/>
 {TERROR_ROOMS.map(r=>{const info=TERROR_ROOM_INFO[r],layout=MANOR_ROOMS[r],at=team?.survivors.filter(p=>p.location===r&&p.outcome!=='ESCAPED')??[],tokens=[...(g.killerLocation===r?[g.killerType]:[]),...at.map(p=>p.character)];return <g key={r} className={'tsc-floor-room '+(r[0]==='R'?'tsc-zone-red':r[0]==='B'?'tsc-zone-blue':'tsc-zone-green')+(destination===r?' tsc-floor-picked':'')+(activeRooms.includes(r)?' tsc-floor-reachable':'')} role="button" tabIndex={0} aria-label={`${info.name}${g.noises.includes(r)?' · 소음':''}${g.killerLocation===r?' · 살인마':''}`} aria-pressed={destination===r} onClick={()=>onRoom(r)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onRoom(r);}}}>
 <title>{`${r} ${info.name} · ${info.hint||'일반 장소'}`}</title>
 <polygon className="tsc-floor-base" points={layout.polygon} fill="transparent" stroke="#182322" strokeWidth="5" strokeLinejoin="round"/>
 <g clipPath={`url(#${id}-${r})`}><polygon className="tsc-zone-border" points={layout.polygon} fill="none" strokeWidth="20"/><polygon className="tsc-floor-highlight" points={layout.polygon}/></g>
 <g transform={`translate(${layout.label[0]} ${layout.label[1]})`} className="tsc-floor-label"><rect x={cabin?-77:-87} y="-20" width={cabin?154:174} height="35" rx="4"/><text textAnchor="middle" y="4"><tspan className="tsc-floor-code">{r} </tspan>{info.name}</text></g>
 {info.search&&<g className="tsc-passage-badge" aria-hidden="true" transform={`translate(${layout.label[0]+72} ${layout.label[1]-43})`}><circle r="19"/><circle cx="-3" cy="-5" r="6" fill="none" stroke="#f2e9c9" strokeWidth="3"/><path d="M-3 1V12H5M-3 7H3" fill="none" stroke="#f2e9c9" strokeWidth="3"/></g>}
 {[board.radio,board.book,board.occult,board.tools].some(feature=>feature===r)&&<g className="tsc-floor-feature" transform={`translate(${layout.label[0]-63} ${layout.label[1]-41})`}><rect x="-22" y="-15" width="44" height="28" rx="5"/><text textAnchor="middle" y="5">{r===board.radio?'수리':r===board.book?'책':r===board.occult?'주술':'공구'}</text></g>}
 {Boolean(board.passages[r])&&<g className="tsc-passage-badge" transform={`translate(${layout.label[0]+(info.search?27:72)} ${layout.label[1]-43})`}><circle r="19"/><text textAnchor="middle" y="6">{(cabin?r==='R5'||r==='B2':r==='B1'||r==='G2')?'Ⅰ':'Ⅱ'}</text></g>}
 {tokens.map((c,i)=>{const killer=c===g.killerType,width=killer?64:44;return <foreignObject key={c} x={layout.furniture[0]+(i-(tokens.length-1)/2)*68-width/2} y={layout.furniture[1]-(killer?43:25)} width={width} height={killer?70:52} className={'tsc-floor-token'+(killer?' tsc-floor-killer':'')}><div className="tsc-token-face"><Portrait character={c}/>{killer&&<span className="tsc-killer-tag">살인자</span>}</div></foreignObject>;})}
 {g.noises.includes(r)&&<g className="tsc-floor-noise" transform={`translate(${layout.label[0]-68} ${layout.label[1]-42})`}><circle r="18"/><text textAnchor="middle" y="7">◉</text></g>}
 {notes.includes(r)&&g.privateState.role==='KILLER'&&<text x={layout.furniture[0]} y={layout.furniture[1]+57} className="tsc-floor-note">?</text>}
 {g.huntingTrapRooms.includes(r)&&<g className="tsc-hunt-trap" transform={`translate(${layout.furniture[0]+(cabin&&r==='B3'?20:0)} ${layout.furniture[1]+40})`}><rect x="-40" y="-11" width="80" height="22" rx="5"/><text textAnchor="middle" y="5">{g.privateState.role==='KILLER'?HUNT_TRAP_NAME[g.privateState.killer.traps.find(t=>t.room===r)?.trap??'NET_A']:'? 함정'}</text></g>}
 {team?.treasures.includes(r)&&<text x={layout.label[0]} y={layout.label[1]-35} className="tsc-floor-cache">보물 상자</text>}
 {team&&cabin&&r==='R4'&&<text x={layout.label[0]} y={layout.label[1]-35} className="tsc-floor-cache">{team.suitcase?'여행 가방':'가방 사용함'}</text>}
 {team?.trap===r&&<text x={layout.label[0]} y={layout.label[1]-30} className="tsc-floor-note">덫</text>}
 </g>;})}
 <g className="tsc-map-effects" aria-hidden="true">{TERROR_ROOMS.map(room=>{const event=[...feedback].reverse().find(e=>e.rooms.includes(room)&&!e.edge);if(!event)return null;const layout=MANOR_ROOMS[room];return <g key={event.id+room} className={'tsc-map-effect tsc-effect-'+event.kind}><polygon points={layout.polygon}/><g transform={`translate(${layout.label[0]} ${layout.label[1]-44})`}><rect x="-46" y="-14" width="92" height="27" rx="6"/><text textAnchor="middle" y="5">{{TRAP:'함정 발동',MOVE:'이동',NOISE:'소음',SENSE:'감지 범위',ATTACK:'조우!',HURT:'부상',FEAR:'공포',DEFENSE:'방어',REVEAL:'재등장',BLOCK:'봉쇄',TURN:'차례',WIN:'종료',CARD:'카드'}[event.kind]}</text></g></g>;})}</g>
 <g className="tsc-outdoor-boundaries"><path d={cabin?'M487.507 3.46L431.813 56.089M127.018 311.137L290.048 138.069M433.839 396.153L267.77 561.125M952.295 196.77L1156.842 196.77M1246.965 368.827L1205.448 446.758M1026.216 446.758L1205.448 446.758M1205.448 446.758L1189.246 653.226L1157.855 815.161':'M540 740Q527 777 540 833M850 740Q837 777 850 833M1013 487Q1054 582 1214 585'}/></g>
 {route.length>1&&<polyline className="tsc-floor-route" points={route.map(p=>p.join(',')).join(' ')}/>}
 {TERROR_DOORS.map(([a,b])=>{const key=terrorEdge(a,b),door=MANOR_DOORS[key]!,blocked=g.blocks.includes(key);return <g key={key} className={'tsc-floor-door'+(feedback.some(e=>e.edge===key)?' tsc-door-feedback':'')+(blocked?' is-blocked':'')+(edge===key?' is-selected':'')} transform={`translate(${door.at[0]} ${door.at[1]}) rotate(${door.angle})`} role="button" tabIndex={disabled?-1:0} aria-disabled={disabled} aria-pressed={edge===key} aria-label={`${TERROR_ROOM_INFO[a].name} ↔ ${TERROR_ROOM_INFO[b].name} 문${blocked?' · 봉쇄':''}`} onClick={()=>{if(!disabled)onDoor(key);}} onKeyDown={e=>{if(!disabled&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onDoor(key);}}}><rect className="tsc-door-hit" x="-43" y="-22" width="86" height="44"/><rect x="-36" y="-9" width="72" height="18" rx="2" className="tsc-door-plank"/>{blocked?<path d="M-25 -6L25 6M-25 6L25 -6"/>:<path d="M-27 0H27"/>}</g>;})}
 {cabin?<g className="tsc-floor-exit"><path d="M597 750L580 790M1090 66L1130 108"/><text x="601" y="814">정문</text><text x="1090" y="90">숨겨진 출구</text></g>:<g className="tsc-floor-exit"><path d="M0 338v67M1220 338v67"/><text transform="translate(-14 375) rotate(-90)" textAnchor="middle">정문 출구</text><text transform="translate(1239 375) rotate(90)" textAnchor="middle">숨겨진 출구</text></g>}
 {cabin&&<path d="M573 304L437 362" stroke="#e8b956" strokeWidth="6" strokeDasharray="5 12" pointerEvents="none"><title>살인자 전용 이동 통로 · R5 ↔ G2</title></path>}
 </svg></div><div className="tsc-feedback-feed" role="log" aria-live="polite" aria-relevant="additions text">{feedback.slice(-4).map(e=><p key={e.id} className={'tsc-feedback-entry tsc-effect-'+e.kind}>{e.text}</p>)}</div>{edge&&<p className="tsc-door-selection" role="status">선택한 문: {edge.split('-').map(r=>TERROR_ROOMS.find(room=>room===r)).map(r=>r?TERROR_ROOM_INFO[r].name:'').join(' ↔ ')} · 카드 또는 행동에서 확정하세요.</p>}
 <div className="tsc-map-legend"><span>흰색 문 · 봉쇄 가능</span><span>붉은 × · 봉쇄됨</span><span>야외 점선 · 봉쇄 불가</span><span>{cabin?'Ⅰ 101호↔호숫가 별장 · Ⅱ 채석장↔동쪽 야영지':'Ⅰ 거실↔무덤 · Ⅱ 연회장↔정원'}</span>{cabin&&<span>금색 점선 · 살인자 이동/은신 통로</span>}<span>열쇠 표시 · 수색 / ◉ 소음</span></div></>;
}
