import {useEffect,useRef,useState} from 'react';
import type {TerrorscapeProjection} from '@hangul-rummikub/shared';
type Cue='STEP'|'CARD'|'NOISE'|'BLOCK'|'FEAR'|'DEFENSE'|'HURT'|'TURN'|'WIN'|'NONE'|'SELECT';
const read=(key:string,fallback:number)=>{try{const raw=localStorage.getItem(key),n=Number(raw);return raw!==null&&Number.isFinite(n)?Math.min(100,Math.max(0,n)):fallback;}catch{return fallback;}};
/** Original procedural score. Never receives hidden positions, cards or canonical game state. */
class TerrorAudio {
 context:AudioContext|null=null;music:GainNode|null=null;effects:GainNode|null=null;timer:ReturnType<typeof setInterval>|null=null;beat=0;musicVolume=22;effectVolume=40;active=true;
 async unlock(){if(!this.context){const c=new AudioContext();this.context=c;const compressor=c.createDynamicsCompressor();compressor.threshold.value=-18;compressor.ratio.value=8;compressor.connect(c.destination);this.music=c.createGain();this.effects=c.createGain();this.music.connect(compressor);this.effects.connect(compressor);this.setVolumes(this.musicVolume,this.effectVolume);this.score();this.timer=setInterval(()=>this.score(),4000);}if(this.active&&document.visibilityState==='visible')await this.context.resume();}
 setVolumes(m:number,e:number){this.musicVolume=m;this.effectVolume=e;const c=this.context;if(c){this.music?.gain.setTargetAtTime(m/100*.2,c.currentTime,.15);this.effects?.gain.setTargetAtTime(e/100*.3,c.currentTime,.05);}}
 tone(freq:number,at:number,duration:number,volume:number,dest:AudioNode,type:OscillatorType='sine',end?:number){const c=this.context;if(!c)return;const osc=c.createOscillator(),gain=c.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,at);if(end)osc.frequency.exponentialRampToValueAtTime(end,at+duration);gain.gain.setValueAtTime(.0001,at);gain.gain.exponentialRampToValueAtTime(Math.max(.0002,volume),at+.04);gain.gain.exponentialRampToValueAtTime(.0001,at+duration);osc.connect(gain);gain.connect(dest);osc.start(at);osc.stop(at+duration+.05);osc.onended=()=>{osc.disconnect();gain.disconnect();};}
 wind(at:number,duration:number,volume:number,dest:AudioNode,frequency=450){const c=this.context;if(!c)return;const buffer=c.createBuffer(1,Math.ceil(c.sampleRate*duration),c.sampleRate),data=buffer.getChannelData(0);let brown=0;for(let i=0;i<data.length;i++){brown=(brown+(Math.random()*2-1)*.02)/1.02;data[i]=brown*3.5;}const source=c.createBufferSource(),filter=c.createBiquadFilter(),gain=c.createGain();source.buffer=buffer;filter.type='lowpass';filter.frequency.value=frequency;gain.gain.setValueAtTime(.0001,at);gain.gain.linearRampToValueAtTime(volume,at+Math.min(.2,duration/3));gain.gain.exponentialRampToValueAtTime(.0001,at+duration);source.connect(filter);filter.connect(gain);gain.connect(dest);source.start(at);source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();};}
 score(){const c=this.context,m=this.music;if(!c||!m||c.state!=='running'||!this.active||!this.musicVolume)return;const t=c.currentTime;this.tone(55,t,5,.19,m,'triangle');this.tone(55.35,t,5,.13,m);this.tone(82.41,t,4.8,.09,m);this.wind(t,4.9,.1,m);const notes=[220,261.63,207.65,164.81,246.94,196];this.tone(notes[this.beat%notes.length]!,t+1.2,3.8,.09,m);this.tone(notes[this.beat%notes.length]!*2,t+1.24,2.2,.022,m);this.beat++;}
 play(cue:Cue){const c=this.context,e=this.effects;if(!c||!e||c.state!=='running'||!this.active||cue==='NONE')return;const t=c.currentTime;if(cue==='SELECT'){this.tone(460,t,.09,.12,e);return;}if(cue==='STEP'){this.wind(t,.18,.5,e,250);this.wind(t+.24,.18,.4,e,220);}else if(cue==='CARD'){this.wind(t,.25,.25,e,2200);}else if(cue==='NOISE'||cue==='BLOCK'){this.tone(cue==='BLOCK'?95:720,t,.35,.3,e,'triangle',55);this.wind(t,.4,.4,e,900);}else if(cue==='HURT'||cue==='FEAR'){this.tone(110,t,1,.28,e,'sawtooth',45);this.tone(116,t,.8,.14,e,'triangle');}else if(cue==='DEFENSE'){[0,.12,.24].forEach(o=>this.wind(t+o,.12,.3,e,1300));this.tone(220,t+.4,.4,.2,e);}else if(cue==='WIN'){[220,261.63,329.63].forEach((f,i)=>this.tone(f,t+i*.3,2,.2,e));}else {this.tone(110,t,1.8,.22,e);this.tone(164.81,t+.25,1.6,.15,e);}}
 async pause(hidden:boolean){this.active=!hidden;if(this.context){if(hidden)await this.context.suspend();else await this.context.resume();}}
 close(){if(this.timer)clearInterval(this.timer);this.timer=null;void this.context?.close();this.context=null;}
}
export function useTerrorSound(g:TerrorscapeProjection|null,connected:boolean){const [music,setMusic]=useState(()=>read('terror.music',22)),[effects,setEffects]=useState(()=>read('terror.effects',40)),[audioError,setAudioError]=useState(false);const engine=useRef<TerrorAudio|null>(null);const seen=useRef<{game:string;id:number}|null>(null);
 useEffect(()=>{const a=new TerrorAudio();engine.current=a;const visibility=()=>{void a.pause(document.hidden||!connected).catch(()=>setAudioError(true));};document.addEventListener('visibilitychange',visibility);visibility();return()=>{document.removeEventListener('visibilitychange',visibility);a.close();engine.current=null;};},[connected]);
 useEffect(()=>{engine.current?.setVolumes(music,effects);try{localStorage.setItem('terror.music',String(music));localStorage.setItem('terror.effects',String(effects));}catch{/* Browser storage is optional; current-session audio controls still work. */}},[music,effects,connected]);
 useEffect(()=>{if(!g){seen.current=null;return;}const last=g.history.at(-1);if(seen.current?.game===g.gameId&&last&&last.id>seen.current.id)engine.current?.play(last.sound);seen.current={game:g.gameId,id:last?.id??0};},[g]);
 return {music,effects,setMusic,setEffects,audioError,unlock:()=>{void engine.current?.unlock().catch(()=>setAudioError(true));},play:(cue:Cue)=>engine.current?.play(cue)};
}
