import {useState,useRef,useEffect,type CSSProperties} from 'react';
import {TERROR_CHARACTERS,TERROR_CHARACTER_INFO,TERROR_ROOMS,TERROR_ROOM_INFO,TERROR_DOORS,TERROR_PATHS,TERROR_PASSAGES,TERROR_ITEM_INFO,TERROR_SKILL_INFO,terrorPaths,terrorEdge,terrorAdjacent,PROTOCOL_VERSION,type TerrorCharacter,type TerrorRoom,type TileId,type PlayerId,type TerrorscapeAction,type TerrorscapeClientCommand,type TerrorscapeProjection,type TerrorCard} from '@hangul-rummikub/shared';
import type {TerrorscapeWebSnapshot} from '../../lib/snapshot-wire-decoder.js';
import {createRequestId} from '../../lib/request-id.js';
import {getGameStartControl} from '../../lib/game-start.js';
import {TerrorscapeCommandRejected} from '../../lib/terrorscape-command-error.js';
import {useTerrorSound} from './sound.js';
import {Portrait,ItemFace,SkillFace} from './art.js';
type Props={snapshot:TerrorscapeWebSnapshot;connected:boolean;pending:boolean;error:string|null;connectionLabel:string;onCommand(command:TerrorscapeClientCommand):Promise<void>;onRematch():void;onStart():void;onLeave():void;onCopy():void};
const phases:Record<TerrorscapeProjection['phase'],string>={SETUP:'배역을 선택하세요',SURVIVORS:'숨죽여 움직일 시간',LOOT:'발견한 물건을 살펴보세요',KILLER:'사냥이 시작되었습니다',FAST:'빠른 카드 단계',MAIN:'살인마 행동 단계',SLOW:'느린 카드 단계',RAGE:'분노가 계속됩니다',UNLOCK:'새로운 능력 각성',DEFENDER:'누가 먼저 맞설까요?',DEFEND:'살아남기 위한 방어',FLEE:'지금, 달아나세요',FINISHED:'저택의 밤이 끝났습니다'};
export function TerrorscapeScreen(props:Props){const {snapshot:s}=props;const sound=useTerrorSound(s.game,props.connected),start=getGameStartControl(s,props.pending||!props.connected);return <section className="terror-screen" aria-label="테러스케이프" onPointerDownCapture={sound.unlock} onKeyDownCapture={e=>{if(e.key==='Enter'||e.key===' ')sound.unlock();}}>
 <header className="tsc-header"><div><span className="tsc-eyebrow">A NIGHT IN THE MANOR</span><h1>TERRORSCAPE <small>테러스케이프</small></h1></div><div className="tsc-tools"><span className="tsc-connection" role="status">{props.connectionLabel}</span><details className="tsc-audio"><summary>♫ 소리 설정</summary><div><label>공포 배경음악 {sound.music}%<input aria-label="배경음악 음량" type="range" min="0" max="100" value={sound.music} onChange={e=>sound.setMusic(Number(e.target.value))}/></label><label>상호작용 효과음 {sound.effects}%<input aria-label="효과음 음량" type="range" min="0" max="100" value={sound.effects} onChange={e=>sound.setEffects(Number(e.target.value))}/></label><button onClick={()=>{sound.setMusic(0);sound.setEffects(0);}}>모든 소리 끄기</button><button onClick={()=>{sound.setMusic(22);sound.setEffects(40);sound.unlock();sound.play('TURN');}}>소리 켜기</button><small>{sound.audioError?'브라우저 소리 재생을 허용한 뒤 소리 켜기를 눌러주세요.':'첫 클릭 후 음악이 시작됩니다. 다른 탭으로 이동하면 멈춥니다.'}</small></div></details><button onClick={props.onCopy}>초대 · {s.room.roomCode}</button><button disabled={props.pending} onClick={props.onLeave}>나가기</button></div></header>
 {props.error&&<p className="tsc-error" role="alert">{props.error}</p>}
 {s.game?<Table key={s.game.gameId+':'+s.self.playerId} {...props} game={s.game} selectSound={()=>sound.play('SELECT')}/>:<div className="tsc-lobby"><div className="tsc-lobby-copy"><span className="tsc-eyebrow">ONE KILLER. THREE SURVIVORS.</span><h2>문은 잠겼다.<br/>누군가 듣고 있다.</h2><p>흩어져 열쇠를 찾고, 무전기를 고치세요.<br/>살인마에게 들키기 전에, 모두 함께 탈출해야 합니다.</p><div className="tsc-seats">{s.room.players.map(p=><div key={p.playerId}><span className={p.connectionStatus==='CONNECTED'?'tsc-online':''}>●</span> {p.nickname}<small>{p.isHost?'방장':'참가자'}</small></div>)}</div><button className="tsc-primary" disabled={!start.canStart} onClick={props.onStart}>저택에 들어가기 →</button><p className="tsc-muted">{start.guidance}</p><small>2–4인 · 저택 / 도살자 개발판 · 시간 제한 없음</small></div></div>}
 <details className="tsc-guide"><summary>생존 안내서 <span>조작법과 승리 조건</span></summary><div><p><b>화면 조작</b> 담당 캐릭터 → 행동 → 지도 목적지를 선택하고 확정합니다. 카드를 누르면 설명과 사용·전달 방법이 나타납니다. 지도 아래 목적지 목록도 사용할 수 있습니다.</p><p><b>탈출</b> 열쇠 5개와 세 생존자가 모두 대현관에 모여 다음 생존자 차례를 맞으면 승리합니다. 비밀 지도가 있으면 정원에서도 탈출합니다. 거실 무전기를 5 수리하면 5차례 뒤 구조됩니다. 수리는 팀 전체에서 라운드당 한 번입니다.</p><p><b>생존자 차례</b> 각 캐릭터가 기본 행동을 한 번 합니다. 아이템 추가 행동과 같은 장소의 교환도 가능합니다. 모두 행동을 마치고 준비 완료를 누른 후 한 캐릭터가 발견 카드 2장 중 최대 1장을 가져갑니다. 소음은 차례가 끝날 때 공개됩니다.</p><p><b>살인마 차례</b> 빠른 카드 → 기본 행동 두 번 또는 특수 카드 하나 → 느린 카드 최대 한 장 → 카드 3장 뽑기. 기본 이동은 한 칸이며 수색해야 조우합니다. 이동 중 봉쇄를 부숩니다.</p><p><b>방어와 도주</b> 각 담당자가 자신의 캐릭터를 방어자로 선택할 수 있습니다. 공포에 따라 4~2개의 주사위를 굴려 공격력 이상이면 성공. 실패하면 부상, 두 번째 부상은 팀 패배입니다. 조우가 끝나면 같은 장소의 생존자는 인접 한 칸 도주하거나 머무릅니다.</p><p><b>정보와 소리</b> 팀 위치·아이템·탈출 준비는 생존자만 봅니다. 살인마의 추측 표시는 이 브라우저에만 저장됩니다. 음악과 효과음은 개별 조절이 가능하며, 화면에 없는 비밀 정보를 소리로 전달하지 않습니다.</p></div></details>
 </section>;}
function Table({game:g,selectSound,...props}:Props&{game:TerrorscapeProjection;selectSound():void}){
 const self=props.snapshot.self.playerId,people=props.snapshot.room.players,killer=g.privateState.role==='KILLER',team=g.privateState.role==='SURVIVOR'?g.privateState.team:null,kh=g.privateState.role==='KILLER'?g.privateState.killer:null;
 const [character,setCharacter]=useState<TerrorCharacter>(()=>team?.survivors.find(p=>p.playerId===self)?.character??'ANNA');
 const p=team?.survivors.find(p=>p.character===character),mine=p?.playerId===self;
 const [mode,setMode]=useState<'MOVE'|'SPRINT'|'ITEM'|'KILLER'|'FLEE'|'NOTE'>('MOVE'),[destination,setDestination]=useState<TerrorRoom|null>(null),[cardId,setCardId]=useState<TileId|null>(null),[target,setTarget]=useState<TerrorCharacter>('ANNA'),[edge,setEdge]=useState(''),[zone,setZone]=useState<'R'|'B'|'G'>('R'),[cost,setCost]=useState<TileId[]>([]),[replaces,setReplaces]=useState<string[]>([]);
 const [manualMode,setManualMode]=useState(false),[manualPath,setManualPath]=useState<TerrorRoom[]>([]);
 const [flight,setFlight]=useState(false),[retry,setRetry]=useState<TerrorscapeClientCommand|null>(null),[message,setMessage]=useState<string|null>(null),[mobile,setMobile]=useState<'MAP'|'ACTIONS'|'LOG'>('MAP');
 const busy=useRef(false),mounted=useRef(true),scope=g.phase==='FINISHED'?'finished':g.turnId,scopeRef=useRef(scope);scopeRef.current=scope;
 const noteKey=`terror.notes:${g.gameId}:${self}`;
 const [notes,setNotes]=useState<TerrorRoom[]>(()=>{try{const x:unknown=JSON.parse(localStorage.getItem(noteKey)??'[]');return Array.isArray(x)?TERROR_ROOMS.filter(r=>x.includes(r)):[];}catch{return [];}});
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useEffect(()=>{setDestination(null);setManualPath([]);setManualMode(false);setCardId(null);setCost([]);setReplaces([]);setEdge('');setRetry(null);setMessage(null);},[scope,character]);
 const disabled=!props.connected||props.pending||flight||retry!==null||g.phase==='FINISHED';
 const name=(id:PlayerId)=>people.find(p=>p.playerId===id)?.nickname??'플레이어';
 async function send(command:TerrorscapeClientCommand){if(busy.current||!props.connected)return;busy.current=true;setFlight(true);setMessage(null);const sent=scope;try{await props.onCommand(command);if(mounted.current&&scopeRef.current===sent)setRetry(null);}catch(e){if(mounted.current&&scopeRef.current===sent){if(e instanceof TerrorscapeCommandRejected){setRetry(null);setMessage(e.message);}else {setRetry(command);setMessage('응답을 확인하지 못했습니다. 같은 요청의 결과를 다시 확인해주세요.');}}}finally{busy.current=false;if(mounted.current)setFlight(false);}}
 function act(payload:TerrorscapeAction){if(g.phase==='FINISHED'||disabled)return;selectSound();void send({kind:'terrorscape:act',protocolVersion:PROTOCOL_VERSION,requestId:createRequestId(),gameId:g.gameId,expectedGameRevision:g.gameRevision,turnId:g.turnId,payload});}
 const basic=(kind:Extract<TerrorscapeAction,{type:'BASIC'}>['kind'],path:TerrorRoom[]=[],id:TileId|null=null)=>act({type:'BASIC',character,kind,path,edge,cardId:id});
 const selectedItem=p?.hand.find(c=>c.cardId===cardId),selectedSkill=kh?.hand.find(c=>c.cardId===cardId);
 const start=killer?g.killerLocation:p?.location??'R1';
 const steps=mode==='FLEE'||selectedItem?.key==='ADRENALINE'?1:mode==='SPRINT'?3:killer?(selectedSkill?.key==='RAGE'||g.phase==='RAGE'?2:1):2;
 const paths=terrorPaths(start,steps,killer?[]:g.blocks);
 const doors=TERROR_DOORS.filter(([a,b])=>a===start||b===start).map(([a,b])=>terrorEdge(a,b));
 const path=manualMode?manualPath:destination?paths.get(destination)??[]:[];
 function pickRoom(room:TerrorRoom){selectSound();if(mode==='NOTE'&&killer){const next=notes.includes(room)?notes.filter(r=>r!==room):[...notes,room];setNotes(next);try{localStorage.setItem(noteKey,JSON.stringify(next));}catch{setMessage('이 브라우저에는 추측 메모를 저장할 수 없습니다. 현재 화면에서는 유지됩니다.');}return;}if(manualMode){const from=manualPath.at(-1)??start;if(manualPath.length>=steps||!terrorAdjacent(from,room)||!killer&&g.blocks.includes(terrorEdge(from,room))){setMessage('남은 이동 횟수 안에서 연결된 장소를 선택하세요.');return;}setManualPath([...manualPath,room]);setMessage(null);}setDestination(room);}
 const showMove=(killer&&selectedSkill&&['PURSUE','RAGE','CHAINSAW'].includes(selectedSkill.key))||(!killer&&mine&&g.phase==='SURVIVORS'&&!p?.acted&&(mode==='MOVE'||mode==='SPRINT'))||(killer&&mode!=='NOTE'&&['MAIN','RAGE'].includes(g.phase))||mode==='ITEM'||g.phase==='FLEE';
 const activeRooms=mode==='NOTE'?TERROR_ROOMS:manualMode?TERROR_ROOMS.filter(r=>manualPath.length<steps&&terrorAdjacent(manualPath.at(-1)??start,r)&&(killer||!g.blocks.includes(terrorEdge(manualPath.at(-1)??start,r)))):showMove?[...paths.keys()]:[];
 const itemUse=()=>selectedItem&&act({type:'ITEM',character,cardId:selectedItem.cardId,target,destination:destination??start,edge});
 const full=team?.survivors.some(p=>p.hand.length>3)??false;
 return <div className="tsc-game">
 <div className="tsc-turn"><div><span className="tsc-eyebrow">ROUND {String(g.round).padStart(2,'0')} · {killer?'KILLER':'SURVIVORS'}</span><h2>{phases[g.phase]}</h2></div><div className="tsc-role"><Portrait character={killer?'BUTCHER':character}/><div><b>{killer?'당신은 살인마입니다':'당신은 생존자입니다'}</b><small>{killer?'소음과 흔적을 좇으세요':'팀의 위치와 계획은 비공개입니다'}</small></div></div></div>
 {g.phase==='SETUP'&&message&&<p className="tsc-error" role="alert">{message}</p>}{g.phase==='SETUP'&&retry&&<button disabled={flight||!props.connected} onClick={()=>void send(retry)}>같은 요청 결과 다시 확인</button>}
 {g.phase==='SETUP'?<Setup g={g} people={people} self={self} disabled={disabled} act={act}/>:<>
 {g.phase==='FINISHED'&&<div className="tsc-result" role="status"><span className="tsc-eyebrow">THE END</span><h2>{g.result.reason==='CANCELLED'?'게임이 중단되었습니다':['ESCAPED','RESCUED'].includes(g.result.reason)?'생존자 팀 승리':'살인마 승리'}</h2><p>{{ESCAPED:'생존자 전원이 저택을 탈출했습니다.',RESCUED:'구조대가 도착했습니다.',KILLED:'생존자가 두 번째 부상을 입었습니다.',EXHAUSTED:'생존에 필요한 시간이 다했습니다.',CANCELLED:'참가자가 방에서 나갔습니다.'}[g.result.reason]}</p>{people.find(p=>p.playerId===self)?.isHost&&<button className="tsc-primary" disabled={props.pending||!props.connected} onClick={props.onRematch}>새로운 밤 준비하기</button>}</div>}
 <div className="tsc-status"><div><span>도살자</span><b>레벨 {g.level}</b><small>공격력 {g.strength}</small></div><div><span>공개 소음</span><b>{g.firecracker?'폭죽':g.noises.length+'곳'}</b><small>봉쇄 {g.blocks.length}/7</small></div>{team?<><div><span>열쇠</span><b>{team.keys} / 5</b><small>모두 함께 탈출</small></div><div><span>무전기</span><b>{team.repair} / 5</b><small>{team.rescue!==null?`구조까지 ${team.rescue}차례`:team.repaired?'이번 수리 완료':'거실에서 수리'}</small></div><div><span>남은 발견</span><b>{team.discoverCount}장</b><small>수색 {team.searchCount}장</small></div></>:<div><span>추적의 원칙</span><b>보이지 않는 생존자</b><small>수색으로 조우 · 감지는 안나 제외</small></div>}</div>
 <div className="tsc-survivors">{g.conditions.map(c=>{const visible=team?.survivors.find(p=>p.character===c.character),owner=g.owners[TERROR_CHARACTERS.indexOf(c.character)]!;return <button key={c.character} className={(character===c.character?'tsc-character-selected ':'')+(visible?.acted?'tsc-acted':'')} onClick={()=>{setCharacter(c.character);setMode('MOVE');selectSound();}}><Portrait character={c.character}/><span><b>{TERROR_CHARACTER_INFO[c.character].name} <em>{owner===self?'나':name(owner)}</em></b><small>{visible?TERROR_ROOM_INFO[visible.location].name:'위치 비공개'} · 공포 {c.fear}/2 · 부상 {c.injuries}/2</small><small>{visible?(visible.ready?'✓ 준비 완료':visible.acted?'행동 완료 · 추가 행동 가능':'기본 행동 가능'):TERROR_CHARACTER_INFO[c.character].ability}</small></span></button>;})}</div>
 <nav className="tsc-mobile-nav" aria-label="게임 화면"><button aria-pressed={mobile==='MAP'} onClick={()=>setMobile('MAP')}>저택 지도</button><button aria-pressed={mobile==='ACTIONS'} onClick={()=>setMobile('ACTIONS')}>행동 · 카드</button><button aria-pressed={mobile==='LOG'} onClick={()=>setMobile('LOG')}>기록</button></nav>
 <div className={'tsc-layout tsc-mobile-'+mobile}>
 <main className="tsc-map-column"><div className="tsc-map-caption"><span>THE MANOR <small>저택 · 연결 지도</small></span>{killer?<button aria-pressed={mode==='NOTE'} onClick={()=>setMode(mode==='NOTE'?'KILLER':'NOTE')}>{mode==='NOTE'?'추측 표시 중 · 종료':'추측 메모'}</button>:<span>● 생존자 팀 전용 위치</span>}</div><div className="tsc-map-scroll"><div className="tsc-map"><svg viewBox="0 0 1000 720" aria-hidden="true" className="tsc-map-lines">{[...TERROR_DOORS,...TERROR_PATHS].map(([a,b])=>{const x=TERROR_ROOM_INFO[a],y=TERROR_ROOM_INFO[b],blocked=g.blocks.includes(terrorEdge(a,b)),highlight=path.some((to,i)=>terrorEdge(i?path[i-1]!:start,to)===terrorEdge(a,b));return <g key={terrorEdge(a,b)}><line x1={x.x*10} y1={x.y*7.2} x2={y.x*10} y2={y.y*7.2} className={(blocked?'tsc-blocked-line ':'')+(highlight?'tsc-route-line':'')}/>{blocked&&<text x={(x.x+y.x)*5} y={(x.y+y.y)*3.6}>×</text>}</g>;})}</svg>
 {TERROR_ROOMS.map((r,i)=>{const info=TERROR_ROOM_INFO[r],at=team?.survivors.filter(p=>p.location===r)??[],sensed=g.sensed.filter(p=>p.location===r);return <button key={r} className={'tsc-room '+(destination===r?'tsc-room-picked ':'')+(activeRooms.includes(r)?'tsc-reachable ':'')+(g.noises.includes(r)?'tsc-noisy ':'')+(g.killerLocation===r?'tsc-killer-here':'')} style={{left:info.x+'%',top:info.y+'%','--room-art-x':`${i%4/3*100}%`,'--room-art-y':`${Math.floor(i/4)/3*100}%`} as CSSProperties} onClick={()=>pickRoom(r)} aria-label={`${info.name}${g.noises.includes(r)?' · 소음':''}${g.killerLocation===r?' · 살인마':''}`} aria-pressed={destination===r}><span className="tsc-room-art"/><span className="tsc-room-label"><small>{r} {info.search?'⌕':''}</small><b>{info.name}</b></span><span className="tsc-room-tokens">{g.killerLocation===r&&<Portrait character="BUTCHER"/>}{at.map(p=><Portrait key={p.character} character={p.character}/>)}{!team&&sensed.map(p=><span className="tsc-sensed" key={p.character}>{TERROR_CHARACTER_INFO[p.character].name} 감지</span>)}</span>{g.noises.includes(r)&&<span className="tsc-noise" aria-hidden="true">◉</span>}{notes.includes(r)&&killer&&<span className="tsc-note">?</span>}{team?.trap===r&&<span className="tsc-trap">덫</span>}</button>;})}
 </div></div><div className="tsc-map-legend"><span>청록 · 선택 가능한 경로</span><span>붉은 × · 봉쇄</span><span>◉ · 공개 소음</span><span>통로 · 거실↔묘지 / 연회장↔정원</span></div>
 <div className="tsc-destination"><label>목적지<select value={destination??''} onChange={e=>{const r=TERROR_ROOMS.find(r=>r===e.target.value);if(r)pickRoom(r);}}><option value="">지도 또는 목록에서 선택</option>{TERROR_ROOMS.map(r=><option key={r} value={r}>{TERROR_ROOM_INFO[r].name}{paths.has(r)?' · '+paths.get(r)!.length+'칸':''}</option>)}</select></label>{destination&&<p>{path.length?[start,...path].map(r=>TERROR_ROOM_INFO[r].name).join(' → '):TERROR_ROOM_INFO[destination].hint||TERROR_ROOM_INFO[destination].name}</p>}</div>
 {showMove&&<div className="tsc-route-tools"><label><input type="checkbox" checked={manualMode} onChange={e=>{setManualMode(e.target.checked);setManualPath([]);setDestination(null);}}/>직접 경로 선택 · 중간 장소부터 차례로 클릭</label>{manualMode&&<button onClick={()=>{const next=manualPath.slice(0,-1);setManualPath(next);setDestination(next.at(-1)??null);}}>마지막 한 칸 취소 ({manualPath.length}/{steps})</button>}</div>}
 {!killer&&mine&&g.phase==='SURVIVORS'&&!p?.acted&&(mode==='MOVE'||mode==='SPRINT')&&<div className="tsc-map-confirm"><button className="tsc-primary" disabled={disabled||full||!path.length} onClick={()=>basic(mode==='SPRINT'?'SPRINT':'MOVE',path)}>{destination?TERROR_ROOM_INFO[destination].name+' 이동 확정':'지도에서 목적지를 선택하세요'}</button></div>}
 {!killer&&<div className="tsc-pings"><span>팀에게 알리기</span>{(['GO','SEARCH','REPAIR','HELP'] as const).map(message=><button key={message} disabled={disabled||!destination} onClick={()=>destination&&act({type:'PING',room:destination,message})}>{{GO:'여기로 모여요',SEARCH:'수색할게요',REPAIR:'수리할게요',HELP:'도와주세요'}[message]}</button>)}{team?.pings.map((ping,i)=><small key={i}>{name(ping.playerId)} · {TERROR_ROOM_INFO[ping.room].name} · {{GO:'모여요',SEARCH:'수색',REPAIR:'수리',HELP:'도움 요청'}[ping.message]}</small>)}</div>}
 </main>
 <aside className="tsc-actions"><span className="tsc-eyebrow">YOUR NEXT MOVE</span><h3>{killer?'사냥의 계획':TERROR_CHARACTER_INFO[character].name}</h3>
 {message&&<p className="tsc-error" role="alert">{message}</p>}{retry&&<button disabled={flight||!props.connected} onClick={()=>void send(retry)}>같은 요청 결과 다시 확인</button>}{!props.connected&&<p role="status">연결 복구를 기다리고 있습니다.</p>}
 {g.phase==='SURVIVORS'&&team&&p&&<><p className="tsc-muted">{TERROR_CHARACTER_INFO[character].ability}</p>{!mine?<p>{name(p.playerId)}님이 조작하는 캐릭터입니다.</p>:<>
 {p.hand.length>3?<><h4>소지 한도 3장 · 한 장을 버리세요</h4><div className="tsc-cards">{p.hand.map(c=><button key={c.cardId} disabled={disabled} onClick={()=>act({type:'DISCARD',character,cardId:c.cardId})}><ItemFace item={c.key}/><b>버리기</b></button>)}</div></>:<>
 {!p.acted&&<div className="tsc-action-grid"><button disabled={disabled||full} aria-pressed={mode==='MOVE'} onClick={()=>{setMode('MOVE');setCardId(null);}}>발소리 낮춰 이동<small>최대 2칸</small></button><button disabled={disabled||full} onClick={()=>basic('CALM')}>진정하기<small>공포 모두 제거</small></button><button disabled={disabled||full||!TERROR_ROOM_INFO[p.location].search||p.location===g.killerLocation||team.searchCount===0} onClick={()=>basic('SEARCH')}>주변 수색<small>지정 장소 · 1장</small></button><button disabled={disabled||full||p.location!=='B1'||p.location===g.killerLocation||team.repaired||team.rescue!==null} onClick={()=>basic('REPAIR')}>무전기 수리<small>진행 +1 · 소음</small></button>{character==='WILLIAM'&&<button disabled={disabled||full} onClick={()=>{setMode('SPRINT');setCardId(null);}}>달리기<small>3칸 · 목적지 소음</small></button>}</div>}
 {!p.acted&&(mode==='MOVE'||mode==='SPRINT')&&<button className="tsc-primary" disabled={disabled||full||!path.length} onClick={()=>basic(mode==='SPRINT'?'SPRINT':'MOVE',path)}>{destination?TERROR_ROOM_INFO[destination].name+' 이동 확정':'지도에서 목적지를 선택하세요'}</button>}
 {!p.acted&&g.blocks.some(e=>doors.includes(e))&&<><DoorSelect doors={doors.filter(e=>g.blocks.includes(e))} value={edge} set={setEdge}/><button disabled={disabled||full||!edge} onClick={()=>basic('REMOVE_BLOCK')}>봉쇄 제거 · 기본 행동 / 즉시 소음</button></>}
 {!p.acted&&character==='MARCO'&&team.discard.some(c=>['ADRENALINE','TRANQUILIZER'].includes(c.key))&&<details><summary>마르코 · 약품 회수</summary>{team.discard.filter(c=>['ADRENALINE','TRANQUILIZER'].includes(c.key)).map(c=><button disabled={disabled||full} key={c.cardId} onClick={()=>basic('RECOVER',[],c.cardId)}>{TERROR_ITEM_INFO[c.key].name} 회수</button>)}</details>}
 {p.acted&&<button className={p.ready?'':'tsc-primary'} disabled={disabled||full} onClick={()=>act({type:'READY',character,ready:!p.ready})}>{p.ready?'준비 완료 취소':'추가 행동도 마쳤어요 · 준비 완료'}</button>}
 {team.survivors.every(p=>p.acted&&p.ready)&&<button className="tsc-primary" disabled={disabled||full} onClick={()=>act({type:'DISCOVER',character})}>{TERROR_CHARACTER_INFO[character].name}이 발견 카드 확인 · 팀 차례 종료</button>}
 <h4>소지품 <span>{p.hand.length}/3</span></h4><div className="tsc-cards">{p.hand.map(c=><button key={c.cardId} aria-pressed={cardId===c.cardId} onClick={()=>{setCardId(c.cardId);setManualPath([]);setManualMode(false);setMode('ITEM');setDestination(null);setTarget(character);selectSound();}}><ItemFace item={c.key}/></button>)}</div>{!p.hand.length&&<p className="tsc-muted">빈 주머니. 수색하거나 동료에게 물건을 받으세요.</p>}
 {selectedItem&&<div className="tsc-card-detail"><h4>{TERROR_ITEM_INFO[selectedItem.key].name}</h4><p>{TERROR_ITEM_INFO[selectedItem.key].description}</p><label>대상 캐릭터<select value={target} onChange={e=>{const c=TERROR_CHARACTERS.find(c=>c===e.target.value);if(c)setTarget(c);}}>{TERROR_CHARACTERS.map(c=><option key={c} value={c}>{TERROR_CHARACTER_INFO[c].name}</option>)}</select></label>{selectedItem.key==='HATCHET'&&<DoorSelect doors={doors.filter(e=>g.blocks.includes(e))} value={edge} set={setEdge}/>}{selectedItem.key==='FLASHLIGHT'&&TERROR_PASSAGES[p.location]&&<button onClick={()=>setDestination(TERROR_PASSAGES[p.location]??null)}>비밀 통로 목적지 선택</button>}{!['KEY','REVOLVER','AMMO','POWDER','AMULET','SHORTSWORD','LONGSWORD','SECRET_MAP'].includes(selectedItem.key)&&<button className="tsc-primary" disabled={disabled||full||(['TOOLBOX','HERBS','MEDKIT','FIRECRACKER','FLASHLIGHT','TRAP_PARTS'].includes(selectedItem.key)&&p.acted)||(['WHISKEY','ADRENALINE','FLASHLIGHT'].includes(selectedItem.key)&&!destination)} onClick={itemUse}>아이템 사용 확정</button>}<button disabled={disabled||full||target===character||team.survivors.find(p=>p.character===target)?.location!==p.location} onClick={()=>act({type:'TRADE',character,target,cardId:selectedItem.cardId})}>같은 장소의 동료에게 전달</button></div>}
 </>}
 </>}</>}
 {g.phase==='LOOT'&&team?.loot&&<><p>{TERROR_CHARACTER_INFO[team.loot.character].name}의 {team.loot.source==='SEARCH'?'수색':'발견'}. 최대 한 장을 보관합니다.</p>{team.survivors.find(p=>p.character===team.loot!.character)?.playerId===self?<><div className="tsc-cards">{team.loot.cards.map(c=><button disabled={disabled} key={c.cardId} onClick={()=>act({type:'KEEP',cardId:c.cardId})}><ItemFace item={c.key}/><b>이 물건 보관</b></button>)}</div><button disabled={disabled} onClick={()=>act({type:'KEEP',cardId:null})}>모두 버리기</button></>:<p>담당자가 물건을 고르고 있습니다.</p>}</>}
 {killer&&kh&&<><p className="tsc-muted">{g.phase==='MAIN'?`기본 행동 ${kh.actionsLeft}회 남음 · 특수 카드는 기본 행동 전에 사용`:g.phase==='SLOW'?'느린 카드 최대 한 장. 사용하지 않고 종료할 수 있습니다.':'카드를 선택하면 비용과 세부 행동을 정할 수 있습니다.'}</p>
 {g.phase==='FAST'&&<button className="tsc-primary" disabled={disabled} onClick={()=>act({type:'KILLER_NEXT'})}>빠른 카드 마치고 행동하기 →</button>}
 {g.phase==='MAIN'&&<div className="tsc-action-grid"><button disabled={disabled||!path.length||path.length!==1} onClick={()=>act({type:'KILLER_BASIC',kind:'MOVE',destination:destination??start})}>선택 장소로 이동<small>기본 행동 1회</small></button><button disabled={disabled} onClick={()=>act({type:'KILLER_BASIC',kind:'SEARCH',destination:start})}>현재 장소 수색<small>기본 행동 1회</small></button></div>}
 {g.phase==='RAGE'&&<button className="tsc-primary" disabled={disabled||!path.length} onClick={()=>act({type:'RAGE_MOVE',path})}>분노 · 이동하고 다시 수색</button>}
 {g.phase==='SLOW'&&<button className="tsc-primary" disabled={disabled} onClick={()=>act({type:'KILLER_NEXT'})}>사냥 마치기 · 카드 3장 뽑기</button>}
 <h4>살인마 손패 <span>{kh.hand.length}/5</span></h4><div className="tsc-cards tsc-killer-cards">{kh.hand.map(c=><button key={c.cardId} aria-pressed={cardId===c.cardId} disabled={g.phase==='UNLOCK'?disabled:false} onClick={()=>{if(g.phase==='UNLOCK'){act({type:'UNLOCK_DISCARD',cardId:c.cardId});return;}setCardId(c.cardId);setManualPath([]);setManualMode(false);setCost([]);setMode('KILLER');setDestination(null);selectSound();}}><SkillFace skill={c.key}/>{g.phase==='UNLOCK'&&<b>이 카드 버리기</b>}</button>)}</div><small>덱 {kh.deckCount}장 · 버림패 {kh.discardCount}장</small>
 {selectedSkill&&['FAST','MAIN','SLOW'].includes(g.phase)&&<div className="tsc-card-detail"><h4>{TERROR_SKILL_INFO[selectedSkill.key].name}</h4><p>{TERROR_SKILL_INFO[selectedSkill.key].description}</p>{TERROR_SKILL_INFO[selectedSkill.key].cost>0&&<fieldset><legend>비용으로 버릴 카드 {cost.length}/{TERROR_SKILL_INFO[selectedSkill.key].cost}</legend>{kh.hand.filter(c=>c.cardId!==selectedSkill.cardId).map(c=><label key={c.cardId}><input type="checkbox" checked={cost.includes(c.cardId)} onChange={()=>setCost(cost.includes(c.cardId)?cost.filter(id=>id!==c.cardId):[...cost,c.cardId])}/>{TERROR_SKILL_INFO[c.key].name}</label>)}</fieldset>}
 {selectedSkill.key==='SENSE'&&<label>감지 구역<select value={zone} onChange={e=>{if(e.target.value==='R'||e.target.value==='B'||e.target.value==='G')setZone(e.target.value);}}><option value="R">붉은 구역 · 현관 / 도서관</option><option value="B">푸른 구역 · 거실 / 주방</option><option value="G">초록 구역 · 야외</option></select></label>}
 {['BARRICADE','MADNESS'].includes(selectedSkill.key)&&<DoorSelect doors={doors.filter(e=>!g.blocks.includes(e))} value={edge} set={setEdge}/>}
 {['BARRICADE','MADNESS','STAY'].includes(selectedSkill.key)&&g.blocks.length>=4&&<fieldset><legend>7개를 넘으면 기존 봉쇄를 선택해 재배치</legend>{g.blocks.map(e=><label key={e}><input type="checkbox" checked={replaces.includes(e)} onChange={()=>setReplaces(replaces.includes(e)?replaces.filter(x=>x!==e):[...replaces,e])}/>{e}</label>)}</fieldset>}
 {['PURSUE','RAGE','CHAINSAW'].includes(selectedSkill.key)&&<p>{destination?`이동: ${TERROR_ROOM_INFO[destination].name}`:selectedSkill.key==='CHAINSAW'?'이동 없이 사용하거나 지도에서 인접 장소를 고르세요.':'지도에서 이동할 장소를 선택하세요.'}</p>}
 <button className="tsc-primary" disabled={disabled||cost.length!==TERROR_SKILL_INFO[selectedSkill.key].cost||(selectedSkill.key==='CHAINSAW'&&g.level>=4?'FAST':TERROR_SKILL_INFO[selectedSkill.key].timing)!==g.phase||(g.phase==='MAIN'&&kh.actionsLeft!==2)||(g.phase==='SLOW'&&kh.slowUsed)||(['PURSUE','RAGE'].includes(selectedSkill.key)&&!path.length)||(['BARRICADE','MADNESS'].includes(selectedSkill.key)&&!edge)} onClick={()=>act({type:'KILLER_CARD',cardId:selectedSkill.cardId,cost,path,zone,edge,replaces})}>카드 사용 확정</button></div>}
 </>}
 {g.encounter&&['DEFENDER','DEFEND','FLEE'].includes(g.phase)&&<div className="tsc-encounter"><h4>조우 · {TERROR_ROOM_INFO[g.encounter.location].name}</h4><p>공격력 {g.strength} · 방어 성공 시 추격을 떨쳐냅니다.</p>{g.phase==='DEFENDER'&&team&&g.encounter.targets.filter(c=>!g.encounter!.attacked.includes(c)).map(c=><button key={c} disabled={disabled||team.survivors.find(p=>p.character===c)?.playerId!==self} onClick={()=>{setCharacter(c);act({type:'DEFENDER',character:c});}}>{TERROR_CHARACTER_INFO[c].name} 먼저 방어</button>)}{g.phase==='DEFEND'&&g.encounter.defender&&<Defense game={g} self={self} disabled={disabled} act={act}/>}{g.phase==='FLEE'&&team&&<>{g.encounter.fleePending.map(c=>{const fleeing=team.survivors.find(p=>p.character===c)!;return <div key={c}><b>{TERROR_CHARACTER_INFO[c].name}</b>{fleeing.playerId===self?<><button disabled={disabled} onClick={()=>{setCharacter(c);setMode('FLEE');}}>이 캐릭터 도주 경로 선택</button><button disabled={disabled||character!==c||!destination||!terrorAdjacent(fleeing.location,destination)||g.blocks.includes(terrorEdge(fleeing.location,destination))} onClick={()=>act({type:'FLEE',character:c,destination:destination??fleeing.location})}>선택 장소로 도주</button><button disabled={disabled} onClick={()=>act({type:'FLEE',character:c,destination:fleeing.location})}>현 위치에 머무르기</button></>:<small>담당자 선택 대기</small>}</div>;})}</>}{killer&&<p>생존자들이 대응하고 있습니다.</p>}</div>}
 {g.dice.length>0&&<div className="tsc-dice-result" aria-label={'방어 주사위 '+g.dice.join(', ')}><div>{g.dice.map((d,i)=><span key={g.history.at(-1)?.id+':'+i}>{d===0?'—':d}</span>)}</div><b>최근 방어 합계 {g.defenseTotal??'계산 중'}</b></div>}
 {!killer&&['KILLER'].includes(g.phase)&&<div className="tsc-waiting"><Portrait character="BUTCHER"/><p>발소리가 가까워집니다.<br/>살인마의 행동을 지켜보세요.</p></div>}
 </aside>
 <section className="tsc-log"><h3>밤의 기록 <small>{killer?'공개 정보 / 살인마 기록':'생존자 팀 기록'}</small></h3><ol>{[...g.history].reverse().map(event=><li key={event.id}><span>{String(event.id).padStart(2,'0')}</span>{event.text}</li>)}</ol></section>
 </div></>}
 </div>;
}
function DoorSelect({doors,value,set}:{doors:readonly string[];value:string;set(v:string):void}){return <label>대상 문<select value={value} onChange={e=>set(e.target.value)}><option value="">문 선택</option>{doors.map(e=><option key={e} value={e}>{e.split('-').map(r=>TERROR_ROOMS.find(x=>x===r)).map(r=>r?TERROR_ROOM_INFO[r].name:'').join(' ↔ ')}</option>)}</select></label>;}
function Defense({game:g,self,disabled,act}:{game:TerrorscapeProjection;self:PlayerId;disabled:boolean;act(a:TerrorscapeAction):void}){if(g.privateState.role!=='SURVIVOR')return null;const p=g.privateState.team.survivors.find(p=>p.character===g.encounter?.defender);if(!p)return null;if(p.playerId!==self)return <p>{TERROR_CHARACTER_INFO[p.character].name}의 담당자가 방어를 준비합니다.</p>;const cards=p.hand.filter(c=>['HATCHET','POWDER','SHORTSWORD','LONGSWORD'].includes(c.key)||c.key==='AMMO'&&p.hand.some(c=>c.key==='REVOLVER'));return <><p>{4-p.fear}개의 주사위 · {TERROR_CHARACTER_INFO[p.character].name}</p><button className="tsc-primary" disabled={disabled} onClick={()=>act({type:'DEFEND',cardId:null})}>맨손으로 방어 주사위 굴리기{p.character==='WILLIAM'?' (+1)':''}</button><div className="tsc-cards">{cards.map((c:TerrorCard)=><button disabled={disabled} key={c.cardId} onClick={()=>act({type:'DEFEND',cardId:c.cardId})}><ItemFace item={c.key}/><b>사용하고 방어</b></button>)}</div></>;}
function Setup({g,people,self,disabled,act}:{g:TerrorscapeProjection;people:TerrorscapeWebSnapshot['room']['players'];self:PlayerId;disabled:boolean;act(a:TerrorscapeAction):void}){const [killer,setKiller]=useState(g.killerPlayerId),[owners,setOwners]=useState(g.owners);useEffect(()=>{setKiller(g.killerPlayerId);setOwners(g.owners);},[g.killerPlayerId,g.owners.join('|')]);const host=people.find(p=>p.playerId===self)?.isHost,valid=owners.every(id=>id!==killer)&&people.every(p=>p.playerId===killer||owners.includes(p.playerId));return <div className="tsc-setup"><div><span className="tsc-eyebrow">CHOOSE YOUR SIDE</span><h2>한 명은 사냥하고,<br/>세 명은 살아남는다.</h2><p>생존자 세 캐릭터를 나누어 맡습니다. 2인 게임에서는 한 사람이 세 생존자를 모두 조작합니다.</p></div><div className="tsc-role-cards"><div><Portrait character="BUTCHER"/><h3>도살자</h3><select aria-label="살인마 담당자" disabled={!host||disabled} value={killer} onChange={e=>{const id=people.find(p=>p.playerId===e.target.value)?.playerId;if(id){setKiller(id);const other=people.filter(p=>p.playerId!==id);setOwners(TERROR_CHARACTERS.map((_,i)=>other[i%other.length]!.playerId));}}}>{people.map(p=><option key={p.playerId} value={p.playerId}>{p.nickname}</option>)}</select><p>공격력 5 · 소음을 좇는 추격자</p></div>{TERROR_CHARACTERS.map((c,i)=><div key={c}><Portrait character={c}/><h3>{TERROR_CHARACTER_INFO[c].name}</h3><select aria-label={TERROR_CHARACTER_INFO[c].name+' 담당자'} disabled={!host||disabled} value={owners[i]} onChange={e=>{const id=people.find(p=>p.playerId===e.target.value)?.playerId;if(id)setOwners(owners.map((x,j)=>i===j?id:x));}}>{people.filter(p=>p.playerId!==killer).map(p=><option key={p.playerId} value={p.playerId}>{p.nickname}</option>)}</select><p>{TERROR_CHARACTER_INFO[c].ability}</p></div>)}</div>{host?<div className="tsc-setup-actions"><button disabled={disabled||!valid} onClick={()=>act({type:'SET_ROLES',killerPlayerId:killer,owners})}>담당 배역 저장</button><button className="tsc-primary" disabled={disabled||!valid||killer!==g.killerPlayerId||owners.join('|')!==g.owners.join('|')} onClick={()=>act({type:'BEGIN_HUNT'})}>불을 끄고, 사냥 시작 →</button></div>:<p>방장이 배역을 정하고 있습니다.</p>}</div>;}
