import {useState} from 'react';
import {TERROR_TRAIT_INFO,TERROR_CHARACTER_INFO,TERROR_ROOM_INFO,TERROR_ROOMS,TERROR_DOORS,terrorAdjacent,terrorEdge,type TerrorRoom,type TerrorTrait,type TerrorCharacter,type TileId,type PlayerId,type TerrorscapeProjection,type TerrorscapeAction} from '@hangul-rummikub/shared';
type Props={g:TerrorscapeProjection;self:PlayerId;disabled:boolean;act(a:TerrorscapeAction):void};
export function Traits({g,self,disabled,act}:Props){
 const team=g.privateState.role==='SURVIVOR'?g.privateState.team:null,kh=g.privateState.role==='KILLER'?g.privateState.killer:null;
 const [picks,setPicks]=useState<TerrorTrait[]>([]),[room,setRoom]=useState<TerrorRoom>('R1'),[target,setTarget]=useState<TerrorCharacter>(g.conditions[0]!.character),[path,setPath]=useState<TerrorRoom[]>([]),[cost,setCost]=useState<TileId[]>([]),[edges,setEdges]=useState<string[]>([]),[replaces,setReplaces]=useState<string[]>([]),[choice,setChoice]=useState<'FEAR'|'NOISE'|'BLOCK'>('FEAR'),[zone,setZone]=useState<'R'|'B'|'G'>('R');
 const owns=(c:TerrorCharacter)=>g.owners[g.conditions.findIndex(p=>p.character===c)]===self;
 const available=kh?g.killerTraits.map(trait=>({trait,character:null})):team?.traits.filter(p=>p.chosen&&owns(p.character)).map(p=>({trait:p.chosen!,character:p.character}))??[];
 function canUse(t:TerrorTrait,c:TerrorCharacter|null){if((kh?.usedTraits??team?.usedTraits??[]).includes(t))return false;const timing=TERROR_TRAIT_INFO[t].timing;
  if(timing==='PASSIVE')return false;
  if(timing==='ACTION')return c?g.phase==='SURVIVORS'&&team?.survivors.find(p=>p.character===c)?.outcome==='ACTIVE':['KILLER_START','FAST','MAIN','SLOW','KILLER_END'].includes(g.phase);
  if(timing==='LOOT')return g.phase==='LOOT'&&team?.loot?.source==='DISCOVER'&&team.loot.character===c;
  if(timing==='DEFEND')return g.phase==='DEFEND'&&g.encounter?.defender===c;
  if(timing==='ENCOUNTER')return c?g.phase==='HEROIC'&&g.encounter?.targets.includes(c):g.phase==='TOYING';
  if(timing==='START')return g.phase==='KILLER_START';
  if(timing==='END')return g.phase==='KILLER_END';
  if(timing==='LEVEL')return g.phase==='LEVEL_TRAIT'&&kh?.levelTrait===t;
  return g.phase==='SENSE_REACTION'&&Boolean(kh?.senseTargets.length);
 }
 if(g.phase==='TRAIT_DRAFT')return <section className="tsc-card-detail"><h3>특성 선택 · {g.difficulty}</h3>{kh?<><p>{kh.traitsChosen?'선택 완료 · 생존자를 기다립니다.':`${kh.traitOffer.length}장 중 ${kh.traitOffer.length/2}장 선택`}</p>{kh.traitOffer.map(t=><label key={t}><input type="checkbox" disabled={disabled||kh.traitsChosen} checked={picks.includes(t)} onChange={()=>setPicks(picks.includes(t)?picks.filter(x=>x!==t):[...picks,t])}/><b>{TERROR_TRAIT_INFO[t].name}</b><p>{TERROR_TRAIT_INFO[t].description}</p></label>)}<button disabled={disabled||kh.traitsChosen||picks.length!==kh.traitOffer.length/2} onClick={()=>act({type:'CHOOSE_TRAITS',character:null,traits:picks})}>살인마 특성 확정</button></>:team?.traits.filter(p=>owns(p.character)).map(p=><div key={p.character}><h4>{TERROR_CHARACTER_INFO[p.character].name}{p.chosen?' · 선택 완료':''}</h4>{p.offered.map(t=><button key={t} disabled={disabled||p.chosen!==null} onClick={()=>act({type:'CHOOSE_TRAITS',character:p.character,traits:[t]})}><b>{TERROR_TRAIT_INFO[t].name}</b><p>{TERROR_TRAIT_INFO[t].description}</p></button>)}</div>)}</section>;
 return <section className="tsc-traits">
 {!kh&&g.killerTraits.length>0&&<details><summary>살인마 공개 특성</summary>{g.killerTraits.map(t=><p key={t}><b>{TERROR_TRAIT_INFO[t].name}</b> · {TERROR_TRAIT_INFO[t].description}</p>)}</details>}
 {available.map(({trait:t,character:c})=><details key={t} className="tsc-card-detail"><summary>{c?TERROR_CHARACTER_INFO[c].name+' · ':''}{TERROR_TRAIT_INFO[t].name}{(kh?.usedTraits??team?.usedTraits??[]).includes(t)?' · 사용 완료':''}</summary><p>{TERROR_TRAIT_INFO[t].description}</p>{canUse(t,c)&&<>
 {['FIRST_AID','DETERRENCE'].includes(t)&&<label>대상 생존자<select value={target} onChange={e=>{const p=g.conditions.find(p=>p.character===e.target.value);if(p)setTarget(p.character);}}>{g.conditions.filter(p=>p.outcome==='ACTIVE').map(p=><option key={p.character} value={p.character}>{TERROR_CHARACTER_INFO[p.character].name}</option>)}</select></label>}
 {['DECOY','ACUTE','JUDICIOUS'].includes(t)&&<label>대상 장소<select value={room} onChange={e=>{const r=TERROR_ROOMS.find(r=>r===e.target.value);if(r)setRoom(r);}}>{TERROR_ROOMS.map(r=><option key={r}>{r}</option>)}</select></label>}
 {['SWIFT','IMMEDIATE','PERILOUS','PROMPT','BURST'].includes(t)&&<div><p>이동 경로 · {path.map(r=>TERROR_ROOM_INFO[r].name).join(' → ')||'머무르기'}</p>{TERROR_ROOMS.filter(r=>terrorAdjacent(path.at(-1)??(c?team?.survivors.find(p=>p.character===c)?.location:g.killerLocation)??'R1',r)).map(r=><button key={r} disabled={path.length>=4} onClick={()=>setPath([...path,r])}>{TERROR_ROOM_INFO[r].name}</button>)}<button onClick={()=>setPath([])}>경로 초기화</button></div>}
 {['ENTRAPMENT','ENCIRCLE','SLY','JUDICIOUS'].includes(t)&&<><fieldset><legend>대상 문 (최대 2개)</legend>{TERROR_DOORS.map(([a,b])=>terrorEdge(a,b)).map(e=><label key={e}><input type="checkbox" checked={edges.includes(e)} disabled={!edges.includes(e)&&edges.length>=2} onChange={()=>setEdges(edges.includes(e)?edges.filter(x=>x!==e):[...edges,e])}/>{e}</label>)}</fieldset><fieldset><legend>봉쇄가 부족할 때 재배치</legend>{g.blocks.map(e=><label key={e}><input type="checkbox" checked={replaces.includes(e)} onChange={()=>setReplaces(replaces.includes(e)?replaces.filter(x=>x!==e):[...replaces,e])}/>{e}</label>)}</fieldset></>}
 {t==='HEIGHTENED'&&<select aria-label="추가 감지 구역" value={zone} onChange={e=>{if(e.target.value==='R'||e.target.value==='B'||e.target.value==='G')setZone(e.target.value);}}><option>R</option><option>B</option><option>G</option></select>}
 {t==='JUDICIOUS'&&<select aria-label="현명한 이동 효과" value={choice} onChange={e=>{if(e.target.value==='FEAR'||e.target.value==='NOISE'||e.target.value==='BLOCK')setChoice(e.target.value);}}><option value="FEAR">자신 공포 제거</option><option value="NOISE">인접 장소 소음</option><option value="BLOCK">봉쇄 제거</option></select>}
 {['SWIFT','ACUTE','ENHANCED','MURDEROUS','IMMEDIATE','PERILOUS','ENCIRCLE','SECRET_WEAPON'].includes(t)&&<fieldset><legend>비용으로 버릴 카드 (효과에 필요한 경우)</legend>{(kh?.hand??team?.survivors.find(p=>p.character===c)?.hand??[]).map(card=><label key={card.cardId}><input type="checkbox" checked={cost.includes(card.cardId)} onChange={()=>setCost(cost.includes(card.cardId)?cost.filter(id=>id!==card.cardId):[...cost,card.cardId])}/>{card.key}</label>)}</fieldset>}
 <button disabled={disabled} onClick={()=>act({type:'TRAIT_USE',trait:t,character:c,target,path,cost,room,zone,choice,edges,replaces})}>특성 실행</button>
 </>}</details>)}
 {(kh&&['SENSE_REACTION','TOYING'].includes(g.phase)||!kh&&g.phase==='HEROIC'&&available.some(p=>p.trait==='HEROIC_SAVE'&&p.character&&g.encounter?.targets.includes(p.character)))&&<button disabled={disabled} onClick={()=>act({type:'TRAIT_PASS'})}>특성을 사용하지 않고 계속</button>}
 {team&&g.phase==='GROUP_MOVE'&&g.groupMove&&<div><h4>동료가 이동 기회를 만들었습니다 · 최대 {g.groupMove.max}칸</h4>{g.groupMove.targets.filter(owns).map(c=><div key={c}><p>{TERROR_CHARACTER_INFO[c].name} · {path.join(' → ')||'머무르기'}</p>{TERROR_ROOMS.filter(r=>terrorAdjacent(path.at(-1)??team.survivors.find(p=>p.character===c)!.location,r)).map(r=><button key={r} disabled={path.length>=g.groupMove!.max} onClick={()=>setPath([...path,r])}>{TERROR_ROOM_INFO[r].name}</button>)}<button onClick={()=>setPath([])}>경로 초기화</button><button disabled={disabled} onClick={()=>act({type:'GROUP_MOVE',character:c,path})}>이동 확정</button><button disabled={disabled} onClick={()=>act({type:'GROUP_MOVE',character:c,path:[]})}>머무르기</button></div>)}</div>}
 </section>;
}
