import {useEffect,useRef,useState} from 'react';
import {safeParse} from 'valibot';
import {PANDEMIC_CITIES,PANDEMIC_CITY_INFO,PANDEMIC_COLORS,PANDEMIC_EVENTS,PANDEMIC_EVENT_INFO,PANDEMIC_ROLES,PANDEMIC_ROLE_INFO,PANDEMIC_RATE,PandemicCitySchema,PROTOCOL_VERSION,type PandemicAction,type PandemicCity,type PandemicClientCommand,type PandemicProjection,type PlayerId,type TileId} from '@hangul-rummikub/shared';
import type {PandemicWebSnapshot} from '../../lib/snapshot-wire-decoder.js';
import {createRequestId} from '../../lib/request-id.js';
import {getGameStartControl} from '../../lib/game-start.js';
import {PandemicCommandRejected} from '../../lib/pandemic-command-error.js';
import {PandemicBoard} from './PandemicBoard.js';
import {PandemicArt,PandemicCardFace} from './art.js';
import {usePandemicSound} from './sound.js';
import {cardName,DISEASE_COLORS,DISEASE_NAMES,STAGE_NAMES,pandemicMoveOptions} from './presentation.js';
type Props={snapshot:PandemicWebSnapshot;connected:boolean;pending:boolean;error:string|null;connectionLabel:string;onCommand(command:PandemicClientCommand):Promise<void>;onRematch():void;onStart():void;onLeave():void;onCopy():void};
export function PandemicScreen(props:Props){const s=props.snapshot,sound=usePandemicSound(s.game,props.connected),start=getGameStartControl(s,props.pending||!props.connected);return <section className="pandemic-screen" aria-label="팬데믹" onPointerDownCapture={sound.unlock} onKeyDownCapture={e=>{if(e.key==='Enter'||e.key===' ')sound.unlock();}}>
 <header className="pd-header"><div><span className="pd-eyebrow">TOGETHER, WE CAN SAVE THE WORLD</span><h1>PANDEMIC <small>팬데믹</small></h1></div><div className="pd-tools"><span className="pd-connection">{props.connectionLabel}</span><details className="pd-audio"><summary>♫ 소리</summary><div><label>효과음 {sound.effects}%<input aria-label="효과음 음량" type="range" min="0" max="100" value={sound.effects} onChange={e=>sound.setEffects(Number(e.target.value))}/></label><label>배경음악 {sound.music}%<input aria-label="배경음악 음량" type="range" min="0" max="100" value={sound.music} onChange={e=>sound.setMusic(Number(e.target.value))}/></label><button onClick={()=>{sound.setEffects(0);sound.setMusic(0);}}>모두 음소거</button><button onClick={()=>{sound.setEffects(40);sound.unlock();sound.select();}}>효과음 켜기</button></div></details><button onClick={props.onCopy}>초대 · {s.room.roomCode}</button><button onClick={props.onLeave} disabled={props.pending}>나가기</button></div></header>
 {!props.connected&&<p className="pd-alert" role="status">연결 복구를 기다리고 있습니다. 다시 연결되면 현재 선택 단계로 돌아옵니다.</p>}{props.error&&<p className="pd-alert" role="alert">{props.error}</p>}
 {s.game?<PandemicTable key={s.game.gameId+':'+s.self.playerId} {...props} game={s.game} selectSound={sound.select}/>:<div className="pd-lobby"><div className="pd-lobby-copy"><span className="pd-eyebrow">GLOBAL RESPONSE / COOPERATIVE MISSION</span><h2>위기는 전 세계에.<br/>희망은 우리 손에.</h2><p>도시를 지키고, 지식을 나누고, 치료제를 발견하세요.<br/>서로 다른 능력을 가진 팀이 하나의 목표를 향해 움직입니다.</p><div className="pd-lobby-seats">{s.room.players.map(p=><div key={p.playerId}><span>{p.connectionStatus==='CONNECTED'?'●':'○'}</span> {p.nickname}<small>{p.isHost?'방장':'팀원'}</small></div>)}</div><button className="pd-primary" disabled={!start.canStart} onClick={props.onStart}>팀 구성하고 출동 준비 →</button><p>{start.guidance}</p><small>2–4인 협동 · 기본판 7역할 · 시간 제한 없음</small></div><PandemicArt index={7} className="pd-lobby-art"/></div>}
 <details className="pd-guide"><summary>작전 안내서 · 처음 플레이하시나요?</summary><div><p><b>목표</b> 네 가지 치료제를 모두 발견하면 즉시 팀 승리입니다. 모든 큐브를 없앨 필요는 없습니다. 발병 8회, 필요한 큐브 부족, 뽑을 플레이어 카드 부족은 팀 패배입니다.</p><p><b>내 차례</b> 최대 4행동을 합니다. 도시나 손패를 선택하고, 행동 비용을 확인한 뒤 확정하세요. 연구소에서 같은 색 도시 카드 5장(과학자는 4장)을 버리면 치료제를 발견합니다.</p><p><b>자동 처리와 이벤트</b> 행동 후 카드 2장을 뽑고 감염을 진행합니다. 각 경계에서 모두 ‘이벤트 없이 계속’을 누르면 서버가 다음 단계를 처리합니다. 이벤트를 사용하면 진행 동의를 다시 받습니다. 이미 공개된 감염 카드의 효과를 보고 소급해 막을 수 없습니다.</p><p><b>함께 결정</b> 같은 도시에서 카드를 주고받거나 다른 사람의 말을 움직이면 동료 동의가 필요합니다. 차례가 아니어도 이벤트와 도시 핑을 사용할 수 있습니다. 손패가 7장을 넘으면 정리해야 합니다.</p><p><b>지도와 소리</b> 도시를 누르거나 지도 아래 목록에서 선택합니다. 모바일은 확대·가로 스크롤로 탐색합니다. 색상 옆 숫자는 큐브 수, 원형 번호는 팀원입니다. 소리는 첫 클릭 후 활성화되고 개별 조절할 수 있습니다.</p></div></details>
 </section>;}
type Draft={action:PandemicAction;label:string;cost:string};
function PandemicTable({game:g,selectSound,...props}:Props&{game:PandemicProjection;selectSound():void}){
 const self=props.snapshot.self.playerId,people=props.snapshot.room.players,me=g.playerStates.find(p=>p.playerId===self)!,host=people.find(p=>p.playerId===self)?.isHost===true;
 const [selected,setSelected]=useState<PandemicCity>(me.city),[target,setTarget]=useState<PlayerId>(self),[tab,setTab]=useState('MOVE'),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[uncertain,setUncertain]=useState(false),[cardId,setCardId]=useState<TileId|null>(null),[replace,setReplace]=useState<PandemicCity|null>(null),[cureCards,setCureCards]=useState<TileId[]>([]),[forecast,setForecast]=useState<PandemicCity[]>(g.privateState.forecast??[]);
 const envelope=useRef<PandemicClientCommand|null>(null),inFlight=useRef(false);
 const blocked=props.pending||!props.connected||busy||uncertain,canAct=g.phase==='ACTIONS'&&g.activePlayerId===self&&!g.pending&&g.playerStates.every(p=>p.handCount<=7),selectedCard=[...me.hand??[],...me.stored?[me.stored]:[]].find(c=>c.cardId===cardId),city=PANDEMIC_CITY_INFO[selected],cityState=g.board.find(b=>b.city===selected)!,ownCity=g.board.find(b=>b.city===me.city)!;
 useEffect(()=>{setDraft(null);setCureCards([]);},[g.gameRevision]);
 const forecastKey=g.privateState.forecast?.join(',')??'';
 useEffect(()=>{setForecast(g.privateState.forecast??[]);},[forecastKey]);
 const name=(id:PlayerId)=>people.find(p=>p.playerId===id)?.nickname??'팀원';
 async function submit(action:PandemicAction,retry=false){if(inFlight.current||!props.connected||g.phase==='FINISHED')return;inFlight.current=true;setBusy(true);setError(null);if(!retry)envelope.current={kind:'pandemic:act',protocolVersion:PROTOCOL_VERSION,requestId:createRequestId(),gameId:g.gameId,expectedGameRevision:g.gameRevision,turnId:g.turnId,payload:action};const command=envelope.current;if(!command){inFlight.current=false;setBusy(false);return;}try{await props.onCommand(command);envelope.current=null;setUncertain(false);setDraft(null);}catch(e){setError(e instanceof Error?e.message:'명령을 확인하지 못했습니다.');if(e instanceof PandemicCommandRejected){envelope.current=null;setUncertain(false);}else setUncertain(true);}finally{inFlight.current=false;setBusy(false);}}
 function choose(action:PandemicAction,label:string,cost:string){setDraft({action,label,cost});selectSound();}
 function selectCity(c:PandemicCity){setSelected(c);setDraft(null);selectSound();}
 function citySelect(value:string,fn:(c:PandemicCity)=>void){const result=safeParse(PandemicCitySchema,value);if(result.success)fn(result.output);}
 const stationPicker=<label className="pd-field">이전할 연구소<select aria-label="이전할 연구소" value={replace??''} onChange={e=>{setDraft(null);if(e.target.value==='')setReplace(null);else citySelect(e.target.value,setReplace);}}><option value="">{g.stations.length===6?'연구소 6개 사용 중 · 하나 선택':'새 연구소 사용'}</option>{g.stations.map(c=><option key={c} value={c}>{PANDEMIC_CITY_INFO[c].name}</option>)}</select></label>;
 const finished=g.phase==='FINISHED';
 return <>
 <div className="pd-status-bar"><div className="pd-turn"><span>{finished?'작전 결과':g.phase==='SETUP'?'팀 구성':`${name(g.activePlayerId)}의 차례`}</span><strong>{STAGE_NAMES[g.phase]}</strong><span className="pd-action-dots" aria-label={`남은 행동 ${g.actionsLeft}회`}>{[0,1,2,3].map(i=><i key={i} className={i<g.actionsLeft?'on':''}/>)}</span></div><div className="pd-threat"><span>발병 <b>{g.outbreaks}/8</b></span><div className="pd-outbreak-track">{Array.from({length:8},(_,i)=><i key={i} className={i<g.outbreaks?'on':''}/>)}</div></div><div className="pd-rate">감염률 <strong>{PANDEMIC_RATE[g.rateIndex]}</strong><small>{PANDEMIC_RATE.map((n,i)=><span className={i===g.rateIndex?'active':''} key={i}>{n}</span>)}</small></div><div className="pd-deck-stat">플레이어 덱 <strong>{g.phase==='SETUP'?'준비 중':g.playerDeckCount}</strong><small>감염 덱 {g.infectionDeckCount}장</small></div><div className="pd-cures">{PANDEMIC_COLORS.map(c=><div key={c} style={{color:DISEASE_COLORS[c]}}><span>{g.cures[c]==='ERADICATED'?'✦':g.cures[c]==='CURED'?'✚':'◇'} {DISEASE_NAMES[c]}</span><small>{g.cures[c]==='ACTIVE'?'미발견':g.cures[c]==='CURED'?'치료제':'박멸'} · 잔여 {g.supply[c]}</small></div>)}</div></div>
 {error&&<div className="pd-alert" role="alert">{error}{uncertain&&<button disabled={busy||!props.connected} onClick={()=>{if(envelope.current)void submit(envelope.current.payload,true);}}>같은 요청 결과 다시 확인</button>}</div>}
 {finished&&<div className={`pd-result ${g.result.reason==='CURED'?'won':''}`}><PandemicArt index={g.result.reason==='CURED'?11:7}/><div><span className="pd-eyebrow">MISSION {g.result.reason==='CURED'?'ACCOMPLISHED':g.result.reason==='CANCELLED'?'CANCELLED':'REPORT'}</span><h2>{g.result.reason==='CURED'?'우리가 함께 세상을 구했습니다.':g.result.reason==='CANCELLED'?'작전이 취소되었습니다.':'이번 위기를 막지 못했습니다.'}</h2><p>{g.result.reason==='OUTBREAKS'?'발병이 8회 발생했습니다.':g.result.reason==='CUBES'?'필요한 질병 큐브가 부족합니다.':g.result.reason==='DECK'?'플레이어 카드 2장을 뽑을 수 없습니다.':g.result.reason==='CURED'?'네 가지 치료제 발견. 팀원 모두의 승리입니다.':'참가자가 방을 나갔습니다.'}</p>{host&&<button className="pd-primary" disabled={blocked} onClick={props.onRematch}>같은 팀으로 다시 준비</button>}</div></div>}
 {g.phase==='SETUP'&&<div className="pd-setup"><div><h2>당신의 역할을 선택하세요</h2><p>각자 역할을 고른 뒤 방장이 출동을 시작합니다. 현재 배정된 역할로 바로 시작해도 됩니다.</p><div className="pd-roles">{PANDEMIC_ROLES.map(role=>{const info=PANDEMIC_ROLE_INFO[role],owner=g.playerStates.find(p=>p.role===role);return <button key={role} disabled={blocked||!!owner&&owner.playerId!==self} aria-pressed={me.role===role} onClick={()=>void submit({type:'ROLE',role})}><PandemicArt index={info.art}/><strong>{info.name}</strong><small>{info.description}</small><span>{owner?name(owner.playerId):'선택 가능'}</span></button>;})}</div></div><div className="pd-setup-options"><label>난이도<select disabled={!host||blocked} value={g.settings.epidemics} onChange={e=>{const n=Number(e.target.value);if(n===4||n===5||n===6)void submit({type:'CONFIGURE',epidemics:n,openHands:g.settings.openHands});}}><option value="4">입문 · 전염병 4장</option><option value="5">일반 · 전염병 5장</option><option value="6">영웅 · 전염병 6장</option></select></label><label><input type="checkbox" disabled={!host||blocked} checked={g.settings.openHands} onChange={e=>void submit({type:'CONFIGURE',epidemics:g.settings.epidemics,openHands:e.target.checked})}/> 손패 공개 · 함께 의논하기</label><p>이벤트 사용 기회를 위해 각 자동 단계는 팀원 모두가 확인한 뒤 진행됩니다.</p><button className="pd-primary" disabled={!host||blocked||people.some(p=>p.connectionStatus!=='CONNECTED')} onClick={()=>void submit({type:'BEGIN'})}>전 세계 대응 작전 시작 →</button></div></div>}
 <div className="pd-main"><div className="pd-board-column"><PandemicBoard game={g} selected={selected} onSelect={selectCity}/><div className="pd-team">{g.playerStates.map((p,i)=><button key={p.playerId} className={g.activePlayerId===p.playerId?'active':''} onClick={()=>selectCity(p.city)}><PandemicArt index={PANDEMIC_ROLE_INFO[p.role].art}/><div><strong><span style={{color:PANDEMIC_ROLE_INFO[p.role].color}}>{i+1}.</span> {name(p.playerId)}{p.playerId===self?' · 나':''}</strong><span>{PANDEMIC_ROLE_INFO[p.role].name}</span><small>{PANDEMIC_CITY_INFO[p.city].name} · 손패 {p.handCount}/7</small></div></button>)}</div></div>
 <aside className="pd-sidebar"><div className="pd-city-panel"><span className="pd-eyebrow">SELECTED CITY / {city.color}</span><h2>{city.name}</h2><div className="pd-city-inventory">{PANDEMIC_COLORS.map(c=><span key={c} style={{color:DISEASE_COLORS[c]}}>{DISEASE_NAMES[c]} <b>{cityState.cubes[c]}</b></span>)}{g.stations.includes(selected)&&<span>✚ 연구소</span>}</div><label className="pd-field">도시 찾기<select aria-label="도시 찾기" value={selected} onChange={e=>citySelect(e.target.value,selectCity)}>{PANDEMIC_CITIES.map(c=><option key={c} value={c}>{PANDEMIC_CITY_INFO[c].name}</option>)}</select></label>{!finished&&g.phase!=='SETUP'&&<div className="pd-ping-buttons">{(['HELP','MEET','TREAT'] as const).map((message,i)=><button key={message} disabled={blocked} onClick={()=>void submit({type:'PING',city:selected,message})}>{['도움 요청','여기서 만나요','치료 요청'][i]}</button>)}</div>}</div>
 {g.pending?<div className="pd-choice" role="status"><span className="pd-eyebrow">TEAM DECISION</span>{g.pending.kind==='SHARE_PICK'?<><h3>{name(g.pending.proposer)}님이 카드를 요청합니다.</h3>{g.pending.responder===self?<><p>공유할 도시 카드를 선택하세요. 거절하면 손패를 공개하지 않습니다.</p>{(me.hand??[]).filter(c=>c.kind==='CITY'&&(me.role==='RESEARCHER'||c.city===me.city)).map(c=><button className="pd-action-option" disabled={blocked} key={c.cardId} onClick={()=>void submit({type:'OFFER_CARD',cardId:c.cardId})}>{cardName(c)} 전달 동의</button>)}<button disabled={blocked} onClick={()=>void submit({type:'OFFER_CARD',cardId:null})}>거절</button></>:<p>{name(g.pending.responder)}님의 선택을 기다립니다.</p>}</>:g.pending.kind==='CONSENT'?<><h3>{name(g.pending.proposer)}님의 제안</h3><p>{g.pending.action.type==='SHARE'?'지식 공유를 요청합니다. 카드 한 장을 전달합니다.':`${g.pending.action.type==='MOVE'?PANDEMIC_CITY_INFO[g.pending.action.destination].name:g.pending.action.city?PANDEMIC_CITY_INFO[g.pending.action.city].name:'선택 도시'}로 이동합니다.`}</p>{g.pending.responder===self?<div className="pd-buttons"><button className="pd-primary" disabled={blocked} onClick={()=>void submit({type:'CONSENT',accept:true})}>동의</button><button disabled={blocked} onClick={()=>void submit({type:'CONSENT',accept:false})}>거절</button></div>:<p>{name(g.pending.responder)}님의 동의를 기다립니다.</p>}</>:<><h3>예측 · 감염 카드 정렬</h3>{g.privateState.forecast?<><p>위에서부터 다음 감염 순서입니다.</p>{forecast.map((c,i)=><div className="pd-forecast-row" key={c}><span>{i+1}. {PANDEMIC_CITY_INFO[c].name}</span><button disabled={blocked||i===0} aria-label={`${PANDEMIC_CITY_INFO[c].name} 위로`} onClick={()=>{const a=[...forecast];[a[i-1],a[i]]=[a[i]!,a[i-1]!];setForecast(a);}}>↑</button><button disabled={blocked||i===forecast.length-1} aria-label={`${PANDEMIC_CITY_INFO[c].name} 아래로`} onClick={()=>{const a=[...forecast];[a[i+1],a[i]]=[a[i]!,a[i+1]!];setForecast(a);}}>↓</button></div>)}<button className="pd-primary" disabled={blocked} onClick={()=>void submit({type:'FORECAST_ORDER',cities:forecast})}>이 순서로 확정</button></>:<p>{name(g.pending.playerId)}님이 순서를 정하고 있습니다.</p>}</>}</div>:null}
 {!finished&&g.phase!=='SETUP'&&!g.pending&&<>
 {me.handCount>7&&g.epidemicsRemaining===0&&<div className="pd-choice"><h3>손패 {me.handCount-7}장 정리</h3><p>아래 손패를 선택해 버리거나 이벤트를 사용하세요.</p>{selectedCard&&<button disabled={blocked||me.stored?.cardId===selectedCard.cardId} onClick={()=>choose({type:'DISCARD',cardId:selectedCard.cardId},`${cardName(selectedCard)} 버리기`,'손패 제한 정리 · 행동 소모 없음')}>선택한 카드 버리기</button>}</div>}
 {g.phase!=='ACTIONS'&&<div className="pd-choice"><h3>{STAGE_NAMES[g.phase]}</h3><p>{g.phase==='INTENSIFY'?'감염 버림패가 곧 덱 위로 돌아갑니다. 이벤트를 사용할 수 있습니다.':'이벤트를 사용하려면 손패에서 선택하세요.'}</p><div className="pd-ready-list">{g.playerStates.map(p=><span key={p.playerId}>{g.continueReady.includes(p.playerId)?'✓':'○'} {name(p.playerId)}</span>)}</div><button className="pd-primary" disabled={blocked||g.continueReady.includes(self)||g.epidemicsRemaining===0&&g.playerStates.some(p=>p.handCount>7)} onClick={()=>void submit({type:'CONTINUE'})}>{g.continueReady.includes(self)?'팀원 확인을 기다리는 중':'이벤트 없이 계속'}</button></div>}
 {canAct?<div className="pd-actions"><div className="pd-action-tabs">{[['MOVE','이동'],['TREAT','치료'],['BUILD','연구소'],['SHARE','공유'],['CURE','치료제']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>{setTab(key!);setDraft(null);selectSound();}}>{label}</button>)}</div>
 {tab==='MOVE'&&<><p>목적지를 지도에서 선택하세요.</p>{me.role==='DISPATCHER'&&<label className="pd-field">움직일 플레이어<select value={target} onChange={e=>{const p=g.playerStates.find(p=>p.playerId===e.target.value);if(p){setTarget(p.playerId);setDraft(null);}}}>{g.playerStates.map(p=><option key={p.playerId} value={p.playerId}>{name(p.playerId)}</option>)}</select></label>}{pandemicMoveOptions(g,self,target,selected).map((o,i)=><button className="pd-action-option" key={i} disabled={blocked} onClick={()=>choose(o.action,`${city.name} · ${o.label}`,o.cost)}><strong>{o.label}</strong><small>{o.cost}</small></button>)}{pandemicMoveOptions(g,self,target,selected).length===0&&<p className="pd-muted">현재 위치와 손패로 이 도시로 이동할 수 없습니다. 인접 도시를 선택하거나 항공편에 필요한 카드를 확인하세요.</p>}</>}
 {tab==='TREAT'&&<><p>현재 위치: {PANDEMIC_CITY_INFO[me.city].name}</p>{PANDEMIC_COLORS.map(c=><button className="pd-action-option" disabled={blocked||ownCity.cubes[c]===0} key={c} onClick={()=>choose({type:'TREAT',color:c},`${DISEASE_NAMES[c]} 질병 치료`,`행동 1회 · 큐브 ${me.role==='MEDIC'||g.cures[c]!=='ACTIVE'?ownCity.cubes[c]:1}개 제거`)}>{DISEASE_NAMES[c]} 질병 · {ownCity.cubes[c]}개</button>)}</>}
 {tab==='BUILD'&&<><p>{PANDEMIC_CITY_INFO[me.city].name}에 연구소를 세웁니다.</p>{g.stations.length===6&&stationPicker}<button disabled={blocked||g.stations.includes(me.city)||me.role!=='OPERATIONS'&&!me.hand?.some(c=>c.kind==='CITY'&&c.city===me.city)||g.stations.length===6&&!replace} onClick={()=>choose({type:'BUILD',replace:g.stations.length===6?replace:null},'연구소 건설',`행동 1회 · ${me.role==='OPERATIONS'?'카드 소모 없음':PANDEMIC_CITY_INFO[me.city].name+' 카드 버림'}`)}>연구소 건설 선택</button><small>{g.stations.includes(me.city)?'현재 도시에 이미 연구소가 있습니다.':'건설 전문가는 카드를 쓰지 않습니다. 그 외에는 현재 도시 카드가 필요합니다.'}</small></>}
 {tab==='SHARE'&&<><p>같은 도시에 있는 동료와 공유합니다.</p>{g.playerStates.filter(p=>p!==me&&p.city===me.city).map(p=><div key={p.playerId}><h4>{name(p.playerId)}</h4>{p.hand===null&&<button className="pd-action-option" disabled={blocked} onClick={()=>choose({type:'REQUEST_SHARE',from:p.playerId},`${name(p.playerId)}에게 카드 요청`,'동료가 전달할 카드를 선택합니다. 승인 시 행동 1회.')}>비공개 손패에서 카드 요청</button>}{(me.hand??[]).filter(c=>c.kind==='CITY'&&(me.role==='RESEARCHER'||c.city===me.city)).map(c=><button className="pd-action-option" key={c.cardId} disabled={blocked} onClick={()=>choose({type:'SHARE',from:self,to:p.playerId,cardId:c.cardId},`${name(p.playerId)}에게 ${cardName(c)} 주기`,'행동 1회 · 동료 동의 필요')}>{cardName(c)} 주기</button>)}{(p.hand??[]).filter(c=>c.kind==='CITY'&&(p.role==='RESEARCHER'||c.city===me.city)).map(c=><button className="pd-action-option" key={c.cardId} disabled={blocked} onClick={()=>choose({type:'SHARE',from:p.playerId,to:self,cardId:c.cardId},`${name(p.playerId)}에게 ${cardName(c)} 받기`,'행동 1회 · 동료 동의 필요')}>{cardName(c)} 받기</button>)}</div>)}{!g.playerStates.some(p=>p!==me&&p.city===me.city)&&<p className="pd-muted">같은 도시에 동료가 없습니다.</p>}</>}
 {tab==='CURE'&&<><p>연구소에서 같은 색 {me.role==='SCIENTIST'?4:5}장을 선택합니다.</p>{PANDEMIC_COLORS.map(c=>{const cards=(me.hand??[]).filter(x=>x.kind==='CITY'&&PANDEMIC_CITY_INFO[x.city].color===c),needed=me.role==='SCIENTIST'?4:5;return <div className="pd-cure-choice" key={c}><strong style={{color:DISEASE_COLORS[c]}}>{DISEASE_NAMES[c]} · {cards.length}/{needed}장</strong>{cards.map(card=><label key={card.cardId}><input type="checkbox" checked={cureCards.includes(card.cardId)} onChange={e=>{setDraft(null);setCureCards(old=>e.target.checked?[...old,card.cardId]:old.filter(id=>id!==card.cardId));}}/>{cardName(card)}</label>)}<button disabled={blocked||!g.stations.includes(me.city)||g.cures[c]!=='ACTIVE'||cureCards.length!==needed||!cureCards.every(id=>cards.some(c=>c.cardId===id))} onClick={()=>choose({type:'CURE',color:c,cards:cureCards},`${DISEASE_NAMES[c]} 치료제 발견`,`행동 1회 · ${cards.filter(c=>cureCards.includes(c.cardId)).map(cardName).join(', ')} 버림`)}>치료제 발견 선택</button></div>})}{!g.stations.includes(me.city)&&<p>먼저 연구소로 이동하세요.</p>}</>}
 <button className="pd-end-actions" disabled={blocked} onClick={()=>choose({type:'END_ACTIONS'},'행동을 마치고 카드 뽑기 준비',`남은 행동 ${g.actionsLeft}회를 사용하지 않습니다.`)}>남은 행동 마치기 →</button>
 </div>:g.phase==='ACTIONS'&&<div className="pd-wait"><h3>{name(g.activePlayerId)}님의 차례</h3><p>도시를 살펴보고 요청을 남기거나 이벤트를 사용할 수 있습니다.</p></div>}
 </>}
 {selectedCard?.kind==='EVENT'&&!finished&&g.phase!=='SETUP'&&!g.pending&&<div className="pd-event-detail"><h3>{PANDEMIC_EVENT_INFO[selectedCard.event].name}</h3><p>{PANDEMIC_EVENT_INFO[selectedCard.event].description}</p>{selectedCard.event==='AIRLIFT'&&<label className="pd-field">이동할 팀원<select value={target} onChange={e=>{const p=g.playerStates.find(p=>p.playerId===e.target.value);if(p){setTarget(p.playerId);setDraft(null);}}}>{g.playerStates.map(p=><option key={p.playerId} value={p.playerId}>{name(p.playerId)}</option>)}</select></label>}{selectedCard.event==='GRANT'&&g.stations.length===6&&stationPicker}{['AIRLIFT','GRANT','RESILIENT'].includes(selectedCard.event)&&<p>대상: {city.name}{selectedCard.event==='RESILIENT'?' (감염 버림패에서 선택)':''}</p>}<button disabled={blocked} onClick={()=>choose({type:'EVENT',cardId:selectedCard.cardId,target:selectedCard.event==='AIRLIFT'?target:null,city:['AIRLIFT','GRANT','RESILIENT'].includes(selectedCard.event)?selected:null,replace:selectedCard.event==='GRANT'&&g.stations.length===6?replace:null},PANDEMIC_EVENT_INFO[selectedCard.event].name,`행동 소모 없음 · ${me.stored?.cardId===selectedCard.cardId?'보관 이벤트를 게임에서 제거':'이벤트 카드 버림'}`)}>이벤트 사용 선택</button></div>}
 {draft&&!g.pending&&<div className="pd-confirm" role="status"><span className="pd-eyebrow">CONFIRM ACTION</span><h3>{draft.label}</h3><p>{draft.cost}</p><div className="pd-buttons"><button className="pd-primary" disabled={blocked} onClick={()=>void submit(draft.action)}>확정</button><button disabled={busy} onClick={()=>setDraft(null)}>취소</button></div></div>}
 <details className="pd-log"><summary>작전 기록 · {g.history.length}</summary><ol>{[...g.history].reverse().map(l=><li key={l.id}><span>{l.id.toString().padStart(2,'0')}</span>{l.text}</li>)}</ol></details>
 </aside></div>
 <div className="pd-hand-zone"><div className="pd-role-panel"><PandemicArt index={PANDEMIC_ROLE_INFO[me.role].art}/><div><span className="pd-eyebrow">YOUR SPECIALTY</span><h3>{PANDEMIC_ROLE_INFO[me.role].name}</h3><p>{PANDEMIC_ROLE_INFO[me.role].description}</p></div></div><div className="pd-hand"><div className="pd-hand-title"><h3>내 손패 <small>{me.handCount}/7</small></h3><span>{g.settings.openHands?'팀에게 공개':'나만 볼 수 있음'}</span></div><div className="pd-cards">{(me.hand??[]).map(card=><button key={card.cardId} aria-pressed={cardId===card.cardId} className={`pd-card ${card.kind==='CITY'?PANDEMIC_CITY_INFO[card.city].color:'EVENT'}`} onClick={()=>{setCardId(card.cardId);setDraft(null);if(card.kind==='CITY')setSelected(card.city);selectSound();}}><PandemicCardFace card={card}/></button>)}{me.handCount===0&&<p className="pd-muted">{g.phase==='SETUP'?'작전을 시작하면 카드를 받습니다.':'보유 카드가 없습니다.'}</p>}{me.stored&&<button className="pd-card EVENT" aria-pressed={cardId===me.stored.cardId} onClick={()=>{setCardId(me.stored!.cardId);selectSound();}}><PandemicCardFace card={me.stored}/><small>역할에 보관 · 손패 제외</small></button>}</div></div></div>
 <div className="pd-piles"><details><summary>팀원 손패 확인</summary><div>{g.playerStates.filter(p=>p!==me).map(p=><div key={p.playerId}><h4>{name(p.playerId)} · {PANDEMIC_ROLE_INFO[p.role].name}</h4>{p.hand?<div className="pd-compact-cards">{p.hand.map(c=><span key={c.cardId}>{cardName(c)}</span>)}</div>:<p>비공개 손패 {p.handCount}장 · 동료와 의논하세요.</p>}</div>)}</div></details><details><summary>감염 버림패 · {g.infectionDiscard.length}장</summary><div className="pd-compact-cards">{g.infectionDiscard.map(c=><button key={c} onClick={()=>selectCity(c)}>{PANDEMIC_CITY_INFO[c].name}</button>)}</div></details><details><summary>플레이어 버림패 · {g.discard.length}장</summary><div className="pd-compact-cards">{g.discard.map(c=><div key={c.cardId}><span>{cardName(c)}</span>{me.role==='PLANNER'&&c.kind==='EVENT'&&canAct&&!me.stored&&<button disabled={blocked} onClick={()=>choose({type:'STORE',cardId:c.cardId},`${cardName(c)} 보관`,'행동 1회 · 손패 제한에 포함되지 않음')}>보관 선택</button>}</div>)}</div></details><details><summary>이벤트 카드 안내</summary><div>{PANDEMIC_EVENTS.map(e=><p key={e}><b>{PANDEMIC_EVENT_INFO[e].name}</b> · {PANDEMIC_EVENT_INFO[e].description}</p>)}</div></details></div>
 </>;
}
