/** Optional Chrome check. Build first; set PLAYWRIGHT_MODULE and MARS_CHROME_PATH.
 * Own disposable server and trusted effect fixtures: no debug routes, no expansion deck activation.
 */
import assert from 'node:assert/strict';
import test from 'node:test';
import {createRequire} from 'node:module';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHttpServer} from '../apps/server/dist/server.js';
import {parseMarsState, applyMarsAction, marsOffers} from '../apps/server/dist/games/mars/domain/game.js';
import {transitionMars} from '../apps/server/dist/games/mars/application/service.js';
const require=createRequire(import.meta.url);

test('Mars private choice: illustrations, selection, reconnect, mobile, heat purchase, next-card discount, hand exchange, protection, production copy, land reservation and resource attacks', {timeout:120000}, async t=>{
 const server=createHttpServer({serveWeb:true});
 t.after(()=>server.shutdown());
 await new Promise(resolve=>server.httpServer.listen(0,'127.0.0.1',resolve));
 const url=`http://127.0.0.1:${server.httpServer.address().port}`;
 const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
 const browser=await chromium.launch({headless:true,...(process.env.MARS_CHROME_PATH?{executablePath:process.env.MARS_CHROME_PATH}:{})});
 t.after(async()=>{for(const [i,page] of pages.entries())if(!page.isClosed())await page.screenshot({path:join(output,`final-${i}.png`),fullPage:true});await browser.close();});
 const output=await mkdtemp(join(tmpdir(),'mars-private-browser-'));
 const errors=[],pages=[];
 for(let i=0;i<2;i++){
  const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
  const page=await context.newPage();page.setDefaultTimeout(15000);
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(url);pages.push(page);
 }
 const [host,guest]=pages;
 await host.getByLabel('닉네임',{exact:true}).fill('선택연구원');
 await host.locator('.game-option').filter({hasText:'테라포밍 마스'}).click();
 await host.getByRole('button',{name:'선택한 게임으로 방 만들기',exact:true}).click();
 const invite=host.getByRole('button',{name:/초대 ·/});await invite.waitFor();
 const code=(await invite.innerText()).split(' · ')[1];
 await guest.getByLabel('닉네임',{exact:true}).fill('다른연구원');
 await guest.locator('#room-code').fill(code);
 await guest.getByRole('button',{name:'방 참가하기',exact:true}).click();
 await guest.locator('.tm-lobby').waitFor();
 await host.getByRole('button',{name:'테라포밍 시작 →'}).click();
 await host.getByRole('button',{name:'선택 확정',exact:true}).click();
 await host.getByText('다른 기업의 선택을 기다립니다',{exact:true}).waitFor();
 await guest.getByRole('button',{name:'선택 확정',exact:true}).click();
 await host.locator('.tm-map').waitFor();
 const service=server.runtime.marsService;
 let owner,ownerPage;
 async function fixture(effect,helion=false){
  const room=await server.runtime.persistence.findByCode(code);
  assert.ok(room?.gameType==='TERRAFORMING_MARS'&&room.game);
  const state=parseMarsState(room.game.state);
  owner=state.players.find(p=>p.playerId===state.activePlayerId);
  ownerPage=room.players.find(p=>p.playerId===owner.playerId).nickname==='선택연구원'?host:guest;
  if(helion){owner.corporationId='Helion';owner.resources.money=1;owner.resources.heat=2;}
  state.frames=[[{id:state.nextJob++,source:'비공개 카드 열람',effect}]];
  state.actionInProgress=true;
  const offer=marsOffers(state,state.activePlayerId).find(o=>o.kind==='EFFECT');assert.ok(offer);
  const opened=applyMarsAction(state,state.activePlayerId,{type:'TAKE',actionId:offer.id},service.deps.clock.now(),service.deps.ids.generateTurnId(),service.deps.random);
  assert.ok(opened.ok);
  const result=await server.runtime.persistence.replace({candidate:transitionMars(room,opened.state,service.deps.clock.now()),expectedRoomRevision:room.roomRevision,expectedStorageRevision:room.storageRevision});
  assert.equal(result.status,'REPLACED');
  await service.notify(room.roomId);
  return opened.state.cardChoice?.view ?? null;
 }
 const pending=await fixture({kind:'keepCards',count:4,keep:2});
 const actor=ownerPage,other=actor===host?guest:host;
 const panel=actor.locator('.tm-card-choice');await panel.waitFor();
 assert.equal(await other.locator('.tm-card-choice').count(),0);
 assert.equal(await panel.locator('.tm-art').count(),4);
 assert.equal(await panel.getByRole('button',{name:'2장 선택 확정'}).isDisabled(),true);
 const titles=await panel.locator('.tm-card').allTextContents();
 await actor.reload();await panel.waitFor();
 assert.deepEqual(await panel.locator('.tm-card').allTextContents(),titles);
 await panel.locator('.tm-card').nth(0).focus();
 await panel.locator('.tm-card').nth(0).press('Space');
 await panel.locator('.tm-card').nth(1).click();
 assert.equal(await panel.locator('.tm-card').nth(2).isDisabled(),true);
 await actor.screenshot({path:join(output,'keep-desktop.png'),fullPage:true});
 await actor.setViewportSize({width:320,height:740});
 await actor.locator('.tm-mobile-nav').getByRole('button',{name:/^카드 선택/}).click();
 assert.equal(await actor.evaluate(()=>document.documentElement.scrollWidth),320);
 await actor.screenshot({path:join(output,'keep-mobile.png'),fullPage:true});
 await panel.getByRole('button',{name:'2장 선택 확정'}).click();await panel.waitFor({state:'detached'});
 let room=await server.runtime.persistence.findByCode(code),state=parseMarsState(room.game.state);
 let player=state.players.find(p=>p.playerId===owner.playerId);
 assert.equal(player.hand.length,12);
 for(const card of pending.cards.slice(0,2))assert.ok(player.hand.some(c=>c.tileId===card.tileId));
 await fixture({kind:'buyCard'},true);await panel.waitFor();
 await panel.locator('.tm-card').click();
 assert.equal(await panel.getByRole('button',{name:'구매 확정 · 3 M€'}).isDisabled(),true);
 await panel.getByLabel('구매에 사용할 열').fill('2');
 const heatBox=await panel.getByLabel('구매에 사용할 열').boundingBox();assert.ok(heatBox&&heatBox.height>=44);
 assert.equal(await actor.evaluate(()=>document.documentElement.scrollWidth),320);
 await actor.screenshot({path:join(output,'buy-heat-mobile.png'),fullPage:true});
 await panel.getByRole('button',{name:'구매 확정 · 3 M€'}).click();await panel.waitFor({state:'detached'});
 room=await server.runtime.persistence.findByCode(code);state=parseMarsState(room.game.state);
 player=state.players.find(p=>p.playerId===owner.playerId);
 assert.equal(player.resources.money,0);assert.equal(player.resources.heat,0);assert.equal(player.hand.length,13);
 await fixture({kind:'buyCard'});
 // Two actions advance ownership; only the next owner receives the next fixture.
 const nextActor=ownerPage;
 const nextPanel=nextActor.locator('.tm-card-choice');await nextPanel.waitFor();
 await nextPanel.getByRole('button',{name:'구매하지 않고 버리기'}).click();await nextPanel.waitFor({state:'detached'});
 // Trusted fixture for Indentured Workers' pending effect, while its full card remains outside the live deck.
 room=await server.runtime.persistence.findByCode(code);state=parseMarsState(room.game.state);
 const discountOwner=state.players.find(p=>p.playerId===state.activePlayerId);
 const discountPage=room.players.find(p=>p.playerId===discountOwner.playerId).nickname==='선택연구원'?host:guest;
 discountOwner.nextCardDiscount=8;
 let powerPlant;
 for(const zone of [state.deck,state.discard,...state.players.flatMap(p=>[p.hand,p.research,p.played])]){
  const index=zone.findIndex(c=>c.definitionId==='PowerPlant');
  if(index>=0){powerPlant=zone.splice(index,1)[0];break;}
 }
 assert.ok(powerPlant);discountOwner.hand.push(powerPlant);
 for(const p of state.players)p.handCount=p.hand.length;
 state.revision++;state.transitionId=service.deps.ids.generateTurnId();
 const replacement=await server.runtime.persistence.replace({candidate:transitionMars(room,parseMarsState(state),service.deps.clock.now()),expectedRoomRevision:room.roomRevision,expectedStorageRevision:room.storageRevision});
 assert.equal(replacement.status,'REPLACED');await service.notify(room.roomId);
 await discountPage.locator('.tm-next-discount').waitFor();
 await discountPage.reload();await discountPage.locator('.tm-next-discount').waitFor();
 await discountPage.setViewportSize({width:320,height:740});
 await discountPage.getByLabel('카드 검색',{exact:true}).fill('발전소');
 await discountPage.locator('.tm-hand-row').getByRole('button',{name:'발전소 · 0 M€',exact:true}).click();
 await discountPage.getByRole('button',{name:'행동 확정',exact:true}).click();
 await discountPage.locator('.tm-payment').waitFor();
 assert.match(await discountPage.locator('.tm-next-discount').innerText(),/필요 비용에 반영/);
 await discountPage.getByRole('button',{name:'지불 전 선택 취소',exact:true}).click();
 await discountPage.locator('.tm-payment').waitFor({state:'detached'});
 assert.equal(await discountPage.locator('.tm-next-discount').count(),1);
 await discountPage.locator('.tm-hand-row').getByRole('button',{name:'발전소 · 0 M€',exact:true}).click();
 await discountPage.getByRole('button',{name:'행동 확정',exact:true}).click();
 await discountPage.locator('.tm-payment').waitFor();
 await discountPage.screenshot({path:join(output,'next-card-discount-mobile.png'),fullPage:true});
 assert.equal(await discountPage.evaluate(()=>document.documentElement.scrollWidth),320);
 await discountPage.getByRole('button',{name:'지불·실행 확정',exact:true}).click();
 await discountPage.locator('.tm-next-discount').waitFor({state:'detached'});
 room=await server.runtime.persistence.findByCode(code);state=parseMarsState(room.game.state);
 const paid=state.players.find(p=>p.playerId===discountOwner.playerId);
 assert.equal(paid.nextCardDiscount,0);assert.equal(paid.resources.money,discountOwner.resources.money);
 assert.ok(paid.played.some(c=>c.tileId===powerPlant.tileId));
 const exchange=await fixture({kind:'exchangeCard'});assert.equal(exchange.kind,'EXCHANGE');
 const exchangePage=ownerPage,exchangePanel=exchangePage.locator('.tm-card-choice');await exchangePanel.waitFor();
 const unchangedHand=owner.hand.map(c=>c.tileId),drawnCard=(await server.runtime.persistence.findByCode(code)).game.state.deck[0];
 await exchangePage.reload();await exchangePanel.waitFor();
 assert.equal(await exchangePanel.locator('.tm-card').count(),unchangedHand.length);
 const exchangeOther=exchangePage===host?guest:host;assert.equal(await exchangeOther.locator('.tm-card-choice').count(),0);
 await exchangePanel.getByLabel('교환할 손패 검색').fill('아무카드도없음');assert.equal(await exchangePanel.locator('.tm-card').count(),0);
 await exchangePanel.getByLabel('교환할 손패 검색').fill('');
 await exchangePanel.locator('.tm-card').first().focus();await exchangePanel.locator('.tm-card').first().press('Space');
 await exchangePage.setViewportSize({width:320,height:740});
 assert.equal(await exchangePage.evaluate(()=>document.documentElement.scrollWidth),320);
 await exchangePage.screenshot({path:join(output,'hand-exchange-mobile.png'),fullPage:true});
 await exchangePanel.getByRole('button',{name:'1장 버리고 1장 뽑기 확정',exact:true}).click();await exchangePanel.waitFor({state:'detached'});
 room=await server.runtime.persistence.findByCode(code);state=parseMarsState(room.game.state);
 const exchanged=state.players.find(p=>p.playerId===owner.playerId);
 assert.equal(exchanged.hand.length,unchangedHand.length);assert.ok(exchanged.hand.some(c=>c.tileId===drawnCard.tileId));assert.ok(!exchanged.hand.some(c=>c.tileId===unchangedHand[0]));
 await fixture({kind:'exchangeCard'});const skipPage=ownerPage,skipPanel=skipPage.locator('.tm-card-choice');await skipPanel.waitFor();
 const skipHand=owner.hand.map(c=>c.tileId);
 await skipPanel.getByRole('button',{name:'교환하지 않고 계속',exact:true}).click();await skipPanel.waitFor({state:'detached'});
 room=await server.runtime.persistence.findByCode(code);state=parseMarsState(room.game.state);
 assert.deepEqual(state.players.find(p=>p.playerId===owner.playerId).hand.map(c=>c.tileId),skipHand);
 await fixture({kind:'protectHabitats'});
 const protectedName=ownerPage===host?'선택연구원':'다른연구원';
 for(const page of pages)await page.locator('.tm-player').filter({hasText:protectedName}).getByText('서식지 보호',{exact:true}).waitFor();
 await ownerPage.reload();await ownerPage.locator('.tm-player').filter({hasText:protectedName}).getByText('서식지 보호',{exact:true}).waitFor();
 assert.equal(await ownerPage.evaluate(()=>document.documentElement.scrollWidth), (await ownerPage.viewportSize()).width);
 await ownerPage.screenshot({path:join(output,'habitat-protection.png'),fullPage:true});
 room=await server.runtime.persistence.findByCode(code);state=parseMarsState(room.game.state);
 const copyOwner=state.players.find(p=>p.playerId===state.activePlayerId);copyOwner.production.energy=2;
 let building;
 for(const zone of [state.deck,state.discard,...state.players.flatMap(p=>[p.hand,p.research,p.played])]){
  const index=zone.findIndex(c=>c.definitionId==='DomedCrater');if(index>=0){building=zone.splice(index,1)[0];break;}
 }
 assert.ok(building);copyOwner.played.push(building);for(const p of state.players)p.handCount=p.hand.length;
 state.revision++;state.transitionId=service.deps.ids.generateTurnId();
 const copyPrepared=await server.runtime.persistence.replace({candidate:transitionMars(room,parseMarsState(state),service.deps.clock.now()),expectedRoomRevision:room.roomRevision,expectedStorageRevision:room.storageRevision});assert.equal(copyPrepared.status,'REPLACED');
 await fixture({kind:'copyProduction'});const copyPage=ownerPage;
 await copyPage.getByText('복제할 생산량 상자를 선택하세요',{exact:true}).waitFor();
 await copyPage.reload();await copyPage.getByText('복제할 생산량 상자를 선택하세요',{exact:true}).waitFor();
 await copyPage.locator('.tm-offer').filter({hasText:'돔 분화구 생산량 복제'}).click();
 await copyPage.setViewportSize({width:320,height:740});assert.equal(await copyPage.evaluate(()=>document.documentElement.scrollWidth),320);
 await copyPage.screenshot({path:join(output,'production-copy-mobile.png'),fullPage:true});
 await copyPage.getByRole('button',{name:'행동 확정',exact:true}).click();
 await copyPage.getByText('복제할 생산량 상자를 선택하세요',{exact:true}).waitFor({state:'detached'});
 room=await server.runtime.persistence.findByCode(code);state=parseMarsState(room.game.state);
 const copied=state.players.find(p=>p.playerId===copyOwner.playerId);
 assert.equal(copied.production.energy,1);assert.equal(copied.production.money,copyOwner.production.money+3);assert.deepEqual(copied.resources,copyOwner.resources);
 await fixture({kind:'claimLand'});const claimPage=ownerPage,claimOwner=owner.playerId;
 await claimPage.getByText('예약할 육지를 선택하세요',{exact:true}).waitFor();
 await claimPage.reload();await claimPage.getByText('예약할 육지를 선택하세요',{exact:true}).waitFor();
 const claimCell=claimPage.locator('.tm-hex').filter({has:claimPage.locator('text.tm-space-id').filter({hasText:/^4-4$/})});
 await claimCell.focus();await claimPage.keyboard.press('Enter');
 await claimPage.getByRole('button',{name:'예약 확정',exact:true}).click();
 await claimPage.getByText('예약할 육지를 선택하세요',{exact:true}).waitFor({state:'detached'});
 for(const page of pages){await page.getByRole('button',{name:'화성 지도',exact:true}).click();await page.locator('.tm-land-claim').waitFor();}
 room=await server.runtime.persistence.findByCode(code);state=parseMarsState(room.game.state);
 assert.deepEqual(state.landClaims,[{spaceId:'4-4',ownerId:claimOwner}]);assert.equal(state.tiles.some(t=>t.spaceId==='4-4'),false);
 await claimPage.reload();await claimPage.locator('.tm-land-claim').waitFor();
 await claimPage.setViewportSize({width:320,height:740});assert.equal(await claimPage.evaluate(()=>document.documentElement.scrollWidth),320);
 await claimPage.locator('.tm-center').screenshot({path:join(output,'land-reservation-mobile.png')});
 room=await server.runtime.persistence.findByCode(code);state=parseMarsState(room.game.state);
 const attackActor=state.players.find(p=>p.playerId===state.activePlayerId),victim=state.players.find(p=>p.playerId!==attackActor.playerId);
 victim.resources.steel=2;const actorSteel=attackActor.resources.steel;
 state.revision++;state.transitionId=service.deps.ids.generateTurnId();
 const attackPrepared=await server.runtime.persistence.replace({candidate:transitionMars(room,parseMarsState(state),service.deps.clock.now()),expectedRoomRevision:room.roomRevision,expectedStorageRevision:room.storageRevision});assert.equal(attackPrepared.status,'REPLACED');
 await fixture({kind:'attackStock',resource:'steel',amount:2,steal:true});const attackPage=ownerPage;
 await attackPage.getByText('대상과 자원 수량을 확인하세요',{exact:true}).waitFor();
 await attackPage.reload();await attackPage.getByText('대상과 자원 수량을 확인하세요',{exact:true}).waitFor();
 await attackPage.locator('.tm-offer').filter({hasText:'강철 1 탈취'}).click();
 await attackPage.setViewportSize({width:320,height:740});assert.equal(await attackPage.evaluate(()=>document.documentElement.scrollWidth),320);
 await attackPage.locator('.tm-confirm').screenshot({path:join(output,'resource-attack-mobile.png')});
 await attackPage.getByRole('button',{name:'행동 확정',exact:true}).click();
 await attackPage.getByText('대상과 자원 수량을 확인하세요',{exact:true}).waitFor({state:'detached'});
 room=await server.runtime.persistence.findByCode(code);state=parseMarsState(room.game.state);
 assert.equal(state.players.find(p=>p.playerId===attackActor.playerId).resources.steel,actorSteel+1);
 assert.equal(state.players.find(p=>p.playerId===victim.playerId).resources.steel,1);
 assert.equal(state.history.at(-1).kind,'ATTACK');
 room=await server.runtime.persistence.findByCode(code);state=parseMarsState(room.game.state);
 const fishOwner=state.players.find(p=>p.playerId===state.activePlayerId);
 const fishPage=room.players.find(p=>p.playerId===fishOwner.playerId).nickname==='선택연구원'?host:guest;
 let fish;
 for(const zone of [state.deck,state.discard,...state.players.flatMap(p=>[p.hand,p.research,p.played])]){
  const index=zone.findIndex(c=>c.definitionId==='Fish');if(index>=0){fish=zone.splice(index,1)[0];break;}
 }
 assert.ok(fish);fish.resources=1;fish.usedGeneration=0;fishOwner.played.push(fish);
 for(const p of state.players)p.handCount=p.hand.length;
 state.actionsTaken=0;state.revision++;state.transitionId=service.deps.ids.generateTurnId();
 const fishPrepared=await server.runtime.persistence.replace({candidate:transitionMars(room,parseMarsState(state),service.deps.clock.now()),expectedRoomRevision:room.roomRevision,expectedStorageRevision:room.storageRevision});assert.equal(fishPrepared.status,'REPLACED');await service.notify(room.roomId);
 await fishPage.getByRole('button',{name:'낸 카드',exact:true}).click();
 const fishCard=fishPage.locator('.tm-card').filter({has:fishPage.locator('.tm-card-top strong').filter({hasText:/^어류$/})});
 await fishCard.getByText('동물 1개당 1 VP',{exact:true}).waitFor();await fishCard.getByText('동물 1',{exact:true}).waitFor();
 await fishCard.click();await fishPage.getByRole('button',{name:'행동 확정',exact:true}).click();
 await fishCard.getByText('동물 2',{exact:true}).waitFor();
 await fishPage.setViewportSize({width:320,height:740});assert.equal(await fishPage.evaluate(()=>document.documentElement.scrollWidth),320);
 await fishCard.screenshot({path:join(output,'card-resource-scoring-mobile.png')});
 room=await server.runtime.persistence.findByCode(code);state=parseMarsState(room.game.state);
 const savedFish=state.players.find(p=>p.playerId===fishOwner.playerId).played.find(c=>c.tileId===fish.tileId);
 assert.equal(savedFish.resources,2);assert.equal(savedFish.usedGeneration,state.generation);
 room=await server.runtime.persistence.findByCode(code);state=parseMarsState(room.game.state);
 const reducedPlayer=state.players.find(p=>p.playerId!==state.activePlayerId);reducedPlayer.production.money=-3;reducedPlayer.protectedHabitats=true;
 const beforeReduction=structuredClone(reducedPlayer.resources);state.revision++;state.transitionId=service.deps.ids.generateTurnId();
 const reductionPrepared=await server.runtime.persistence.replace({candidate:transitionMars(room,parseMarsState(state),service.deps.clock.now()),expectedRoomRevision:room.roomRevision,expectedStorageRevision:room.storageRevision});assert.equal(reductionPrepared.status,'REPLACED');
 await fixture({kind:'attackProduction',resource:'money',amount:2});const reductionPage=ownerPage;
 await reductionPage.getByText('생산량을 줄일 기업을 선택하세요',{exact:true}).waitFor();
 await reductionPage.reload();await reductionPage.getByText('생산량을 줄일 기업을 선택하세요',{exact:true}).waitFor();
 await reductionPage.locator('.tm-offer').filter({hasText:'-3 → -5'}).click();
 await reductionPage.setViewportSize({width:320,height:740});assert.equal(await reductionPage.evaluate(()=>document.documentElement.scrollWidth),320);
 await reductionPage.locator('.tm-confirm').screenshot({path:join(output,'production-attack-mobile.png')});
 await reductionPage.getByRole('button',{name:'행동 확정',exact:true}).click();
 await reductionPage.getByText('생산량을 줄일 기업을 선택하세요',{exact:true}).waitFor({state:'detached'});
 room=await server.runtime.persistence.findByCode(code);state=parseMarsState(room.game.state);
 const reduced=state.players.find(p=>p.playerId===reducedPlayer.playerId);assert.equal(reduced.production.money,-5);assert.deepEqual(reduced.resources,beforeReduction);
 assert.deepEqual(errors,[]);
 t.diagnostic(`Screenshots: ${output}`);
});
