import * as v from 'valibot';
import { MARS_BOARD } from './board.js';
import { GameIdSchema, PlayerIdSchema, TurnIdSchema, TileIdSchema } from '../../identifiers.js';
import { GameRevisionSchema } from '../../protocol.js';
import { MarsCountSchema, MarsIntegerSchema, MarsRefSchema, MarsCardSchema, MarsPlayerPublicSchema, MarsOfferSchema } from './actions.js';
export const MarsTileSchema = v.strictObject({ spaceId: MarsRefSchema, kind: v.picklist(['city', 'greenery', 'ocean', 'special']), ownerId: v.nullable(PlayerIdSchema), source: MarsRefSchema });
export const MarsScoreSchema = v.strictObject({ playerId: PlayerIdSchema, tr: MarsCountSchema, cards: MarsIntegerSchema, greenery: MarsCountSchema, cities: MarsCountSchema, milestones: MarsCountSchema, awards: MarsCountSchema, total: MarsIntegerSchema, money: MarsCountSchema });
export const MarsResultSchema = v.strictObject({ reason: v.picklist(['SCORED', 'CANCELLED']), scores: v.array(MarsScoreSchema), winnerPlayerIds: v.array(PlayerIdSchema) });
export const MarsClaimSchema = v.strictObject({ id: MarsRefSchema, playerId: PlayerIdSchema });
export const MarsHistorySchema = v.strictObject({ id: MarsCountSchema, generation: MarsCountSchema, playerId: PlayerIdSchema, kind: v.picklist(['SETUP', 'RESEARCH', 'CARD', 'ACTION', 'PLACE', 'TERRAFORM', 'PRODUCTION', 'PASS', 'CLAIM', 'ATTACK', 'FINISH']), text: v.pipe(v.string(), v.maxLength(700)) });
export const MarsPublicFields = { corporateEra: v.optional(v.boolean()), prelude:v.optional(v.boolean()), generation: v.pipe(MarsCountSchema, v.minValue(1)), stage: v.picklist(['SETUP', 'PRELUDE', 'RESEARCH', 'ACTION', 'FINAL_GREENERY']), activePlayerId: PlayerIdSchema, startingPlayerId: PlayerIdSchema, actionsTaken: v.pipe(MarsCountSchema, v.maxValue(2)), oxygen: v.pipe(MarsCountSchema, v.maxValue(14)), temperature: v.pipe(MarsIntegerSchema, v.minValue(-30), v.maxValue(8)), oceans: v.pipe(MarsCountSchema, v.maxValue(9)), tiles: v.array(MarsTileSchema), landClaims: v.pipe(v.array(v.strictObject({ spaceId: MarsRefSchema, ownerId: PlayerIdSchema })), v.maxLength(61)), milestones: v.pipe(v.array(MarsClaimSchema), v.maxLength(3)), awards: v.pipe(v.array(MarsClaimSchema), v.maxLength(3)), history: v.pipe(v.array(MarsHistorySchema), v.maxLength(120)), playerStates: v.pipe(v.array(MarsPlayerPublicSchema), v.minLength(2), v.maxLength(5)), deckCount: MarsCountSchema, discardCount: MarsCountSchema };
export const MarsPaymentViewSchema = v.strictObject({ label: MarsRefSchema, cost: MarsCountSchema, microbes:v.optional(MarsCountSchema), steel: v.boolean(), titanium: v.boolean(), heat: v.boolean(), steelValue: v.picklist([2, 3]), titaniumValue: v.picklist([3, 4, 5]), cardId: v.nullable(TileIdSchema), cancelable: v.boolean() });
const ChoiceCards = v.pipe(v.array(MarsCardSchema), v.minLength(1), v.maxLength(4));
const ChoiceBase = { id: v.pipe(MarsCountSchema, v.minValue(1)), label: MarsRefSchema, cards: ChoiceCards };
export const MarsCardChoiceSchema = v.variant('kind', [
    v.strictObject({ ...ChoiceBase, kind: v.literal('EXCHANGE'), cards: v.pipe(v.array(MarsCardSchema), v.length(0)) }),
    v.pipe(v.strictObject({ ...ChoiceBase, kind: v.literal('KEEP'), keepCount: v.pipe(MarsCountSchema, v.minValue(1), v.maxValue(4)) }), v.check(c => c.keepCount <= c.cards.length)),
    v.strictObject({ ...ChoiceBase, kind: v.literal('BUY'), cards: v.pipe(ChoiceCards, v.length(1)), cost: v.literal(3), canUseHeat: v.boolean() }),
]);
export type MarsCardChoice = v.InferOutput<typeof MarsCardChoiceSchema>;
const Base = { gameType: v.literal('TERRAFORMING_MARS'), gameId: GameIdSchema, gameRevision: GameRevisionSchema, rulesVersion: v.literal('mars-base-v1'), ...MarsPublicFields, privateState: v.strictObject({ playerId: PlayerIdSchema, preludes:v.optional(v.array(MarsCardSchema)), nextCardDiscount: v.picklist([0, 8]), hand: v.array(MarsCardSchema), research: v.array(MarsCardSchema), corporations: v.array(MarsRefSchema), offers: v.array(MarsOfferSchema), payment: v.nullable(MarsPaymentViewSchema), cardChoice: v.nullable(MarsCardChoiceSchema), cardStatus: v.array(v.strictObject({ tileId: TileIdSchema, cost: MarsCountSchema, reason: v.nullable(v.pipe(v.string(), v.maxLength(700))) })) }) };
export const MarsPlayingProjectionSchema = v.strictObject({ ...Base, phase: v.literal('PLAYING'), turnId: TurnIdSchema });
export const MarsFinishedProjectionSchema = v.strictObject({ ...Base, phase: v.literal('FINISHED'), result: MarsResultSchema });
export type MarsProjection = v.InferOutput<typeof MarsPlayingProjectionSchema> | v.InferOutput<typeof MarsFinishedProjectionSchema>;
export function marsProjectionIsConsistent(g: MarsProjection): boolean { const ids = g.playerStates.map(p => p.playerId), me = g.playerStates.find(p => p.playerId === g.privateState.playerId); return marsLandClaimsAreConsistent(g, ids) && new Set(ids).size === ids.length && ids.includes(g.activePlayerId) && ids.includes(g.startingPlayerId) && !!me && me.handCount === g.privateState.hand.length && new Set(g.tiles.map(t => t.spaceId)).size === g.tiles.length && g.tiles.every(t => t.ownerId === null || ids.includes(t.ownerId)) && g.tiles.filter(t => t.kind === 'ocean').length === g.oceans && [...g.milestones, ...g.awards].every(c => ids.includes(c.playerId)) && new Set(g.privateState.offers.map(o => o.id)).size === g.privateState.offers.length && (!g.privateState.cardChoice || (g.phase === 'PLAYING' && ['ACTION','PRELUDE'].includes(g.stage) && g.activePlayerId === g.privateState.playerId && g.privateState.payment === null && g.privateState.offers.length === 0 && (g.privateState.cardChoice.kind !== 'EXCHANGE' || g.privateState.hand.length > 0) && new Set(g.privateState.cardChoice.cards.map(c => c.tileId)).size === g.privateState.cardChoice.cards.length && g.privateState.cardChoice.cards.every(c => ![...g.privateState.hand, ...g.privateState.research, ...g.playerStates.flatMap(p => p.played)].some(other => other.tileId === c.tileId)))) && (g.phase !== 'FINISHED' || g.result.winnerPlayerIds.every(id => ids.includes(id))); }

export function marsLandClaimsAreConsistent(g: Pick<MarsProjection, 'landClaims' | 'tiles'>, playerIds: readonly string[]): boolean {
    return new Set(g.landClaims.map(c => c.spaceId)).size === g.landClaims.length && g.landClaims.every(c => playerIds.includes(c.ownerId) && MARS_BOARD.some(b => b.id === c.spaceId && !b.ocean && !b.reserved) && !g.tiles.some(t => t.spaceId === c.spaceId));
}
