import * as v from 'valibot';
import { GameIdSchema, PlayerIdSchema, TurnIdSchema, TileIdSchema } from '../../identifiers.js';
import { GameRevisionSchema } from '../../protocol.js';
import { MarsCountSchema, MarsIntegerSchema, MarsRefSchema, MarsCardSchema, MarsPlayerPublicSchema, MarsOfferSchema } from './actions.js';
export const MarsTileSchema = v.strictObject({ spaceId: MarsRefSchema, kind: v.picklist(['city', 'greenery', 'ocean', 'special']), ownerId: v.nullable(PlayerIdSchema), source: MarsRefSchema });
export const MarsScoreSchema = v.strictObject({ playerId: PlayerIdSchema, tr: MarsCountSchema, cards: MarsIntegerSchema, greenery: MarsCountSchema, cities: MarsCountSchema, milestones: MarsCountSchema, awards: MarsCountSchema, total: MarsIntegerSchema, money: MarsCountSchema });
export const MarsResultSchema = v.strictObject({ reason: v.picklist(['SCORED', 'CANCELLED']), scores: v.array(MarsScoreSchema), winnerPlayerIds: v.array(PlayerIdSchema) });
export const MarsClaimSchema = v.strictObject({ id: MarsRefSchema, playerId: PlayerIdSchema });
export const MarsHistorySchema = v.strictObject({ id: MarsCountSchema, generation: MarsCountSchema, playerId: PlayerIdSchema, kind: v.picklist(['SETUP', 'RESEARCH', 'CARD', 'ACTION', 'PLACE', 'TERRAFORM', 'PRODUCTION', 'PASS', 'CLAIM', 'FINISH']), text: v.pipe(v.string(), v.maxLength(700)) });
export const MarsPublicFields = { generation: v.pipe(MarsCountSchema, v.minValue(1)), stage: v.picklist(['SETUP', 'RESEARCH', 'ACTION', 'FINAL_GREENERY']), activePlayerId: PlayerIdSchema, startingPlayerId: PlayerIdSchema, actionsTaken: v.pipe(MarsCountSchema, v.maxValue(2)), oxygen: v.pipe(MarsCountSchema, v.maxValue(14)), temperature: v.pipe(MarsIntegerSchema, v.minValue(-30), v.maxValue(8)), oceans: v.pipe(MarsCountSchema, v.maxValue(9)), tiles: v.array(MarsTileSchema), milestones: v.pipe(v.array(MarsClaimSchema), v.maxLength(3)), awards: v.pipe(v.array(MarsClaimSchema), v.maxLength(3)), history: v.pipe(v.array(MarsHistorySchema), v.maxLength(120)), playerStates: v.pipe(v.array(MarsPlayerPublicSchema), v.minLength(2), v.maxLength(5)), deckCount: MarsCountSchema, discardCount: MarsCountSchema };
export const MarsPaymentViewSchema = v.strictObject({ label: MarsRefSchema, cost: MarsCountSchema, steel: v.boolean(), titanium: v.boolean(), heat: v.boolean(), steelValue: v.picklist([2, 3]), titaniumValue: v.picklist([3, 4, 5]), cardId: v.nullable(TileIdSchema), cancelable: v.boolean() });
const Base = { gameType: v.literal('TERRAFORMING_MARS'), gameId: GameIdSchema, gameRevision: GameRevisionSchema, rulesVersion: v.literal('mars-base-v1'), ...MarsPublicFields, privateState: v.strictObject({ playerId: PlayerIdSchema, hand: v.array(MarsCardSchema), research: v.array(MarsCardSchema), corporations: v.array(MarsRefSchema), offers: v.array(MarsOfferSchema), payment: v.nullable(MarsPaymentViewSchema), cardStatus: v.array(v.strictObject({ tileId: TileIdSchema, cost: MarsCountSchema, reason: v.nullable(v.pipe(v.string(), v.maxLength(700))) })) }) };
export const MarsPlayingProjectionSchema = v.strictObject({ ...Base, phase: v.literal('PLAYING'), turnId: TurnIdSchema });
export const MarsFinishedProjectionSchema = v.strictObject({ ...Base, phase: v.literal('FINISHED'), result: MarsResultSchema });
export type MarsProjection = v.InferOutput<typeof MarsPlayingProjectionSchema> | v.InferOutput<typeof MarsFinishedProjectionSchema>;
export function marsProjectionIsConsistent(g: MarsProjection): boolean { const ids = g.playerStates.map(p => p.playerId), me = g.playerStates.find(p => p.playerId === g.privateState.playerId); return new Set(ids).size === ids.length && ids.includes(g.activePlayerId) && ids.includes(g.startingPlayerId) && !!me && me.handCount === g.privateState.hand.length && new Set(g.tiles.map(t => t.spaceId)).size === g.tiles.length && g.tiles.every(t => t.ownerId === null || ids.includes(t.ownerId)) && g.tiles.filter(t => t.kind === 'ocean').length === g.oceans && [...g.milestones, ...g.awards].every(c => ids.includes(c.playerId)) && new Set(g.privateState.offers.map(o => o.id)).size === g.privateState.offers.length && (g.phase !== 'FINISHED' || g.result.winnerPlayerIds.every(id => ids.includes(id))); }
