// Display names cross-checked with the public Korean locale; publisher verification remains separate.
export const MARS_KOREAN_NAMES: Readonly<Record<string,string>> = {
  "AdaptationTechnology": "적응기술",
  "AdaptedLichen": "개량종 지의류",
  "AdvancedEcosystems": "발달된 생태계",
  "AerobrakedAmmoniaAsteroid": "암모니아 소행성 대기권제동 소각",
  "Ants": "개미",
  "AquiferPumping": "지하수 개발",
  "Algae": "조류",
  "ArchaeBacteria": "고세균",
  "ArcticAlgae": "극지 미세조류",
  "ArtificialLake": "인공 호수",
  "ArtificialPhotosynthesis": "인공 광합성 기술",
  "AsteroidMining": "소행성 채굴",
  "BeamFromAThoriumAsteroid": "토륨 소행성 핵발전소",
  "BigAsteroid": "대형 소행성",
  "BiomassCombustors": "바이오매스 연소시설",
  "Birds": "새",
  "BlackPolarDust": "흑색 분말",
  "BreathingFilters": "호흡 필터",
  "Bushes": "덤불",
  "CarbonateProcessing": "탄산염 분해 작업",
  "CloudSeeding": "인공 구름 형성",
  "ColonizerTrainingCamp": "개척단 훈련소",
  "Comet": "혜성",
  "ConvoyFromEuropa": "유로파 수송선단",
  "CupolaCity": "반구형 도시",
  "Decomposers": "분해자 생물",
  "DeepWellHeating": "심부유정 발열",
  "DesignedMicroOrganisms": "인공 미생물",
  "DomedCrater": "돔 크레이터",
  "DustSeals": "더스트 실",
  "EnergySaving": "에너지 절약",
  "EosChasmaNationalPark": "에오스 협곡 국립공원",
  "EquatorialMagnetizer": "적도 자기장 생성기",
  "ExtremeColdFungus": "극호냉성 진균류",
  "Farming": "농업시설",
  "Fish": "물고기",
  "Flooding": "홍수",
  "FoodFactory": "식량 공장",
  "FusionPower": "핵융합 발전",
  "FueledGenerators": "화력 발전",
  "GanymedeColony": "가니메데 정착지",
  "GeothermalPower": "지열 발전",
  "GHGFactories": "온실가스 공장",
  "GHGProducingBacteria": "온실가스 생산 세균",
  "GiantIceAsteroid": "거대 얼음형 소행성",
  "GiantSpaceMirror": "초대형 우주 거울",
  "Grass": "풀",
  "Greenhouses": "온실",
  "Heather": "칼루나",
  "HeatTrappers": "축열 장치",
  "Herbivores": "초식동물",
  "IceAsteroid": "얼음형 소행성",
  "IceCapMelting": "극관 해빙",
  "ImmigrantCity": "이민자 도시",
  "ImmigrationShuttles": "이민자 수송 왕복선",
  "ImportedGHG": "온실가스 수입",
  "ImportedHydrogen": "수소 수입",
  "ImportedNitrogen": "질소 수입",
  "ImportOfAdvancedGHG": "강화형 온실가스 수입",
  "IndustrialMicrobes": "공업용 미생물",
  "Insects": "곤충",
  "Insulation": "단열 처리",
  "Ironworks": "제철소",
  "KelpFarming": "해초 양식장",
  "LakeMarineris": "마리네리스 호수",
  "LargeConvoy": "대규모 수송선단",
  "Lichen": "지의류",
  "Livestock": "가축",
  "LocalHeatTrapping": "국소적 축열",
  "LunarBeam": "루나 빔",
  "MagneticFieldDome": "자기장 돔",
  "Mangrove": "맹그로브",
  "MartianRails": "화성 열차",
  "MethaneFromTitan": "타이탄에서 메테인 수입",
  "MicroMills": "소형 풍차",
  "MiningExpedition": "대규모 채굴",
  "Moss": "이끼류",
  "NitriteReducingBacteria": "질산환원균",
  "NitrogenRichAsteroid": "다질소 소행성",
  "NitrophilicMoss": "호질소성 이끼류",
  "NoctisCity": "녹티스 시티",
  "NoctisFarming": "녹티스 농경지",
  "NuclearPower": "원자력 발전",
  "OpenCity": "개방형 도시",
  "OptimalAerobraking": "첨단 대기권제동기술",
  "OreProcessor": "광석 제련",
  "PermafrostExtraction": "영구동토층 해동",
  "PeroxidePower": "과산화물 발전",
  "Pets": "애완동물",
  "PhobosSpaceHaven": "포보스 우주휴게소",
  "Plantation": "산림조성지",
  "PowerGrid": "전력망",
  "Predators": "포식동물",
  "ProtectedValley": "계곡 보호",
  "RadChemFactory": "방사선흡수화합물 공장",
  "RegolithEaters": "표토 섭식 미생물",
  "ReleaseOfInertGases": "불활성기체 분출",
  "ResearchOutpost": "연구 전진기지",
  "RoverConstruction": "로버 공장",
  "SearchForLife": "생명체 탐사",
  "Shuttles": "왕복선",
  "SmallAnimals": "소형 동물",
  "SoilFactory": "토양정화소",
  "SolarPower": "태양광 발전",
  "SolarWindPower": "태양풍 발전",
  "Soletta": "솔레타",
  "SpaceMirrors": "우주 거울",
  "SpecialDesign": "특수 설계",
  "Steelworks": "제강소",
  "StripMine": "노천채굴",
  "SubterraneanReservoir": "대수층",
  "SymbioticFungus": "공생성 진균류",
  "TectonicStressPower": "지체응력 발전",
  "TowingAComet": "혜성 견인",
  "Trees": "나무",
  "TundraFarming": "툰드라 농경지",
  "UndergroundCity": "지하 도시",
  "UndergroundDetonations": "지하 핵폭발",
  "UrbanizedArea": "광역 대도시권",
  "WaterImportFromEuropa": "유로파에서 물 수입",
  "WaterSplittingPlant": "전기분해설비",
  "WavePower": "파력 발전",
  "Windmills": "풍차",
  "Worms": "연형동물",
  "Zeppelins": "체펠린 비행선",
  "AcquiredCompany": "합병 회사",
  "AdvancedAlloys": "첨단 합금",
  "AICentral": "중앙 인공지능 센터",
  "AntiGravityTechnology": "반중력기술",
  "AsteroidMiningConsortium": "소행성 채굴 컨소시엄",
  "BribedCommittee": "위원회 매수",
  "BuildingIndustries": "공업단지 건설",
  "BusinessContacts": "사업 계약",
  "BusinessNetwork": "비즈니스 네트워크",
  "CallistoPenalMines": "칼리스토 교도소 노역장",
  "CaretakerContract": "항온 관리 계약",
  "Cartel": "카르텔",
  "CEOsFavoriteProject": "회장님께서 좋아하시는 프로젝트",
  "CommercialDistrict": "상업지구",
  "CorporateStronghold": "사유화 도시",
  "DevelopmentCenter": "개발본부",
  "EarthCatapult": "지구 우주발사기지",
  "EarthOffice": "지구 지사",
  "ElectroCatapult": "전자기식 투사장치",
  "EnergyTapping": "전기 도둑질",
  "FuelFactory": "정유소",
  "GeneRepair": "유전자 복구 기술",
  "GreatEscarpmentConsortium": "단애 채굴 컨소시엄",
  "Hackers": "해커",
  "HiredRaiders": "무장강도단 고용",
  "IndenturedWorkers": "무급계약노동자",
  "InterstellarColonyShip": "항성간 개척선",
  "InventionContest": "발명 대회",
  "InventorsGuild": "발명가 협회",
  "InvestmentLoan": "투자차관",
  "IoMiningIndustries": "이오 채굴산업",
  "LagrangeObservatory": "라그랑주 천문관측소",
  "LandClaim": "영토 소유권 주장",
  "LightningHarvest": "번개걷이",
  "MarsUniversity": "화성 대학교",
  "MassConverter": "질량변환기",
  "MediaArchives": "미디어 아카이브",
  "MediaGroup": "미디어 그룹",
  "MedicalLab": "의학 연구실",
  "Mine": "광산",
  "MineralDeposit": "광물 매장층",
  "MirandaResort": "미란다 리조트",
  "OlympusConference": "올림푸스 컨퍼런스",
  "PhysicsComplex": "물리 복합연구단지",
  "PowerInfrastructure": "전력 공급 인프라",
  "PowerSupplyConsortium": "전력 공급 컨소시엄",
  "ProtectedHabitats": "서식지 보호",
  "QuantumExtractor": "양자추출기",
  "RadSuits": "방사선 안전복",
  "Research": "연구",
  "RoboticWorkforce": "산업용 로봇",
  "Satellites": "인공위성",
  "SecurityFleet": "평화수호함대",
  "SpaceElevator": "우주 엘리베이터",
  "SpaceStation": "우주정거장",
  "Sponsors": "후원",
  "StandardTechnology": "표준 기술",
  "Tardigrades": "완보동물",
  "TechnologyDemonstration": "신기술 시연",
  "TerraformingGanymede": "테라포밍 가니메데",
  "TitaniumMine": "티타늄 광산",
  "TollStation": "통행료 징수기지",
  "TransNeptuneProbe": "해왕성 궤도 바깥 탐사선",
  "TropicalResort": "열대 리조트",
  "VestaShipyard": "베스타 조선소",
  "ViralEnhancers": "바이러스 벡터",
  "Virus": "바이러스",
  "IndustrialCenter":"산업 중심지",
  "MiningArea":"채굴 구역",
  "RestrictedArea":"제한 구역",
  "Sabotage":"사보타주"
};
