import * as v from 'valibot';
import { PlayerIdSchema, TileIdSchema } from '../../identifiers.js';
export const ArnakCountSchema = v.pipe(v.number(), v.safeInteger(), v.minValue(0), v.maxValue(10000));
export const ArnakRefSchema = v.pipe(v.string(), v.minLength(1), v.maxLength(300));
export const ArnakResourcesSchema = v.strictObject({ coin: ArnakCountSchema, compass: ArnakCountSchema, tablet: ArnakCountSchema, arrow: ArnakCountSchema, jewel: ArnakCountSchema });
export type ArnakResources = v.InferOutput<typeof ArnakResourcesSchema>;
export type ArnakResource = keyof ArnakResources;
export const ArnakTravelSchema = v.picklist(['foot', 'car', 'boat', 'plane']);
export type ArnakTravel = v.InferOutput<typeof ArnakTravelSchema>;
export const ArnakCardSchema = v.strictObject({ tileId: TileIdSchema, definitionId: ArnakRefSchema });
export type ArnakCard = v.InferOutput<typeof ArnakCardSchema>;
export const ArnakActionSchema = v.strictObject({ type: v.literal('TAKE'), actionId: ArnakRefSchema });
export type ArnakAction = v.InferOutput<typeof ArnakActionSchema>;
export const ArnakOfferSchema = v.strictObject({ id: ArnakRefSchema, kind: v.picklist(['DIG', 'DISCOVER', 'BUY', 'CARD', 'RESEARCH', 'GUARDIAN', 'ASSISTANT', 'IDOL', 'BOON', 'EFFECT', 'END', 'PASS', 'KEEP']), targetId: ArnakRefSchema, label: ArnakRefSchema, detail: v.pipe(v.string(), v.maxLength(1000)), cost: ArnakResourcesSchema, cards: v.pipe(v.array(TileIdSchema), v.maxLength(100)), free: v.boolean() });
export type ArnakOffer = v.InferOutput<typeof ArnakOfferSchema>;
export const ArnakAssistantSchema = v.strictObject({ definitionId: ArnakRefSchema, gold: v.boolean(), ready: v.boolean() });
export const ArnakGuardianSchema = v.strictObject({ definitionId: ArnakRefSchema, used: v.boolean() });
export const ArnakPlayerPublicSchema = v.strictObject({ playerId: PlayerIdSchema, resources: ArnakResourcesSchema, workers: ArnakCountSchema, handCount: ArnakCountSchema, deckCount: ArnakCountSchema, played: v.array(ArnakCardSchema), assistants: v.pipe(v.array(ArnakAssistantSchema), v.maxLength(2)), guardians: v.array(ArnakGuardianSchema), idols: ArnakCountSchema, idolSlots: v.pipe(ArnakCountSchema, v.maxValue(4)), magnifier: ArnakRefSchema, notebook: ArnakRefSchema, templePoints: ArnakCountSchema, fearTiles: ArnakCountSchema, passed: v.boolean() });
export type ArnakPlayerPublic = v.InferOutput<typeof ArnakPlayerPublicSchema>;
