import * as v from 'valibot';
import { GameIdSchema, PlayerIdSchema, TurnIdSchema } from '../../identifiers.js';
import { GameRevisionSchema } from '../../protocol.js';
import { ArnakCountSchema, ArnakRefSchema, ArnakTravelSchema, ArnakCardSchema, ArnakPlayerPublicSchema, ArnakOfferSchema } from './actions.js';
export const ArnakSiteSchema = v.strictObject({ id: ArnakRefSchema, level: v.picklist([0, 1, 2]), definitionId: v.nullable(ArnakRefSchema), guardianId: v.nullable(ArnakRefSchema), travel: v.array(v.array(ArnakTravelSchema)), occupants: v.array(v.nullable(PlayerIdSchema)), blocked: v.array(v.boolean()), idolReward: v.nullable(ArnakRefSchema), idolCount: ArnakCountSchema });
export const ArnakScoreSchema = v.strictObject({ playerId: PlayerIdSchema, research: ArnakCountSchema, temple: ArnakCountSchema, guardians: ArnakCountSchema, idols: ArnakCountSchema, slots: ArnakCountSchema, cards: v.pipe(v.number(), v.safeInteger()), fear: ArnakCountSchema, total: v.pipe(v.number(), v.safeInteger()) });
export const ArnakResultSchema = v.strictObject({ reason: v.picklist(['SCORED', 'CANCELLED']), winnerPlayerIds: v.array(PlayerIdSchema), scores: v.array(ArnakScoreSchema) });
export const ArnakLogSchema = v.strictObject({ id: ArnakCountSchema, playerId: PlayerIdSchema, kind: ArnakRefSchema, text: v.pipe(v.string(), v.maxLength(1000)), round: ArnakCountSchema });
export const ArnakPublicFields = { round: v.pipe(ArnakCountSchema, v.minValue(1), v.maxValue(5)), playerStates: v.pipe(v.array(ArnakPlayerPublicSchema), v.minLength(2), v.maxLength(4)), activePlayerId: PlayerIdSchema, startingPlayerId: PlayerIdSchema, mainActionUsed: v.boolean(), stage: v.picklist(['ACTION', 'CLEANUP']), sites: v.array(ArnakSiteSchema), market: v.array(ArnakCardSchema), itemDeckCount: ArnakCountSchema, artifactDeckCount: ArnakCountSchema, assistantSupply: v.array(v.array(ArnakRefSchema)), researchBonuses: v.record(ArnakRefSchema, ArnakRefSchema), templeRewards: v.array(ArnakRefSchema), templeSupply: v.array(ArnakCountSchema), templeArrival: v.array(PlayerIdSchema), history: v.pipe(v.array(ArnakLogSchema), v.maxLength(120)), pendingLabels: v.array(ArnakRefSchema) };
const Base = { gameType: v.literal('ARNAK'), gameId: GameIdSchema, gameRevision: GameRevisionSchema, rulesVersion: v.literal('arnak-bird-v1'), ...ArnakPublicFields, privateState: v.strictObject({ playerId: PlayerIdSchema, hand: v.array(ArnakCardSchema), revealedCards: v.array(ArnakCardSchema), keep: v.array(ArnakRefSchema), travel: v.optional(v.array(ArnakTravelSchema)), blockedActions: v.optional(v.array(v.strictObject({ targetId: ArnakRefSchema, label: ArnakRefSchema, reasons: v.pipe(v.array(ArnakRefSchema), v.maxLength(20)) }))), offers: v.pipe(v.array(ArnakOfferSchema), v.maxLength(5000)) }) };
export const ArnakPlayingProjectionSchema = v.strictObject({ ...Base, phase: v.literal('PLAYING'), turnId: TurnIdSchema });
export const ArnakFinishedProjectionSchema = v.strictObject({ ...Base, phase: v.literal('FINISHED'), result: ArnakResultSchema });
export type ArnakProjection = v.InferOutput<typeof ArnakPlayingProjectionSchema> | v.InferOutput<typeof ArnakFinishedProjectionSchema>;
export function arnakProjectionIsConsistent(g: ArnakProjection): boolean {
    const ids = g.playerStates.map(p => p.playerId), self = g.playerStates.find(p => p.playerId === g.privateState.playerId);
    return new Set(ids).size === ids.length && ids.includes(g.activePlayerId) && ids.includes(g.startingPlayerId) && !!self && self.handCount === g.privateState.hand.length && g.sites.every(s => s.travel.length === s.occupants.length && s.blocked.length === s.travel.length && s.occupants.every(id => id === null || ids.includes(id))) && new Set(g.privateState.offers.map(o => o.id)).size === g.privateState.offers.length && (g.phase !== 'FINISHED' || g.result.winnerPlayerIds.every(id => ids.includes(id)));
}
