import * as v from 'valibot';
import {TERROR_TRAITS,TERROR_TRAIT_INFO,type TerrorTrait,TERROR_PLANS,TERROR_PLAN_INFO,type TerrorPlan,GameRevisionSchema,terrorInventoryLimit,terrorSkillCost,type TerrorKiller,TERROR_CHARACTERS,TERROR_ITEMS,TERROR_SKILLS,TERROR_ITEM_INFO,TERROR_SKILL_INFO,TERROR_CHARACTER_INFO,TERROR_ROOM_INFO,TERROR_DOORS,TERROR_ROOMS,TERROR_PASSAGES,terrorAdjacent,terrorEdge,type TerrorscapeAction,type TerrorCard,type TerrorItem,type TerrorSkill,type TerrorCharacter,type TerrorRoom,type PlayerId,type TileId,type TurnId,type GameId,type ServerTime} from '@hangul-rummikub/shared';
import type {RandomSource} from '../../../ports/system.js';
import {StateSchema,type TerrorscapeState} from './state.js';
import {terrorView} from './visibility.js';
export type {TerrorscapeState} from './state.js';
const SEARCH:Partial<Record<TerrorItem,number>>={KEY:5,TOOLBOX:2,WHISKEY:1,HATCHET:1,HERBS:1,POWDER:1};
const DISCOVER:Partial<Record<TerrorItem,number>>={AMMO:3,HERBS:3,ADRENALINE:3,HATCHET:3,TRANQUILIZER:3,WHISKEY:3,TOOLBOX:2,REVOLVER:2,KEY:2,FIRECRACKER:1,AMULET:1,SHORTSWORD:1,SECRET_MAP:1,POWDER:1,FLASHLIGHT:1,LONGSWORD:1,TRAP_PARTS:1};
const KILLER:Partial<Record<TerrorSkill,number>>={PURSUE:3,BARRICADE:3,SENSE:2,CHAINSAW:2,MADNESS:1,STAY:1,RAGE:1};
const KILLER_DECKS:Record<TerrorKiller,Partial<Record<TerrorSkill,number>>>={BUTCHER:KILLER,SPECTRE:{PURSUE:2,SENSE:3,SCREAM:2,WHIZZ:2,TRAIL:1,VANISH:2,DRAIN:1},MURDERER:{PURSUE:4,SENSE:1,DEDUCTION:2,NOTICE:1,STALK:3,LURK:1,BLOSSOM:1}};
const LOCKED:Record<TerrorKiller,TerrorSkill>={BUTCHER:'RAGE',SPECTRE:'DRAIN',MURDERER:'BLOSSOM'};
export function makeTerrorscapeCards(id:()=>TileId){const make=(counts:Partial<Record<TerrorItem,number>>)=>TERROR_ITEMS.flatMap(key=>Array.from({length:counts[key]??0},()=>({cardId:id(),key})));const skills=(killer:TerrorKiller)=>TERROR_SKILLS.flatMap(key=>Array.from({length:KILLER_DECKS[killer][key]??0},()=>({cardId:id(),key})));return {search:make(SEARCH),discover:make(DISCOVER),medkit:{cardId:id(),key:'MEDKIT' as const},camera:{cardId:id(),key:'CAMERA' as const},killer:skills('BUTCHER'),reserveSkills:[...skills('SPECTRE'),...skills('MURDERER')]};}
function shuffle<T>(values:readonly T[],r:RandomSource):T[]{const a=[...values];for(let i=a.length-1;i>0;i--){const j=r.nextInt(i+1);[a[i],a[j]]=[a[j]!,a[i]!];}return a;}
export function parseTerrorscapeState(input:unknown):TerrorscapeState {
 const s=v.parse(StateSchema,input),ids=new Set(s.players.map(p=>p.playerId));
 if(ids.size!==s.players.length||!ids.has(s.killerPlayerId)||new Set(s.survivors.map(p=>p.character)).size!==3||s.survivors.some(p=>!ids.has(p.playerId)||p.playerId===s.killerPlayerId)||s.players.some(p=>p.playerId!==s.killerPlayerId&&!s.survivors.some(c=>c.playerId===p.playerId)))throw new Error('Invalid Terrorscape roles');
 const items=[...s.reserveItems,...s.searchDeck,...s.discoverDeck,...s.keys,...s.discard,...s.survivors.flatMap(p=>p.hand),...(s.loot?.cards??[])];
 const skills=[...s.reserveSkills,...s.hand,...s.killerDeck,...s.killerDiscard,...(s.locked?[s.locked]:[])];
 if(items.length!==45||skills.length!==39||new Set([...items,...skills].map(c=>c.cardId)).size!==84||TERROR_ITEMS.some(k=>items.filter(c=>c.key===k).length!==(SEARCH[k]??0)+(DISCOVER[k]??0)+(['MEDKIT','CAMERA'].includes(k)?1:0))||TERROR_SKILLS.some(k=>skills.filter(c=>c.key===k).length!==Object.values(KILLER_DECKS).reduce((n,d)=>n+(d[k]??0),0)))throw new Error('Terrorscape card conservation failed');
 const active=[...s.hand,...s.killerDeck,...s.killerDiscard,...(s.locked?[s.locked]:[])];if(active.length!==13||TERROR_SKILLS.some(k=>active.filter(c=>c.key===k).length!==(KILLER_DECKS[s.killerType][k]??0))||s.survivors.some(p=>p.hand.length>terrorInventoryLimit(p.character)+5))throw new Error('Invalid active deck or inventory');
 if(s.keys.some(c=>c.key!=='KEY')||s.survivors.some(p=>p.hand.some(c=>c.key==='KEY'))||s.blocks.some(e=>!TERROR_DOORS.some(([a,b])=>terrorEdge(a,b)===e))||new Set(s.blocks).size!==s.blocks.length||new Set(s.noises).size!==s.noises.length)throw new Error('Invalid Terrorscape board');
 if((s.phase==='LOOT')!==Boolean(s.loot)&&s.phase!=='FINISHED'||s.phase==='UNLOCK'&&(!s.pendingDraw||s.hand.length!==6)||!['UNLOCK','FINISHED'].includes(s.phase)&&s.hand.length>5)throw new Error('Invalid pending Terrorscape state');
 if((s.phase==='FINISHED')!==(s.result!==null&&s.finishedAt!==null))throw new Error('Invalid Terrorscape result');
 if(s.encounter&&(new Set(s.encounter.targets).size!==s.encounter.targets.length||s.encounter.attacked.some(c=>!s.encounter!.targets.includes(c))||s.encounter.fleePending.some(c=>!s.encounter!.targets.includes(c))))throw new Error('Invalid encounter participants');
 if(['DEFENDER','DEFEND','FLEE'].includes(s.phase)&&!s.encounter)throw new Error('Missing encounter');
 return s;
}
export function createTerrorscapeGame(input:{gameId:GameId;playerIds:readonly PlayerId[];cards:ReturnType<typeof makeTerrorscapeCards>;now:ServerTime;turnId:TurnId;random:RandomSource}):TerrorscapeState {
 const {cards,random}=input;const guaranteed=cards.search.find(c=>c.key==='KEY')!;
 const deck=shuffle(cards.killer.filter(c=>c.key!=='RAGE'),random);
 return parseTerrorscapeState({rulesVersion:'terrorscape-base-v2',gameId:input.gameId,revision:0,transitionId:input.turnId,survivorRevision:0,killerRevision:0,survivorTurnId:input.turnId,killerTurnId:input.turnId,startedAt:input.now,finishedAt:null,phase:'SETUP',players:input.playerIds.map(playerId=>({playerId})),killerPlayerId:input.playerIds[0],survivors:TERROR_CHARACTERS.slice(0,3).map((character,i)=>({character,outcome:'ACTIVE',playerId:input.playerIds[1+i%(input.playerIds.length-1)],location:'R1',fear:0,injuries:0,hand:character==='MARCO'?[cards.medkit]:[],acted:false,ready:false})),difficulty:'NONE',survivorTraits:TERROR_CHARACTERS.slice(0,3).map(character=>({character,offered:[],chosen:null})),killerTraits:[],killerTraitOffer:[],killerTraitsChosen:true,usedTraits:[],turnTraits:[],senseUsed:[],senseTargets:[],senseReturn:'FAST',levelTraitQueue:[],traitPower:0,drawNeedsShuffle:false,lootNoiseAdded:false,groupMove:null,separateWays:false,firstDiscover:null,keyOwners:[],rewardResume:null,plansEnabled:false,plan:{cards:[],active:null,progress:0,complete:false,used:false,location:null,chooser:null},discoveryDone:false,afterLoot:'SURVIVORS',encounteredLastTurn:false,encounteredThisTurn:false,round:0,killerType:'BUTCHER',killerLocation:'G5',stealth:null,attackBonus:0,reappearing:false,fearQueue:[],reactionReturn:null,levelBlocksRemaining:0,reserveItems:[cards.camera],reserveSkills:cards.reserveSkills,level:1,bonus:0,blocks:[],noises:[],pendingNoises:[],firecracker:false,pendingFirecracker:false,keys:[],repair:0,repaired:false,rescue:null,trap:null,searchDeck:[guaranteed,...shuffle(cards.search.filter(c=>c.cardId!==guaranteed.cardId),random)],discoverDeck:shuffle(cards.discover,random),discard:[],loot:null,hand:deck.splice(-2),killerDeck:deck,killerDiscard:[],locked:cards.killer.find(c=>c.key==='RAGE'),actionsLeft:2,slowUsed:false,sensed:[],encounter:null,dice:[],defenseTotal:null,defenseBonus:0,pendingDraw:null,logs:{survivor:[],killer:[],survivorSeq:0,killerSeq:0},pings:[],result:null});
}
class RuleError extends Error {}
function requireRule(test:unknown):asserts test {if(!test)throw new RuleError('INVALID_ACTION');}
function survivor(s:TerrorscapeState,c:TerrorCharacter){const p=s.survivors.find(p=>p.character===c);requireRule(p);return p;}
function log(s:TerrorscapeState,text:string,sound:TerrorscapeState['logs']['survivor'][number]['sound']='NONE',side:'BOTH'|'SURVIVOR'|'KILLER'='BOTH'){if(side!=='KILLER'){s.logs.survivor.push({id:++s.logs.survivorSeq,text,sound});s.logs.survivor=s.logs.survivor.slice(-80);}if(side!=='SURVIVOR'){s.logs.killer.push({id:++s.logs.killerSeq,text,sound});s.logs.killer=s.logs.killer.slice(-80);}}
function noise(s:TerrorscapeState,at:TerrorRoom,immediate=false){const a=immediate?s.noises:s.pendingNoises;if(!a.includes(at))a.push(at);if(immediate)log(s,`${TERROR_ROOM_INFO[at].name}에서 소음이 들립니다.`,'NOISE');}
function fear(s:TerrorscapeState,c:TerrorCharacter){const p=survivor(s,c);if(p.outcome!=='ACTIVE')return;if(p.fear===2){noise(s,p.location,true);if(s.killerType==='SPECTRE'&&s.level>=3)s.fearQueue.push(c);}else p.fear++;}
function finish(s:TerrorscapeState,reason:NonNullable<TerrorscapeState['result']>['reason'],now:ServerTime){s.phase='FINISHED';s.finishedAt=now;const team=reason==='ESCAPED'||reason==='RESCUED'||reason==='STRIKE_BACK';s.result={reason,winnerPlayerIds:reason==='CANCELLED'?[]:s.players.filter(p=>(p.playerId!==s.killerPlayerId)===team).map(p=>p.playerId)};if(s.separateWays&&reason!=='CANCELLED'){if(team)for(const p of living(s))p.outcome='ESCAPED';s.result.winnerPlayerIds=[...new Set(s.survivors.filter(p=>p.outcome==='ESCAPED').map(p=>p.playerId))];if(reason==='EXHAUSTED'||s.survivors.filter(p=>p.outcome==='DEAD').length>=2)s.result.winnerPlayerIds.push(s.killerPlayerId);}log(s,reason==='CANCELLED'?'참가자가 나가 게임이 종료되었습니다.':team?'생존자들이 저택을 벗어났습니다.':'저택의 사냥이 끝났습니다.','WIN');}
function hurt(s:TerrorscapeState,c:TerrorCharacter,now:ServerTime,direct=false){const p=survivor(s,c);if(p.outcome!=='ACTIVE')return;const amulet=direct?p.hand.find(card=>card.key==='AMULET'):null;if(amulet){consume(s,p,amulet);log(s,`${TERROR_CHARACTER_INFO[c].name} · 부적이 피해를 막았습니다.`,'CARD');return;}p.injuries++;log(s,`${TERROR_CHARACTER_INFO[c].name}이 부상을 입었습니다.`,'HURT');if(p.injuries>=2){if(!s.separateWays)finish(s,'KILLED',now);else{p.outcome='DEAD';gainLevel(s);if(!living(s).length)finish(s,'SEPARATE_WAYS',now);}}if(!s.result&&hasTrait(s,null,'TERRORISING'))for(const target of living(s))fear(s,target.character);}
function living(s:TerrorscapeState){return s.survivors.filter(p=>p.outcome==='ACTIVE');}
function addKey(s:TerrorscapeState,card:TerrorCard,character:TerrorCharacter){s.keys.push(card);if(s.separateWays)s.keyOwners.push({cardId:card.cardId,character});log(s,`열쇠 확보 · ${s.keys.length}개`,'CARD');}
function startSurvivors(s:TerrorscapeState,now:ServerTime){s.phase='SURVIVORS';s.discoveryDone=false;s.afterLoot='SURVIVORS';s.encounteredLastTurn=s.encounteredThisTurn;s.round++;s.noises=[];s.pendingNoises=[];s.firecracker=false;s.pendingFirecracker=false;s.repaired=false;s.encounter=null;s.sensed=[];s.bonus=0;s.attackBonus=0;s.reappearing=false;s.pings=[];for(const p of s.survivors){p.acted=p.outcome!=='ACTIVE';p.ready=p.outcome!=='ACTIVE';}if(s.separateWays){for(const p of living(s))if(s.keyOwners.filter(k=>k.character===p.character).length>=3&&(p.location==='R1'||p.location==='G5'&&p.hand.some(c=>c.key==='SECRET_MAP'))){p.outcome='ESCAPED';p.acted=true;p.ready=true;log(s,`${TERROR_CHARACTER_INFO[p.character].name} 개별 탈출!`,'WIN');}if(!living(s).length){finish(s,'SEPARATE_WAYS',now);return;}if(!living(s).some(p=>p.character===s.firstDiscover))s.firstDiscover=living(s)[0]!.character;}if(s.rescue!==null){s.rescue--;if(s.rescue<=0){finish(s,'RESCUED',now);return;}}if(!s.separateWays&&s.keys.length>=5&&(living(s).every(p=>p.location==='R1')||living(s).every(p=>p.location==='G5')&&s.survivors.some(p=>p.hand.some(c=>c.key==='SECRET_MAP')))){finish(s,'ESCAPED',now);return;}if(planActive(s,'ROCKET')&&!s.stealth&&!s.encounteredLastTurn&&living(s).every(p=>p.location===living(s)[0]!.location)&&terrorAdjacent(living(s)[0]!.location,s.killerLocation)){finish(s,'STRIKE_BACK',now);return;}if(planActive(s,'PORTAL')&&living(s).every(p=>p.location==='G2')&&['SECRET_MAP','FLASHLIGHT','AMULET'].every(k=>living(s).some(p=>p.hand.some(c=>c.key===k)))){finish(s,'ESCAPED',now);return;}log(s,`${s.round}라운드 · 생존자의 차례입니다.`,'TURN');}
function startKiller(s:TerrorscapeState,now:ServerTime){s.phase=s.killerTraits.length?'KILLER_START':'FAST';s.turnTraits=[];s.encounteredThisTurn=false;if(hasTrait(s,null,'LIE_WAIT')&&s.round===1){log(s,'Lie in Wait · 첫 살인마 차례를 건너뜁니다.','TURN');startSurvivors(s,now);return;}s.actionsLeft=2;s.slowUsed=false;s.noises=[...new Set([...s.noises,...s.pendingNoises])];s.firecracker=s.pendingFirecracker;if(s.firecracker)s.noises=[...TERROR_ROOMS];s.pendingNoises=[];log(s,'살인마의 차례입니다. 드러난 소음에 귀를 기울이세요.','TURN');
 if(s.stealth){const effect=s.stealth.effect;s.stealth=null;s.reappearing=true;log(s,`살인마가 ${TERROR_ROOM_INFO[s.killerLocation].name}에 재등장했습니다.`,'FEAR');if(effect==='LURK'){s.phase='REAPPEAR';return;}if(effect==='VANISH')for(const p of living(s))if(inRange(s.killerLocation,p.location))fear(s,p.character);if(effect==='BLOSSOM')for(const p of living(s))if(inRange(s.killerLocation,p.location)){p.injuries=1;hurt(s,p.character,now);if(s.result)return;}s.phase='REAPPEAR_SEARCH';}
}
function move(s:TerrorscapeState,start:TerrorRoom,path:readonly TerrorRoom[],max:number,killer:boolean):{at:TerrorRoom;removed:boolean}{requireRule(path.length>0&&path.length<=max);let at=start,removed=false;for(const to of path){requireRule(terrorAdjacent(at,to));const edge=terrorEdge(at,to);if(s.blocks.includes(edge)){requireRule(killer);s.blocks=s.blocks.filter(e=>e!==edge);removed=true;}at=to;}return {at,removed};}
function killerMove(s:TerrorscapeState,path:readonly TerrorRoom[],max:number){const m=move(s,s.killerLocation,path,max,true);s.killerLocation=m.at;log(s,`살인마 이동: ${path.map(at=>TERROR_ROOM_INFO[at].name).join(' → ')}`,'STEP');return m.removed;}
const inRange=(a:TerrorRoom,b:TerrorRoom)=>a===b||terrorAdjacent(a,b);
export function terrorStrength(s:TerrorscapeState){return Math.min(10,(s.killerType==='BUTCHER'?(s.level>=2?6:5):s.killerType==='SPECTRE'?2:s.level>=4?6:4)+s.bonus+s.attackBonus+(hasTrait(s,null,'FATAL')?1:0)-(hasTrait(s,null,'SELF_CHALLENGE')?1:0)-(hasTrait(s,null,'SUPPRESSED')?1:0)+s.traitPower);}
function stealth(s:TerrorscapeState,path:readonly TerrorRoom[],effect:NonNullable<TerrorscapeState['stealth']>['effect']){requireRule(path.length<=2);const origin=s.killerLocation;let at=origin;for(const to of path){requireRule(terrorAdjacent(at,to));at=to;}s.killerLocation=at;s.stealth={origin,effect};log(s,'살인마가 은신했습니다. 다음 등장까지 실제 위치는 보이지 않습니다.','CARD');}
function pay(s:TerrorscapeState,ids:readonly TileId[],count:number){requireRule(ids.length===count&&new Set(ids).size===ids.length&&ids.every(id=>s.hand.some(c=>c.cardId===id)));s.killerDiscard.push(...s.hand.filter(c=>ids.includes(c.cardId)));s.hand=s.hand.filter(c=>!ids.includes(c.cardId));}
function assignCast(s:TerrorscapeState,killer:TerrorKiller,characters:readonly TerrorCharacter[],r:RandomSource){requireRule(new Set(characters).size===3);const pool=[...s.hand,...s.killerDeck,...s.killerDiscard,...s.reserveSkills,...(s.locked?[s.locked]:[])];const selected:TerrorscapeState['hand']=[];for(const key of TERROR_SKILLS){for(let i=0;i<(KILLER_DECKS[killer][key]??0);i++){const at=pool.findIndex(c=>c.key===key);requireRule(at>=0);selected.push(pool.splice(at,1)[0]!);}}s.killerType=killer;s.locked=selected.find(c=>c.key===LOCKED[killer])!;s.killerDeck=shuffle(selected.filter(c=>c!==s.locked),r);s.hand=s.killerDeck.splice(-2);s.killerDiscard=[];s.reserveSkills=pool;const items=[...s.reserveItems,...s.survivors.flatMap(p=>p.hand)];s.survivors=s.survivors.map((p,i)=>{const character=characters[i]!;const key=character==='MARCO'?'MEDKIT':character==='SOPHIA'?'CAMERA':null;return {...p,character,hand:key?items.filter(c=>c.key===key):[]};});s.survivorTraits=characters.map(character=>({character,offered:[],chosen:null}));s.reserveItems=items.filter(c=>!s.survivors.some(p=>p.hand.includes(c)));}

function planActive(s:TerrorscapeState,plan:TerrorPlan){return s.plan.complete&&s.plan.active===plan;}
function planEligible(s:TerrorscapeState,plan:TerrorPlan){const step=TERROR_PLAN_INFO[plan].steps[s.plan.active===plan?s.plan.progress:0];const room=step==='BOOK'?'R5':step==='TOOLS'?'G3':step==='OCCULT'?'G2':step==='RADIO'?'B1':step==='EXIT'?'G5':step==='KILLER'&&!s.stealth?s.killerLocation:null;if(room)return living(s).some(p=>p.location===room);if(step==='TOGETHER')return new Set(living(s).map(p=>p.location)).size===1;if(step==='APART')return new Set(living(s).map(p=>p.location)).size===living(s).length;return false;}
function completeDiscovery(s:TerrorscapeState,now:ServerTime){if(s.separateWays){const index=s.survivors.findIndex(p=>p.character===s.firstDiscover);s.firstDiscover=Array.from({length:3},(_,i)=>s.survivors[(index+i+1)%3]!).find(p=>p.outcome==='ACTIVE')?.character??null;}s.afterLoot='SURVIVORS';if(s.plansEnabled&&!s.plan.complete)s.phase='PLAN';else startKiller(s,now);}
function afterLoot(s:TerrorscapeState,now:ServerTime){if(living(s).some(p=>p.hand.length>terrorInventoryLimit(p.character)))return;const next=s.afterLoot;s.afterLoot='SURVIVORS';if(next==='DISCOVERY')completeDiscovery(s,now);else if(next==='KILLER')startKiller(s,now);}
function reward(s:TerrorscapeState,p:TerrorscapeState['survivors'][number],count:number,next:TerrorscapeState['afterLoot']){const cards=s.searchDeck.splice(Math.max(0,s.searchDeck.length-count));if(cards.some(c=>TERROR_ITEM_INFO[c.key].noisy))survivorNoise(s,p,p.location);s.loot={character:p.character,source:'REWARD',cards};s.afterLoot=next;s.phase='LOOT';}
function hasTrait(s:TerrorscapeState,c:TerrorCharacter|null,t:TerrorTrait){return (c===null?s.killerTraits.includes(t):s.survivorTraits.some(p=>p.character===c&&p.chosen===t))&&!s.usedTraits.includes(t);}
function survivorNoise(s:TerrorscapeState,p:TerrorscapeState['survivors'][number],at:TerrorRoom,force=false,immediate=false){if(!force&&!s.stealth&&p.location===s.killerLocation&&hasTrait(s,p.character,'VIGILANT'))return;noise(s,at,immediate);}
function sense(s:TerrorscapeState,rooms:readonly TerrorRoom[],zone:'R'|'B'|'G'|null){const found=living(s).filter(p=>p.character!=='ANNA'&&rooms.includes(p.location));s.sensed=found.map(p=>zone?{kind:'ZONE' as const,character:p.character,zone}:{kind:'PAIR' as const,character:p.character,rooms:[...rooms]});s.senseTargets=found.map(p=>p.character);s.senseUsed=[];if(found.length&&['MURDEROUS','HEIGHTENED','IMMEDIATE'].some(t=>s.killerTraits.some(k=>k===t))){s.senseReturn=s.phase==='SENSE_REACTION'?s.senseReturn:s.phase==='KILLER_START'?'KILLER_START':'FAST';s.phase='SENSE_REACTION';}}
function finishDraft(s:TerrorscapeState,r:RandomSource,now:ServerTime){for(const p of s.survivors)if(hasTrait(s,p.character,'MARKSMAN')){const c=s.discoverDeck.find(c=>c.key==='REVOLVER');requireRule(c);s.discoverDeck=s.discoverDeck.filter(x=>x!==c);p.hand.push(c);s.discoverDeck=shuffle(s.discoverDeck,r);}for(const t of ['DEVIOUS','SELF_CHALLENGE'] as const)if(hasTrait(s,null,t)){const c=s.killerDeck.pop();requireRule(c);s.hand.push(c);}if(hasTrait(s,null,'LIE_WAIT'))gainLevel(s);if(hasTrait(s,null,'NIGHTMARE'))for(const p of s.survivors)fear(s,p.character);startSurvivors(s,now);}
function heroicAvailable(s:TerrorscapeState){return s.encounter&&s.encounter.targets.length>1?s.encounter.targets.find(c=>hasTrait(s,c,'HEROIC_SAVE')):undefined;}
function encounterChoice(s:TerrorscapeState){s.phase=hasTrait(s,null,'TOYING')?'TOYING':heroicAvailable(s)?'HEROIC':'ENCOUNTER_FEAR';}
function consume(s:TerrorscapeState,p:TerrorscapeState['survivors'][number],card:TerrorCard){p.hand=p.hand.filter(c=>c.cardId!==card.cardId);s.discard.push(card);}
function repair(s:TerrorscapeState,p:TerrorscapeState['survivors'][number],amount:number){requireRule(p.location==='B1'&&(s.stealth!==null||p.location!==s.killerLocation)&&!s.repaired&&s.rescue===null);const before=s.repair;s.repair=Math.min(5,s.repair+amount+(planActive(s,'BLUEPRINT')?1:0));s.repaired=true;if(!(amount>1&&planActive(s,'CAREFUL_REPAIR')))survivorNoise(s,p,p.location);if(s.repair===5)s.rescue=5;log(s,`무전기 수리 ${s.repair}/5${s.rescue!==null?' · 구조 요청 완료':''}`,'CARD','SURVIVOR');if(s.separateWays)reward(s,p,s.repair-before,'SURVIVORS');}
function openLoot(s:TerrorscapeState,p:TerrorscapeState['survivors'][number],source:'SEARCH'|'DISCOVER'){const deck=source==='SEARCH'?s.searchDeck:s.discoverDeck;requireRule(deck.length>0);const cards=deck.splice(Math.max(0,deck.length-(source==='SEARCH'?1:2)));const prior=s.pendingNoises.includes(p.location);if(!(source==='SEARCH'&&p.character==='ANNA')&&cards.some(c=>TERROR_ITEM_INFO[c.key].noisy))survivorNoise(s,p,p.location);s.lootNoiseAdded=!prior&&s.pendingNoises.includes(p.location);s.afterLoot=source==='DISCOVER'?'DISCOVERY':'SURVIVORS';s.loot={character:p.character,source,cards};s.phase='LOOT';}
function flee(s:TerrorscapeState){if(!s.encounter)throw new Error('Missing encounter');s.phase='FLEE';s.encounter.defender=null;s.encounter.fleePending=s.encounter.targets.filter(c=>survivor(s,c).outcome==='ACTIVE');}
function gainLevel(s:TerrorscapeState){const old=s.level;s.level=Math.min(5,s.level+1);if(s.level===old)return;if(hasTrait(s,null,'SUPPRESSED'))s.traitPower++;if(hasTrait(s,null,'SLY')&&[2,4].includes(s.level))s.levelTraitQueue.push('SLY');if(hasTrait(s,null,'DETERRENCE')&&s.level>=3)s.levelTraitQueue.push('DETERRENCE');if(s.killerType==='MURDERER'&&s.level===4)s.levelBlocksRemaining=4;if(s.level>=(s.killerType==='SPECTRE'?4:3)&&s.locked){s.hand.push(s.locked);s.locked=null;}log(s,`살인마가 레벨 ${s.level}로 각성했습니다.`,'FEAR');if(s.level===3&&hasTrait(s,null,'SELF_CHALLENGE'))gainLevel(s);}
function draw(s:TerrorscapeState,random:RandomSource,now:ServerTime){const pending=s.pendingDraw;requireRule(pending);while(pending.remaining>0||s.drawNeedsShuffle){
 if(s.drawNeedsShuffle){if(s.hand.length>5){s.phase='UNLOCK';return;}if(s.levelBlocksRemaining){s.phase='LEVEL_BLOCK';return;}if(s.levelTraitQueue.length){s.phase='LEVEL_TRAIT';return;}s.killerDeck=shuffle(s.killerDiscard,random);s.killerDiscard=[];s.drawNeedsShuffle=false;if(!s.killerDeck.length){pending.remaining=0;break;}}
 if(!pending.remaining)break;
 if(!s.killerDeck.length){gainLevel(s);s.drawNeedsShuffle=true;continue;}
 const card=s.killerDeck.pop()!;pending.remaining--;if(pending.mode==='DRAW'&&(s.hand.length<5||hasTrait(s,null,'DEVIOUS'))){s.hand.push(card);if(s.hand.length>5){s.phase='UNLOCK';return;}}else s.killerDiscard.push(card);
 }
 s.pendingDraw=null;if(pending.then==='SURVIVORS')startSurvivors(s,now);else if(pending.then==='FLEE')flee(s);else if(pending.then==='TAUNT_DRAW')beginDraw(s,1,'DRAW','RESUME',random,now);else if(pending.then==='RESUME'){requireRule(s.rewardResume);s.phase=s.rewardResume;s.rewardResume=null;}else rollDefense(s,random,now);
}
function beginDraw(s:TerrorscapeState,remaining:number,mode:'DRAW'|'DISCARD',then:'SURVIVORS'|'FLEE'|'ROLL'|'RESUME'|'TAUNT_DRAW',r:RandomSource,now:ServerTime){s.pendingDraw={remaining,mode,then};draw(s,r,now);}
function encounter(s:TerrorscapeState,_now:ServerTime):boolean{const targets=living(s).filter(p=>p.location===s.killerLocation).map(p=>p.character);if(!targets.length&&planActive(s,'EXPLOSIVE')&&s.plan.location===s.killerLocation){finish(s,'STRIKE_BACK',_now);return true;}if(!targets.length){log(s,'수색했지만 아무도 발견하지 못했습니다.','CARD');return false;}s.encounteredThisTurn=true;s.encounter={location:s.killerLocation,targets,attacked:[],defender:null,fleePending:[]};s.dice=[];s.defenseTotal=null;log(s,`${TERROR_ROOM_INFO[s.killerLocation].name}에서 ${targets.map(c=>TERROR_CHARACTER_INFO[c].name).join(', ')} 발견!`,'FEAR');if(s.reappearing&&s.killerType==='MURDERER'&&s.level>=2)s.bonus+=3;s.reappearing=false;encounterChoice(s);return true;}
function rollDefense(s:TerrorscapeState,r:RandomSource,now:ServerTime){const e=s.encounter;requireRule(e?.defender);const p=survivor(s,e.defender);s.dice=Array.from({length:4-p.fear},()=>[0,1,1,1,1,3][r.nextInt(6)]!);if(s.trap===p.location){s.defenseBonus+=2;s.trap=null;log(s,'덫 발동 · 방어 +2','BLOCK');}s.defenseTotal=s.dice.reduce((n,v)=>n+v,0)+s.defenseBonus;const success=s.defenseTotal>=terrorStrength(s)||hasTrait(s,p.character,'LUCK')&&s.dice.every(d=>d===0);log(s,`${TERROR_CHARACTER_INFO[p.character].name} 방어 ${s.defenseTotal} · ${success?'성공':'실패'}`,'DEFENSE');e.attacked.push(p.character);if(success&&((planActive(s,'AMBUSH')&&p.location===s.plan.location&&s.defenseTotal>=terrorStrength(s)+3)||(planActive(s,'SEAL')&&p.location==='G2'))){finish(s,'STRIKE_BACK',now);return;}if(success){beginDraw(s,2,'DISCARD','FLEE',r,now);return;}hurt(s,p.character,now);if(s.phase==='FINISHED')return;e.defender=null;if(e.targets.some(c=>!e.attacked.includes(c)&&survivor(s,c).outcome==='ACTIVE')){s.attackBonus=0;s.phase=s.killerType==='MURDERER'?'ATTACK':'DEFENDER';}else flee(s);}
function block(s:TerrorscapeState,edges:readonly string[],replaces:readonly string[]){requireRule(new Set(replaces).size===replaces.length&&replaces.every(e=>s.blocks.includes(e)&&!edges.includes(e)));const fresh=edges.filter(e=>!s.blocks.includes(e));requireRule(replaces.length===Math.max(0,s.blocks.length+fresh.length-7));s.blocks=s.blocks.filter(e=>!replaces.includes(e));s.blocks.push(...fresh);log(s,'살인마가 문을 봉쇄했습니다.','BLOCK');}
const localDoors=(at:TerrorRoom)=>TERROR_DOORS.filter(([a,b])=>a===at||b===at).map(([a,b])=>terrorEdge(a,b));
function basicDone(p:TerrorscapeState['survivors'][number]){requireRule(!p.acted);p.acted=true;p.ready=false;}
function revisions(old:TerrorscapeState,s:TerrorscapeState,id:TurnId){s.revision=v.parse(GameRevisionSchema,old.revision+1);s.transitionId=id;for(const side of ['SURVIVOR','KILLER'] as const){const actor=side==='KILLER'?old.killerPlayerId:old.survivors[0]!.playerId;const changed=JSON.stringify(terrorView(old,actor))!==JSON.stringify(terrorView(s,actor));if(changed){if(side==='KILLER'){s.killerRevision=v.parse(GameRevisionSchema,old.killerRevision+1);s.killerTurnId=id;}else{s.survivorRevision=v.parse(GameRevisionSchema,old.survivorRevision+1);s.survivorTurnId=id;}}}}
export function cancelTerrorscape(state:TerrorscapeState,now:ServerTime){const s=parseTerrorscapeState(state);if(s.phase==='FINISHED')return s;finish(s,'CANCELLED',now);revisions(state,s,s.transitionId);return parseTerrorscapeState(s);}
export function applyTerrorscapeAction(state:TerrorscapeState,actor:PlayerId,a:TerrorscapeAction,now:ServerTime,turnId:TurnId,random:RandomSource,hostPlayerId:PlayerId|null=state.players[0]!.playerId):{ok:true;state:TerrorscapeState}|{ok:false;reason:'INVALID_ACTION'} {
 try {const s=parseTerrorscapeState(state);requireRule(s.phase!=='FINISHED'&&s.players.some(p=>p.playerId===actor));const killer=actor===s.killerPlayerId;
 const own=(c:TerrorCharacter)=>{const p=survivor(s,c);requireRule(!killer&&p.playerId===actor&&p.outcome==='ACTIVE');return p;};
 const teamAction=()=>requireRule(s.phase==='SURVIVORS'&&!killer&&!living(s).some(p=>p.hand.length>terrorInventoryLimit(p.character)));
 switch(a.type){
 case 'SET_ROLES':requireRule(s.phase==='SETUP'&&actor===hostPlayerId&&s.players.some(p=>p.playerId===a.killerPlayerId)&&a.owners.every(id=>id!==a.killerPlayerId&&s.players.some(p=>p.playerId===id))&&s.players.every(p=>p.playerId===a.killerPlayerId||a.owners.includes(p.playerId)));s.killerPlayerId=a.killerPlayerId;s.survivors.forEach((p,i)=>{p.playerId=a.owners[i]!;});break;
 case 'SET_CAST':requireRule(s.phase==='SETUP'&&actor===hostPlayerId);assignCast(s,a.killer,a.characters,random);break;
 case 'PASSAGE':{teamAction();const p=own(a.character);requireRule(p.character==='SOPHIA');const to=TERROR_PASSAGES[p.location];requireRule(to);if(!p.hand.some(c=>c.key==='FLASHLIGHT'))basicDone(p);p.ready=false;p.location=to;log(s,'소피아가 비밀 통로를 이용했습니다.','STEP','SURVIVOR');break;}
 case 'ATTACK_CARD':{requireRule(killer&&s.phase==='ATTACK'&&s.encounter);if(a.cardId){const c=s.hand.find(c=>c.cardId===a.cardId);requireRule(c?.key==='STALK');pay(s,[c.cardId],1);s.attackBonus=1;log(s,'학살자가 잠복 카드로 이번 공격을 강화했습니다.','CARD');}s.phase='DEFENDER';break;}
 case 'SPECTRE_SEARCH':requireRule(killer&&s.phase==='WHIZZ');if(a.cost.length){pay(s,a.cost,2);s.phase='SLOW';encounter(s,now);}else s.phase='SLOW';break;
 case 'FEAR_REACTION':{requireRule(killer&&s.phase==='REACTION'&&s.fearQueue.length&&s.reactionReturn);const target=s.fearQueue.shift()!;if(a.cost.length){pay(s,a.cost,3);hurt(s,target,now,true);}if(!s.result&&!s.fearQueue.length){s.phase=s.reactionReturn;s.reactionReturn=null;}break;}
 case 'REAPPEAR_TARGET':requireRule(killer&&s.phase==='REAPPEAR'&&survivor(s,a.target).outcome==='ACTIVE');fear(s,a.target);s.phase='REAPPEAR_SEARCH';break;
 case 'LEVEL_BLOCK':requireRule(killer&&s.phase==='LEVEL_BLOCK'&&s.pendingDraw&&s.levelBlocksRemaining>0&&TERROR_DOORS.some(([x,y])=>terrorEdge(x,y)===a.edge));block(s,[a.edge],a.replaces);s.levelBlocksRemaining--;if(!s.levelBlocksRemaining){if(s.levelTraitQueue.length)s.phase='LEVEL_TRAIT';else draw(s,random,now);}break;
 case 'SET_DIFFICULTY':requireRule(s.phase==='SETUP'&&actor===hostPlayerId);s.difficulty=a.difficulty;break;
 case 'CHOOSE_TRAITS':{requireRule(s.phase==='TRAIT_DRAFT'&&new Set(a.traits).size===a.traits.length);if(a.character===null){requireRule(killer&&!s.killerTraitsChosen&&a.traits.length===s.killerTraitOffer.length/2&&a.traits.every(t=>s.killerTraitOffer.includes(t)));s.killerTraits=a.traits;s.killerTraitsChosen=true;}else{own(a.character);const offer=s.survivorTraits.find(p=>p.character===a.character);requireRule(offer&&offer.chosen===null&&a.traits.length===1&&offer.offered.includes(a.traits[0]!));offer.chosen=a.traits[0]!;}if(s.killerTraitsChosen&&s.survivorTraits.every(p=>p.chosen))finishDraft(s,random,now);break;}
 case 'TRAIT_PASS':if(s.phase==='SENSE_REACTION'){requireRule(killer);s.phase=s.senseReturn;}else if(s.phase==='TOYING'){requireRule(killer);s.phase=heroicAvailable(s)?'HEROIC':'ENCOUNTER_FEAR';}else {requireRule(s.phase==='HEROIC');const c=heroicAvailable(s);requireRule(c);own(c);s.phase='ENCOUNTER_FEAR';}break;
 case 'GROUP_MOVE':{requireRule(s.phase==='GROUP_MOVE'&&s.groupMove&&s.groupMove.targets.includes(a.character));const p=own(a.character);if(a.path.length)p.location=move(s,p.location,a.path,s.groupMove.max,false).at;p.ready=false;s.groupMove.targets=s.groupMove.targets.filter(c=>c!==a.character);if(!s.groupMove.targets.length){s.phase=s.groupMove.then;s.groupMove=null;}log(s,'동료 이동 결정 완료','STEP','SURVIVOR');break;}
 case 'TRAIT_USE':{
 const t=a.trait,info=TERROR_TRAIT_INFO[t];requireRule(hasTrait(s,a.character,t)&&(killer?info.side==='KILLER'&&a.character===null:info.side==='SURVIVOR'&&a.character!==null));
 if(killer){
  if(info.timing==='START')requireRule(s.phase==='KILLER_START'&&!s.turnTraits.includes(t));
  else if(info.timing==='END')requireRule(s.phase==='KILLER_END'&&!s.stealth&&!s.encounteredThisTurn&&!s.turnTraits.includes(t));
  else if(info.timing==='SENSE')requireRule(s.phase==='SENSE_REACTION'&&s.senseTargets.length&&!s.senseUsed.includes(t));
  else if(info.timing==='LEVEL')requireRule(s.phase==='LEVEL_TRAIT'&&s.levelTraitQueue[0]===t);
  else if(info.timing==='ENCOUNTER')requireRule(s.phase==='TOYING');
  else requireRule(t==='ENTRAPMENT'&&['KILLER_START','FAST','MAIN','SLOW','KILLER_END'].includes(s.phase));
  if(t==='ENTRAPMENT'){requireRule(a.edges.length===2&&new Set(a.edges).size===2&&a.edges.every(e=>TERROR_DOORS.some(([x,y])=>terrorEdge(x,y)===e)));block(s,a.edges,a.replaces);}
  else if(t==='SWIFT'){requireRule(!s.stealth);pay(s,a.cost,2);killerMove(s,a.path,1);}
  else if(t==='ACUTE'){requireRule(s.noises.includes(a.room));pay(s,a.cost,1);sense(s,[a.room],null);}
  else if(t==='ENHANCED'){requireRule(!s.stealth);pay(s,a.cost,1);sense(s,TERROR_ROOMS.filter(r=>inRange(r,s.killerLocation)),null);}
  else if(t==='MURDEROUS'){pay(s,a.cost,1);for(const c of s.senseTargets)fear(s,c);s.senseUsed.push(t);}
  else if(t==='HEIGHTENED'){requireRule(!s.turnTraits.includes(t));sense(s,TERROR_ROOMS.filter(r=>r.startsWith(a.zone)),a.zone);s.phase='SENSE_REACTION';}
  else if(t==='IMMEDIATE'){pay(s,a.cost,1);killerMove(s,a.path,1);s.senseUsed.push(t);}
  else if(t==='PERILOUS'){pay(s,a.cost,2);stealth(s,a.path,'NONE');}
  else if(t==='ENCIRCLE'){pay(s,a.cost,2);requireRule(a.edges.length===1&&localDoors(s.killerLocation).includes(a.edges[0]!));block(s,a.edges,a.replaces);}
  else if(t==='AURA'){for(const p of living(s).filter(p=>p.location===s.killerLocation))fear(s,p.character);}
  else if(t==='TOYING'){s.encounter=null;beginDraw(s,6,'DRAW','SURVIVORS',random,now);}
  else if(t==='DETERRENCE'){requireRule(living(s).some(p=>p.character===a.target));s.levelTraitQueue.shift();fear(s,a.target);}
  else if(t==='SLY'){requireRule(a.edges.length===1&&TERROR_DOORS.some(([x,y])=>terrorEdge(x,y)===a.edges[0]));s.levelTraitQueue.shift();block(s,a.edges,a.replaces);}
  else requireRule(false);
  if(!s.turnTraits.includes(t))s.turnTraits.push(t);log(s,`특성 · ${info.name}`,'CARD');
 }else{
  requireRule(a.character);const p=own(a.character);
  if(info.timing==='ACTION')teamAction();
  else if(info.timing==='LOOT')requireRule(s.phase==='LOOT'&&s.loot?.source==='DISCOVER'&&s.loot.character===p.character);
  else if(info.timing==='DEFEND')requireRule(s.phase==='DEFEND'&&s.encounter?.defender===p.character);
  else requireRule(t==='HEROIC_SAVE'&&s.phase==='HEROIC'&&heroicAvailable(s)===p.character);
  if(t==='FIRST_AID'){basicDone(p);const to=survivor(s,a.target);requireRule(to!==p&&to.outcome==='ACTIVE'&&to.location===p.location);to.injuries=0;}
  else if(t==='MORALE'){basicDone(p);for(const to of living(s).filter(x=>x!==p))to.fear=Math.max(0,to.fear-1);}
  else if(t==='DECOY')survivorNoise(s,p,a.room,true);
  else if(t==='TAUNT'){basicDone(p);survivorNoise(s,p,p.location,true);s.rewardResume='SURVIVORS';beginDraw(s,3,'DISCARD','TAUNT_DRAW',random,now);}
  else if(t==='JUDICIOUS'){if(a.choice==='FEAR')p.fear=0;else if(a.choice==='NOISE'){requireRule(terrorAdjacent(p.location,a.room));survivorNoise(s,p,a.room,true);}else{requireRule(a.edges.length===1&&s.blocks.includes(a.edges[0]!));s.blocks=s.blocks.filter(e=>e!==a.edges[0]);}}
  else if(t==='PROMPT')p.location=move(s,p.location,a.path,1,false).at;
  else if(t==='BURST'){basicDone(p);requireRule(a.path.length>=2);survivorNoise(s,p,p.location,true);p.location=move(s,p.location,a.path,4,false).at;}
  else if(t==='COORDINATOR'||t==='HEROIC_SAVE'){if(t==='COORDINATOR')basicDone(p);const targets=living(s).filter(to=>to!==p&&to.location===p.location).map(to=>to.character);requireRule(targets.length>0);s.groupMove={targets,max:t==='COORDINATOR'?2:1,then:t==='COORDINATOR'?'SURVIVORS':'ENCOUNTER_FEAR'};s.phase='GROUP_MOVE';}
  else if(t==='SILENT_RETRIEVAL'){requireRule(s.loot);if(s.lootNoiseAdded)s.pendingNoises=s.pendingNoises.filter(r=>r!==p.location);s.lootNoiseAdded=false;}
  else if(t==='SLEIGHT'){requireRule(s.loot);for(const c of s.loot.cards){if(c.key==='KEY')addKey(s,c,p.character);else p.hand.push(c);}s.loot=null;s.phase='SURVIVORS';afterLoot(s,now);}
  else if(t==='SECRET_WEAPON'){s.defenseBonus=4;if(a.cost.length){requireRule(planActive(s,'MOLOTOV')&&a.cost.length===1);const whiskey=p.hand.find(c=>c.cardId===a.cost[0]&&c.key==='WHISKEY');requireRule(whiskey);consume(s,p,whiskey);s.defenseBonus+=2;}rollDefense(s,random,now);}
  else requireRule(false);
  if(info.timing==='ACTION')p.ready=false;log(s,`특성 · ${info.name}`,'CARD',info.timing==='DEFEND'||info.timing==='ENCOUNTER'?'BOTH':'SURVIVOR');
 }
 if(info.once)s.usedTraits.push(t);
 break;
 }

 case 'SET_SEPARATE':requireRule(s.phase==='SETUP'&&actor===hostPlayerId&&(!a.enabled||s.players.length===4));s.separateWays=a.enabled;break;
 case 'CORPSE_LOOT':{teamAction();const p=own(a.character),body=survivor(s,a.target);requireRule(body.outcome==='DEAD'&&body.location===p.location);const card=body.hand.find(c=>c.cardId===a.cardId),key=s.keyOwners.find(k=>k.cardId===a.cardId&&k.character===body.character);requireRule(card||key);if(card){body.hand=body.hand.filter(c=>c!==card);p.hand.push(card);}else{requireRule(key);key.character=p.character;}p.ready=false;break;}
 case 'SET_PLANS':requireRule(s.phase==='SETUP'&&actor===hostPlayerId);s.plansEnabled=a.enabled;break;
 case 'PLAN_PROGRESS':{requireRule(!killer&&s.phase==='PLAN'&&s.plan.chooser);own(s.plan.chooser);if(a.plan){requireRule(s.plan.cards.includes(a.plan)&&planEligible(s,a.plan));s.plan.progress=s.plan.active===a.plan?s.plan.progress+1:1;s.plan.active=a.plan;if(s.plan.progress===TERROR_PLAN_INFO[a.plan].steps.length){s.plan.complete=true;s.plan.cards=[a.plan];if(a.plan==='AMBUSH')s.plan.location=living(s)[0]!.location;if(a.plan==='SEAL')noise(s,'G2');if(a.plan==='INTEL'){const p=survivor(s,a.target);requireRule(p.outcome==='ACTIVE');reward(s,p,1,'KILLER');break;}}}startKiller(s,now);break;}
 case 'PLAN_USE':{teamAction();const p=own(a.character),plan=s.plan.active;requireRule(plan&&s.plan.complete);const cards=a.cards.map(id=>p.hand.find(c=>c.cardId===id));requireRule(new Set(a.cards).size===a.cards.length&&cards.every(c=>c));const spend=(key:TerrorItem,n:number)=>{requireRule(cards.length===n&&cards.every(c=>c?.key===key));for(const c of cards){requireRule(c);consume(s,p,c);}};const once=()=>{requireRule(!s.plan.used);s.plan.used=true;};
 if(plan==='EXPLOSIVE'||plan==='BUZZER'&&!s.plan.used){basicDone(p);once();spend('TOOLBOX',1);s.plan.location=p.location;}
 else if(plan==='BUZZER'){requireRule(s.plan.location);noise(s,s.plan.location);}
 else if(plan==='SITE_STUDY'){once();p.location=move(s,p.location,a.path,2,false).at;}
 else if(plan==='TUNNELS'){if(p.character!=='SOPHIA'||!p.hand.some(c=>c.key==='FLASHLIGHT'))basicDone(p);requireRule(TERROR_PASSAGES[p.location]&&TERROR_PASSAGES[a.destination]&&p.location!==a.destination);p.location=a.destination;}
 else if(plan==='DIY_RADIO'){basicDone(p);requireRule(s.rescue===null);spend('TOOLBOX',3);s.repair=5;s.rescue=5;noise(s,p.location);}
 else if(plan==='SKELETON_KEY'){basicDone(p);once();requireRule(p.location==='R1'&&s.searchDeck[0]?.key==='KEY');spend('TOOLBOX',1);addKey(s,s.searchDeck.shift()!,p.character);}
 else if(plan==='MYSTIC_HERBS'){once();const to=survivor(s,a.target);requireRule(p.location==='G2'&&to.location==='G2'&&to.outcome==='ACTIVE');to.injuries=0;to.fear=0;}
 else if(plan==='ANCIENT_CHEST'){basicDone(p);once();spend('AMULET',1);reward(s,p,3,'SURVIVORS');}
 else requireRule(false);p.ready=false;log(s,`생존 계획 · ${TERROR_PLAN_INFO[plan].name}`,'CARD','SURVIVOR');break;}
 case 'BEGIN_HUNT':requireRule(s.phase==='SETUP'&&actor===hostPlayerId);if(s.separateWays)s.firstDiscover=s.survivors[random.nextInt(3)]!.character;if(s.plansEnabled)s.plan.cards=shuffle(TERROR_PLANS,random).slice(0,2);if(s.difficulty==='NONE')startSurvivors(s,now);else{const deck=shuffle(TERROR_TRAITS.filter(t=>TERROR_TRAIT_INFO[t].side==='SURVIVOR'),random);s.survivorTraits=s.survivors.map(p=>({character:p.character,offered:deck.splice(-2),chosen:null}));const count={EASY:0,NORMAL:2,HARD:4,NIGHTMARE:6}[s.difficulty];s.killerTraitOffer=shuffle(TERROR_TRAITS.filter(t=>TERROR_TRAIT_INFO[t].side==='KILLER'),random).slice(0,count);s.killerTraitsChosen=count===0;s.phase='TRAIT_DRAFT';}break;
 case 'PING':requireRule(!killer&&s.phase!=='SETUP');s.pings.push({room:a.room,message:a.message,playerId:actor});s.pings=s.pings.slice(-6);break;
 case 'BASIC':{teamAction();const p=own(a.character);basicDone(p);if(a.kind==='MOVE'||a.kind==='SPRINT'){requireRule(a.kind!=='SPRINT'||p.character==='WILLIAM');p.location=move(s,p.location,a.path,a.kind==='SPRINT'?3:hasTrait(s,p.character,'HURRIED')&&!s.stealth&&inRange(p.location,s.killerLocation)?3:2,false).at;if(a.kind==='SPRINT')survivorNoise(s,p,p.location);if(a.kind==='MOVE'&&hasTrait(s,p.character,'INTREPID'))p.fear=Math.max(0,p.fear-1);log(s,`${TERROR_CHARACTER_INFO[p.character].name} → ${TERROR_ROOM_INFO[p.location].name}`,'STEP','SURVIVOR');}else if(a.kind==='CALM'){p.fear=0;log(s,`${TERROR_CHARACTER_INFO[p.character].name}이 공포를 가라앉혔습니다.`,'CARD','SURVIVOR');}else if(a.kind==='REPAIR')repair(s,p,1);else if(a.kind==='SEARCH'){requireRule(TERROR_ROOM_INFO[p.location].search&&(s.stealth!==null||p.location!==s.killerLocation));openLoot(s,p,'SEARCH');}else if(a.kind==='REMOVE_BLOCK'){requireRule(localDoors(p.location).includes(a.edge)&&s.blocks.includes(a.edge));s.blocks=s.blocks.filter(e=>e!==a.edge);survivorNoise(s,p,p.location,false,true);}else {requireRule(p.character==='MARCO');const c=s.discard.find(c=>c.cardId===a.cardId&&(c.key==='ADRENALINE'||c.key==='TRANQUILIZER'));requireRule(c);s.discard=s.discard.filter(i=>i.cardId!==c.cardId);p.hand.push(c);}break;}
 case 'READY':{teamAction();const p=own(a.character);requireRule(p.acted);p.ready=a.ready;break;}
 case 'DISCOVER':{teamAction();requireRule(!s.discoveryDone&&living(s).every(p=>p.acted&&p.ready));const p=own(a.character);requireRule(!s.separateWays||s.firstDiscover===p.character);s.plan.chooser=p.character;s.discoveryDone=true;if(!s.discoverDeck.length){if(s.rescue===null)finish(s,'EXHAUSTED',now);else completeDiscovery(s,now);}else openLoot(s,p,'DISCOVER');break;}
 case 'KEEP':{requireRule(s.phase==='LOOT'&&s.loot);const loot=s.loot,p=own(loot.character);requireRule(a.cardId===null||loot.cards.some(c=>c.cardId===a.cardId));for(const c of loot.cards){if(loot.source==='REWARD'||c.cardId===a.cardId){if(c.key==='KEY'){addKey(s,c,p.character);}else p.hand.push(c);}else s.discard.push(c);}s.loot=null;s.phase='SURVIVORS';afterLoot(s,now);break;}
 case 'DISCARD':{requireRule(s.phase==='SURVIVORS');const p=own(a.character);requireRule(p.hand.length>terrorInventoryLimit(p.character));const c=p.hand.find(c=>c.cardId===a.cardId);requireRule(c);consume(s,p,c);afterLoot(s,now);break;}
 case 'TRADE':{teamAction();const p=own(a.character),to=survivor(s,a.target),c=p.hand.find(c=>c.cardId===a.cardId);requireRule(c&&to!==p&&to.outcome==='ACTIVE'&&p.location===to.location&&to.hand.length<terrorInventoryLimit(to.character)+1);p.hand=p.hand.filter(i=>i.cardId!==c.cardId);to.hand.push(c);p.ready=false;to.ready=false;break;}
 case 'ITEM':{teamAction();const p=own(a.character),c=p.hand.find(c=>c.cardId===a.cardId),to=survivor(s,a.target);requireRule(c);const special=['TOOLBOX','HERBS','MEDKIT','FIRECRACKER','FLASHLIGHT','TRAP_PARTS'].includes(c.key);if(special&&!(c.key==='FLASHLIGHT'&&p.character==='SOPHIA'))basicDone(p);else p.ready=false;let spent=true;
 if(c.key==='TOOLBOX')repair(s,p,p.character==='JOHNSON'?3:2);
 else if(c.key==='CAMERA'){requireRule(p.character==='SOPHIA');survivorNoise(s,p,p.location);}
 else if(c.key==='WHISKEY'){requireRule(terrorAdjacent(p.location,a.destination));survivorNoise(s,p,a.destination);}
 else if(c.key==='HATCHET'){requireRule(localDoors(p.location).includes(a.edge)&&s.blocks.includes(a.edge));s.blocks=s.blocks.filter(e=>e!==a.edge);survivorNoise(s,p,p.location,false,true);}
 else if(c.key==='TRANQUILIZER')p.fear=0;
 else if(c.key==='ADRENALINE')p.location=move(s,p.location,[a.destination],1,false).at;
 else if(c.key==='HERBS'||c.key==='MEDKIT'){requireRule(to.outcome==='ACTIVE'&&to.location===p.location&&(c.key!=='MEDKIT'||p.character==='MARCO'));to.injuries=0;to.ready=false;if(c.key==='MEDKIT')to.fear=0;else if(!hasTrait(s,p.character,'HERBOLOGY'))survivorNoise(s,p,p.location);}
 else if(c.key==='FIRECRACKER')s.pendingFirecracker=true;
 else if(c.key==='FLASHLIGHT'){requireRule(TERROR_PASSAGES[p.location]&&(TERROR_PASSAGES[p.location]===a.destination||planActive(s,'TUNNELS')&&TERROR_PASSAGES[a.destination]&&a.destination!==p.location));p.location=a.destination;spent=false;}
 else if(c.key==='TRAP_PARTS'){requireRule(s.trap===null);s.trap=p.location;}
 else requireRule(false);if(spent)consume(s,p,c);log(s,`${TERROR_CHARACTER_INFO[p.character].name} · ${TERROR_ITEM_INFO[c.key].name} 사용`,'CARD','SURVIVOR');break;}
 case 'KILLER_NEXT':requireRule(killer);if(s.phase==='KILLER_START')s.phase='FAST';else if(s.phase==='KILLER_END'){if(!s.stealth&&!s.encounteredThisTurn&&hasTrait(s,null,'AURA')&&!s.turnTraits.includes('AURA'))for(const p of living(s).filter(p=>p.location===s.killerLocation))fear(s,p.character);s.phase='END_COMPLETE';}else if(s.phase==='FAST')s.phase='MAIN';else if(s.phase==='MAIN'){s.actionsLeft=0;s.phase='SLOW';}else {requireRule(s.phase==='SLOW');if(!s.encounteredThisTurn&&!s.stealth&&['AURA','PERILOUS','ENCIRCLE'].some(t=>s.killerTraits.some(k=>k===t)))s.phase='KILLER_END';else beginDraw(s,3,'DRAW','SURVIVORS',random,now);}break;
 case 'KILLER_BASIC':requireRule(killer&&s.phase==='MAIN'&&s.actionsLeft>0);s.actionsLeft--;if(a.kind==='MOVE')killerMove(s,[a.destination],1);else encounter(s,now);if(s.phase==='MAIN'&&s.actionsLeft===0)s.phase='SLOW';break;
 case 'KILLER_CARD':{requireRule(killer);const c=s.hand.find(c=>c.cardId===a.cardId);requireRule(c);const info=TERROR_SKILL_INFO[c.key],timing=c.key==='CHAINSAW'&&s.level>=4?'FAST':info.timing;requireRule(s.phase===timing&&(timing!=='MAIN'||s.actionsLeft===2)&&(timing!=='SLOW'||!s.slowUsed));requireRule(a.cost.length===terrorSkillCost(c.key,s.hand.length)&&new Set(a.cost).size===a.cost.length&&a.cost.every(id=>id!==c.cardId&&s.hand.some(c=>c.cardId===id)));const spent=[...a.cost.map(id=>{const paid=s.hand.find(i=>i.cardId===id);requireRule(paid);return paid;}),c];s.hand=s.hand.filter(i=>!spent.includes(i));s.killerDiscard.push(...spent);log(s,`살인마 · ${info.name}`,'CARD');if(timing==='MAIN'){s.actionsLeft=0;s.phase='SLOW';}if(timing==='SLOW')s.slowUsed=true;
 if(['VANISH','STALK','LURK','BLOSSOM'].includes(c.key))stealth(s,a.path,c.key==='VANISH'?'VANISH':c.key==='LURK'?'LURK':c.key==='BLOSSOM'?'BLOSSOM':'NONE');
 else if(c.key==='SCREAM'){for(const p of living(s))if(inRange(s.killerLocation,p.location))fear(s,p.character);}
 else if(c.key==='WHIZZ'){const origin=s.killerLocation;killerMove(s,a.path,4);for(const p of living(s))if([origin,...a.path].includes(p.location))fear(s,p.character);if(s.level>=2)s.phase='WHIZZ';}
 else if(c.key==='TRAIL')s.sensed=living(s).filter(p=>p.fear>0).map(({character,location})=>({kind:'LOCATION',character,location}));
 else if(c.key==='DRAIN'){for(const p of living(s).filter(p=>p.fear>0)){hurt(s,p.character,now,true);if(s.result)break;}}
 else if(c.key==='NOTICE'){for(const p of living(s))fear(s,p.character);}
 else if(c.key==='DEDUCTION'){requireRule(a.path.length===2&&terrorAdjacent(a.path[0]!,a.path[1]!));sense(s,a.path,null);}
 else if(c.key==='PURSUE')killerMove(s,a.path,1);
 else if(c.key==='SENSE'){sense(s,TERROR_ROOMS.filter(r=>r.startsWith(a.zone)),a.zone);log(s,`${a.zone} 구역 감지 · ${s.sensed.length}명`,'FEAR');}
 else if(c.key==='BARRICADE'||c.key==='MADNESS'){requireRule(localDoors(s.killerLocation).includes(a.edge));block(s,[a.edge],a.replaces);if(c.key==='MADNESS')s.bonus+=2;}
 else if(c.key==='STAY')block(s,localDoors(s.killerLocation),a.replaces);
 else if(c.key==='CHAINSAW'){for(const p of living(s))if(p.location===s.killerLocation||terrorAdjacent(p.location,s.killerLocation))fear(s,p.character);requireRule(a.path.length<=1);if(a.path.length)killerMove(s,a.path,1);for(const p of living(s).filter(p=>p.location===s.killerLocation)){hurt(s,p.character,now,true);if(s.result)break;}}
 else {const removed=killerMove(s,a.path,2);if(!encounter(s,now)&&removed)s.phase='RAGE';}break;}
 case 'RAGE_MOVE':{requireRule(killer&&s.phase==='RAGE');const removed=killerMove(s,a.path,2);if(!encounter(s,now))s.phase=removed?'RAGE':'SLOW';break;}
 case 'UNLOCK_DISCARD':{requireRule(killer&&s.phase==='UNLOCK'&&s.pendingDraw);const c=s.hand.find(c=>c.cardId===a.cardId);requireRule(c);s.hand=s.hand.filter(i=>i.cardId!==a.cardId);s.killerDiscard.push(c);if(s.levelBlocksRemaining)s.phase='LEVEL_BLOCK';else if(s.levelTraitQueue.length)s.phase='LEVEL_TRAIT';else draw(s,random,now);break;}
 case 'DEFENDER':requireRule(!killer&&s.phase==='DEFENDER'&&s.encounter&&s.encounter.targets.includes(a.character)&&!s.encounter.attacked.includes(a.character));own(a.character);s.encounter.defender=a.character;s.phase='DEFEND';break;
 case 'DEFEND':{requireRule(s.phase==='DEFEND'&&s.encounter?.defender);const p=own(s.encounter.defender),c=a.cardId===null?null:p.hand.find(c=>c.cardId===a.cardId);requireRule(a.cardId===null||c);let bonus=0;if(a.molotov){requireRule(planActive(s,'MOLOTOV'));const whiskey=p.hand.find(c=>c.key==='WHISKEY');requireRule(whiskey);consume(s,p,whiskey);bonus=2;}const molotovBonus=bonus;if(c){requireRule(['HATCHET','POWDER','AMMO','LONGSWORD','SHORTSWORD'].includes(c.key));if(c.key==='AMMO')requireRule(p.hand.some(c=>c.key==='REVOLVER'));bonus=c.key==='AMMO'?4:c.key==='LONGSWORD'?3:c.key==='POWDER'?2:1;if(['HATCHET','POWDER','AMMO'].includes(c.key))consume(s,p,c);log(s,`${TERROR_CHARACTER_INFO[p.character].name} · ${TERROR_ITEM_INFO[c.key].name} 방어`,'CARD');}else bonus=(p.character==='WILLIAM'?1:0)+(hasTrait(s,p.character,'MARTIAL')&&!a.molotov?1:0);if(c?.key==='AMMO'&&hasTrait(s,p.character,'MARKSMAN'))bonus++;s.defenseBonus=bonus+molotovBonus;if(c?.key==='LONGSWORD')beginDraw(s,1,'DRAW','ROLL',random,now);else rollDefense(s,random,now);break;}
 case 'FLEE':{requireRule(s.phase==='FLEE'&&s.encounter&&s.encounter.fleePending.includes(a.character));const p=own(a.character);if(a.destination!==p.location){const path=a.path??[a.destination];requireRule(path.at(-1)===a.destination);p.location=move(s,p.location,path,hasTrait(s,p.character,'SURVIVAL_INSTINCT')?2:1,false).at;}if(hasTrait(s,p.character,'SURVIVAL_INSTINCT'))p.fear=0;s.encounter.fleePending=s.encounter.fleePending.filter(c=>c!==a.character);log(s,`${TERROR_CHARACTER_INFO[p.character].name} 도주 결정 완료`,'STEP','SURVIVOR');if(!s.encounter.fleePending.length)beginDraw(s,3,'DRAW','SURVIVORS',random,now);break;}
 }
 for(let i=0;i<8&&!s.result;i++){
 if(!s.pendingDraw&&(s.hand.length>5||s.levelBlocksRemaining>0||s.levelTraitQueue.length>0)){requireRule(s.phase==='KILLER_START'||s.phase==='KILLER_END'||s.phase==='SENSE_REACTION'||s.phase==='ENCOUNTER_FEAR'||s.phase==='TOYING'||s.phase==='HEROIC'||s.phase==='GROUP_MOVE'||s.phase==='SURVIVORS'||s.phase==='FAST'||s.phase==='SLOW'||s.phase==='WHIZZ'||s.phase==='REAPPEAR_SEARCH'||s.phase==='ENCOUNTER_START'||s.phase==='ATTACK'||s.phase==='DEFENDER'||s.phase==='FLEE'||s.phase==='REACTION');s.rewardResume=s.phase;s.pendingDraw={remaining:0,mode:'DRAW',then:'RESUME'};s.phase=s.hand.length>5?'UNLOCK':s.levelBlocksRemaining?'LEVEL_BLOCK':'LEVEL_TRAIT';break;}
 if(s.phase==='FLEE'&&s.encounter&&!s.encounter.fleePending.length){beginDraw(s,3,'DRAW','SURVIVORS',random,now);continue;}
 if(s.phase==='DEFENDER'&&s.encounter&&!s.encounter.targets.some(c=>!s.encounter!.attacked.includes(c)&&survivor(s,c).outcome==='ACTIVE')){flee(s);continue;}
 if(s.fearQueue.length&&s.phase!=='REACTION'){requireRule(s.phase==='KILLER_START'||s.phase==='KILLER_END'||s.phase==='SENSE_REACTION'||s.phase==='LEVEL_TRAIT'||s.phase==='ENCOUNTER_FEAR'||s.phase==='END_COMPLETE'||s.phase==='FAST'||s.phase==='SLOW'||s.phase==='WHIZZ'||s.phase==='REAPPEAR_SEARCH'||s.phase==='ENCOUNTER_START'||s.phase==='ATTACK'||s.phase==='DEFENDER');s.reactionReturn=s.phase;s.phase='REACTION';break;}
 if(s.phase==='LEVEL_TRAIT'&&!s.levelTraitQueue.length){draw(s,random,now);continue;}
 if(s.phase==='END_COMPLETE'){beginDraw(s,3,'DRAW','SURVIVORS',random,now);continue;}
 if(s.phase==='ENCOUNTER_FEAR'){requireRule(s.encounter);s.encounter.targets=s.encounter.targets.filter(c=>survivor(s,c).outcome==='ACTIVE'&&survivor(s,c).location===s.encounter!.location);if(s.killerType==='SPECTRE')for(const c of s.encounter.targets)fear(s,c);s.phase='ENCOUNTER_START';continue;}
 if(s.phase==='REAPPEAR_SEARCH'){s.phase=s.killerTraits.length?'KILLER_START':'FAST';if(!encounter(s,now))s.reappearing=false;continue;}
 if(s.phase==='ENCOUNTER_START'){requireRule(s.encounter);if(s.level>=5)for(const c of s.encounter.targets){hurt(s,c,now);if(s.result)break;}if(!s.result){s.attackBonus=0;s.phase=s.killerType==='MURDERER'?'ATTACK':'DEFENDER';}continue;}
 break;
 }
 revisions(state,s,turnId);return {ok:true,state:parseTerrorscapeState(s)};
 }catch(error){if(error instanceof RuleError)return {ok:false,reason:'INVALID_ACTION'};throw error;}
}
