import * as v from 'valibot';
import {GameRevisionSchema,TERROR_CHARACTERS,TERROR_ITEMS,TERROR_SKILLS,TERROR_ITEM_INFO,TERROR_SKILL_INFO,TERROR_CHARACTER_INFO,TERROR_ROOM_INFO,TERROR_DOORS,TERROR_ROOMS,TERROR_PASSAGES,terrorAdjacent,terrorEdge,type TerrorscapeAction,type TerrorCard,type TerrorItem,type TerrorSkill,type TerrorCharacter,type TerrorRoom,type PlayerId,type TileId,type TurnId,type GameId,type ServerTime} from '@hangul-rummikub/shared';
import type {RandomSource} from '../../../ports/system.js';
import {StateSchema,type TerrorscapeState} from './state.js';
import {terrorView} from './visibility.js';
export type {TerrorscapeState} from './state.js';
const SEARCH:Partial<Record<TerrorItem,number>>={KEY:5,TOOLBOX:2,WHISKEY:1,HATCHET:1,HERBS:1,POWDER:1};
const DISCOVER:Partial<Record<TerrorItem,number>>={AMMO:3,HERBS:3,ADRENALINE:3,HATCHET:3,TRANQUILIZER:3,WHISKEY:3,TOOLBOX:2,REVOLVER:2,KEY:2,FIRECRACKER:1,AMULET:1,SHORTSWORD:1,SECRET_MAP:1,POWDER:1,FLASHLIGHT:1,LONGSWORD:1,TRAP_PARTS:1};
const KILLER:Record<TerrorSkill,number>={PURSUE:3,BARRICADE:3,SENSE:2,CHAINSAW:2,MADNESS:1,STAY:1,RAGE:1};
export function makeTerrorscapeCards(id:()=>TileId){const make=(counts:Partial<Record<TerrorItem,number>>)=>TERROR_ITEMS.flatMap(key=>Array.from({length:counts[key]??0},()=>({cardId:id(),key})));return {search:make(SEARCH),discover:make(DISCOVER),medkit:{cardId:id(),key:'MEDKIT' as const},killer:TERROR_SKILLS.flatMap(key=>Array.from({length:KILLER[key]},()=>({cardId:id(),key})))};}
function shuffle<T>(values:readonly T[],r:RandomSource):T[]{const a=[...values];for(let i=a.length-1;i>0;i--){const j=r.nextInt(i+1);[a[i],a[j]]=[a[j]!,a[i]!];}return a;}
export function parseTerrorscapeState(input:unknown):TerrorscapeState {
 const s=v.parse(StateSchema,input),ids=new Set(s.players.map(p=>p.playerId));
 if(ids.size!==s.players.length||!ids.has(s.killerPlayerId)||new Set(s.survivors.map(p=>p.character)).size!==3||s.survivors.some(p=>!ids.has(p.playerId)||p.playerId===s.killerPlayerId)||s.players.some(p=>p.playerId!==s.killerPlayerId&&!s.survivors.some(c=>c.playerId===p.playerId)))throw new Error('Invalid Terrorscape roles');
 const items=[...s.searchDeck,...s.discoverDeck,...s.keys,...s.discard,...s.survivors.flatMap(p=>p.hand),...(s.loot?.cards??[])];
 const skills=[...s.hand,...s.killerDeck,...s.killerDiscard,...(s.locked?[s.locked]:[])];
 if(items.length!==44||skills.length!==13||new Set([...items,...skills].map(c=>c.cardId)).size!==57||TERROR_ITEMS.some(k=>items.filter(c=>c.key===k).length!==(SEARCH[k]??0)+(DISCOVER[k]??0)+(k==='MEDKIT'?1:0))||TERROR_SKILLS.some(k=>skills.filter(c=>c.key===k).length!==KILLER[k]))throw new Error('Terrorscape card conservation failed');
 if(s.keys.some(c=>c.key!=='KEY')||s.survivors.some(p=>p.hand.some(c=>c.key==='KEY'))||s.blocks.some(e=>!TERROR_DOORS.some(([a,b])=>terrorEdge(a,b)===e))||new Set(s.blocks).size!==s.blocks.length||new Set(s.noises).size!==s.noises.length)throw new Error('Invalid Terrorscape board');
 if((s.phase==='LOOT')!==Boolean(s.loot)&&s.phase!=='FINISHED'||s.phase==='UNLOCK'&&(!s.pendingDraw||s.hand.length!==6)||s.phase!=='UNLOCK'&&s.hand.length>5)throw new Error('Invalid pending Terrorscape state');
 if((s.phase==='FINISHED')!==(s.result!==null&&s.finishedAt!==null))throw new Error('Invalid Terrorscape result');
 if(s.encounter&&(new Set(s.encounter.targets).size!==s.encounter.targets.length||s.encounter.attacked.some(c=>!s.encounter!.targets.includes(c))||s.encounter.fleePending.some(c=>!s.encounter!.targets.includes(c))))throw new Error('Invalid encounter participants');
 if(['DEFENDER','DEFEND','FLEE'].includes(s.phase)&&!s.encounter)throw new Error('Missing encounter');
 return s;
}
export function createTerrorscapeGame(input:{gameId:GameId;playerIds:readonly PlayerId[];cards:ReturnType<typeof makeTerrorscapeCards>;now:ServerTime;turnId:TurnId;random:RandomSource}):TerrorscapeState {
 const {cards,random}=input;const guaranteed=cards.search.find(c=>c.key==='KEY')!;
 const deck=shuffle(cards.killer.filter(c=>c.key!=='RAGE'),random);
 return parseTerrorscapeState({rulesVersion:'terrorscape-manor-butcher-v1',gameId:input.gameId,revision:0,transitionId:input.turnId,survivorRevision:0,killerRevision:0,survivorTurnId:input.turnId,killerTurnId:input.turnId,startedAt:input.now,finishedAt:null,phase:'SETUP',players:input.playerIds.map(playerId=>({playerId})),killerPlayerId:input.playerIds[0],survivors:TERROR_CHARACTERS.map((character,i)=>({character,playerId:input.playerIds[1+i%(input.playerIds.length-1)],location:'R1',fear:0,injuries:0,hand:character==='MARCO'?[cards.medkit]:[],acted:false,ready:false})),round:0,killerLocation:'G5',level:1,bonus:0,blocks:[],noises:[],pendingNoises:[],firecracker:false,pendingFirecracker:false,keys:[],repair:0,repaired:false,rescue:null,trap:null,searchDeck:[guaranteed,...shuffle(cards.search.filter(c=>c.cardId!==guaranteed.cardId),random)],discoverDeck:shuffle(cards.discover,random),discard:[],loot:null,hand:deck.splice(-2),killerDeck:deck,killerDiscard:[],locked:cards.killer.find(c=>c.key==='RAGE'),actionsLeft:2,slowUsed:false,sensed:[],encounter:null,dice:[],defenseTotal:null,defenseBonus:0,pendingDraw:null,logs:{survivor:[],killer:[],survivorSeq:0,killerSeq:0},pings:[],result:null});
}
class RuleError extends Error {}
function requireRule(test:unknown):asserts test {if(!test)throw new RuleError('INVALID_ACTION');}
function survivor(s:TerrorscapeState,c:TerrorCharacter){const p=s.survivors.find(p=>p.character===c);if(!p)throw new Error('Missing survivor');return p;}
function log(s:TerrorscapeState,text:string,sound:TerrorscapeState['logs']['survivor'][number]['sound']='NONE',side:'BOTH'|'SURVIVOR'|'KILLER'='BOTH'){if(side!=='KILLER'){s.logs.survivor.push({id:++s.logs.survivorSeq,text,sound});s.logs.survivor=s.logs.survivor.slice(-80);}if(side!=='SURVIVOR'){s.logs.killer.push({id:++s.logs.killerSeq,text,sound});s.logs.killer=s.logs.killer.slice(-80);}}
function noise(s:TerrorscapeState,at:TerrorRoom,immediate=false){const a=immediate?s.noises:s.pendingNoises;if(!a.includes(at))a.push(at);if(immediate)log(s,`${TERROR_ROOM_INFO[at].name}에서 소음이 들립니다.`,'NOISE');}
function fear(s:TerrorscapeState,c:TerrorCharacter){const p=survivor(s,c);if(p.fear===2)noise(s,p.location,true);else p.fear++;}
function finish(s:TerrorscapeState,reason:NonNullable<TerrorscapeState['result']>['reason'],now:ServerTime){s.phase='FINISHED';s.finishedAt=now;const team=reason==='ESCAPED'||reason==='RESCUED';s.result={reason,winnerPlayerIds:reason==='CANCELLED'?[]:s.players.filter(p=>(p.playerId!==s.killerPlayerId)===team).map(p=>p.playerId)};log(s,reason==='CANCELLED'?'참가자가 나가 게임이 종료되었습니다.':team?'생존자들이 저택을 벗어났습니다.':'저택의 사냥이 끝났습니다.','WIN');}
function hurt(s:TerrorscapeState,c:TerrorCharacter,now:ServerTime){const p=survivor(s,c);p.injuries++;log(s,`${TERROR_CHARACTER_INFO[c].name}이 부상을 입었습니다.`,'HURT');if(p.injuries>=2)finish(s,'KILLED',now);}
function startSurvivors(s:TerrorscapeState,now:ServerTime){s.phase='SURVIVORS';s.round++;s.noises=[];s.pendingNoises=[];s.firecracker=false;s.pendingFirecracker=false;s.repaired=false;s.encounter=null;s.sensed=[];s.bonus=0;s.pings=[];for(const p of s.survivors){p.acted=false;p.ready=false;if(p.hand.some(c=>c.key==='AMULET'))p.fear=Math.max(0,p.fear-1);}if(s.rescue!==null){s.rescue--;if(s.rescue<=0){finish(s,'RESCUED',now);return;}}if(s.keys.length>=5&&(s.survivors.every(p=>p.location==='R1')||s.survivors.every(p=>p.location==='G5')&&s.survivors.some(p=>p.hand.some(c=>c.key==='SECRET_MAP')))){finish(s,'ESCAPED',now);return;}log(s,`${s.round}라운드 · 생존자의 차례입니다.`,'TURN');}
function startKiller(s:TerrorscapeState){s.phase='FAST';s.actionsLeft=2;s.slowUsed=false;s.noises=[...new Set([...s.noises,...s.pendingNoises])];s.firecracker=s.pendingFirecracker;if(s.firecracker)s.noises=[...TERROR_ROOMS];s.pendingNoises=[];log(s,'살인마의 차례입니다. 드러난 소음에 귀를 기울이세요.','TURN');}
function move(s:TerrorscapeState,start:TerrorRoom,path:readonly TerrorRoom[],max:number,killer:boolean):{at:TerrorRoom;removed:boolean}{requireRule(path.length>0&&path.length<=max);let at=start,removed=false;for(const to of path){requireRule(terrorAdjacent(at,to));const edge=terrorEdge(at,to);if(s.blocks.includes(edge)){requireRule(killer);s.blocks=s.blocks.filter(e=>e!==edge);removed=true;}at=to;}return {at,removed};}
function killerMove(s:TerrorscapeState,path:readonly TerrorRoom[],max:number){const m=move(s,s.killerLocation,path,max,true);s.killerLocation=m.at;log(s,`살인마가 ${TERROR_ROOM_INFO[m.at].name}(으)로 이동했습니다.`,'STEP');return m.removed;}
function consume(s:TerrorscapeState,p:TerrorscapeState['survivors'][number],card:TerrorCard){p.hand=p.hand.filter(c=>c.cardId!==card.cardId);s.discard.push(card);}
function repair(s:TerrorscapeState,p:TerrorscapeState['survivors'][number],amount:number){requireRule(p.location==='B1'&&p.location!==s.killerLocation&&!s.repaired&&s.rescue===null);s.repair=Math.min(5,s.repair+amount);s.repaired=true;noise(s,p.location);if(s.repair===5)s.rescue=5;log(s,`무전기 수리 ${s.repair}/5${s.rescue!==null?' · 구조 요청 완료':''}`,'CARD','SURVIVOR');}
function openLoot(s:TerrorscapeState,p:TerrorscapeState['survivors'][number],source:'SEARCH'|'DISCOVER'){const deck=source==='SEARCH'?s.searchDeck:s.discoverDeck;requireRule(deck.length>0);const cards=deck.splice(Math.max(0,deck.length-(source==='SEARCH'?1:2)));if(!(source==='SEARCH'&&p.character==='ANNA')&&cards.some(c=>TERROR_ITEM_INFO[c.key].noisy))noise(s,p.location);s.loot={character:p.character,source,cards};s.phase='LOOT';}
function flee(s:TerrorscapeState){if(!s.encounter)throw new Error('Missing encounter');s.phase='FLEE';s.encounter.defender=null;s.encounter.fleePending=[...s.encounter.targets];}
function draw(s:TerrorscapeState,random:RandomSource,now:ServerTime){const pending=s.pendingDraw;if(!pending)throw new Error('Missing draw');while(pending.remaining>0){if(s.killerDeck.length===0){s.level=Math.min(5,s.level+1);log(s,`살인마가 레벨 ${s.level}로 각성했습니다.`,'FEAR');if(s.level>=3&&s.locked){s.hand.push(s.locked);s.locked=null;if(s.hand.length>5){s.phase='UNLOCK';return;}}s.killerDeck=shuffle(s.killerDiscard,random);s.killerDiscard=[];if(!s.killerDeck.length){pending.remaining=0;break;}}const card=s.killerDeck.pop()!;if(pending.mode==='DRAW'&&s.hand.length<5)s.hand.push(card);else s.killerDiscard.push(card);pending.remaining--;}
 s.pendingDraw=null;if(pending.then==='SURVIVORS')startSurvivors(s,now);else if(pending.then==='FLEE')flee(s);else rollDefense(s,random,now);
}
function beginDraw(s:TerrorscapeState,remaining:number,mode:'DRAW'|'DISCARD',then:'SURVIVORS'|'FLEE'|'ROLL',r:RandomSource,now:ServerTime){s.pendingDraw={remaining,mode,then};draw(s,r,now);}
function encounter(s:TerrorscapeState,now:ServerTime):boolean{const targets=s.survivors.filter(p=>p.location===s.killerLocation).map(p=>p.character);if(!targets.length){log(s,'수색했지만 아무도 발견하지 못했습니다.','CARD');return false;}s.encounter={location:s.killerLocation,targets,attacked:[],defender:null,fleePending:[]};s.dice=[];s.defenseTotal=null;log(s,`${TERROR_ROOM_INFO[s.killerLocation].name}에서 ${targets.map(c=>TERROR_CHARACTER_INFO[c].name).join(', ')} 발견!`,'FEAR');if(s.level>=5)for(const c of targets){hurt(s,c,now);if(s.phase==='FINISHED')return true;}s.phase='DEFENDER';return true;}
function rollDefense(s:TerrorscapeState,r:RandomSource,now:ServerTime){const e=s.encounter;requireRule(e?.defender);const p=survivor(s,e.defender);s.dice=Array.from({length:4-p.fear},()=>[0,1,1,1,1,3][r.nextInt(6)]!);s.defenseTotal=s.dice.reduce((n,v)=>n+v,0)+s.defenseBonus;const success=s.defenseTotal>=(s.level>=2?6:5)+s.bonus;log(s,`${TERROR_CHARACTER_INFO[p.character].name} 방어 ${s.defenseTotal} · ${success?'성공':'실패'}`,'DEFENSE');e.attacked.push(p.character);if(success){beginDraw(s,2,'DISCARD','FLEE',r,now);return;}hurt(s,p.character,now);if(s.phase==='FINISHED')return;e.defender=null;if(e.attacked.length<e.targets.length)s.phase='DEFENDER';else flee(s);}
function block(s:TerrorscapeState,edges:readonly string[],replaces:readonly string[]){requireRule(new Set(replaces).size===replaces.length&&replaces.every(e=>s.blocks.includes(e)&&!edges.includes(e)));const fresh=edges.filter(e=>!s.blocks.includes(e));requireRule(replaces.length===Math.max(0,s.blocks.length+fresh.length-7));s.blocks=s.blocks.filter(e=>!replaces.includes(e));s.blocks.push(...fresh);log(s,'살인마가 문을 봉쇄했습니다.','BLOCK');}
const localDoors=(at:TerrorRoom)=>TERROR_DOORS.filter(([a,b])=>a===at||b===at).map(([a,b])=>terrorEdge(a,b));
function basicDone(p:TerrorscapeState['survivors'][number]){requireRule(!p.acted);p.acted=true;p.ready=false;}
function revisions(old:TerrorscapeState,s:TerrorscapeState,id:TurnId){s.revision=v.parse(GameRevisionSchema,old.revision+1);s.transitionId=id;for(const side of ['SURVIVOR','KILLER'] as const){const actor=side==='KILLER'?old.killerPlayerId:old.survivors[0]!.playerId;const changed=JSON.stringify(terrorView(old,actor))!==JSON.stringify(terrorView(s,actor));if(changed){if(side==='KILLER'){s.killerRevision=v.parse(GameRevisionSchema,old.killerRevision+1);s.killerTurnId=id;}else{s.survivorRevision=v.parse(GameRevisionSchema,old.survivorRevision+1);s.survivorTurnId=id;}}}}
export function cancelTerrorscape(state:TerrorscapeState,now:ServerTime){const s=parseTerrorscapeState(state);if(s.phase==='FINISHED')return s;finish(s,'CANCELLED',now);revisions(state,s,s.transitionId);return parseTerrorscapeState(s);}
export function applyTerrorscapeAction(state:TerrorscapeState,actor:PlayerId,a:TerrorscapeAction,now:ServerTime,turnId:TurnId,random:RandomSource,hostPlayerId:PlayerId|null=state.players[0]!.playerId):{ok:true;state:TerrorscapeState}|{ok:false;reason:'INVALID_ACTION'} {
 try {const s=parseTerrorscapeState(state);requireRule(s.phase!=='FINISHED'&&s.players.some(p=>p.playerId===actor));const killer=actor===s.killerPlayerId;
 const own=(c:TerrorCharacter)=>{const p=survivor(s,c);requireRule(!killer&&p.playerId===actor);return p;};
 const teamAction=()=>requireRule(s.phase==='SURVIVORS'&&!killer&&!s.survivors.some(p=>p.hand.length>3));
 switch(a.type){
 case 'SET_ROLES':requireRule(s.phase==='SETUP'&&actor===hostPlayerId&&s.players.some(p=>p.playerId===a.killerPlayerId)&&a.owners.every(id=>id!==a.killerPlayerId&&s.players.some(p=>p.playerId===id))&&s.players.every(p=>p.playerId===a.killerPlayerId||a.owners.includes(p.playerId)));s.killerPlayerId=a.killerPlayerId;s.survivors.forEach((p,i)=>{p.playerId=a.owners[i]!;});break;
 case 'BEGIN_HUNT':requireRule(s.phase==='SETUP'&&actor===hostPlayerId);startSurvivors(s,now);break;
 case 'PING':requireRule(!killer&&s.phase!=='SETUP');s.pings.push({room:a.room,message:a.message,playerId:actor});s.pings=s.pings.slice(-6);break;
 case 'BASIC':{teamAction();const p=own(a.character);basicDone(p);if(a.kind==='MOVE'||a.kind==='SPRINT'){requireRule(a.kind!=='SPRINT'||p.character==='WILLIAM');p.location=move(s,p.location,a.path,a.kind==='SPRINT'?3:2,false).at;if(a.kind==='SPRINT')noise(s,p.location);log(s,`${TERROR_CHARACTER_INFO[p.character].name} → ${TERROR_ROOM_INFO[p.location].name}`,'STEP','SURVIVOR');}else if(a.kind==='CALM'){p.fear=0;log(s,`${TERROR_CHARACTER_INFO[p.character].name}이 공포를 가라앉혔습니다.`,'CARD','SURVIVOR');}else if(a.kind==='REPAIR')repair(s,p,1);else if(a.kind==='SEARCH'){requireRule(TERROR_ROOM_INFO[p.location].search&&p.location!==s.killerLocation);openLoot(s,p,'SEARCH');}else if(a.kind==='REMOVE_BLOCK'){requireRule(localDoors(p.location).includes(a.edge)&&s.blocks.includes(a.edge));s.blocks=s.blocks.filter(e=>e!==a.edge);noise(s,p.location,true);}else {requireRule(p.character==='MARCO');const c=s.discard.find(c=>c.cardId===a.cardId&&(c.key==='ADRENALINE'||c.key==='TRANQUILIZER'));requireRule(c);s.discard=s.discard.filter(i=>i.cardId!==c.cardId);p.hand.push(c);}break;}
 case 'READY':{teamAction();const p=own(a.character);requireRule(p.acted);p.ready=a.ready;break;}
 case 'DISCOVER':{teamAction();requireRule(s.survivors.every(p=>p.acted&&p.ready));const p=own(a.character);if(!s.discoverDeck.length){if(s.rescue===null)finish(s,'EXHAUSTED',now);else startKiller(s);}else openLoot(s,p,'DISCOVER');break;}
 case 'KEEP':{requireRule(s.phase==='LOOT'&&s.loot);const loot=s.loot,p=own(loot.character);requireRule(a.cardId===null||loot.cards.some(c=>c.cardId===a.cardId));for(const c of loot.cards){if(c.cardId===a.cardId){if(c.key==='KEY')s.keys.push(c);else p.hand.push(c);}else s.discard.push(c);}s.loot=null;if(loot.source==='DISCOVER'){s.phase='SURVIVORS';if(p.hand.length<=3)startKiller(s);else p.ready=true;}else s.phase='SURVIVORS';break;}
 case 'DISCARD':{requireRule(s.phase==='SURVIVORS');const p=own(a.character);requireRule(p.hand.length>3);const c=p.hand.find(c=>c.cardId===a.cardId);requireRule(c);consume(s,p,c);if(s.survivors.every(p=>p.acted&&p.ready)&&!s.survivors.some(p=>p.hand.length>3))startKiller(s);break;}
 case 'TRADE':{teamAction();const p=own(a.character),to=survivor(s,a.target),c=p.hand.find(c=>c.cardId===a.cardId);requireRule(c&&to!==p&&p.location===to.location&&to.hand.length<4);p.hand=p.hand.filter(i=>i.cardId!==c.cardId);to.hand.push(c);p.ready=false;to.ready=false;break;}
 case 'ITEM':{teamAction();const p=own(a.character),c=p.hand.find(c=>c.cardId===a.cardId),to=survivor(s,a.target);requireRule(c);const special=['TOOLBOX','HERBS','MEDKIT','FIRECRACKER','FLASHLIGHT','TRAP_PARTS'].includes(c.key);if(special)basicDone(p);else p.ready=false;let spent=true;
 if(c.key==='TOOLBOX')repair(s,p,2);
 else if(c.key==='WHISKEY'){requireRule(terrorAdjacent(p.location,a.destination));noise(s,a.destination);}
 else if(c.key==='HATCHET'){requireRule(localDoors(p.location).includes(a.edge)&&s.blocks.includes(a.edge));s.blocks=s.blocks.filter(e=>e!==a.edge);noise(s,p.location,true);}
 else if(c.key==='TRANQUILIZER')p.fear=0;
 else if(c.key==='ADRENALINE')p.location=move(s,p.location,[a.destination],1,false).at;
 else if(c.key==='HERBS'||c.key==='MEDKIT'){requireRule(to.location===p.location&&to.injuries===1&&(c.key!=='MEDKIT'||p.character==='MARCO'));to.injuries=0;to.ready=false;if(c.key==='MEDKIT')to.fear=0;else noise(s,p.location);}
 else if(c.key==='FIRECRACKER')s.pendingFirecracker=true;
 else if(c.key==='FLASHLIGHT'){requireRule(TERROR_PASSAGES[p.location]===a.destination);p.location=a.destination;spent=false;}
 else if(c.key==='TRAP_PARTS'){requireRule(s.trap===null);s.trap=p.location;}
 else requireRule(false);if(spent)consume(s,p,c);log(s,`${TERROR_CHARACTER_INFO[p.character].name} · ${TERROR_ITEM_INFO[c.key].name} 사용`,'CARD','SURVIVOR');break;}
 case 'KILLER_NEXT':requireRule(killer);if(s.phase==='FAST')s.phase='MAIN';else if(s.phase==='MAIN'){requireRule(s.actionsLeft===0);s.phase='SLOW';}else {requireRule(s.phase==='SLOW');beginDraw(s,3,'DRAW','SURVIVORS',random,now);}break;
 case 'KILLER_BASIC':requireRule(killer&&s.phase==='MAIN'&&s.actionsLeft>0);s.actionsLeft--;if(a.kind==='MOVE')killerMove(s,[a.destination],1);else encounter(s,now);if(s.phase==='MAIN'&&s.actionsLeft===0)s.phase='SLOW';break;
 case 'KILLER_CARD':{requireRule(killer);const c=s.hand.find(c=>c.cardId===a.cardId);requireRule(c);const info=TERROR_SKILL_INFO[c.key],timing=c.key==='CHAINSAW'&&s.level>=4?'FAST':info.timing;requireRule(s.phase===timing&&(timing!=='MAIN'||s.actionsLeft===2)&&(timing!=='SLOW'||!s.slowUsed));requireRule(a.cost.length===info.cost&&new Set(a.cost).size===a.cost.length&&a.cost.every(id=>id!==c.cardId&&s.hand.some(c=>c.cardId===id)));const spent=s.hand.filter(i=>i.cardId===c.cardId||a.cost.includes(i.cardId));s.hand=s.hand.filter(i=>!spent.includes(i));s.killerDiscard.push(...spent);log(s,`살인마 · ${info.name}`,'CARD');if(timing==='MAIN'){s.actionsLeft=0;s.phase='SLOW';}if(timing==='SLOW')s.slowUsed=true;
 if(c.key==='PURSUE')killerMove(s,a.path,1);
 else if(c.key==='SENSE'){s.sensed=s.survivors.filter(p=>p.character!=='ANNA'&&p.location.startsWith(a.zone)).map(({character,location})=>({character,location}));log(s,`${a.zone} 구역 감지 · ${s.sensed.length}명`,'FEAR');}
 else if(c.key==='BARRICADE'||c.key==='MADNESS'){requireRule(localDoors(s.killerLocation).includes(a.edge)&&!s.blocks.includes(a.edge));block(s,[a.edge],a.replaces);if(c.key==='MADNESS')s.bonus+=2;}
 else if(c.key==='STAY')block(s,localDoors(s.killerLocation),a.replaces);
 else if(c.key==='CHAINSAW'){for(const p of s.survivors)if(p.location===s.killerLocation||terrorAdjacent(p.location,s.killerLocation))fear(s,p.character);requireRule(a.path.length<=1);if(a.path.length)killerMove(s,a.path,1);for(const p of s.survivors.filter(p=>p.location===s.killerLocation)){hurt(s,p.character,now);if(s.result)break;}}
 else {const removed=killerMove(s,a.path,2);if(!encounter(s,now)&&removed)s.phase='RAGE';}break;}
 case 'RAGE_MOVE':{requireRule(killer&&s.phase==='RAGE');const removed=killerMove(s,a.path,2);if(!encounter(s,now))s.phase=removed?'RAGE':'SLOW';break;}
 case 'UNLOCK_DISCARD':{requireRule(killer&&s.phase==='UNLOCK'&&s.pendingDraw);const c=s.hand.find(c=>c.cardId===a.cardId);requireRule(c);s.hand=s.hand.filter(i=>i.cardId!==a.cardId);s.killerDiscard.push(c);s.killerDeck=shuffle(s.killerDiscard,random);s.killerDiscard=[];draw(s,random,now);break;}
 case 'DEFENDER':requireRule(!killer&&s.phase==='DEFENDER'&&s.encounter&&s.encounter.targets.includes(a.character)&&!s.encounter.attacked.includes(a.character));own(a.character);s.encounter.defender=a.character;s.phase='DEFEND';break;
 case 'DEFEND':{requireRule(s.phase==='DEFEND'&&s.encounter?.defender);const p=own(s.encounter.defender),c=a.cardId===null?null:p.hand.find(c=>c.cardId===a.cardId);requireRule(a.cardId===null||c);let bonus=0;if(c){requireRule(['HATCHET','POWDER','AMMO','LONGSWORD','SHORTSWORD'].includes(c.key));if(c.key==='AMMO')requireRule(p.hand.some(c=>c.key==='REVOLVER'));bonus=c.key==='AMMO'?4:c.key==='LONGSWORD'?3:c.key==='POWDER'?2:1;if(['HATCHET','POWDER','AMMO'].includes(c.key))consume(s,p,c);log(s,`${TERROR_CHARACTER_INFO[p.character].name} · ${TERROR_ITEM_INFO[c.key].name} 방어`,'CARD');}else if(p.character==='WILLIAM')bonus=1;if(s.trap===p.location){bonus+=2;s.trap=null;log(s,'덫 발동 · 방어 +2','BLOCK');}s.defenseBonus=bonus;if(c?.key==='LONGSWORD')beginDraw(s,1,'DRAW','ROLL',random,now);else rollDefense(s,random,now);break;}
 case 'FLEE':{requireRule(s.phase==='FLEE'&&s.encounter&&s.encounter.fleePending.includes(a.character));const p=own(a.character);if(a.destination!==p.location)p.location=move(s,p.location,[a.destination],1,false).at;s.encounter.fleePending=s.encounter.fleePending.filter(c=>c!==a.character);log(s,`${TERROR_CHARACTER_INFO[p.character].name} 도주 결정 완료`,'STEP','SURVIVOR');if(!s.encounter.fleePending.length)beginDraw(s,3,'DRAW','SURVIVORS',random,now);break;}
 }
 revisions(state,s,turnId);return {ok:true,state:parseTerrorscapeState(s)};
 }catch(error){if(error instanceof RuleError)return {ok:false,reason:'INVALID_ACTION'};throw error;}
}
