import type {PlayerId,TerrorscapeProjection} from '@hangul-rummikub/shared';
import {terrorStrength} from './game.js';
import type {TerrorscapeState} from './state.js';
export function terrorView(s:TerrorscapeState,playerId:PlayerId):TerrorscapeProjection {
 const killer=playerId===s.killerPlayerId;
 const base={gameType:'TERRORSCAPE' as const,gameId:s.gameId,gameRevision:killer?s.killerRevision:s.survivorRevision,rulesVersion:s.rulesVersion,playerStates:s.players,killerPlayerId:s.killerPlayerId,owners:s.survivors.map(p=>p.playerId),round:s.round,difficulty:s.difficulty,killerTraits:s.phase==='SETUP'||s.phase==='TRAIT_DRAFT'?[]:s.killerTraits,groupMove:s.groupMove&&!(killer&&s.groupMove.then==='SURVIVORS')?{targets:s.groupMove.targets,max:s.groupMove.max}:null,plansEnabled:s.plansEnabled,separateWays:s.separateWays,firstDiscover:s.firstDiscover,keys:s.keys.length,killerType:s.killerType,killerLocation:!killer&&s.stealth?null:s.killerLocation,stealthOrigin:s.stealth?.origin??null,level:s.level,strength:terrorStrength(s),blocks:s.blocks,noises:s.noises,firecracker:s.firecracker,conditions:s.survivors.map(({character,fear,injuries,outcome})=>({character,fear,injuries,outcome,keys:s.separateWays?s.keyOwners.filter(k=>k.character===character).length:0})),sensed:s.sensed,encounter:s.encounter,dice:s.dice,defenseTotal:s.defenseTotal,history:killer?s.logs.killer:s.logs.survivor,
 privateState:killer?{role:'KILLER' as const,playerId,killer:{traitOffer:s.killerTraitOffer,traitsChosen:s.killerTraitsChosen,usedTraits:[...new Set([...s.usedTraits.filter(t=>s.killerTraits.includes(t)),...s.turnTraits.filter(t=>['SWIFT','ACUTE','ENHANCED','HEIGHTENED','AURA','PERILOUS','ENCIRCLE'].includes(t)),...s.senseUsed])],senseTargets:s.senseTargets,levelTrait:s.levelTraitQueue[0]??null,hand:s.phase==='SETUP'?[]:s.hand,deckCount:s.killerDeck.length,discardCount:s.killerDiscard.length,actionsLeft:s.actionsLeft,slowUsed:s.slowUsed,discard:s.killerDiscard,fearTarget:s.fearQueue[0]??null,levelBlocksRemaining:s.levelBlocksRemaining}}:{role:'SURVIVOR' as const,playerId,team:{traits:s.survivorTraits,usedTraits:s.usedTraits.filter(t=>s.survivorTraits.some(p=>p.chosen===t)),survivors:s.survivors,plan:s.plan,keyOwners:s.keyOwners,keys:s.keys.length,repair:s.repair,repaired:s.repaired,rescue:s.rescue,trap:s.trap,searchCount:s.searchDeck.length,discoverCount:s.discoverDeck.length,discard:s.discard,loot:s.loot,pings:s.pings}}};
 if(s.phase==='FINISHED'){if(!s.result)throw new Error('Missing result');return {...base,phase:'FINISHED',result:s.result};}
 if(s.phase==='END_COMPLETE'||s.phase==='ENCOUNTER_FEAR'||s.phase==='REAPPEAR_SEARCH'||s.phase==='ENCOUNTER_START')throw new Error('Unsettled encounter');
 const phase=killer&&(['LOOT','PLAN'].includes(s.phase)||s.phase==='GROUP_MOVE'&&s.groupMove?.then==='SURVIVORS')?'SURVIVORS':!killer&&['KILLER_START','KILLER_END','SENSE_REACTION','LEVEL_TRAIT','FAST','MAIN','SLOW','RAGE','UNLOCK','WHIZZ','REACTION','REAPPEAR','LEVEL_BLOCK'].includes(s.phase)?'KILLER':s.phase;
 return {...base,phase,turnId:killer?s.killerTurnId:s.survivorTurnId};
}
