import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {HARMONIES_CELLS,HARMONIES_COLOR_NAMES,harmoniesAnimal,harmoniesReplay,harmoniesMatches,harmoniesCanPlace,harmoniesScore,PROTOCOL_VERSION,type HarmoniesStep,type HarmoniesProjection,type HarmoniesClientCommand,type HarmoniesOwnedCard,type HarmoniesScoreKind,type TileId} from '@hangul-rummikub/shared';
import type {HarmoniesWebSnapshot} from '../../lib/snapshot-wire-decoder.js';
import {createRequestId} from '../../lib/request-id.js';
import {getGameStartControl} from '../../lib/game-start.js';
import {HarmoniesCommandRejected} from '../../lib/harmonies-command-error.js';
import {AnimalPattern,TerrainToken,HARMONIES_PALETTE} from './art.js';
import {useHarmoniesSound,type HarmoniesCue} from './sound.js';
type Props={snapshot:HarmoniesWebSnapshot;connected:boolean;pending:boolean;error:string|null;connectionLabel:string;onCommand(c:HarmoniesClientCommand):Promise<void>;onRematch():void;onStart():void;onLeave():void;onCopy():void};
const SCORE_LABELS:Record<HarmoniesScoreKind,string>={trees:'나무',mountains:'산',fields:'들판',buildings:'건물',water:'강',animals:'동물'};
const SCORE_HELP:Record<HarmoniesScoreKind,string>={trees:'나무 높이 1 / 2 / 3층마다 1 / 3 / 7점. 줄기만 있으면 0점입니다.',mountains:'산 높이 1 / 2 / 3층마다 1 / 3 / 7점. 다른 산과 인접해야 점수를 얻어요.',fields:'노란 토큰이 2개 이상 이어진 덩어리마다 5점. 덩어리가 합쳐지면 점수가 줄 수 있어요.',buildings:'2층 건물에 인접한 칸의 맨 위 토큰 색이 3종류 이상이면 5점입니다.',water:'가장 좋은 강 하나를 계산해요. 양 끝 사이 최단 경로의 길이 1~6칸은 0·2·5·8·11·15점, 이후 칸마다 4점.',animals:'카드에서 동물을 옮기며 드러난 가장 높은 점수를 얻습니다. 미완성 카드도 점수를 얻어요.'};
function AnimalCard({id,owned,selected=false,onSelect,compact=false}:{id:number;owned?:HarmoniesOwnedCard;selected?:boolean;onSelect():void;compact?:boolean}){
 const c=harmoniesAnimal(id),anchor=c.pattern.find(p=>p.animal)!,color=anchor.stack.at(-1),accent=color==='BUILDING'||!color?'#c25a4f':HARMONIES_PALETTE[color];
 return <button type="button" className={`hm-animal-card ${compact?'compact':''} ${owned?.placed===c.points.length?'complete':''}`} aria-label={`${c.name} 카드${owned?` · 동물 ${owned.placed}/${c.points.length}`:''} · 서식지 보기`} aria-pressed={selected} onClick={onSelect} style={{'--animal-accent':accent} as CSSProperties}><div className="hm-card-art" style={{backgroundPosition:`${((id-1)%8)/7*100}% ${Math.floor((id-1)/8)/3*100}%`}}/><div className="hm-card-title"><strong>{c.name}</strong><span>{owned?c.points[owned.placed-1]??0:c.points.at(-1)}<small>점</small></span></div><div className="hm-card-bottom"><AnimalPattern cardId={id}/><div className="hm-card-track" aria-label="배치한 동물에 따른 점수">{c.points.map((n,i)=><span key={i} className={owned&&i<owned.placed?'earned':''}>{owned&&i<owned.placed?'◆':'◇'}<b>{n}</b></span>)}</div></div>{owned?.placed===c.points.length&&<span className="hm-complete-label">서식지 완성</span>}</button>;
}
export function HarmoniesScreen(props:Props){
 const g=props.snapshot.game,sound=useHarmoniesSound(g,props.connected),start=getGameStartControl(props.snapshot,props.pending||!props.connected);
 return <section className="harmonies-screen" aria-label="하모니즈" onPointerDownCapture={()=>void sound.unlock()} onKeyDownCapture={e=>{if(e.key==='Enter'||e.key===' ')void sound.unlock();}}>
  <header className="hm-header"><div className="hm-brand"><span className="hm-brand-leaf" aria-hidden="true">❧</span><div><span className="hm-eyebrow">A LITTLE WORLD OF YOUR OWN</span><h1>Harmonies <small>하모니즈</small></h1></div></div><div className="hm-tools"><span className="hm-connection">{props.connectionLabel}</span><details className="hm-sound"><summary>♫ 소리</summary><div><label>효과음 {sound.volume}%<input type="range" min="0" max="100" value={sound.volume} aria-label="하모니즈 효과음 음량" onChange={e=>sound.setVolume(Number(e.target.value))}/></label><button onClick={()=>sound.setVolume(sound.volume?0:35)}>{sound.volume?'음소거':'소리 켜기'}</button><button onClick={()=>void sound.unlock().then(()=>sound.play('WATER'))}>물소리 들어보기</button><small>{sound.enabled?'소리가 준비됐어요.':'화면을 누르면 소리가 켜집니다.'}</small></div></details><button onClick={props.onCopy}>초대 · {props.snapshot.room.roomCode}</button><button onClick={props.onLeave} disabled={props.pending}>나가기</button></div></header>
  {!props.connected&&<p className="hm-alert" role="status">연결을 복구하고 있어요. 확정된 풍경은 그대로 보존됩니다.</p>}{props.error&&<p className="hm-alert" role="alert">{props.error}</p>}
  {g?<HarmoniesTable key={`${g.gameId}:${props.snapshot.self.playerId}`} {...props} game={g} play={sound.play}/>:<div className="hm-lobby"><div className="hm-lobby-art"><img src="/images/harmonies/landscape.webp" alt="따뜻한 들판과 숲 사이로 흐르는 푸른 강"/><div className="hm-lobby-cards">{[23,18,7].map(id=><AnimalCard key={id} id={id} onSelect={()=>sound.play('CARD')}/>)}</div></div><div className="hm-lobby-copy"><span className="hm-eyebrow">BUILD A LANDSCAPE. WELCOME LIFE.</span><h2>작은 풍경에,<br/>생명을 초대하세요.</h2><p>나무를 키우고, 산을 쌓고, 강을 이어요.<br/>동물들이 머무를 자리를 만들며<br/>나만의 조화로운 세상을 완성하세요.</p><div className="hm-lobby-tags"><span>2–4명</span><span>기본판 A면</span><span>여유로운 턴 · 시간제한 없음</span></div><div className="hm-seats">{props.snapshot.room.players.map((p,i)=><div key={p.playerId}><span className="hm-seat-dot">{i+1}</span><strong>{p.nickname}</strong><small>{p.isHost?'방장 · ':''}{p.connectionStatus==='CONNECTED'?'접속 중':'재접속 중'}</small></div>)}</div><button className="hm-primary" disabled={!start.canStart} onClick={props.onStart}>우리의 풍경 만들기 →</button><p className="hm-subtle">{start.canStart?'방장이 시작하면 각자 빈 보드에서 출발해요.':start.guidance}</p></div></div>}
 </section>;
}
function HarmoniesTable(props:Props&{game:HarmoniesProjection;play(cue:HarmoniesCue):void}){
 const g=props.game,self=props.snapshot.self.playerId,me=g.playerStates.find(p=>p.playerId===self)!;
 const [steps,setSteps]=useState<HarmoniesStep[]>([]),[tokenId,setTokenId]=useState<TileId|null>(null),[selectedCard,setSelectedCard]=useState<number|null>(null),[viewId,setViewId]=useState(self),[scoreKind,setScoreKind]=useState<HarmoniesScoreKind|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[hover,setHover]=useState<number|null>(null),[rules,setRules]=useState(false);
 const sending=useRef(false),request=useRef<HarmoniesClientCommand|null>(null),boardRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{setSteps([]);setTokenId(null);setSelectedCard(null);setError(null);setUncertain(false);request.current=null;},[g.gameId,g.gameRevision]);
 const replay=useMemo(()=>harmoniesReplay(me,g.markets,g.animalMarket,steps),[me,g.markets,g.animalMarket,steps]);
 const draft=replay.ok?replay.draft:null,player=viewId===self&&draft?draft.player:g.playerStates.find(p=>p.playerId===viewId)??me,finished=g.phase==='FINISHED';
 const blocked=props.pending||busy||!props.connected||uncertain,canAct=!blocked&&!finished&&g.activePlayerId===self&&viewId===self;
 const pool=draft?.pool??[],selectedToken=selectedCard===null?(pool.find(t=>t.tileId===tokenId)??pool[0]):undefined,ownSelected=player.cards.find(c=>c.cardId===selectedCard),matches=selectedCard!==null&&ownSelected&&ownSelected.placed<harmoniesAnimal(selectedCard).points.length?harmoniesMatches(player.board,selectedCard):[];
 const score=harmoniesScore(player.board,player.cards),before=harmoniesScore(me.board,me.cards),delta=viewId===self?score.total-before.total:0;
 const name=(id:string)=>props.snapshot.room.players.find(p=>p.playerId===id)?.nickname??'플레이어';
 const activeCards=player.cards.filter(c=>c.placed<harmoniesAnimal(c.cardId).points.length),completedCards=player.cards.filter(c=>c.placed===harmoniesAnimal(c.cardId).points.length);
 const availableCards=g.animalMarket.filter(id=>id!==draft?.takenCard),marketSelected=selectedCard!==null&&availableCards.includes(selectedCard),highlight=new Set(scoreKind?score.lines.filter(l=>l.kind===scoreKind&&l.points>0).flatMap(l=>l.cells):hover!==null?matches.find(m=>m.target===hover)?.cells??[]:[]);
 function append(step:HarmoniesStep){if(!canAct)return;const next=[...steps,step],r=harmoniesReplay(me,g.markets,g.animalMarket,next);if(!r.ok){setError(r.message);props.play('ERROR');return;}setSteps(next);setError(null);if(step.type==='TAKE_TOKENS'){setTokenId(r.draft.pool[0]?.tileId??null);setSelectedCard(null);setScoreKind(null);}if(step.type==='PLACE')setTokenId(r.draft.pool[0]?.tileId??null);props.play(step.type==='SETTLE'?'ANIMAL':step.type==='TAKE_ANIMAL'?'CARD':step.type==='PLACE'?selectedToken?.color??'SELECT':'SELECT');}
 function selectCard(id:number){setSelectedCard(id);setTokenId(null);setScoreKind(null);setError(null);props.play('SELECT');}
 function place(cell:number,explicit?:TileId){if(!canAct)return;setScoreKind(null);if(explicit){setSelectedCard(null);append({type:'PLACE',tileId:explicit,cell});return;}if(selectedCard!==null&&ownSelected){const match=matches.find(m=>m.target===cell);if(match)append({type:'SETTLE',cardId:selectedCard,origin:match.origin,rotation:match.rotation});else{setError('밝게 표시된 동물 자리 중 하나를 선택하세요.');props.play('ERROR');}}else if(selectedToken)append({type:'PLACE',tileId:selectedToken.tileId,cell});}
 function undo(){if(blocked||!steps.length)return;setSteps(steps.slice(0,-1));setError(null);setTokenId(null);props.play('UNDO');}
 async function submit(){if(sending.current||!props.connected||g.phase!=='PLAYING'||(!uncertain&&!draft?.ready))return;const command=request.current??{protocolVersion:PROTOCOL_VERSION,kind:'harmonies:act' as const,requestId:createRequestId(),gameId:g.gameId,expectedGameRevision:g.gameRevision,turnId:g.turnId,payload:{type:'SUBMIT_TURN' as const,steps}};request.current=command;sending.current=true;setBusy(true);setError(null);try{await props.onCommand(command);setSteps([]);request.current=null;setUncertain(false);}catch(e){if(e instanceof HarmoniesCommandRejected){setError(e.message);setUncertain(false);request.current=null;}else{setUncertain(true);setError('결과를 아직 받지 못했어요. 같은 요청의 처리 결과를 다시 확인하세요.');}props.play('ERROR');}finally{sending.current=false;setBusy(false);}}
 const latest=g.history.at(-1),newCells=new Set(latest?.playerId===player.playerId?latest.cells:[]);
 return <>
  <div className={`hm-turn-banner ${g.activePlayerId===self&&!finished?'my-turn':''}`}><div><span className="hm-eyebrow">{finished?'A LANDSCAPE TO REMEMBER':`ROUND ${g.round} · SIDE A`}</span><h2>{finished?'완성된 우리의 풍경':g.activePlayerId===self?'당신의 풍경을 가꿀 시간':`${name(g.activePlayerId)}님의 차례`}</h2></div><span className="hm-turn-hint">{finished?'점수 항목을 누르면 계산 근거를 볼 수 있어요.':g.lastRound?'마지막 라운드 · 모두 같은 횟수의 턴을 마치면 종료해요.':'토큰 3개를 놓고, 원할 때 동물을 초대하세요.'}</span><button className="hm-rule-button" aria-expanded={rules} onClick={()=>setRules(!rules)}>놀이 방법 {rules?'닫기':'보기'}</button></div>
  {rules&&<div className="hm-rulebook"><h3>세 개의 토큰, 하나의 작은 세상</h3><ol><li>다섯 묶음 중 하나의 토큰 3개를 모두 놓습니다. 빈칸 또는 허용되는 지형 위에 놓으세요.</li><li>동물 카드는 차례마다 한 장 가져올 수 있어요. 미완성 카드는 최대 네 장입니다.</li><li>카드와 같은 모양·높이를 만들면 동물을 놓아요. 회전은 가능하고 뒤집기는 하지 않습니다.</li><li>동물 행동은 토큰 배치 사이에도 가능해요. 동물이 있는 칸에는 더 쌓을 수 없습니다.</li><li>빈칸이 2개 이하가 되거나 주머니에서 보충할 수 없으면 마지막 라운드를 마칩니다.</li></ol><p>쌓기: 돌은 3층까지 · 줄기는 2층까지, 그 위에 잎 하나 · 건물은 빨강을 줄기/돌/빨강 하나 위에.</p><p>확정 전 되돌리기는 이번 턴의 행동만 취소합니다. 상대 보드는 이름을 눌러 볼 수 있어요.</p></div>}
  <nav className="hm-player-tabs" aria-label="플레이어 보드 선택">{g.playerStates.map((p,i)=>{const total=harmoniesScore(p.board,p.cards).total;return <button key={p.playerId} aria-pressed={viewId===p.playerId} onClick={()=>{setViewId(p.playerId);setSelectedCard(null);setScoreKind(null);props.play('SELECT');}}><span className={`hm-seat-dot seat-${i}`}>{i+1}</span><span><strong>{name(p.playerId)}{p.playerId===self?' · 나':''}</strong><small>{g.activePlayerId===p.playerId&&!finished?'현재 차례 · ':''}{p.board.filter(c=>!c.stack.length).length}칸 남음</small></span><b>{total}<small>점</small></b></button>;})}</nav>
  {!finished&&<details className="hm-market-section" open><summary>공용 공급처 <span>동물 {g.deckCount}장 · 주머니 {g.bagCount}개</span></summary><div className="hm-market-layout"><div className="hm-animal-market">{availableCards.map(id=><AnimalCard key={id} id={id} selected={selectedCard===id} compact onSelect={()=>selectCard(id)}/>)}{availableCards.length===0&&<p>공개 동물 카드가 없어요.</p>}</div><div className="hm-token-market"><span className="hm-eyebrow">CHOOSE A LITTLE LANDSCAPE</span><h3>토큰 세 개를 골라요</h3><div className="hm-sources">{g.markets.map((tokens,i)=><button key={i} className={`hm-source ${draft?.source===i?'taken':''}`} aria-label={`${i+1}번 토큰 묶음: ${tokens.map(t=>HARMONIES_COLOR_NAMES[t.color]).join(', ')}`} aria-pressed={draft?.source===i} disabled={!canAct||draft?.source!==null||tokens.length!==3} onClick={()=>append({type:'TAKE_TOKENS',source:i})}>{tokens.map((t,j)=><span key={t.tileId} className={`hm-source-token pos-${j}`}><TerrainToken colors={[t.color]} size={48}/></span>)}<span className="hm-source-number">{draft?.source===i?'선택':i+1}</span></button>)}</div><small>한 묶음의 토큰을 모두 놓아요.<br/>다시 고르려면 이번 턴을 초기화하세요.</small></div></div></details>}
  {marketSelected&&selectedCard!==null&&!finished&&<div className="hm-selection-banner"><span><strong>{harmoniesAnimal(selectedCard).name}</strong> · 카드 패턴의 주황색 큐브가 동물의 자리예요.</span><button className="hm-primary" disabled={!canAct||draft?.takenCard!==null||activeCards.length>=4} onClick={()=>append({type:"TAKE_ANIMAL",cardId:selectedCard})}>{draft?.takenCard!==null?"이번 턴 카드 선택 완료":activeCards.length>=4?"진행 중인 카드가 네 장이에요":"이 동물 카드 가져오기"}</button></div>}
  {finished&&<div className="hm-results"><span className="hm-eyebrow">OUR HARMONIES</span><h2>{g.result.reason==='CANCELLED'?'플레이어가 나가 이번 게임을 마쳤어요':`${g.result.winnerPlayerIds.map(name).join(' · ')}${g.result.winnerPlayerIds.length>1?' 공동':''} 승리`}</h2><p>{g.result.reason==='SCORED'?'동점은 배치한 동물 수로 비교하고, 그것도 같으면 공동 승리입니다.':'중단된 게임에는 승자를 정하지 않습니다.'}</p>{props.snapshot.room.players.find(p=>p.playerId===self)?.isHost&&<button className="hm-primary" onClick={props.onRematch} disabled={blocked}>같은 방에서 다시 준비하기 →</button>}</div>}
  <div className="hm-workspace"><section className="hm-board-panel"><div className="hm-panel-heading"><div><span className="hm-eyebrow">YOUR LITTLE WORLD</span><h3>{viewId===self?'나의 풍경':`${name(player.playerId)}님의 풍경`}</h3></div><span>{player.board.filter(c=>!c.stack.length).length} / 23칸 비어 있음</span></div><div className="hm-board-wrap" ref={boardRef}><div className="hm-board" aria-label={`${name(player.playerId)}의 육각형 보드`}>
  {HARMONIES_CELLS.map((p,i)=>{const cell=player.board[i]!,x=62+p.q*77,y=62+(p.r+p.q/2)*89,valid=canAct&&(selectedCard!==null&&ownSelected?matches.some(m=>m.target===i):selectedToken?harmoniesCanPlace(cell,selectedToken):false),fresh=draft&&viewId===self&&steps.some(a=>a.type==='PLACE'&&a.cell===i),colors=cell.stack.map(t=>t.color);return <button key={i} type="button" className={`hm-hex ${valid?'valid':''} ${highlight.has(i)?'highlight':''} ${fresh?'draft':''} ${newCells.has(i)?'recent':''}`} style={{left:`${x/432*100}%`,top:`${y/484*100}%`}} aria-label={`${i+1}번 칸 · ${colors.length?colors.map(c=>HARMONIES_COLOR_NAMES[c]).join(' 위에 ')+` · ${colors.length}층`:'빈칸'}${cell.animal?` · ${harmoniesAnimal(cell.animal).name} 정착`:''}${valid?' · 배치 가능':''}`} aria-disabled={!canAct} onClick={()=>place(i)} onMouseEnter={()=>setHover(i)} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(i)} onBlur={()=>setHover(null)} onDragOver={e=>{if(canAct)e.preventDefault();}} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain'),token=pool.find(t=>t.tileId===id);if(token)place(i,token.tileId);}}><span className="hm-hex-face"/>{colors.length>0?<><TerrainToken key={`${cell.stack.map(t=>t.tileId).join(":")}:${cell.animal}`} colors={colors} animal={cell.animal!==null}/><span className="hm-height">{colors.length}</span>{cell.animal!==null&&<span className="hm-animal-tag">{harmoniesAnimal(cell.animal).name}</span>}</>:<span className="hm-empty-mark">{valid?'+':'·'}</span>}{valid&&selectedCard!==null&&ownSelected&&<span className="hm-settle-mark">◆</span>}</button>;})}
  </div></div><div className="hm-board-caption" role="status">{viewId!==self?'상대의 공개 보드를 보고 있어요. 내 이름을 누르면 돌아갑니다.':selectedCard!==null&&ownSelected?`${harmoniesAnimal(selectedCard).name} · 배치 가능한 자리 ${matches.length}곳${matches.length?' · 빛나는 칸을 누르세요.':' · 카드의 높이와 모양을 확인하세요.'}`:selectedToken?`${HARMONIES_COLOR_NAMES[selectedToken.color]} 토큰 · 빛나는 칸에 놓을 수 있어요.`:'토큰 묶음이나 동물 카드를 선택하세요.'}</div><div className="hm-score-strip">{(Object.keys(SCORE_LABELS) as HarmoniesScoreKind[]).map(kind=><button key={kind} aria-pressed={scoreKind===kind} onClick={()=>{setScoreKind(scoreKind===kind?null:kind);setSelectedCard(null);}}><span>{SCORE_LABELS[kind]}</span><b>{score[kind]}</b></button>)}<div className="hm-total"><span>{finished?'최종':'예상'} 총점</span><strong>{score.total}</strong>{delta!==0&&<small>{delta>0?'+':''}{delta}</small>}</div></div>{scoreKind&&<p className="hm-score-help">{SCORE_HELP[scoreKind]}</p>}</section>
  <aside className="hm-hand-panel"><div className="hm-panel-heading"><div><span className="hm-eyebrow">WELCOME THE WILD</span><h3>{viewId===self?'나의 동물들':`${name(player.playerId)}님의 동물들`}</h3></div><span>진행 중 {activeCards.length} / 4</span></div>
  {marketSelected&&selectedCard!==null&&<div className="hm-card-inspector"><strong>{harmoniesAnimal(selectedCard).name}을 초대할까요?</strong><AnimalPattern cardId={selectedCard}/><p>주황색 큐브가 표시된 칸에 동물을 놓아요. 높이와 모양이 정확히 같아야 합니다.</p><button className="hm-primary" disabled={!canAct||draft?.takenCard!==null||activeCards.length>=4} onClick={()=>append({type:'TAKE_ANIMAL',cardId:selectedCard})}>{draft?.takenCard!==null?'이번 턴 카드를 가져왔어요':activeCards.length>=4?'진행 중인 카드가 네 장이에요':'이 동물 카드 가져오기'}</button></div>}
  <div className="hm-hand-cards">{activeCards.map(c=><AnimalCard key={c.cardId} id={c.cardId} owned={c} selected={selectedCard===c.cardId} onSelect={()=>selectCard(c.cardId)}/>)}{Array.from({length:Math.max(0,4-activeCards.length)},(_,i)=><div className="hm-card-slot" key={`empty-${i}`}><span>❧</span><p>새로운 동물을<br/>기다리는 자리</p></div>)}</div>
  {completedCards.length>0&&<details className="hm-completed"><summary>완성한 동물 카드 {completedCards.length}장</summary><div className="hm-hand-cards">{completedCards.map(c=><AnimalCard key={c.cardId} id={c.cardId} owned={c} selected={selectedCard===c.cardId} onSelect={()=>selectCard(c.cardId)}/>)}</div></details>}
  </aside></div>
  {error&&<p className="hm-alert" role="alert">{error}</p>}
  {!finished&&<div className="hm-draft-bar"><div className="hm-draft-status"><span className="hm-eyebrow">{g.activePlayerId===self?'YOUR TURN':'AT THE TABLE'}</span><strong>{g.activePlayerId!==self?`${name(g.activePlayerId)}님의 풍경을 기다려요`:draft?.source===null?'토큰 묶음을 선택하세요':pool.length?`토큰 ${pool.length}개를 더 놓으세요`:'배치 완료 · 동물을 더 놓거나 확정하세요'}</strong></div><div className="hm-token-hand">{pool.map(t=><button key={t.tileId} className="hm-hand-token" draggable={canAct} aria-label={`${HARMONIES_COLOR_NAMES[t.color]} 토큰 선택`} aria-pressed={selectedCard===null&&selectedToken?.tileId===t.tileId} disabled={!canAct} onDragStart={e=>{e.dataTransfer.setData('text/plain',t.tileId);setSelectedCard(null);setTokenId(t.tileId);}} onClick={()=>{setTokenId(t.tileId);setSelectedCard(null);setScoreKind(null);props.play('SELECT');boardRef.current?.scrollIntoView({block:'nearest',behavior:'auto'});}}><TerrainToken colors={[t.color]} size={52}/></button>)}</div><div className="hm-draft-actions"><button onClick={undo} disabled={blocked||!steps.length||g.activePlayerId!==self}>↶ 한 수 되돌리기</button><button onClick={()=>{setSteps([]);setSelectedCard(null);setError(null);setTokenId(null);props.play('UNDO');}} disabled={blocked||!steps.length}>초기화</button><button className="hm-primary" disabled={props.pending||busy||!props.connected||g.activePlayerId!==self||(!draft?.ready&&!uncertain)} onClick={()=>void submit()}>{busy?'처리 중…':uncertain?'처리 결과 다시 확인':'턴 확정 →'}</button></div></div>}
  <details className="hm-history"><summary>숲의 기록 · {g.history.length}턴</summary><ol>{g.history.slice().reverse().map(l=><li key={l.id}><strong>{name(l.playerId)}</strong> {l.text}</li>)}</ol></details>
 </>;
}
