/** Original schematic Japan map; ordinary USA rules, including all island links.
 * Not the official Japan expansion or an actual railway timetable. */
import type { TrainCity, TrainRoute, TrainTicket } from "./catalog.js";
export const JAPAN_CITIES: readonly TrainCity[] = [
    {"cityId": "jp-sapporo", "name": "Sapporo", "label": "삿포로", "x": 920, "y": 100},
    {"cityId": "jp-asahikawa", "name": "Asahikawa", "label": "아사히카와", "x": 1060, "y": 130},
    {"cityId": "jp-hakodate", "name": "Hakodate", "label": "하코다테", "x": 850, "y": 240},
    {"cityId": "jp-aomori", "name": "Aomori", "label": "아오모리", "x": 800, "y": 350},
    {"cityId": "jp-akita", "name": "Akita", "label": "아키타", "x": 690, "y": 460},
    {"cityId": "jp-morioka", "name": "Morioka", "label": "모리오카", "x": 920, "y": 410},
    {"cityId": "jp-sendai", "name": "Sendai", "label": "센다이", "x": 900, "y": 540},
    {"cityId": "jp-niigata", "name": "Niigata", "label": "니가타", "x": 650, "y": 600},
    {"cityId": "jp-fukushima", "name": "Fukushima", "label": "후쿠시마", "x": 820, "y": 630},
    {"cityId": "jp-tokyo", "name": "Tokyo", "label": "도쿄", "x": 980, "y": 740},
    {"cityId": "jp-yokohama", "name": "Yokohama", "label": "요코하마", "x": 1000, "y": 860},
    {"cityId": "jp-nagano", "name": "Nagano", "label": "나가노", "x": 730, "y": 740},
    {"cityId": "jp-kanazawa", "name": "Kanazawa", "label": "가나자와", "x": 480, "y": 640},
    {"cityId": "jp-shizuoka", "name": "Shizuoka", "label": "시즈오카", "x": 830, "y": 890},
    {"cityId": "jp-nagoya", "name": "Nagoya", "label": "나고야", "x": 670, "y": 890},
    {"cityId": "jp-kyoto", "name": "Kyoto", "label": "교토", "x": 530, "y": 810},
    {"cityId": "jp-osaka", "name": "Osaka", "label": "오사카", "x": 480, "y": 940},
    {"cityId": "jp-kobe", "name": "Kobe", "label": "고베", "x": 350, "y": 910},
    {"cityId": "jp-tottori", "name": "Tottori", "label": "돗토리", "x": 320, "y": 730},
    {"cityId": "jp-okayama", "name": "Okayama", "label": "오카야마", "x": 270, "y": 880},
    {"cityId": "jp-hiroshima", "name": "Hiroshima", "label": "히로시마", "x": 150, "y": 920},
    {"cityId": "jp-shimonoseki", "name": "Shimonoseki", "label": "시모노세키", "x": 130, "y": 1050},
    {"cityId": "jp-fukuoka", "name": "Fukuoka", "label": "후쿠오카", "x": 200, "y": 1180},
    {"cityId": "jp-nagasaki", "name": "Nagasaki", "label": "나가사키", "x": 80, "y": 1300},
    {"cityId": "jp-kumamoto", "name": "Kumamoto", "label": "구마모토", "x": 270, "y": 1300},
    {"cityId": "jp-kagoshima", "name": "Kagoshima", "label": "가고시마", "x": 340, "y": 1430},
    {"cityId": "jp-oita", "name": "Oita", "label": "오이타", "x": 390, "y": 1160},
    {"cityId": "jp-matsuyama", "name": "Matsuyama", "label": "마쓰야마", "x": 470, "y": 1090},
    {"cityId": "jp-takamatsu", "name": "Takamatsu", "label": "다카마쓰", "x": 570, "y": 1010},
    {"cityId": "jp-kochi", "name": "Kochi", "label": "고치", "x": 620, "y": 1210},
    {"cityId": "jp-tokushima", "name": "Tokushima", "label": "도쿠시마", "x": 750, "y": 1090},
    {"cityId": "jp-himeji", "name": "Himeji", "label": "히메지", "x": 360, "y": 810},
];
export const JAPAN_ROUTES: readonly TrainRoute[] = [
    {"routeId": "jp-asahikawa--sapporo-1", "a": "jp-sapporo", "b": "jp-asahikawa", "length": 2, "color": "GRAY", "group": "jp-asahikawa--sapporo", "lane": 0},
    {"routeId": "jp-hakodate--sapporo-1", "a": "jp-sapporo", "b": "jp-hakodate", "length": 3, "color": "BLUE", "group": "jp-hakodate--sapporo", "lane": 0},
    {"routeId": "jp-asahikawa--hakodate-1", "a": "jp-asahikawa", "b": "jp-hakodate", "length": 4, "color": "RED", "group": "jp-asahikawa--hakodate", "lane": 0},
    {"routeId": "jp-aomori--hakodate-1", "a": "jp-hakodate", "b": "jp-aomori", "length": 3, "color": "GRAY", "group": "jp-aomori--hakodate", "lane": 0},
    {"routeId": "jp-aomori--hakodate-2", "a": "jp-hakodate", "b": "jp-aomori", "length": 3, "color": "GRAY", "group": "jp-aomori--hakodate", "lane": 1},
    {"routeId": "jp-akita--hakodate-1", "a": "jp-hakodate", "b": "jp-akita", "length": 6, "color": "WHITE", "group": "jp-akita--hakodate", "lane": 0},
    {"routeId": "jp-akita--aomori-1", "a": "jp-aomori", "b": "jp-akita", "length": 3, "color": "GREEN", "group": "jp-akita--aomori", "lane": 0},
    {"routeId": "jp-aomori--morioka-1", "a": "jp-aomori", "b": "jp-morioka", "length": 2, "color": "ORANGE", "group": "jp-aomori--morioka", "lane": 0},
    {"routeId": "jp-aomori--morioka-2", "a": "jp-aomori", "b": "jp-morioka", "length": 2, "color": "ORANGE", "group": "jp-aomori--morioka", "lane": 1},
    {"routeId": "jp-akita--morioka-1", "a": "jp-akita", "b": "jp-morioka", "length": 4, "color": "BLACK", "group": "jp-akita--morioka", "lane": 0},
    {"routeId": "jp-akita--niigata-1", "a": "jp-akita", "b": "jp-niigata", "length": 3, "color": "YELLOW", "group": "jp-akita--niigata", "lane": 0},
    {"routeId": "jp-morioka--sendai-1", "a": "jp-morioka", "b": "jp-sendai", "length": 3, "color": "WHITE", "group": "jp-morioka--sendai", "lane": 0},
    {"routeId": "jp-morioka--sendai-2", "a": "jp-morioka", "b": "jp-sendai", "length": 3, "color": "PURPLE", "group": "jp-morioka--sendai", "lane": 1},
    {"routeId": "jp-akita--sendai-1", "a": "jp-akita", "b": "jp-sendai", "length": 4, "color": "BLUE", "group": "jp-akita--sendai", "lane": 0},
    {"routeId": "jp-fukushima--sendai-1", "a": "jp-sendai", "b": "jp-fukushima", "length": 2, "color": "GRAY", "group": "jp-fukushima--sendai", "lane": 0},
    {"routeId": "jp-fukushima--sendai-2", "a": "jp-sendai", "b": "jp-fukushima", "length": 2, "color": "GRAY", "group": "jp-fukushima--sendai", "lane": 1},
    {"routeId": "jp-fukushima--niigata-1", "a": "jp-niigata", "b": "jp-fukushima", "length": 3, "color": "PURPLE", "group": "jp-fukushima--niigata", "lane": 0},
    {"routeId": "jp-kanazawa--niigata-1", "a": "jp-niigata", "b": "jp-kanazawa", "length": 4, "color": "RED", "group": "jp-kanazawa--niigata", "lane": 0},
    {"routeId": "jp-nagano--niigata-1", "a": "jp-niigata", "b": "jp-nagano", "length": 3, "color": "BLACK", "group": "jp-nagano--niigata", "lane": 0},
    {"routeId": "jp-fukushima--nagano-1", "a": "jp-fukushima", "b": "jp-nagano", "length": 3, "color": "GREEN", "group": "jp-fukushima--nagano", "lane": 0},
    {"routeId": "jp-fukushima--tokyo-1", "a": "jp-fukushima", "b": "jp-tokyo", "length": 4, "color": "YELLOW", "group": "jp-fukushima--tokyo", "lane": 0},
    {"routeId": "jp-fukushima--tokyo-2", "a": "jp-fukushima", "b": "jp-tokyo", "length": 4, "color": "BLUE", "group": "jp-fukushima--tokyo", "lane": 1},
    {"routeId": "jp-sendai--tokyo-1", "a": "jp-sendai", "b": "jp-tokyo", "length": 6, "color": "BLACK", "group": "jp-sendai--tokyo", "lane": 0},
    {"routeId": "jp-tokyo--yokohama-1", "a": "jp-tokyo", "b": "jp-yokohama", "length": 2, "color": "GRAY", "group": "jp-tokyo--yokohama", "lane": 0},
    {"routeId": "jp-tokyo--yokohama-2", "a": "jp-tokyo", "b": "jp-yokohama", "length": 2, "color": "GRAY", "group": "jp-tokyo--yokohama", "lane": 1},
    {"routeId": "jp-nagano--tokyo-1", "a": "jp-tokyo", "b": "jp-nagano", "length": 4, "color": "ORANGE", "group": "jp-nagano--tokyo", "lane": 0},
    {"routeId": "jp-kanazawa--nagano-1", "a": "jp-nagano", "b": "jp-kanazawa", "length": 4, "color": "WHITE", "group": "jp-kanazawa--nagano", "lane": 0},
    {"routeId": "jp-nagano--nagoya-1", "a": "jp-nagano", "b": "jp-nagoya", "length": 3, "color": "YELLOW", "group": "jp-nagano--nagoya", "lane": 0},
    {"routeId": "jp-nagano--shizuoka-1", "a": "jp-nagano", "b": "jp-shizuoka", "length": 3, "color": "RED", "group": "jp-nagano--shizuoka", "lane": 0},
    {"routeId": "jp-shizuoka--yokohama-1", "a": "jp-yokohama", "b": "jp-shizuoka", "length": 3, "color": "GREEN", "group": "jp-shizuoka--yokohama", "lane": 0},
    {"routeId": "jp-nagoya--shizuoka-1", "a": "jp-shizuoka", "b": "jp-nagoya", "length": 3, "color": "BLUE", "group": "jp-nagoya--shizuoka", "lane": 0},
    {"routeId": "jp-nagoya--shizuoka-2", "a": "jp-shizuoka", "b": "jp-nagoya", "length": 3, "color": "WHITE", "group": "jp-nagoya--shizuoka", "lane": 1},
    {"routeId": "jp-kanazawa--kyoto-1", "a": "jp-kanazawa", "b": "jp-kyoto", "length": 3, "color": "PURPLE", "group": "jp-kanazawa--kyoto", "lane": 0},
    {"routeId": "jp-kanazawa--tottori-1", "a": "jp-kanazawa", "b": "jp-tottori", "length": 3, "color": "GREEN", "group": "jp-kanazawa--tottori", "lane": 0},
    {"routeId": "jp-kyoto--nagoya-1", "a": "jp-kyoto", "b": "jp-nagoya", "length": 3, "color": "GRAY", "group": "jp-kyoto--nagoya", "lane": 0},
    {"routeId": "jp-kyoto--nagoya-2", "a": "jp-kyoto", "b": "jp-nagoya", "length": 3, "color": "GRAY", "group": "jp-kyoto--nagoya", "lane": 1},
    {"routeId": "jp-kyoto--osaka-1", "a": "jp-kyoto", "b": "jp-osaka", "length": 2, "color": "ORANGE", "group": "jp-kyoto--osaka", "lane": 0},
    {"routeId": "jp-kyoto--osaka-2", "a": "jp-kyoto", "b": "jp-osaka", "length": 2, "color": "BLACK", "group": "jp-kyoto--osaka", "lane": 1},
    {"routeId": "jp-nagoya--osaka-1", "a": "jp-nagoya", "b": "jp-osaka", "length": 4, "color": "RED", "group": "jp-nagoya--osaka", "lane": 0},
    {"routeId": "jp-himeji--kyoto-1", "a": "jp-kyoto", "b": "jp-himeji", "length": 3, "color": "YELLOW", "group": "jp-himeji--kyoto", "lane": 0},
    {"routeId": "jp-himeji--tottori-1", "a": "jp-himeji", "b": "jp-tottori", "length": 2, "color": "GRAY", "group": "jp-himeji--tottori", "lane": 0},
    {"routeId": "jp-himeji--kobe-1", "a": "jp-himeji", "b": "jp-kobe", "length": 2, "color": "BLUE", "group": "jp-himeji--kobe", "lane": 0},
    {"routeId": "jp-himeji--okayama-1", "a": "jp-himeji", "b": "jp-okayama", "length": 2, "color": "GREEN", "group": "jp-himeji--okayama", "lane": 0},
    {"routeId": "jp-kobe--osaka-1", "a": "jp-osaka", "b": "jp-kobe", "length": 2, "color": "GRAY", "group": "jp-kobe--osaka", "lane": 0},
    {"routeId": "jp-kobe--osaka-2", "a": "jp-osaka", "b": "jp-kobe", "length": 2, "color": "GRAY", "group": "jp-kobe--osaka", "lane": 1},
    {"routeId": "jp-kobe--okayama-1", "a": "jp-kobe", "b": "jp-okayama", "length": 2, "color": "WHITE", "group": "jp-kobe--okayama", "lane": 0},
    {"routeId": "jp-osaka--takamatsu-1", "a": "jp-osaka", "b": "jp-takamatsu", "length": 3, "color": "GREEN", "group": "jp-osaka--takamatsu", "lane": 0},
    {"routeId": "jp-osaka--tokushima-1", "a": "jp-osaka", "b": "jp-tokushima", "length": 5, "color": "PURPLE", "group": "jp-osaka--tokushima", "lane": 0},
    {"routeId": "jp-okayama--tottori-1", "a": "jp-tottori", "b": "jp-okayama", "length": 3, "color": "ORANGE", "group": "jp-okayama--tottori", "lane": 0},
    {"routeId": "jp-hiroshima--tottori-1", "a": "jp-tottori", "b": "jp-hiroshima", "length": 4, "color": "BLUE", "group": "jp-hiroshima--tottori", "lane": 0},
    {"routeId": "jp-hiroshima--okayama-1", "a": "jp-okayama", "b": "jp-hiroshima", "length": 2, "color": "GRAY", "group": "jp-hiroshima--okayama", "lane": 0},
    {"routeId": "jp-hiroshima--okayama-2", "a": "jp-okayama", "b": "jp-hiroshima", "length": 2, "color": "GRAY", "group": "jp-hiroshima--okayama", "lane": 1},
    {"routeId": "jp-hiroshima--shimonoseki-1", "a": "jp-hiroshima", "b": "jp-shimonoseki", "length": 3, "color": "RED", "group": "jp-hiroshima--shimonoseki", "lane": 0},
    {"routeId": "jp-hiroshima--shimonoseki-2", "a": "jp-hiroshima", "b": "jp-shimonoseki", "length": 3, "color": "BLACK", "group": "jp-hiroshima--shimonoseki", "lane": 1},
    {"routeId": "jp-matsuyama--okayama-1", "a": "jp-okayama", "b": "jp-matsuyama", "length": 5, "color": "WHITE", "group": "jp-matsuyama--okayama", "lane": 0},
    {"routeId": "jp-kobe--takamatsu-1", "a": "jp-kobe", "b": "jp-takamatsu", "length": 4, "color": "YELLOW", "group": "jp-kobe--takamatsu", "lane": 0},
    {"routeId": "jp-hiroshima--matsuyama-1", "a": "jp-hiroshima", "b": "jp-matsuyama", "length": 6, "color": "ORANGE", "group": "jp-hiroshima--matsuyama", "lane": 0},
    {"routeId": "jp-fukuoka--shimonoseki-1", "a": "jp-shimonoseki", "b": "jp-fukuoka", "length": 3, "color": "GRAY", "group": "jp-fukuoka--shimonoseki", "lane": 0},
    {"routeId": "jp-fukuoka--shimonoseki-2", "a": "jp-shimonoseki", "b": "jp-fukuoka", "length": 3, "color": "GRAY", "group": "jp-fukuoka--shimonoseki", "lane": 1},
    {"routeId": "jp-oita--shimonoseki-1", "a": "jp-shimonoseki", "b": "jp-oita", "length": 5, "color": "PURPLE", "group": "jp-oita--shimonoseki", "lane": 0},
    {"routeId": "jp-fukuoka--nagasaki-1", "a": "jp-fukuoka", "b": "jp-nagasaki", "length": 3, "color": "YELLOW", "group": "jp-fukuoka--nagasaki", "lane": 0},
    {"routeId": "jp-fukuoka--kumamoto-1", "a": "jp-fukuoka", "b": "jp-kumamoto", "length": 2, "color": "RED", "group": "jp-fukuoka--kumamoto", "lane": 0},
    {"routeId": "jp-fukuoka--kumamoto-2", "a": "jp-fukuoka", "b": "jp-kumamoto", "length": 2, "color": "GREEN", "group": "jp-fukuoka--kumamoto", "lane": 1},
    {"routeId": "jp-fukuoka--oita-1", "a": "jp-fukuoka", "b": "jp-oita", "length": 3, "color": "BLUE", "group": "jp-fukuoka--oita", "lane": 0},
    {"routeId": "jp-kumamoto--nagasaki-1", "a": "jp-nagasaki", "b": "jp-kumamoto", "length": 3, "color": "WHITE", "group": "jp-kumamoto--nagasaki", "lane": 0},
    {"routeId": "jp-kagoshima--kumamoto-1", "a": "jp-kumamoto", "b": "jp-kagoshima", "length": 3, "color": "BLACK", "group": "jp-kagoshima--kumamoto", "lane": 0},
    {"routeId": "jp-kumamoto--oita-1", "a": "jp-kumamoto", "b": "jp-oita", "length": 3, "color": "ORANGE", "group": "jp-kumamoto--oita", "lane": 0},
    {"routeId": "jp-kagoshima--oita-1", "a": "jp-oita", "b": "jp-kagoshima", "length": 5, "color": "GREEN", "group": "jp-kagoshima--oita", "lane": 0},
    {"routeId": "jp-matsuyama--oita-1", "a": "jp-oita", "b": "jp-matsuyama", "length": 3, "color": "GRAY", "group": "jp-matsuyama--oita", "lane": 0},
    {"routeId": "jp-matsuyama--takamatsu-1", "a": "jp-matsuyama", "b": "jp-takamatsu", "length": 2, "color": "RED", "group": "jp-matsuyama--takamatsu", "lane": 0},
    {"routeId": "jp-kochi--matsuyama-1", "a": "jp-matsuyama", "b": "jp-kochi", "length": 3, "color": "BLUE", "group": "jp-kochi--matsuyama", "lane": 0},
    {"routeId": "jp-kochi--tokushima-1", "a": "jp-kochi", "b": "jp-tokushima", "length": 3, "color": "YELLOW", "group": "jp-kochi--tokushima", "lane": 0},
    {"routeId": "jp-takamatsu--tokushima-1", "a": "jp-takamatsu", "b": "jp-tokushima", "length": 3, "color": "WHITE", "group": "jp-takamatsu--tokushima", "lane": 0},
    {"routeId": "jp-kochi--takamatsu-1", "a": "jp-takamatsu", "b": "jp-kochi", "length": 4, "color": "BLACK", "group": "jp-kochi--takamatsu", "lane": 0},
    {"routeId": "jp-kagoshima--nagasaki-1", "a": "jp-nagasaki", "b": "jp-kagoshima", "length": 5, "color": "PURPLE", "group": "jp-kagoshima--nagasaki", "lane": 0},
];
export const JAPAN_TICKETS: readonly TrainTicket[] = [
    {"ticketId": "jp-ticket-01", "a": "jp-sapporo", "b": "jp-osaka", "points": 21},
    {"ticketId": "jp-ticket-02", "a": "jp-asahikawa", "b": "jp-niigata", "points": 13},
    {"ticketId": "jp-ticket-03", "a": "jp-hakodate", "b": "jp-sendai", "points": 8},
    {"ticketId": "jp-ticket-04", "a": "jp-aomori", "b": "jp-kanazawa", "points": 10},
    {"ticketId": "jp-ticket-05", "a": "jp-akita", "b": "jp-nagoya", "points": 9},
    {"ticketId": "jp-ticket-06", "a": "jp-morioka", "b": "jp-tokyo", "points": 9},
    {"ticketId": "jp-ticket-07", "a": "jp-sendai", "b": "jp-yokohama", "points": 8},
    {"ticketId": "jp-ticket-08", "a": "jp-niigata", "b": "jp-osaka", "points": 9},
    {"ticketId": "jp-ticket-09", "a": "jp-fukushima", "b": "jp-kyoto", "points": 9},
    {"ticketId": "jp-ticket-10", "a": "jp-tokyo", "b": "jp-hiroshima", "points": 15},
    {"ticketId": "jp-ticket-11", "a": "jp-yokohama", "b": "jp-kobe", "points": 12},
    {"ticketId": "jp-ticket-12", "a": "jp-nagano", "b": "jp-okayama", "points": 10},
    {"ticketId": "jp-ticket-13", "a": "jp-kanazawa", "b": "jp-shimonoseki", "points": 10},
    {"ticketId": "jp-ticket-14", "a": "jp-shizuoka", "b": "jp-takamatsu", "points": 10},
    {"ticketId": "jp-ticket-15", "a": "jp-nagoya", "b": "jp-fukuoka", "points": 15},
    {"ticketId": "jp-ticket-16", "a": "jp-kyoto", "b": "jp-matsuyama", "points": 7},
    {"ticketId": "jp-ticket-17", "a": "jp-osaka", "b": "jp-kagoshima", "points": 13},
    {"ticketId": "jp-ticket-18", "a": "jp-kobe", "b": "jp-nagasaki", "points": 13},
    {"ticketId": "jp-ticket-19", "a": "jp-tottori", "b": "jp-oita", "points": 11},
    {"ticketId": "jp-ticket-20", "a": "jp-okayama", "b": "jp-kumamoto", "points": 10},
    {"ticketId": "jp-ticket-21", "a": "jp-hiroshima", "b": "jp-kochi", "points": 9},
    {"ticketId": "jp-ticket-22", "a": "jp-shimonoseki", "b": "jp-tokushima", "points": 13},
    {"ticketId": "jp-ticket-23", "a": "jp-fukuoka", "b": "jp-kagoshima", "points": 5},
    {"ticketId": "jp-ticket-24", "a": "jp-nagasaki", "b": "jp-oita", "points": 6},
    {"ticketId": "jp-ticket-25", "a": "jp-kumamoto", "b": "jp-matsuyama", "points": 6},
    {"ticketId": "jp-ticket-26", "a": "jp-matsuyama", "b": "jp-tokushima", "points": 5},
    {"ticketId": "jp-ticket-27", "a": "jp-takamatsu", "b": "jp-kagoshima", "points": 10},
    {"ticketId": "jp-ticket-28", "a": "jp-himeji", "b": "jp-shizuoka", "points": 9},
    {"ticketId": "jp-ticket-29", "a": "jp-sapporo", "b": "jp-akita", "points": 9},
    {"ticketId": "jp-ticket-30", "a": "jp-aomori", "b": "jp-fukushima", "points": 7},
];
