/** Original Korean mainland map. Not the official South Korea expansion.
 * Coordinates are schematic; tickets score the shortest train-distance on this graph.
 * Design and balancing decisions: docs/TRAIN_GAME_RULES.md.
 */
import type { TrainCity, TrainRoute, TrainTicket } from './catalog.js';
export const KOREA_CITIES: readonly TrainCity[] = [
    {"cityId": "kr-paju", "name": "Paju", "label": "파주", "x": 190, "y": 145},
    {"cityId": "kr-incheon", "name": "Incheon", "label": "인천", "x": 150, "y": 295},
    {"cityId": "kr-seoul", "name": "Seoul", "label": "서울", "x": 320, "y": 255},
    {"cityId": "kr-suwon", "name": "Suwon", "label": "수원", "x": 305, "y": 385},
    {"cityId": "kr-chuncheon", "name": "Chuncheon", "label": "춘천", "x": 490, "y": 155},
    {"cityId": "kr-sokcho", "name": "Sokcho", "label": "속초", "x": 695, "y": 105},
    {"cityId": "kr-gangneung", "name": "Gangneung", "label": "강릉", "x": 795, "y": 265},
    {"cityId": "kr-wonju", "name": "Wonju", "label": "원주", "x": 570, "y": 340},
    {"cityId": "kr-jecheon", "name": "Jecheon", "label": "제천", "x": 695, "y": 435},
    {"cityId": "kr-yeongju", "name": "Yeongju", "label": "영주", "x": 815, "y": 480},
    {"cityId": "kr-seosan", "name": "Seosan", "label": "서산", "x": 155, "y": 475},
    {"cityId": "kr-cheonan", "name": "Cheonan", "label": "천안", "x": 355, "y": 500},
    {"cityId": "kr-cheongju", "name": "Cheongju", "label": "청주", "x": 525, "y": 530},
    {"cityId": "kr-daejeon", "name": "Daejeon", "label": "대전", "x": 450, "y": 655},
    {"cityId": "kr-gunsan", "name": "Gunsan", "label": "군산", "x": 210, "y": 700},
    {"cityId": "kr-jeonju", "name": "Jeonju", "label": "전주", "x": 305, "y": 790},
    {"cityId": "kr-namwon", "name": "Namwon", "label": "남원", "x": 485, "y": 850},
    {"cityId": "kr-gwangju", "name": "Gwangju", "label": "광주", "x": 215, "y": 945},
    {"cityId": "kr-mokpo", "name": "Mokpo", "label": "목포", "x": 105, "y": 1055},
    {"cityId": "kr-suncheon", "name": "Suncheon", "label": "순천", "x": 460, "y": 1060},
    {"cityId": "kr-yeosu", "name": "Yeosu", "label": "여수", "x": 580, "y": 1140},
    {"cityId": "kr-jinju", "name": "Jinju", "label": "진주", "x": 645, "y": 940},
    {"cityId": "kr-changwon", "name": "Changwon", "label": "창원", "x": 800, "y": 995},
    {"cityId": "kr-busan", "name": "Busan", "label": "부산", "x": 965, "y": 1015},
    {"cityId": "kr-ulsan", "name": "Ulsan", "label": "울산", "x": 1000, "y": 875},
    {"cityId": "kr-gyeongju", "name": "Gyeongju", "label": "경주", "x": 955, "y": 745},
    {"cityId": "kr-pohang", "name": "Pohang", "label": "포항", "x": 1040, "y": 635},
    {"cityId": "kr-daegu", "name": "Daegu", "label": "대구", "x": 800, "y": 780},
    {"cityId": "kr-andong", "name": "Andong", "label": "안동", "x": 820, "y": 605},
    {"cityId": "kr-gimcheon", "name": "Gimcheon", "label": "김천", "x": 640, "y": 700},
];
export const KOREA_ROUTES: readonly TrainRoute[] = [
    {"routeId": "kr-paju--seoul-1", "a": "kr-paju", "b": "kr-seoul", "length": 2, "color": "GRAY", "group": "kr-paju--seoul", "lane": 0},
    {"routeId": "kr-paju--seoul-2", "a": "kr-paju", "b": "kr-seoul", "length": 2, "color": "GRAY", "group": "kr-paju--seoul", "lane": 1},
    {"routeId": "kr-incheon--paju-1", "a": "kr-paju", "b": "kr-incheon", "length": 3, "color": "GREEN", "group": "kr-incheon--paju", "lane": 0},
    {"routeId": "kr-chuncheon--paju-1", "a": "kr-paju", "b": "kr-chuncheon", "length": 5, "color": "WHITE", "group": "kr-chuncheon--paju", "lane": 0},
    {"routeId": "kr-incheon--seoul-1", "a": "kr-seoul", "b": "kr-incheon", "length": 2, "color": "GRAY", "group": "kr-incheon--seoul", "lane": 0},
    {"routeId": "kr-incheon--seoul-2", "a": "kr-seoul", "b": "kr-incheon", "length": 2, "color": "GRAY", "group": "kr-incheon--seoul", "lane": 1},
    {"routeId": "kr-seoul--suwon-1", "a": "kr-seoul", "b": "kr-suwon", "length": 2, "color": "RED", "group": "kr-seoul--suwon", "lane": 0},
    {"routeId": "kr-seoul--suwon-2", "a": "kr-seoul", "b": "kr-suwon", "length": 2, "color": "YELLOW", "group": "kr-seoul--suwon", "lane": 1},
    {"routeId": "kr-chuncheon--seoul-1", "a": "kr-seoul", "b": "kr-chuncheon", "length": 3, "color": "BLUE", "group": "kr-chuncheon--seoul", "lane": 0},
    {"routeId": "kr-seoul--wonju-1", "a": "kr-seoul", "b": "kr-wonju", "length": 4, "color": "PURPLE", "group": "kr-seoul--wonju", "lane": 0},
    {"routeId": "kr-suwon--wonju-1", "a": "kr-suwon", "b": "kr-wonju", "length": 4, "color": "ORANGE", "group": "kr-suwon--wonju", "lane": 0},
    {"routeId": "kr-chuncheon--sokcho-1", "a": "kr-chuncheon", "b": "kr-sokcho", "length": 4, "color": "YELLOW", "group": "kr-chuncheon--sokcho", "lane": 0},
    {"routeId": "kr-chuncheon--gangneung-1", "a": "kr-chuncheon", "b": "kr-gangneung", "length": 5, "color": "GREEN", "group": "kr-chuncheon--gangneung", "lane": 0},
    {"routeId": "kr-chuncheon--wonju-1", "a": "kr-chuncheon", "b": "kr-wonju", "length": 3, "color": "GRAY", "group": "kr-chuncheon--wonju", "lane": 0},
    {"routeId": "kr-gangneung--sokcho-1", "a": "kr-sokcho", "b": "kr-gangneung", "length": 3, "color": "RED", "group": "kr-gangneung--sokcho", "lane": 0},
    {"routeId": "kr-cheonan--suwon-1", "a": "kr-suwon", "b": "kr-cheonan", "length": 2, "color": "GRAY", "group": "kr-cheonan--suwon", "lane": 0},
    {"routeId": "kr-cheonan--suwon-2", "a": "kr-suwon", "b": "kr-cheonan", "length": 2, "color": "GRAY", "group": "kr-cheonan--suwon", "lane": 1},
    {"routeId": "kr-incheon--seosan-1", "a": "kr-incheon", "b": "kr-seosan", "length": 4, "color": "BLACK", "group": "kr-incheon--seosan", "lane": 0},
    {"routeId": "kr-seosan--suwon-1", "a": "kr-seosan", "b": "kr-suwon", "length": 3, "color": "WHITE", "group": "kr-seosan--suwon", "lane": 0},
    {"routeId": "kr-cheonan--seosan-1", "a": "kr-seosan", "b": "kr-cheonan", "length": 3, "color": "ORANGE", "group": "kr-cheonan--seosan", "lane": 0},
    {"routeId": "kr-gunsan--seosan-1", "a": "kr-seosan", "b": "kr-gunsan", "length": 5, "color": "BLUE", "group": "kr-gunsan--seosan", "lane": 0},
    {"routeId": "kr-cheonan--cheongju-1", "a": "kr-cheonan", "b": "kr-cheongju", "length": 2, "color": "GRAY", "group": "kr-cheonan--cheongju", "lane": 0},
    {"routeId": "kr-cheonan--daejeon-1", "a": "kr-cheonan", "b": "kr-daejeon", "length": 3, "color": "GREEN", "group": "kr-cheonan--daejeon", "lane": 0},
    {"routeId": "kr-cheonan--daejeon-2", "a": "kr-cheonan", "b": "kr-daejeon", "length": 3, "color": "WHITE", "group": "kr-cheonan--daejeon", "lane": 1},
    {"routeId": "kr-cheonan--gunsan-1", "a": "kr-cheonan", "b": "kr-gunsan", "length": 4, "color": "PURPLE", "group": "kr-cheonan--gunsan", "lane": 0},
    {"routeId": "kr-jecheon--wonju-1", "a": "kr-wonju", "b": "kr-jecheon", "length": 2, "color": "GRAY", "group": "kr-jecheon--wonju", "lane": 0},
    {"routeId": "kr-cheongju--wonju-1", "a": "kr-wonju", "b": "kr-cheongju", "length": 3, "color": "RED", "group": "kr-cheongju--wonju", "lane": 0},
    {"routeId": "kr-gangneung--wonju-1", "a": "kr-wonju", "b": "kr-gangneung", "length": 4, "color": "BLACK", "group": "kr-gangneung--wonju", "lane": 0},
    {"routeId": "kr-gangneung--yeongju-1", "a": "kr-gangneung", "b": "kr-yeongju", "length": 4, "color": "WHITE", "group": "kr-gangneung--yeongju", "lane": 0},
    {"routeId": "kr-jecheon--yeongju-1", "a": "kr-jecheon", "b": "kr-yeongju", "length": 2, "color": "GRAY", "group": "kr-jecheon--yeongju", "lane": 0},
    {"routeId": "kr-cheongju--jecheon-1", "a": "kr-jecheon", "b": "kr-cheongju", "length": 3, "color": "YELLOW", "group": "kr-cheongju--jecheon", "lane": 0},
    {"routeId": "kr-andong--jecheon-1", "a": "kr-jecheon", "b": "kr-andong", "length": 3, "color": "PURPLE", "group": "kr-andong--jecheon", "lane": 0},
    {"routeId": "kr-cheongju--daejeon-1", "a": "kr-cheongju", "b": "kr-daejeon", "length": 2, "color": "BLUE", "group": "kr-cheongju--daejeon", "lane": 0},
    {"routeId": "kr-cheongju--daejeon-2", "a": "kr-cheongju", "b": "kr-daejeon", "length": 2, "color": "ORANGE", "group": "kr-cheongju--daejeon", "lane": 1},
    {"routeId": "kr-cheongju--gimcheon-1", "a": "kr-cheongju", "b": "kr-gimcheon", "length": 3, "color": "WHITE", "group": "kr-cheongju--gimcheon", "lane": 0},
    {"routeId": "kr-andong--yeongju-1", "a": "kr-yeongju", "b": "kr-andong", "length": 2, "color": "GRAY", "group": "kr-andong--yeongju", "lane": 0},
    {"routeId": "kr-pohang--yeongju-1", "a": "kr-yeongju", "b": "kr-pohang", "length": 4, "color": "ORANGE", "group": "kr-pohang--yeongju", "lane": 0},
    {"routeId": "kr-andong--gimcheon-1", "a": "kr-andong", "b": "kr-gimcheon", "length": 3, "color": "RED", "group": "kr-andong--gimcheon", "lane": 0},
    {"routeId": "kr-andong--daegu-1", "a": "kr-andong", "b": "kr-daegu", "length": 3, "color": "BLACK", "group": "kr-andong--daegu", "lane": 0},
    {"routeId": "kr-andong--pohang-1", "a": "kr-andong", "b": "kr-pohang", "length": 3, "color": "GREEN", "group": "kr-andong--pohang", "lane": 0},
    {"routeId": "kr-gyeongju--pohang-1", "a": "kr-pohang", "b": "kr-gyeongju", "length": 2, "color": "GRAY", "group": "kr-gyeongju--pohang", "lane": 0},
    {"routeId": "kr-gyeongju--pohang-2", "a": "kr-pohang", "b": "kr-gyeongju", "length": 2, "color": "GRAY", "group": "kr-gyeongju--pohang", "lane": 1},
    {"routeId": "kr-daegu--gyeongju-1", "a": "kr-gyeongju", "b": "kr-daegu", "length": 3, "color": "YELLOW", "group": "kr-daegu--gyeongju", "lane": 0},
    {"routeId": "kr-gyeongju--ulsan-1", "a": "kr-gyeongju", "b": "kr-ulsan", "length": 2, "color": "BLUE", "group": "kr-gyeongju--ulsan", "lane": 0},
    {"routeId": "kr-busan--ulsan-1", "a": "kr-ulsan", "b": "kr-busan", "length": 3, "color": "GRAY", "group": "kr-busan--ulsan", "lane": 0},
    {"routeId": "kr-busan--ulsan-2", "a": "kr-ulsan", "b": "kr-busan", "length": 3, "color": "GRAY", "group": "kr-busan--ulsan", "lane": 1},
    {"routeId": "kr-daegu--ulsan-1", "a": "kr-daegu", "b": "kr-ulsan", "length": 4, "color": "PURPLE", "group": "kr-daegu--ulsan", "lane": 0},
    {"routeId": "kr-changwon--daegu-1", "a": "kr-daegu", "b": "kr-changwon", "length": 3, "color": "WHITE", "group": "kr-changwon--daegu", "lane": 0},
    {"routeId": "kr-daegu--gimcheon-1", "a": "kr-daegu", "b": "kr-gimcheon", "length": 2, "color": "GRAY", "group": "kr-daegu--gimcheon", "lane": 0},
    {"routeId": "kr-daegu--gimcheon-2", "a": "kr-daegu", "b": "kr-gimcheon", "length": 2, "color": "GRAY", "group": "kr-daegu--gimcheon", "lane": 1},
    {"routeId": "kr-daejeon--gimcheon-1", "a": "kr-gimcheon", "b": "kr-daejeon", "length": 3, "color": "BLACK", "group": "kr-daejeon--gimcheon", "lane": 0},
    {"routeId": "kr-daejeon--gimcheon-2", "a": "kr-gimcheon", "b": "kr-daejeon", "length": 3, "color": "YELLOW", "group": "kr-daejeon--gimcheon", "lane": 1},
    {"routeId": "kr-gimcheon--namwon-1", "a": "kr-gimcheon", "b": "kr-namwon", "length": 3, "color": "BLUE", "group": "kr-gimcheon--namwon", "lane": 0},
    {"routeId": "kr-gimcheon--jinju-1", "a": "kr-gimcheon", "b": "kr-jinju", "length": 4, "color": "GREEN", "group": "kr-gimcheon--jinju", "lane": 0},
    {"routeId": "kr-daejeon--gunsan-1", "a": "kr-daejeon", "b": "kr-gunsan", "length": 4, "color": "RED", "group": "kr-daejeon--gunsan", "lane": 0},
    {"routeId": "kr-daejeon--jeonju-1", "a": "kr-daejeon", "b": "kr-jeonju", "length": 3, "color": "GRAY", "group": "kr-daejeon--jeonju", "lane": 0},
    {"routeId": "kr-daejeon--jeonju-2", "a": "kr-daejeon", "b": "kr-jeonju", "length": 3, "color": "GRAY", "group": "kr-daejeon--jeonju", "lane": 1},
    {"routeId": "kr-daejeon--namwon-1", "a": "kr-daejeon", "b": "kr-namwon", "length": 4, "color": "ORANGE", "group": "kr-daejeon--namwon", "lane": 0},
    {"routeId": "kr-gunsan--jeonju-1", "a": "kr-gunsan", "b": "kr-jeonju", "length": 2, "color": "GRAY", "group": "kr-gunsan--jeonju", "lane": 0},
    {"routeId": "kr-gunsan--gwangju-1", "a": "kr-gunsan", "b": "kr-gwangju", "length": 5, "color": "GREEN", "group": "kr-gunsan--gwangju", "lane": 0},
    {"routeId": "kr-gwangju--jeonju-1", "a": "kr-jeonju", "b": "kr-gwangju", "length": 3, "color": "WHITE", "group": "kr-gwangju--jeonju", "lane": 0},
    {"routeId": "kr-gwangju--jeonju-2", "a": "kr-jeonju", "b": "kr-gwangju", "length": 3, "color": "BLACK", "group": "kr-gwangju--jeonju", "lane": 1},
    {"routeId": "kr-jeonju--namwon-1", "a": "kr-jeonju", "b": "kr-namwon", "length": 3, "color": "PURPLE", "group": "kr-jeonju--namwon", "lane": 0},
    {"routeId": "kr-gwangju--namwon-1", "a": "kr-namwon", "b": "kr-gwangju", "length": 4, "color": "YELLOW", "group": "kr-gwangju--namwon", "lane": 0},
    {"routeId": "kr-namwon--suncheon-1", "a": "kr-namwon", "b": "kr-suncheon", "length": 3, "color": "RED", "group": "kr-namwon--suncheon", "lane": 0},
    {"routeId": "kr-jinju--namwon-1", "a": "kr-namwon", "b": "kr-jinju", "length": 3, "color": "GRAY", "group": "kr-jinju--namwon", "lane": 0},
    {"routeId": "kr-gwangju--mokpo-1", "a": "kr-mokpo", "b": "kr-gwangju", "length": 2, "color": "GRAY", "group": "kr-gwangju--mokpo", "lane": 0},
    {"routeId": "kr-gwangju--mokpo-2", "a": "kr-mokpo", "b": "kr-gwangju", "length": 2, "color": "GRAY", "group": "kr-gwangju--mokpo", "lane": 1},
    {"routeId": "kr-mokpo--suncheon-1", "a": "kr-mokpo", "b": "kr-suncheon", "length": 6, "color": "BLACK", "group": "kr-mokpo--suncheon", "lane": 0},
    {"routeId": "kr-gwangju--suncheon-1", "a": "kr-gwangju", "b": "kr-suncheon", "length": 4, "color": "BLUE", "group": "kr-gwangju--suncheon", "lane": 0},
    {"routeId": "kr-suncheon--yeosu-1", "a": "kr-suncheon", "b": "kr-yeosu", "length": 2, "color": "GRAY", "group": "kr-suncheon--yeosu", "lane": 0},
    {"routeId": "kr-jinju--suncheon-1", "a": "kr-suncheon", "b": "kr-jinju", "length": 3, "color": "ORANGE", "group": "kr-jinju--suncheon", "lane": 0},
    {"routeId": "kr-changwon--jinju-1", "a": "kr-jinju", "b": "kr-changwon", "length": 3, "color": "RED", "group": "kr-changwon--jinju", "lane": 0},
    {"routeId": "kr-changwon--jinju-2", "a": "kr-jinju", "b": "kr-changwon", "length": 3, "color": "YELLOW", "group": "kr-changwon--jinju", "lane": 1},
    {"routeId": "kr-jinju--yeosu-1", "a": "kr-jinju", "b": "kr-yeosu", "length": 3, "color": "WHITE", "group": "kr-jinju--yeosu", "lane": 0},
    {"routeId": "kr-busan--changwon-1", "a": "kr-changwon", "b": "kr-busan", "length": 3, "color": "GRAY", "group": "kr-busan--changwon", "lane": 0},
    {"routeId": "kr-busan--changwon-2", "a": "kr-changwon", "b": "kr-busan", "length": 3, "color": "GRAY", "group": "kr-busan--changwon", "lane": 1},
    {"routeId": "kr-changwon--ulsan-1", "a": "kr-changwon", "b": "kr-ulsan", "length": 4, "color": "GREEN", "group": "kr-changwon--ulsan", "lane": 0},
    {"routeId": "kr-seoul--sokcho-1", "a": "kr-seoul", "b": "kr-sokcho", "length": 6, "color": "BLACK", "group": "kr-seoul--sokcho", "lane": 0},
    {"routeId": "kr-mokpo--seosan-1", "a": "kr-seosan", "b": "kr-mokpo", "length": 6, "color": "PURPLE", "group": "kr-mokpo--seosan", "lane": 0},
    {"routeId": "kr-gangneung--pohang-1", "a": "kr-gangneung", "b": "kr-pohang", "length": 6, "color": "BLUE", "group": "kr-gangneung--pohang", "lane": 0},
];
export const KOREA_TICKETS: readonly TrainTicket[] = [
    {"ticketId": "kr-ticket-01", "a": "kr-seoul", "b": "kr-busan", "points": 17},
    {"ticketId": "kr-ticket-02", "a": "kr-incheon", "b": "kr-gangneung", "points": 10},
    {"ticketId": "kr-ticket-03", "a": "kr-paju", "b": "kr-mokpo", "points": 13},
    {"ticketId": "kr-ticket-04", "a": "kr-sokcho", "b": "kr-yeosu", "points": 19},
    {"ticketId": "kr-ticket-05", "a": "kr-chuncheon", "b": "kr-gwangju", "points": 14},
    {"ticketId": "kr-ticket-06", "a": "kr-seoul", "b": "kr-daegu", "points": 11},
    {"ticketId": "kr-ticket-07", "a": "kr-suwon", "b": "kr-jinju", "points": 11},
    {"ticketId": "kr-ticket-08", "a": "kr-seosan", "b": "kr-pohang", "points": 14},
    {"ticketId": "kr-ticket-09", "a": "kr-cheonan", "b": "kr-ulsan", "points": 11},
    {"ticketId": "kr-ticket-10", "a": "kr-gangneung", "b": "kr-mokpo", "points": 17},
    {"ticketId": "kr-ticket-11", "a": "kr-wonju", "b": "kr-suncheon", "points": 12},
    {"ticketId": "kr-ticket-12", "a": "kr-jecheon", "b": "kr-changwon", "points": 9},
    {"ticketId": "kr-ticket-13", "a": "kr-yeongju", "b": "kr-gunsan", "points": 11},
    {"ticketId": "kr-ticket-14", "a": "kr-andong", "b": "kr-gwangju", "points": 10},
    {"ticketId": "kr-ticket-15", "a": "kr-pohang", "b": "kr-jeonju", "points": 12},
    {"ticketId": "kr-ticket-16", "a": "kr-daejeon", "b": "kr-busan", "points": 11},
    {"ticketId": "kr-ticket-17", "a": "kr-cheongju", "b": "kr-yeosu", "points": 10},
    {"ticketId": "kr-ticket-18", "a": "kr-gimcheon", "b": "kr-mokpo", "points": 9},
    {"ticketId": "kr-ticket-19", "a": "kr-incheon", "b": "kr-daejeon", "points": 9},
    {"ticketId": "kr-ticket-20", "a": "kr-paju", "b": "kr-gangneung", "points": 10},
    {"ticketId": "kr-ticket-21", "a": "kr-chuncheon", "b": "kr-jecheon", "points": 5},
    {"ticketId": "kr-ticket-22", "a": "kr-suwon", "b": "kr-seosan", "points": 3},
    {"ticketId": "kr-ticket-23", "a": "kr-gunsan", "b": "kr-namwon", "points": 5},
    {"ticketId": "kr-ticket-24", "a": "kr-gwangju", "b": "kr-yeosu", "points": 6},
    {"ticketId": "kr-ticket-25", "a": "kr-jinju", "b": "kr-busan", "points": 6},
    {"ticketId": "kr-ticket-26", "a": "kr-daegu", "b": "kr-pohang", "points": 5},
    {"ticketId": "kr-ticket-27", "a": "kr-suncheon", "b": "kr-changwon", "points": 6},
    {"ticketId": "kr-ticket-28", "a": "kr-seoul", "b": "kr-jeonju", "points": 10},
    {"ticketId": "kr-ticket-29", "a": "kr-sokcho", "b": "kr-daejeon", "points": 12},
    {"ticketId": "kr-ticket-30", "a": "kr-mokpo", "b": "kr-ulsan", "points": 15},
];
