import { useEffect, useMemo, useRef, useState } from "react";
import { AVALON_DEFAULT_SETTINGS, AVALON_ROLE_LABELS, AVALON_ROLE_HELP, avalonIsEvil, avalonRoles, avalonTeamSize, avalonFailThreshold,
  type AvalonClientCommand, type AvalonRole, type AvalonStage, type AvalonResult, type AvalonProjection, type PlayerId } from "@hangul-rummikub/shared";
import type { AvalonWebSnapshot } from "../../lib/snapshot-wire-decoder.js";
import { createRequestId } from "../../lib/request-id.js";
import { getGameStartControl } from "../../lib/game-start.js";
import { RealtimeClientError } from "../../lib/realtime-client.js";
import { useAvalonSound } from "./sound.js";
export type AvalonScreenProps = Readonly<{ snapshot: AvalonWebSnapshot; connected: boolean; pending: boolean; error: string | null; connectionLabel: string;
  onCommand(command: AvalonClientCommand): Promise<void>; onStart(): void; onLeave(): void; onCopy(): void; onRematch(): void }>;
export const AVALON_STAGE_COPY: Record<AvalonStage,string> = {REVEAL:"원탁에 숨겨진 나의 운명",TEAM_BUILD:"누구와 원정을 떠날까요?",TEAM_VOTE:"이 원정대를 믿으시겠습니까?",VOTE_RESULT:"원탁의 선택",QUEST_VOTE:"성배 앞에 놓인 선택",QUEST_RESULT:"원정의 결말",ASSASSINATION:"마지막 그림자, 멀린을 찾아라"};
export const AVALON_RESULT_COPY: Record<AvalonResult["reason"],string> = {THREE_FAILURES:"세 번의 원정이 실패했습니다. 왕국이 어둠에 잠깁니다.",FIVE_REJECTIONS:"다섯 번 연속 원정대를 승인하지 못했습니다. 불신이 왕국을 무너뜨렸습니다.",MERLIN_FOUND:"암살자가 멀린을 찾아냈습니다. 세 번의 성공 뒤에 마지막 반전이 찾아왔습니다.",MERLIN_SURVIVED:"세 번의 원정이 성공했고 멀린이 살아남았습니다. 아발론의 빛을 지켰습니다.",CANCELLED:"참가자가 방을 나가 이번 판을 취소했습니다. 이번 판에는 승자가 없습니다."};
const SLOT: Record<AvalonRole,number>={MERLIN:0,ASSASSIN:1,PERCIVAL:2,MORGANA:3,SERVANT:4,MINION:5};
export function AvalonArt({slot,className=""}:{slot:number;className?:string}){return <span aria-hidden="true" className={`av-art ${className}`} style={{backgroundPosition:`${slot%3*50}% ${Math.floor(slot/3)*50}%`}}/>;}
function History({game,name}:{game:AvalonProjection;name:(id:string)=>string}){
  return <section className="av-panel av-history"><div className="av-section-title"><div><small>CHRONICLE OF THE ROUND TABLE</small><h2>원탁의 기록</h2></div><span>{game.votes.length}개의 제안</span></div>
    {!game.votes.length ? <p className="av-muted">첫 원정대가 제안되면 대장과 전원의 찬반이 이곳에 기록됩니다.</p> : [...game.votes].reverse().map((vote,i)=>{const q=game.quests.find(q=>q.quest===vote.quest),number=game.votes.length-i;return <details key={number} className="av-history-entry"><summary><span>{String(number).padStart(2,"0")} · {vote.quest}차 원정</span><b>{vote.approved?"승인":"부결"}</b><span>찬성 {vote.ballots.filter(b=>b.agree).length} / {vote.ballots.length}</span></summary><p>대장 {name(vote.leaderId)} · 원정대 {vote.team.map(name).join(", ")}</p><div className="av-ballots">{vote.ballots.map(b=><span key={b.playerId} data-agree={b.agree}>{name(b.playerId)} <b>{b.agree?"찬성 ✓":"반대 ×"}</b></span>)}</div>{vote.approved&&q&&<p className={q.success?"av-good-text":"av-evil-text"}>원정 {q.success?"성공":"실패"} · 성공 {q.team.length-q.failCount}장 / 실패 {q.failCount}장</p>}</details>;})}
  </section>;
}
export function AvalonGameScreen(props:AvalonScreenProps){
  const s=props.snapshot,game=s.game,self=s.self.playerId,playing=game?.phase==="PLAYING"?game:null;
  const host=s.room.players.some(p=>p.playerId===self&&p.isHost);
  const settings=game?.settings??("settings" in s.room?s.room.settings:AVALON_DEFAULT_SETTINGS);
  const scope=`${self}:${game?.gameId??"lobby"}:${playing?.phaseId??"finished"}`;
  const scopeRef=useRef(scope);scopeRef.current=scope;
  const [busy,setBusy]=useState(false),sending=useRef(false),[error,setError]=useState<string|null>(null);
  const [secretScope,setSecretScope]=useState<string|null>(null);
  const [draft,setDraft]=useState<{scope:string;ids:PlayerId[];vote:boolean|null;card:"SUCCESS"|"FAIL"|null}>({scope:"",ids:[],vote:null,card:null});
  const [retry,setRetry]=useState<{scope:string;command:AvalonClientCommand}|null>(null);
  const [,tick]=useState(0);
  const received=useMemo(()=>({server:s.serverTime,local:Date.now()}),[s.serverTime,scope]);
  useEffect(()=>{if(!playing)return;const t=setInterval(()=>tick(n=>n+1),500);return()=>clearInterval(t);},[scope,playing!==null]);
  useEffect(()=>{const hide=()=>setSecretScope(null);window.addEventListener("blur",hide);document.addEventListener("visibilitychange",hide);return()=>{window.removeEventListener("blur",hide);document.removeEventListener("visibilitychange",hide);};},[]);
  useEffect(()=>{setSecretScope(null);setError(null);},[scope,props.connected]);
  const selected=draft.scope===scope?draft.ids:[],vote=draft.scope===scope?draft.vote:null,card=draft.scope===scope?draft.card:null;
  const audio=useAvalonSound(game,self,props.connected),enabled=props.connected&&!props.pending&&!busy;
  const pendingRetry=retry?.scope===scope?retry:null;
  const canAct=enabled&&!pendingRetry;
  const showSecret=secretScope===scope&&props.connected;
  const start=getGameStartControl(s,!enabled);
  const name=(id:string)=>s.room.players.find(p=>p.playerId===id)?.nickname??"참가자";
  const elapsed=playing?Math.max(0,Math.floor((received.server+Date.now()-received.local-playing.stageStartedAt)/1000)):0;
  const envelope=()=>({protocolVersion:1 as const,requestId:createRequestId()});
  const identity=()=>playing?{...envelope(),gameId:playing.gameId,phaseId:playing.phaseId}:null;
  async function send(c:AvalonClientCommand){
    if(!enabled||sending.current)return;
    sending.current=true;setBusy(true);setError(null);const submittedScope=scope;
    try{
      try{await props.onCommand(c);}catch(e){if(e instanceof RealtimeClientError&&e.code==="ACKNOWLEDGEMENT_TIMEOUT")await props.onCommand(c);else throw e;}
      if(scopeRef.current===submittedScope)setRetry(null);
      audio.play("SELECT");
    }catch(e){if(scopeRef.current===submittedScope){setError(e instanceof Error?e.message:"연결과 현재 단계를 확인해주세요.");if(e instanceof RealtimeClientError)setRetry({scope:submittedScope,command:c});}}
    finally{sending.current=false;setBusy(false);}
  }
  function choose(id:PlayerId){if(!canAct||!playing)return;audio.play("SELECT");setDraft({scope,ids:playing.stage==="ASSASSINATION"?[id]:selected.includes(id)?selected.filter(x=>x!==id):selected.length<avalonTeamSize(s.room.players.length,playing.quest)?[...selected,id]:selected,vote,card});}
  function ready(){const id=identity();if(id)void send({...id,kind:"avalon:ready",payload:{}});}
  function proceed(){const id=identity();if(id)void send({...id,kind:"avalon:continue",payload:{}});}
  const roles=avalonRoles(Math.max(5,Math.min(10,s.room.players.length)),settings);
  const roleTypes=[...new Set(roles)];
  const leaderMine=playing?.stage==="TEAM_BUILD"&&playing.leaderId===self;
  const assassinMine=playing?.stage==="ASSASSINATION"&&playing.privateView.role==="ASSASSIN";
  const lastVote=playing?.votes.at(-1),lastQuest=playing?.quests.at(-1);
  return <main className="av-shell" onPointerDownCapture={audio.unlock} onKeyDownCapture={audio.unlock}>
    <header className="av-header"><div className="av-brand"><span aria-hidden="true">♛</span><div><small>THE RESISTANCE</small><h1>아발론 <em>AVALON</em></h1></div></div><div className="av-header-actions"><span className="av-connection">{props.connectionLabel}</span><button onClick={props.onCopy} aria-label={`방 코드 ${s.room.roomCode} 초대 링크 복사`}>방 {s.room.roomCode} ↗</button><button onClick={()=>audio.changeVolume(audio.volume?0:35)} aria-label={audio.volume?"효과음 끄기":"효과음 켜기"}>{audio.volume?"♪ 소리 켜짐":"♪ 소리 꺼짐"}</button><label className="av-volume">음량<input type="range" aria-label="효과음 음량" min="0" max="100" value={audio.volume} onChange={e=>audio.changeVolume(Number(e.target.value))}/></label><button onClick={props.onLeave} disabled={props.pending}>나가기</button></div></header>
    {(props.error||error)&&<div className="av-error" role="alert">{error??props.error}{pendingRetry&&<button disabled={!enabled} onClick={()=>void send(pendingRetry.command)}>같은 요청 다시 확인</button>}</div>}
    {!props.connected&&<p className="av-offline" role="status">연결을 복구하고 있습니다. 역할과 이미 제출한 선택은 유지됩니다.</p>}
    <details className="av-rulebook"><summary>게임 방법 · 원탁의 약속</summary><div><h2>믿음과 배신, 그리고 마지막 암살</h2><ol><li>나만 보는 역할을 확인합니다. 대면 또는 외부 음성 통화로 이야기하세요.</li><li>왕관을 가진 대장이 원정대원을 선택합니다. 전원이 비밀리에 찬반을 내고 동시에 공개합니다.</li><li>과반 찬성으로 출발합니다. 동률은 부결이고, 대장은 다음 좌석으로 넘어갑니다. 같은 원정에서 5회 연속 부결하면 악이 승리합니다.</li><li>원정대원만 성공/실패를 냅니다. 선은 성공만, 악은 둘 중 선택합니다. 누가 냈는지는 공개되지 않습니다.</li><li>7명 이상일 때 4차 원정은 실패 2장 이상이어야 실패합니다. 그 외에는 실패 1장이면 실패합니다.</li><li>원정 실패 3회면 악의 승리. 성공 3회면 암살자가 멀린을 찾습니다. 멀린이 살아남아야 선이 승리합니다.</li></ol><p>확정한 표는 바꿀 수 없습니다. 시간 제한은 없습니다. 결과를 3초 이상 확인한 뒤 누구나 다음으로 진행할 수 있습니다. 역할 화면은 직접 공유하지 마세요.</p><div className="av-role-guide">{roleTypes.map(role=><article key={role}><AvalonArt slot={SLOT[role]}/><div><b>{AVALON_ROLE_LABELS[role]} · {avalonIsEvil(role)?"악":"선"}</b><p>{AVALON_ROLE_HELP[role]}</p></div></article>)}</div></div></details>
    {!game?<div className="av-lobby"><section className="av-hero"><div className="av-hero-copy"><span className="av-eyebrow">A KINGDOM BUILT ON TRUST</span><h2>원탁의 맹세,<br/><em>그 안에 숨은 배신.</em></h2><p>누구의 손에 성배를 맡기겠습니까?<br/>믿음은 원정을 이끌고, 한 번의 거짓은 왕국을 흔듭니다.</p><div className="av-tags"><span>5–10명</span><span>비밀 역할</span><span>토론과 추리</span></div></div><div className="av-hero-strip">I. 운명을 확인하고 <span>II. 믿음을 시험하고</span> III. 멀린을 지켜라</div></section>
      <section className="av-panel av-lobby-panel"><div className="av-section-title"><div><small>THE ROUND TABLE</small><h2>원탁에 모인 사람들</h2></div><b>{s.room.players.length} / 10</b></div><div className="av-lobby-roster">{s.room.players.map((p,i)=><div key={p.playerId}><span className="av-seat-number">{String(i+1).padStart(2,"0")}</span><span><b>{p.nickname}{p.playerId===self?" · 나":""}</b><small>{p.isHost?"방장 · ":""}{p.connectionStatus==="CONNECTED"?"접속 중":"연결 기다리는 중"}</small></span></div>)}</div>
        <fieldset disabled={!host||!canAct}><legend>역할 구성</legend><div className="av-options">{(["BASIC","INTRIGUE"] as const).map(roleSet=><button key={roleSet} aria-pressed={settings.roleSet===roleSet} onClick={()=>void send({...envelope(),kind:"avalon:configure",expectedRoomRevision:s.versions.roomRevision,payload:{roleSet}})}><b>{roleSet==="BASIC"?"첫 원정":"비밀과 기만"}</b><small>{roleSet==="BASIC"?"멀린 · 암살자":"퍼시벌 · 모르가나 추가"}</small></button>)}</div></fieldset>
        <div className="av-roster-roles">{roleTypes.map(role=><span key={role}>{AVALON_ROLE_LABELS[role]} × {roles.filter(r=>r===role).length}</span>)}</div><p className="av-muted">{s.room.players.length<5?"5명 기준 역할 미리보기 · ":""}선 {roles.filter(r=>!avalonIsEvil(r)).length}명 · 악 {roles.filter(avalonIsEvil).length}명. 역할은 시작할 때 무작위로 배분됩니다.</p><p className="av-muted">대화는 함께 또는 음성 통화로 진행하세요.</p><p className="av-start-guidance">{start.guidance}</p>{host?<button className="av-primary av-wide" disabled={!start.canStart} onClick={props.onStart}>♛ 원탁의 맹세 시작하기</button>:<p>방장이 시작하면 나의 역할 카드를 받습니다.</p>}
      </section></div>:game.phase==="FINISHED"?<><section className={`av-panel av-finale ${game.result.winningTeam==="EVIL"?"av-dark-finale":""}`}><AvalonArt slot={game.result.winningTeam==="EVIL"?7:6} className="av-finale-art"/><div><span className="av-eyebrow">THE FINAL CHAPTER</span><h2>{game.result.reason==="CANCELLED"?"원탁이 잠시 흩어졌습니다":game.result.winningTeam==="GOOD"?"아발론의 빛을 지켰습니다":"아발론에 어둠이 내렸습니다"}</h2><p>{AVALON_RESULT_COPY[game.result.reason]}</p>{game.result.targetId&&<p>암살 대상 <b>{name(game.result.targetId)}</b> · {AVALON_ROLE_LABELS[game.result.roles.find(p=>p.playerId===game.result.targetId)!.role]}</p>}{game.result.winningTeam&&<p className="av-winners">승리한 동료들 · {game.result.winnerPlayerIds.map(name).join(", ")}</p>}{host?<button className="av-primary" disabled={!enabled} onClick={props.onRematch}>같은 방에서 다시 모이기 →</button>:<p>방장이 다음 판을 준비할 때까지 기다려주세요.</p>}</div></section><section className="av-final-roles" aria-label="모든 참가자의 역할">{game.result.roles.map(p=><article key={p.playerId}><AvalonArt slot={SLOT[p.role]}/><span className={avalonIsEvil(p.role)?"av-evil-text":"av-good-text"}>{avalonIsEvil(p.role)?"악":"선"}</span><h3>{name(p.playerId)}</h3><p>{AVALON_ROLE_LABELS[p.role]}</p></article>)}</section><History game={game} name={name}/></>:playing&&<>
      <section className="av-phase"><div><span className="av-eyebrow">{playing.stage==="ASSASSINATION"?"THE LAST SHADOW":`QUEST ${playing.quest} / V`}</span><h2>{AVALON_STAGE_COPY[playing.stage]}</h2></div><span className="av-phase-note">{playing.stage==="TEAM_BUILD"?`${Math.floor(elapsed/60)}분 ${elapsed%60}초 토론 중 · 시간 제한 없음`:playing.stage==="REVEAL"?`확인 ${playing.submittedCount} / ${s.room.players.length}`:playing.stage==="TEAM_VOTE"?`투표 ${playing.submittedCount} / ${s.room.players.length}`:playing.stage==="QUEST_VOTE"?`제출 ${playing.submittedCount} / ${playing.team.length}`:"공개 기록은 아래에서 다시 볼 수 있습니다"}</span></section>
      <section className="av-quest-track" aria-label="다섯 번의 원정">{[1,2,3,4,5].map(q=>{const result=playing.quests.find(r=>r.quest===q);return <article key={q} className={`${q===playing.quest?"current":""} ${result?result.success?"success":"failure":""}`}><span className="av-quest-number">{q}차 원정</span><AvalonArt slot={result?result.success?6:7:8}/><b>{result?result.success?"성공":"실패":`${avalonTeamSize(s.room.players.length,q)}명의 원정대`}</b><small>{result?`실패 ${result.failCount}장`:avalonFailThreshold(s.room.players.length,q)===2?"실패 2장 필요":"실패 1장이면 실패"}</small></article>;})}</section>
      <div className="av-play-layout"><div className="av-main-column"><section className="av-table"><div className="av-section-title"><div><small>THE ROUND TABLE</small><h3>♛ {name(playing.leaderId)}님의 원정대</h3></div><div className="av-rejection" aria-label={`연속 부결 ${playing.rejected}회`}>연속 부결 <b>{playing.rejected}</b> / 5</div></div><div className="av-seats">{playing.playerStates.map((p,i)=>{const selected=playing.team.includes(p.playerId)||draft.scope===scope&&draft.ids.includes(p.playerId);const isLeader=p.playerId===playing.leaderId;const allowed=canAct&&(leaderMine||assassinMine&&p.playerId!==self&&!playing.privateView.knownEvilIds.includes(p.playerId));const ballot=playing.stage==="VOTE_RESULT"?lastVote?.ballots.find(b=>b.playerId===p.playerId):null;return <button key={p.playerId} className={`av-seat ${isLeader?"leader":""}`} aria-pressed={selected} disabled={!allowed} onClick={()=>choose(p.playerId)} aria-label={`${name(p.playerId)}${isLeader?" 원정대장":""}${selected?" 선택됨":""}`}><span className="av-shield" aria-hidden="true">{isLeader?"♛":String(i+1).padStart(2,"0")}</span><b>{name(p.playerId)}{p.playerId===self?" · 나":""}</b><small>{s.room.players.find(r=>r.playerId===p.playerId)?.connectionStatus==="OFFLINE"?"연결 끊김":selected?assassinMine?"지목 대상":"원정대원":isLeader?"원정대장":"원탁의 기사"}</small>{ballot&&<span className={`av-vote-badge ${ballot.agree?"agree":"reject"}`}>{ballot.agree?"찬성 ✓":"반대 ×"}</span>}</button>;})}</div></section>
      <section className="av-panel av-action" key={playing.phaseId} aria-live="polite">
        {playing.stage==="REVEAL"&&<><span className="av-eyebrow">FOR YOUR EYES ONLY</span><h3>{playing.privateView.ready?"다른 기사들의 확인을 기다립니다":"나의 역할과 비밀 정보를 확인하세요"}</h3><p>개인 카드를 펼쳐 나의 진영과 능력을 알아보세요. 모두 확인하면 첫 원정이 시작됩니다.</p><button className="av-primary" disabled={!canAct||playing.privateView.ready} onClick={ready}>{playing.privateView.ready?"역할 확인 완료 ✓":"역할을 확인했습니다"}</button></>}
        {playing.stage==="TEAM_BUILD"&&(leaderMine?<><h3>원정을 함께할 {avalonTeamSize(s.room.players.length,playing.quest)}명을 선택하세요</h3><p>내가 원정에 참여하지 않아도 됩니다. 모두의 의견을 듣고 위의 방패를 선택하세요.</p><div className="av-action-row"><span>선택 {selected.length} / {avalonTeamSize(s.room.players.length,playing.quest)}명</span><button className="av-primary" disabled={!canAct||selected.length!==avalonTeamSize(s.room.players.length,playing.quest)} onClick={()=>{const id=identity();if(id)void send({...id,kind:"avalon:propose",payload:{playerIds:selected}});}}>원정대 제안 확정 →</button></div></>:<><h3>{name(playing.leaderId)}님이 원정대를 구성하고 있습니다</h3><p>누구를 믿을 수 있을까요? 지난 제안과 투표 기록을 보며 함께 이야기하세요.</p></>)}
        {playing.stage==="TEAM_VOTE"&&(playing.privateView.teamVote!==null?<><h3>나의 {playing.privateView.teamVote?"찬성":"반대"}표를 봉인했습니다</h3><p>전원이 제출하면 각자의 찬반이 동시에 공개됩니다.</p><div className="av-sealed">✧ 봉인 완료 · {playing.submittedCount} / {s.room.players.length}</div></>:<><h3>이 원정대의 출발에 동의하시나요?</h3><p>{playing.team.map(name).join(", ")} · 동률은 부결입니다.</p><div className="av-vote-options"><button disabled={!canAct} aria-pressed={vote===true} onClick={()=>{setDraft({scope,ids:selected,vote:true,card});audio.play("SELECT");}}><span>☀</span>찬성</button><button disabled={!canAct} aria-pressed={vote===false} onClick={()=>{setDraft({scope,ids:selected,vote:false,card});audio.play("SELECT");}}><span>✕</span>반대</button></div><button className="av-primary" disabled={!canAct||vote===null} onClick={()=>{const id=identity();if(id&&vote!==null)void send({...id,kind:"avalon:vote",payload:{agree:vote}});}}>{vote===null?"찬성 또는 반대를 선택하세요":`${vote?"찬성":"반대"}표 확정 · 제출 후 변경 불가`}</button></>)}
        {playing.stage==="VOTE_RESULT"&&lastVote&&<><span className="av-eyebrow">THE VOTES ARE REVEALED</span><h3>{lastVote.approved?"원정대가 승인되었습니다":"원정대가 부결되었습니다"}</h3><p>찬성 {lastVote.ballots.filter(b=>b.agree).length}명 · 반대 {lastVote.ballots.filter(b=>!b.agree).length}명</p><button className="av-primary" disabled={!canAct||elapsed<3} onClick={proceed}>{elapsed<3?`결과 확인 중 · ${3-elapsed}초`:lastVote.approved?"원정을 시작합니다 →":"다음 대장에게 왕관 넘기기 →"}</button></>}
        {playing.stage==="QUEST_VOTE"&&(!playing.team.includes(self)?<><h3>원정대의 선택을 기다립니다</h3><p>원정대원만 카드를 제출합니다. 누가 어떤 카드를 냈는지는 공개되지 않습니다.</p><div className="av-sealed">✧ 봉인된 카드 {playing.submittedCount} / {playing.team.length}</div></>:playing.privateView.questVote!==null?<><h3>나의 원정 카드를 봉인했습니다</h3><p>내 선택: {playing.privateView.questVote==="SUCCESS"?"성공":"실패"}. 모두 제출하면 장수만 공개됩니다.</p><div className="av-sealed">✧ 봉인 완료 · {playing.submittedCount} / {playing.team.length}</div></>:<><h3>원정에 보낼 카드를 선택하세요</h3><p>{avalonIsEvil(playing.privateView.role)?"성공으로 믿음을 얻거나, 실패로 원정을 방해할 수 있습니다.":"선 진영은 성공 카드만 제출할 수 있습니다."}</p><div className="av-quest-options"><button disabled={!canAct} aria-pressed={card==="SUCCESS"} onClick={()=>{setDraft({scope,ids:selected,vote,card:"SUCCESS"});audio.play("CARD");}}><AvalonArt slot={6}/><b>성공</b></button><button disabled={!canAct||!avalonIsEvil(playing.privateView.role)} aria-pressed={card==="FAIL"} onClick={()=>{setDraft({scope,ids:selected,vote,card:"FAIL"});audio.play("CARD");}}><AvalonArt slot={7}/><b>실패{!avalonIsEvil(playing.privateView.role)?" · 악만 선택":""}</b></button></div><button className="av-primary" disabled={!canAct||!card} onClick={()=>{const id=identity();if(id&&card)void send({...id,kind:"avalon:quest",payload:{card}});}}>{card?`${card==="SUCCESS"?"성공":"실패"} 카드 봉인 · 변경 불가`:"원정 카드를 선택하세요"}</button></>)}
        {playing.stage==="QUEST_RESULT"&&lastQuest&&<div className="av-quest-reveal"><AvalonArt slot={lastQuest.success?6:7}/><div><span className="av-eyebrow">THE GRAIL HAS SPOKEN</span><h3>원정 {lastQuest.success?"성공":"실패"}</h3><p>성공 {lastQuest.team.length-lastQuest.failCount}장 · 실패 {lastQuest.failCount}장</p>{avalonFailThreshold(s.room.players.length,playing.quest)===2&&<p>이번 원정은 실패 2장 이상일 때 실패합니다.</p>}<button className="av-primary" disabled={!canAct||elapsed<3} onClick={proceed}>{elapsed<3?`결과 확인 중 · ${3-elapsed}초`:playing.quests.filter(q=>q.success).length===3?"아직 끝나지 않았습니다 · 마지막 암살 →":"다음 원정으로 →"}</button></div></div>}
        {playing.stage==="ASSASSINATION"&&<><span className="av-eyebrow">ONE FINAL CHANCE</span><h3>{assassinMine?"멀린이라고 생각하는 한 명을 지목하세요":"마지막 암살이 남아 있습니다"}</h3><p>원정은 세 번 성공했습니다. 악의 진영이 토론한 뒤 암살자가 멀린을 찾습니다. 아직 역할을 공개하지 마세요.</p>{assassinMine?<><p>{selected[0]?`지목 대상: ${name(selected[0])}`:"위의 참가자 방패에서 한 명을 선택하세요."}</p><button className="av-danger" disabled={!canAct||selected.length!==1} onClick={()=>{const id=identity(),target=selected[0];if(id&&target)void send({...id,kind:"avalon:assassinate",payload:{playerId:target}});}}>암살 대상 최종 확정</button></>:<p className="av-sealed">✧ 암살자의 마지막 선택을 기다립니다</p>}</>}
      </section></div>
      <aside className="av-panel av-private"><span className="av-eyebrow">MY SECRET</span><h2>나의 운명</h2><button className={`av-role-card ${showSecret?"revealed":""}`} onClick={()=>{setSecretScope(showSecret?null:scope);audio.play("CARD");}} disabled={!props.connected} aria-expanded={showSecret} aria-label={showSecret?"내 역할 가리기":"내 역할과 비밀 정보 확인"}><AvalonArt slot={showSecret?SLOT[playing.privateView.role]:8}/><span>{showSecret?AVALON_ROLE_LABELS[playing.privateView.role]:"봉인된 역할 카드"}</span><small>{showSecret?"눌러서 다시 가리기":"눌러서 나만 확인하기"}</small></button>{showSecret?<div className="av-private-info"><b className={avalonIsEvil(playing.privateView.role)?"av-evil-text":"av-good-text"}>{avalonIsEvil(playing.privateView.role)?"악의 진영":"선의 진영"}</b><p>{AVALON_ROLE_HELP[playing.privateView.role]}</p>{playing.privateView.knownEvilIds.length>0&&<div className="av-knowledge"><small>{playing.privateView.role==="MERLIN"?"내가 아는 악인":"악의 동료"}</small><b>{playing.privateView.knownEvilIds.map(name).join(", ")}</b><p>각자의 세부 역할은 알 수 없습니다.</p></div>}{playing.privateView.merlinCandidates.length>0&&<div className="av-knowledge"><small>멀린과 모르가나 · 구분되지 않는 두 후보</small><b>{playing.privateView.merlinCandidates.map(name).join(", ")}</b></div>}</div>:<p className="av-muted">진영과 비밀 정보는 나에게만 보입니다. 화면을 전환하면 카드는 다시 가려집니다.</p>}</aside></div>
      <History game={playing} name={name}/>
    </>}
    <footer className="av-footer"><span>말은 자유롭게, 카드는 비밀스럽게.</span><span>원탁의 모든 선택은 기록됩니다.</span></footer>
  </main>;
}
