import * as v from 'valibot';
import { SpiritEventKeySchema, SpiritSettingsSchema, SPIRIT_DEFAULT_SETTINGS } from '@hangul-rummikub/shared';
import { GameIdSchema, GameRevisionSchema, PlayerIdSchema, ServerTimeSchema, TurnIdSchema } from '@hangul-rummikub/shared';
import { SpiritCountSchema as count, SpiritRefSchema as ref, SpiritIdSchema, SpiritElementSchema } from '@hangul-rummikub/shared';
import { SpiritLandSchema, SpiritCardSchema, SpiritStageSchema, SpiritResultSchema, SpiritInvaderCardSchema, SpiritFeedbackSchema } from '@hangul-rummikub/shared';
const StepSchema = v.strictObject({ kind: v.picklist(['SPECIAL', 'DAMAGE', 'EACH_DAMAGE', 'FEAR', 'DEFEND', 'ENERGY', 'DESTROY', 'REMOVE', 'REPLACE', 'MOVE', 'BLIGHT', 'REMOVE_BLIGHT', 'PRESENCE', 'GAIN', 'FORGET', 'OPTION', 'LAND', 'CHECK']), actor: PlayerIdSchema, land: v.nullable(ref), n: count, key: v.string(), target: v.nullable(PlayerIdSchema), tags: v.array(v.string()), used: v.array(v.string()) });
export type SpiritStep = v.InferOutput<typeof StepSchema>;
const PlayerSchema = v.strictObject({ playerId: PlayerIdSchema, spirit: v.nullable(SpiritIdSchema), board: v.picklist(['A', 'B', 'C', 'D']), removedPresence:v.optional(count,0), growthSelections:v.optional(v.array(count),[]), reclaimedCards:v.optional(v.array(ref),[]), bonusPlays: v.optional(count, 0), drowned: v.optional(count, 0), greenRepeats: v.optional(count, 0), trackChoices: v.optional(v.array(v.strictObject({ slot: v.picklist(['energyTrack', 'cardTrack']), element: SpiritElementSchema })), []), energy: count, energyTrack: count, cardTrack: count, destroyedPresence: count, grown: v.boolean(), ready: v.boolean(), paid: v.boolean(), reclaimedOne: v.boolean(), hand: v.array(ref), played: v.array(ref), discard: v.array(ref), resolved: v.array(ref), elements: v.array(SpiritElementSchema), fastUsed: count, fastGift: count, repeatGrants: v.array(v.strictObject({ id: ref, remaining: count, maxCost: count, paid: v.boolean(), used: v.array(ref) })), rangeBonus: count, sharedWith: v.array(PlayerIdSchema), reclaimAtEnd: count, progression: count });
export type SpiritPlayer = v.InferOutput<typeof PlayerSchema>;
export const SpiritStateSchema = v.strictObject({ eventIslandState:v.optional(v.nullable(v.picklist(['HEALTHY','BLIGHTED'])),null), eventInvaderStage:v.optional(v.nullable(v.picklist([1,2,3])),null), eventDeck:v.optional(v.array(SpiritEventKeySchema),[]), eventDiscard:v.optional(v.array(SpiritEventKeySchema),[]), currentEvent:v.optional(v.nullable(SpiritEventKeySchema),null), eventPayment:v.optional(v.nullable(v.strictObject({ element:SpiritElementSchema, cost:count, pledges:v.array(v.strictObject({ playerId:PlayerIdSchema, energy:count, cards:v.array(v.strictObject({ cardId:ref, mode:v.picklist(['DISCARD','FORGET']) })) })) })),null), destroyedBoards:v.optional(v.array(v.picklist(['A','B','C','D'])),[]), settings:v.optional(SpiritSettingsSchema,SPIRIT_DEFAULT_SETTINGS), configured:v.optional(v.boolean(),false), blighted:v.optional(v.boolean(),false), blightCard:v.optional(v.nullable(v.picklist(['SPIRAL','MEMORY'])),null), fearTiers:v.optional(v.array(count),[3,3,3]), immigration:v.optional(v.nullable(SpiritInvaderCardSchema),null), hearts:v.optional(v.array(ref),[]), rulesVersion: v.literal('spirit-island-core-v2'), gameId: GameIdSchema, revision: GameRevisionSchema, startedAt: ServerTimeSchema, finishedAt: v.nullable(ServerTimeSchema), phase: v.picklist(['PLAYING', 'FINISHED']), transitionId: TurnIdSchema, round: count, stage: SpiritStageSchema, players: v.pipe(v.array(PlayerSchema), v.minLength(1), v.maxLength(4)), lands: v.array(SpiritLandSchema), cards: v.array(SpiritCardSchema), minor: v.array(ref), major: v.array(ref), minorDiscard: v.array(ref), majorDiscard: v.array(ref), forgotten: v.array(ref), progressions: v.array(v.strictObject({ spirit: SpiritIdSchema, cards: v.array(ref) })),
    revealedFear: v.optional(v.array(ref), []), fear: count, fearDeck: v.array(ref), fearEarned: v.array(ref), fearDiscard: v.array(ref), terror: v.picklist([1, 2, 3, 4]), blightPool: count, blightTotal: count,
    invaderDeck: v.array(SpiritInvaderCardSchema), invaderDiscard: v.array(SpiritInvaderCardSchema), ravage: v.nullable(SpiritInvaderCardSchema), build: v.nullable(SpiritInvaderCardSchema), explore: v.nullable(SpiritInvaderCardSchema), queue: v.array(StepSchema), offered: v.array(ref), offerRecipient: v.nullable(PlayerIdSchema), offerOther: v.nullable(PlayerIdSchema), offerDeck: v.picklist(['MINOR', 'MAJOR']), effectCounter: count, pieceCounter: count, log: v.pipe(v.array(SpiritFeedbackSchema), v.maxLength(50)), plans: v.array(v.strictObject({ playerId: PlayerIdSchema, landId: ref, intent: v.picklist(['DEFEND', 'ATTACK', 'MOVE', 'HELP']) })), flags: v.array(v.string()), vengeance: v.array(v.strictObject({ actor: PlayerIdSchema, land: ref, adjacent: v.boolean() })), result: v.nullable(SpiritResultSchema) });
export type SpiritState = v.InferOutput<typeof SpiritStateSchema>;
