import * as v from 'valibot';
import { GameIdSchema, GameRevisionSchema, PlayerIdSchema, ServerTimeSchema, TurnIdSchema } from '@hangul-rummikub/shared';
import { SpiritCountSchema as count, SpiritRefSchema as ref, SpiritIdSchema, SpiritElementSchema } from '@hangul-rummikub/shared';
import { SpiritLandSchema, SpiritCardSchema, SpiritStageSchema, SpiritResultSchema, SpiritInvaderCardSchema, SpiritFeedbackSchema } from '@hangul-rummikub/shared';
const StepSchema = v.strictObject({ kind: v.picklist(['SPECIAL', 'DAMAGE', 'EACH_DAMAGE', 'FEAR', 'DEFEND', 'ENERGY', 'DESTROY', 'REMOVE', 'REPLACE', 'MOVE', 'BLIGHT', 'REMOVE_BLIGHT', 'PRESENCE', 'GAIN', 'FORGET', 'OPTION', 'LAND', 'CHECK']), actor: PlayerIdSchema, land: v.nullable(ref), n: count, key: v.string(), target: v.nullable(PlayerIdSchema), tags: v.array(v.string()), used: v.array(v.string()) });
export type SpiritStep = v.InferOutput<typeof StepSchema>;
const PlayerSchema = v.strictObject({ playerId: PlayerIdSchema, spirit: v.nullable(SpiritIdSchema), board: v.picklist(['A', 'B', 'C', 'D']), energy: count, energyTrack: count, cardTrack: count, destroyedPresence: count, grown: v.boolean(), ready: v.boolean(), paid: v.boolean(), reclaimedOne: v.boolean(), hand: v.array(ref), played: v.array(ref), discard: v.array(ref), resolved: v.array(ref), elements: v.array(SpiritElementSchema), fastUsed: count, fastGift: count, repeatGrants: v.array(v.strictObject({ id: ref, remaining: count, maxCost: count, paid: v.boolean(), used: v.array(ref) })), rangeBonus: count, sharedWith: v.array(PlayerIdSchema), reclaimAtEnd: count, progression: count });
export type SpiritPlayer = v.InferOutput<typeof PlayerSchema>;
export const SpiritStateSchema = v.strictObject({ rulesVersion: v.literal('spirit-island-intro-v1'), gameId: GameIdSchema, revision: GameRevisionSchema, startedAt: ServerTimeSchema, finishedAt: v.nullable(ServerTimeSchema), phase: v.picklist(['PLAYING', 'FINISHED']), transitionId: TurnIdSchema, round: count, stage: SpiritStageSchema, players: v.pipe(v.array(PlayerSchema), v.minLength(1), v.maxLength(4)), lands: v.array(SpiritLandSchema), cards: v.array(SpiritCardSchema), minor: v.array(ref), major: v.array(ref), minorDiscard: v.array(ref), majorDiscard: v.array(ref), forgotten: v.array(ref), progressions: v.array(v.strictObject({ spirit: SpiritIdSchema, cards: v.array(ref) })),
    fear: count, fearDeck: v.array(ref), fearEarned: v.array(ref), fearDiscard: v.array(ref), terror: v.picklist([1, 2, 3, 4]), blightPool: count, blightTotal: count,
    invaderDeck: v.array(SpiritInvaderCardSchema), invaderDiscard: v.array(SpiritInvaderCardSchema), ravage: v.nullable(SpiritInvaderCardSchema), build: v.nullable(SpiritInvaderCardSchema), explore: v.nullable(SpiritInvaderCardSchema), queue: v.array(StepSchema), offered: v.array(ref), offerRecipient: v.nullable(PlayerIdSchema), offerOther: v.nullable(PlayerIdSchema), offerDeck: v.picklist(['MINOR', 'MAJOR']), effectCounter: count, pieceCounter: count, log: v.pipe(v.array(SpiritFeedbackSchema), v.maxLength(50)), plans: v.array(v.strictObject({ playerId: PlayerIdSchema, landId: ref, intent: v.picklist(['DEFEND', 'ATTACK', 'MOVE', 'HELP']) })), flags: v.array(v.string()), vengeance: v.array(v.strictObject({ actor: PlayerIdSchema, land: ref, adjacent: v.boolean() })), result: v.nullable(SpiritResultSchema) });
export type SpiritState = v.InferOutput<typeof SpiritStateSchema>;
