import {useId} from 'react';
import {patchworkCells,patchworkPatch,PATCHWORK_INCOME,type PatchworkRotation,type PatchworkProjection} from '@hangul-rummikub/shared';
export const PATCHWORK_PALETTES=[['#ce596e','#ffe9bb','#792f57'],['#358fa0','#f7e6a2','#20536d'],['#d3a431','#fff0cc','#857229'],['#687c4d','#f9e6b2','#334c3c'],['#74587c','#f5ccd0','#453750'],['#da8060','#ffecbf','#954a37']] as const;
export function ButtonArt({x=0,y=0,size=16,color='#f8e9b4'}:{x?:number;y?:number;size?:number;color?:string}){return <g transform={`translate(${x} ${y})`}><circle r={size/2} fill={color} stroke="#71533a" strokeWidth="1.3"/><circle r={size*.34} fill="none" stroke="#9a7a53" strokeWidth=".8"/>{[[-1,-1],[1,-1],[-1,1],[1,1]].map(([dx,dy],i)=><circle key={i} cx={dx!*size*.10} cy={dy!*size*.10} r={size*.065} fill="#78543b"/>)}</g>}
export function PatchDrawing({patchId,rotation=0,flipped=false,unit=32}:{patchId:number;rotation?:PatchworkRotation;flipped?:boolean;unit?:number}){
 const id=useId().replace(/:/g,''),patch=patchworkPatch(patchId),cells=patchworkCells(patchId),palette=PATCHWORK_PALETTES[patchId%6]!,[base,cream,dark]=palette,used=new Set(cells.map(c=>`${c.x},${c.y}`)),pattern=`fabric-${id}`;
 const width=(Math.max(...cells.map(c=>c.x))+1)*unit,height=(Math.max(...cells.map(c=>c.y))+1)*unit;
 const turn=rotation===1?`translate(${height} 0) rotate(90)`:rotation===2?`translate(${width} ${height}) rotate(180)`:rotation===3?`translate(0 ${width}) rotate(270)`:'';
 const mirror=flipped?`translate(${width} 0) scale(-1 1)`:'';
 return <g transform={`${turn} ${mirror}`}><defs><pattern id={pattern} width={unit} height={unit} patternUnits="userSpaceOnUse"><rect width={unit} height={unit} fill={patchId===0?'#b38150':base}/>{patchId!==0&&(patchId%4===0?<><path d={`M0 0L${unit} ${unit}M${unit} 0L0 ${unit}`} stroke={cream} strokeWidth={unit*.15}/><path d={`M${unit/2} 0L${unit} ${unit/2}L${unit/2} ${unit}L0 ${unit/2}Z`} fill={cream}/><path d={`M${unit/2} ${unit*.2}L${unit*.8} ${unit/2}L${unit/2} ${unit*.8}L${unit*.2} ${unit/2}Z`} fill={dark}/></>:patchId%4===1?<><path d={`M0 0H${unit/2}V${unit/2}H0ZM${unit/2} ${unit/2}H${unit}V${unit}H${unit/2}Z`} fill={cream}/><path d={`M0 ${unit}L${unit} 0`} stroke={dark} strokeWidth="2" opacity=".5"/></>:patchId%4===2?<><path d={`M${unit*.25} 0V${unit}M${unit*.75} 0V${unit}`} stroke={cream} strokeWidth={unit*.18}/><path d={`M0 ${unit*.25}H${unit}M0 ${unit*.75}H${unit}`} stroke={dark} strokeWidth="1" opacity=".5"/></>:<><circle cx={unit/2} cy={unit/2} r={unit*.27} fill={cream}/><path d={`M${unit/2} ${unit*.15}V${unit*.85}M${unit*.15} ${unit/2}H${unit*.85}`} stroke={base} strokeWidth={unit*.12}/><circle cx={unit/2} cy={unit/2} r={unit*.1} fill={dark}/></>)}<path d={`M0 2H${unit}M2 0V${unit}M0 ${unit-2}H${unit}M${unit-2} 0V${unit}`} stroke="#fff" strokeOpacity=".15" strokeWidth=".7"/></pattern></defs>
 {cells.map(c=><rect key={`${c.x},${c.y}`} x={c.x*unit} y={c.y*unit} width={unit} height={unit} fill={`url(#${pattern})`}/>)}
 {cells.map(c=>{const x=c.x*unit,y=c.y*unit,edges=[!used.has(`${c.x},${c.y-1}`)?`M${x+2} ${y+2}h${unit-4}`:'',!used.has(`${c.x+1},${c.y}`)?`M${x+unit-2} ${y+2}v${unit-4}`:'',!used.has(`${c.x},${c.y+1}`)?`M${x+2} ${y+unit-2}h${unit-4}`:'',!used.has(`${c.x-1},${c.y}`)?`M${x+2} ${y+2}v${unit-4}`:''].join(' ');return <g key={`edge-${c.x},${c.y}`}><path d={edges} fill="none" stroke={dark} strokeWidth="4"/><path d={edges} fill="none" stroke={cream} strokeWidth="1" strokeDasharray="3 2"/></g>})}
 {Array.from({length:patch.income},(_,i)=>{const cell=cells[Math.floor((i+.5)*cells.length/patch.income)]!;return <ButtonArt key={i} x={(cell.x+.5)*unit} y={(cell.y+.5)*unit} size={unit*.58}/>})}</g>;
}
export function PatchArt({patchId,rotation=0,flipped=false}:{patchId:number;rotation?:PatchworkRotation;flipped?:boolean}){const cells=patchworkCells(patchId,rotation,flipped),w=(Math.max(...cells.map(c=>c.x))+1)*32,h=(Math.max(...cells.map(c=>c.y))+1)*32;return <svg viewBox={`-5 -5 ${w+10} ${h+10}`} role="img" aria-label={`조각 ${patchId||'가죽'} · ${cells.length}칸`}><PatchDrawing patchId={patchId} rotation={rotation} flipped={flipped}/></svg>}
export function patchworkSpiral():{x:number;y:number}[]{const points:{x:number;y:number}[]=[];let left=0,right=7,top=0,bottom=7;while(left<=right&&top<=bottom){for(let x=left;x<=right;x++)points.push({x,y:top});top++;for(let y=top;y<=bottom;y++)points.push({x:right,y});right--;for(let x=right;x>=left;x--)points.push({x,y:bottom});bottom--;for(let y=bottom;y>=top;y--)points.push({x:left,y});left++;}return points.slice(0,54);}
export function TimeBoard({game,preview}:{game:PatchworkProjection;preview:number|null}){const points=patchworkSpiral();return <svg className="pw-time-art" viewBox="0 0 300 328" role="img" aria-label={`시간판. ${game.playerStates.map((p,i)=>`${i+1}번 플레이어 ${p.position}칸`).join(', ')}`}><rect x="1" y="1" width="298" height="326" rx="12" fill="#245566"/><rect x="9" y="9" width="282" height="282" rx="8" fill="#e9cd8b" stroke="#c18f43" strokeWidth="3"/>{points.map((p,i)=>{const x=14+p.x*34,y=14+p.y*34,leather=game.leather.some(t=>t.position===i);return <g key={i}><rect x={x} y={y} width="33" height="33" rx="2" fill={i%2?'#e2b86f':'#f4dfaa'} stroke="#ba985c" strokeWidth=".6"/>{PATCHWORK_INCOME.includes(i)?<ButtonArt x={x+17} y={y+16} size={21}/>:leather?<rect x={x+7} y={y+7} width="20" height="20" rx="2" fill="#9b683f" stroke="#fce1a1" strokeDasharray="2 2"/>:<text x={x+16} y={y+21} textAnchor="middle" fill="#826537" fontSize="11">{i===0?'시작':i===53?'끝':i}</text>}{preview===i&&<rect x={x+1} y={y+1} width="31" height="31" rx="4" fill="none" stroke="#fff" strokeWidth="3" strokeDasharray="4 2"/>}</g>})}{game.playerStates.map((p,i)=>({p,i})).sort((a,b)=>Number(a.p.playerId===game.activePlayerId)-Number(b.p.playerId===game.activePlayerId)).map(({p,i})=>{const point=points[p.position]!,same=game.playerStates[0]!.position===game.playerStates[1]!.position,top=game.activePlayerId===p.playerId;return <g key={p.playerId} transform={`translate(${31+point.x*34+(same?(top?5:-5):0)} ${30+point.y*34+(same?(top?-5:5):0)})`}><circle cy="3" r="12" fill="#342e32" opacity=".3"/><circle r="12" fill={i?'#348aa5':'#c14770'} stroke="#fff2cd" strokeWidth={top?'3':'1.5'}/><text y="4" textAnchor="middle" fill="white" fontSize="12" fontWeight="700">{i+1}</text></g>})}<text x="150" y="314" textAnchor="middle" fill="#fff1c9" fontSize="17" fontWeight="700" letterSpacing="3">PATCHWORK</text></svg>}
