import {useEffect,useMemo,useRef,useState,type KeyboardEvent} from 'react';
import {patchworkPatch,patchworkCells,patchworkOccupied,patchworkCanPlace,patchworkFirstPlacement,patchworkScore,patchworkMovePreview,patchworkSeven,PATCHWORK_INCOME,PROTOCOL_VERSION,type PatchworkProjection,type PatchworkPlayer,type PatchworkClientCommand,type PatchworkAction,type PatchworkRotation,type TileId} from '@hangul-rummikub/shared';
import type {PatchworkWebSnapshot} from '../../lib/snapshot-wire-decoder.js';
import {getGameStartControl} from '../../lib/game-start.js';
import {createRequestId} from '../../lib/request-id.js';
import {PatchworkCommandRejected} from '../../lib/patchwork-command-error.js';
import {PatchArt,PatchDrawing,TimeBoard} from './art.js';
import {usePatchworkSound,type PatchworkCue} from './sound.js';
type Props={snapshot:PatchworkWebSnapshot;connected:boolean;pending:boolean;error:string|null;connectionLabel:string;onCommand(c:PatchworkClientCommand):Promise<void>;onRematch():void;onStart():void;onLeave():void;onCopy():void};
type Ghost={patchId:number;x:number;y:number;rotation:PatchworkRotation;flipped:boolean;valid:boolean};
function Quilt({player,seat,ghost,onCell,onHover,onKey,interactive=false,name,bonus=false}:{player:PatchworkPlayer;seat:number;ghost?:Ghost|undefined;onCell?(x:number,y:number):void;onHover?(x:number,y:number):void;onKey?(e:KeyboardEvent<HTMLDivElement>):void;interactive?:boolean;name:string;bonus?:boolean}){
 const [zoom,setZoom]=useState(false),occupied=patchworkOccupied(player.placements),seven=bonus?patchworkSeven(player.placements):null;
 return <div className={`pw-quilt-wrap seat-${seat}`}><div className="pw-panel-top"><strong>{name}</strong><span>{occupied.size}/81칸</span>{interactive&&<button className="pw-zoom" onClick={()=>setZoom(!zoom)} aria-pressed={zoom}>확대 {zoom?'끄기':'켜기'}</button>}</div><div className={`pw-quilt-scroll ${zoom?'zoomed':''}`}><div className="pw-quilt" onKeyDown={onKey}>
 <svg viewBox="0 0 360 360" role="img" aria-label={`${name}, 빈칸 ${81-occupied.size}개`}><rect width="360" height="360" rx="10" fill={seat?'#286779':'#9f3859'}/><rect x="8" y="8" width="344" height="344" rx="6" fill="none" stroke="#f5dfb3" strokeDasharray="3 3" opacity=".6"/>{Array.from({length:81},(_,i)=><rect key={i} x={18+(i%9)*36} y={18+Math.floor(i/9)*36} width="36" height="36" fill={seat?((i%9+Math.floor(i/9))%2?'#b1d6d7':'#d9e9df'):((i%9+Math.floor(i/9))%2?'#e3b3ad':'#f1d1bd')}/>)}
 {player.placements.map(p=><g key={p.tileId} className="pw-sewn-patch" transform={`translate(${18+p.x*36} ${18+p.y*36})`}><PatchDrawing patchId={p.patchId} rotation={p.rotation} flipped={p.flipped} unit={36}/></g>)}
 {seven&&<rect x={18+seven.x*36} y={18+seven.y*36} width="252" height="252" rx="5" fill="none" stroke="#ffe276" strokeWidth="4" strokeDasharray="7 4"/>}
 {ghost&&<g opacity=".78" transform={`translate(${18+ghost.x*36} ${18+ghost.y*36})`}><PatchDrawing patchId={ghost.patchId} rotation={ghost.rotation} flipped={ghost.flipped} unit={36}/>{patchworkCells(ghost.patchId,ghost.rotation,ghost.flipped).map(c=><rect key={`${c.x},${c.y}`} x={c.x*36+2} y={c.y*36+2} width="32" height="32" fill={ghost.valid?'#70d5b340':'#d83c5960'} stroke={ghost.valid?'#fff8d9':'#bf2545'} strokeWidth="2" strokeDasharray="4 3"/>)}</g>}
 </svg>{interactive&&<div className="pw-cell-grid" role="group" aria-label="퀼트 배치 위치">{Array.from({length:81},(_,i)=>{const x=i%9,y=Math.floor(i/9);return <button key={i} aria-label={`${y+1}행 ${x+1}열${occupied.has(i)?' · 천 있음':' · 빈칸'}`} onClick={()=>onCell?.(x,y)} onPointerEnter={e=>{if(e.pointerType==='mouse')onHover?.(x,y);}} onDragOver={e=>{e.preventDefault();onHover?.(x,y);}} onDrop={e=>{e.preventDefault();onCell?.(x,y);}}/>})}</div>}
 </div></div></div>;
}
export function PatchworkScreen(props:Props){
 const [configBusy,setConfigBusy]=useState(false),[configError,setConfigError]=useState<string|null>(null),configSending=useRef(false);
 async function configure(turnDurationSeconds:30|60){
  if(configSending.current||props.pending||!props.connected||!props.snapshot.room.players.find(p=>p.playerId===props.snapshot.self.playerId)?.isHost)return;
  configSending.current=true;setConfigBusy(true);setConfigError(null);
  try{await props.onCommand({protocolVersion:PROTOCOL_VERSION,kind:'patchwork:configure',requestId:createRequestId(),expectedRoomRevision:props.snapshot.versions.roomRevision,payload:{turnDurationSeconds}});}
  catch(e){setConfigError(e instanceof Error?e.message:'시간 설정을 저장하지 못했어요. 다시 선택해주세요.');}
  finally{configSending.current=false;setConfigBusy(false);}
 }
 const game=props.snapshot.game,sound=usePatchworkSound(game,props.connected),start=getGameStartControl(props.snapshot,props.pending||!props.connected||configBusy);
 return <section className="patchwork-screen" aria-label="패치워크" onPointerDownCapture={()=>void sound.unlock()} onKeyDownCapture={e=>{if(e.key==='Enter'||e.key===' ')void sound.unlock();}}>
 <header className="pw-header"><div><span className="pw-kicker">A LITTLE TIME. A LITTLE THREAD.</span><h1>Patchwork<span>패치워크</span></h1></div><div className="pw-header-tools"><span className="pw-connection">{props.connectionLabel}</span><details className="pw-sound"><summary>♫ 소리</summary><div><label>효과음 {sound.volume}%<input type="range" min="0" max="100" value={sound.volume} aria-label="패치워크 효과음 음량" onChange={e=>sound.setVolume(Number(e.target.value))}/></label><button onClick={()=>sound.setVolume(sound.volume?0:35)}>{sound.volume?'음소거':'소리 켜기'}</button><button onClick={()=>void sound.unlock().then(()=>sound.play('INCOME'))}>단추 소리 듣기</button><small>{sound.enabled?'소리 준비 완료':'화면을 누르면 소리가 준비돼요.'}</small></div></details><button onClick={props.onCopy}>초대 · {props.snapshot.room.roomCode}</button><button onClick={props.onLeave} disabled={props.pending}>나가기</button></div></header>
 {!props.connected&&<p className="pw-alert" role="status">연결을 복구하고 있어요. 확정된 퀼트는 서버에 보존되어 있습니다.</p>}{props.error&&<p className="pw-alert" role="alert">{props.error}</p>}
 {game?<PatchworkTable key={`${game.gameId}:${props.snapshot.self.playerId}`} {...props} game={game} play={sound.play}/>:<div className="pw-lobby"><div className="pw-lobby-art"><img src="/images/patchwork/cover.svg" alt="나무 작업대 위에 천 조각, 바늘, 단추와 두 퀼트가 놓인 패치워크 일러스트"/></div><div className="pw-lobby-copy"><span className="pw-kicker">TWO QUILTS, ONE SHARED MOMENT</span><h2>한 조각씩,<br/>우리만의 퀼트.</h2><p>마음에 드는 천을 고르고, 돌리고, 꼭 맞춰 놓아요.<br/>단추와 시간을 아껴 가장 멋진 퀼트를 완성하세요.</p><div className="pw-tags"><span>2인</span><span>기본판</span><span>차례당 {props.snapshot.room.settings.turnDurationSeconds===30?'30초':'1분'}</span></div><fieldset className="pw-timer-settings" disabled={configBusy||props.pending||!props.connected||!props.snapshot.room.players.find(p=>p.playerId===props.snapshot.self.playerId)?.isHost}><legend>한 차례 제한 시간</legend><div role="group" aria-label="한 차례 제한 시간">{([30,60] as const).map(seconds=><button key={seconds} aria-pressed={props.snapshot.room.settings.turnDurationSeconds===seconds} onClick={()=>void configure(seconds)}>{seconds===30?'30초':'1분'}</button>)}</div><small>방장이 선택해요 · 기본 1분</small></fieldset><p className="pw-hint">시간 초과 시 자동 전진해요. 가죽은 빈칸에 자동 배치해요.</p>{configBusy&&<p role="status">시간 설정 저장 중…</p>}{configError&&<p className="pw-alert" role="alert">{configError}</p>}<div className="pw-seats">{props.snapshot.room.players.map((p,i)=><div key={p.playerId}><span className={`pw-player-dot seat-${i}`}>{i+1}</span><strong>{p.nickname}</strong><small>{p.isHost?'방장 · ':''}{p.connectionStatus==='CONNECTED'?'접속 중':'재접속 중'}</small></div>)}</div><button className="pw-primary" onClick={props.onStart} disabled={!start.canStart}>퀼트 만들기 시작 →</button><p className="pw-hint">{start.canStart?'두 사람 모두 단추 5개로 시작해요.':start.guidance}</p></div></div>}
 </section>;
}
function PatchworkTable(props:Props&{game:PatchworkProjection;play(c:PatchworkCue):void}){
 const g=props.game,self=props.snapshot.self.playerId,me=g.playerStates.find(p=>p.playerId===self)!,other=g.playerStates.find(p=>p.playerId!==self)!,seat=g.playerStates.indexOf(me),finished=g.phase==='FINISHED';
 const [selected,setSelected]=useState<TileId|null>(null),[position,setPosition]=useState({x:0,y:0}),[rotation,setRotation]=useState<PatchworkRotation>(0),[flipped,setFlipped]=useState(false),[pinned,setPinned]=useState(false),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[rules,setRules]=useState(false),[opponentOpen,setOpponentOpen]=useState(false);
 const request=useRef<Extract<PatchworkClientCommand,{kind:'patchwork:act'}>|null>(null),sending=useRef(false);
 useEffect(()=>{setSelected(null);setRotation(0);setFlipped(false);setPosition({x:0,y:0});setPinned(false);setError(null);setUncertain(false);request.current=null;},[g.gameId,g.gameRevision]);
 const remaining=usePatchworkCountdown(g.deadlineAt,props.snapshot.serverTime);
 const canAct=(remaining===null||remaining>0)&&!finished&&g.activePlayerId===self&&props.connected&&!props.pending&&!busy&&!uncertain,leather=g.pendingLeather.length>0,tile=leather&&g.activePlayerId===self?g.pendingLeather[0]:g.market.find(p=>p.tileId===selected),patch=tile?patchworkPatch(tile.patchId):null;
 const legal=!!tile&&patchworkCanPlace(me.placements,tile.patchId,position.x,position.y,rotation,flipped),ghost=tile?{patchId:tile.patchId,...position,rotation,flipped,valid:legal}:undefined;
 const fit=useMemo(()=>new Map(g.market.slice(0,3).map(t=>[t.tileId,patchworkFirstPlacement(me.placements,t.patchId)!==null])),[g.market,me.placements]);
 const preview=patch?patchworkMovePreview(me,other.position,patch.id):null,advance=patchworkMovePreview(me,other.position,null),myScore=patchworkScore(me,g.bonusOwner),opponentScore=patchworkScore(other,g.bonusOwner),latest=g.history.at(-1);
 const name=(id:string)=>props.snapshot.room.players.find(p=>p.playerId===id)?.nickname??'플레이어';
 function select(tileId:TileId){if(!canAct||leather)return;const t=g.market.slice(0,3).find(p=>p.tileId===tileId);if(!t)return;setSelected(tileId);setRotation(0);setFlipped(false);setPinned(false);const first=patchworkFirstPlacement(me.placements,t.patchId);if(first){setPosition({x:first.x,y:first.y});setRotation(first.rotation);setFlipped(first.flipped);}setError(null);props.play('SELECT');}
 function locate(x:number,y:number,lock:boolean){if(!canAct||!tile||(!lock&&pinned))return;setPosition({x,y});setPinned(lock);if(lock)props.play('SELECT');}
 function rotate(){if(!canAct||!tile||leather)return;setRotation(rotation===3?0:rotation===2?3:rotation===1?2:1);props.play('ROTATE');}
 function flip(){if(!canAct||!tile||leather)return;setFlipped(!flipped);props.play('FLIP');}
 function cancel(){if(!canAct||leather)return;setSelected(null);setPinned(false);setError(null);props.play('CANCEL');}
 function key(e:KeyboardEvent<HTMLDivElement>){if(!canAct||!tile)return;const moves:Record<string,[number,number]>={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]},delta=moves[e.key];if(delta){e.preventDefault();setPinned(true);setPosition(p=>({x:Math.max(0,Math.min(8,p.x+delta[0])),y:Math.max(0,Math.min(8,p.y+delta[1]))}));}else if(e.key.toLowerCase()==='r'){e.preventDefault();rotate();}else if(e.key.toLowerCase()==='f'){e.preventDefault();flip();}else if(e.key==='Escape')cancel();}
 async function send(action:PatchworkAction){if(sending.current||!props.connected||finished||(!uncertain&&!canAct))return;const command=request.current??{protocolVersion:PROTOCOL_VERSION,kind:'patchwork:act' as const,requestId:createRequestId(),gameId:g.gameId,expectedGameRevision:g.gameRevision,turnId:g.turnId,payload:action};request.current=command;sending.current=true;setBusy(true);setError(null);try{await props.onCommand(command);request.current=null;setUncertain(false);setSelected(null);}catch(e){if(e instanceof PatchworkCommandRejected){request.current=null;setUncertain(false);setError(e.message);}else{setUncertain(true);setError('처리 결과를 아직 받지 못했어요. 같은 요청의 결과를 확인하세요.');}props.play('ERROR');}finally{sending.current=false;setBusy(false);}}
 function confirm(){if(!tile||!legal)return;void send(leather?{type:'PLACE_LEATHER',tileId:tile.tileId,...position}:{type:'BUY',tileId:tile.tileId,...position,rotation,flipped});}
 return <div className="pw-gameplay">
 <div className={`pw-turn-banner ${g.activePlayerId===self&&!finished?'mine':''}`}><div><span className="pw-kicker">{finished?'EVERY STITCH TELLS A STORY':leather?'A LITTLE PIECE OF LEATHER':'YOUR QUILTING TABLE'}</span><h2>{finished?(g.result.reason==='CANCELLED'?'이번 퀼트 만들기를 마쳤어요':`${g.result.winnerPlayerIds.map(name).join('')}님의 승리`):leather?(g.activePlayerId===self?'1칸 가죽 조각을 놓아주세요':`${name(g.activePlayerId)}님이 가죽 조각을 놓고 있어요`):g.activePlayerId===self?'당신의 손길을 기다려요':`${name(g.activePlayerId)}님의 차례`}</h2><p>{finished?(g.result.reason==='CANCELLED'?'플레이어가 나가 게임이 취소되었습니다.':`동점이면 시간판 끝에 먼저 도착한 사람이 이깁니다.`):leather?`남은 가죽 조각 ${g.pendingLeather.length}개 · 배치를 마치면 다음 차례로 이어져요.`:me.position===other.position?'같은 시간 칸에서는 위에 놓인 말이 먼저 행동해요.':`시간판에서 뒤에 있는 사람이 행동해요. ${name(g.activePlayerId)}님이 ${Math.abs(me.position-other.position)}칸 뒤에 있어요.`}</p></div>{!finished&&remaining!==null&&<div className={`pw-countdown ${remaining<=10?'urgent':''}`} role="timer" aria-label={`남은 시간 ${remaining}초`}><strong>{remaining>0?`${remaining}초`:'시간 초과'}</strong><progress max={g.settings.turnDurationSeconds} value={remaining}/><small>{remaining===0?'서버 처리 중':leather?'가죽 배치까지 남은 시간':'차례 제한 시간'}</small></div>}<button onClick={()=>setRules(!rules)} aria-expanded={rules}>놀이 방법 {rules?'닫기':'보기'}</button></div>
 {rules&&<div className="pw-rulebook"><h3>단추를 모으고, 시간을 아끼고, 빈칸을 채워요.</h3><ol><li>중립 말 다음의 조각 3개 중 하나를 사서 놓거나, 상대 말 바로 앞까지 전진하고 이동한 칸만큼 단추를 받아요.</li><li>조각은 회전·뒤집을 수 있지만, 이미 놓은 조각과 겹치거나 보드 밖으로 나갈 수 없어요.</li><li>시간판의 단추 표시를 지나면 내 퀼트에 있는 단추 수만큼 수입을 받아요. 가격과 수입은 달라요.</li><li>가죽 조각을 먼저 지나면 빈칸 하나를 채워요. 빈칸이 없으면 그 조각은 제거돼요.</li><li>제한 시간이 끝나면 미확정 구매는 취소되고 자동 전진해요. 가죽 배치도 같은 차례의 시간을 사용하며, 시간이 끝나면 위쪽 왼쪽 빈칸부터 자동으로 놓아요.</li><li>7×7 정사각형을 먼저 꽉 채우면 보너스 7점! 종료 점수는 남은 단추 + 보너스 − 빈칸×2예요.</li></ol><p>조각 선택 → 보드 클릭·탭·드래그 → 회전·뒤집기 → 확정. 키보드: 방향키 이동 · R 회전 · F 뒤집기 · Esc 선택 취소. 확정 전에는 바꿀 수 있어요.</p></div>}
 {!finished&&!leather&&<section className="pw-choice-section" aria-label="구매할 조각 선택"><div className="pw-market-label"><span className="pw-kicker">FOLLOW THE WOODEN PAWN</span><h3>다음 세 조각</h3><small>가격 · 시간 · 수입을 살펴보세요</small></div><div className="pw-choices">{g.market.slice(0,3).map((t,i)=>{const p=patchworkPatch(t.patchId),afford=me.buttons>=p.cost,room=fit.get(t.tileId);return <button key={t.tileId} className={`pw-patch-card ${selected===t.tileId?'selected':''}`} aria-label={`${i+1}번 조각 ${p.id} · 가격 ${p.cost} · 시간 ${p.time} · 수입 ${p.income}${!afford?' · 단추 부족':!room?' · 놓을 자리 없음':''}`} aria-pressed={selected===t.tileId} disabled={!canAct||!afford||!room} draggable={canAct&&afford&&room} onDragStart={e=>{select(t.tileId);e.dataTransfer.setData('text/plain',t.tileId);e.dataTransfer.effectAllowed='move';}} onClick={()=>select(t.tileId)}><span className="pw-order">{i+1}</span><div className="pw-card-art"><PatchArt patchId={p.id}/></div><div className="pw-price-tag"><span><b>{p.cost}</b> 단추</span><span><b>{p.time}</b> 시간</span><span><b>+{p.income}</b> 수입</span></div><small>{!afford?'단추가 부족해요':!room?'놓을 자리가 없어요':`조각 ${String(p.id).padStart(2,'0')} · ${patchworkCells(p.id).length}칸`}</small></button>})}{!g.market.length&&<p>모든 천을 골랐어요. 앞으로 이동해 마무리하세요.</p>}</div></section>}
 <div className="pw-table-layout"><div className="pw-my-area"><div className="pw-player-summary"><span className={`pw-player-dot seat-${seat}`}>{seat+1}</span><strong>{name(self)} · 나</strong><span>단추 <b>{me.buttons}</b></span><span>수입 <b>{me.income}</b></span>{g.bonusOwner===self&&<span className="pw-bonus">7×7 +7</span>}</div><Quilt player={me} seat={seat} name="나의 퀼트" bonus={g.bonusOwner===self} ghost={!finished?ghost:undefined} interactive={canAct} onCell={(x,y)=>locate(x,y,true)} onHover={(x,y)=>locate(x,y,false)} onKey={key}/><p className="pw-board-help">{!finished&&tile?`${position.y+1}행 ${position.x+1}열 · ${rotation*90}°${flipped?' · 뒤집음':''} · ${legal?'배치 가능':'겹치거나 보드 밖이에요'}`:`남은 ${myScore.empty}칸 · 빈칸 감점 ${myScore.penalty}점`}</p></div>
 <aside className="pw-time-panel"><div className="pw-panel-top"><strong>시간판</strong><span>끝 {53}칸</span></div><TimeBoard game={g} preview={preview&&!leather?preview.target:null}/><div className="pw-time-caption"><span>● 단추 표시 = 수입</span><span>▧ 가죽 = 빈칸 1개</span><strong>{me.position===53?'마지막 칸에 도착했어요':`다음 수입까지 ${(PATCHWORK_INCOME.find(n=>n>me.position)??53)-me.position}칸`}</strong></div><div className={`pw-bonus-ticket ${g.bonusOwner?'claimed':''}`}><b>7 × 7</b><span>{g.bonusOwner?`${name(g.bonusOwner)}님 획득`:'빈틈없이 먼저 채우면'}</span><strong>+7점</strong></div></aside>
 <aside className={`pw-opponent ${opponentOpen?'expanded':''}`}><div className="pw-player-summary"><span className={`pw-player-dot seat-${1-seat}`}>{2-seat}</span><strong>{name(other.playerId)}</strong><span>단추 <b>{other.buttons}</b></span><span>수입 <b>{other.income}</b></span></div><button className="pw-opponent-toggle" onClick={()=>setOpponentOpen(!opponentOpen)} aria-expanded={opponentOpen}>상대 퀼트 {opponentOpen?'접기':'펼치기'} · 빈칸 {opponentScore.empty}개</button><div className="pw-opponent-board"><Quilt player={other} seat={1-seat} name="상대의 퀼트" bonus={g.bonusOwner===other.playerId}/></div><p className="pw-board-help">시간 {other.position}/53 · 빈칸 감점 {opponentScore.penalty}점</p></aside></div>
 {!finished&&<div className={`pw-action-dock ${tile?'has-selection':''}`} ><div className="pw-draft-detail" aria-live="polite">{tile?<><strong>{leather?'1칸 가죽 조각':`조각 ${tile.patchId}`} · {legal?'놓을 수 있어요':'위치를 바꿔주세요'}</strong><span>{leather?'빈칸을 클릭하고 확정하세요.':preview?`확정 후 단추 ${preview.buttons} · ${preview.incomeGain?`수입 +${preview.incomeGain} · `:''}시간 ${preview.target} · ${preview.target===53?'마지막 칸 도착':preview.again?'다시 내 차례':'상대 차례'}`:''}</span></>:<><strong>{g.activePlayerId===self?'마음에 드는 조각을 골라보세요':'상대의 퀼트가 완성되고 있어요'}</strong><span>선택 후 보드를 누르고, 확정 전에 자유롭게 바꿔 놓아요.</span></>}</div><div className="pw-draft-controls"><button disabled={!canAct||!tile||leather} onClick={rotate}>↻ 회전</button><button disabled={!canAct||!tile||leather} onClick={flip}>↔ 뒤집기</button><button disabled={!canAct||!tile||leather} onClick={cancel}>선택 취소</button><button className="pw-primary" disabled={!canAct||!tile||!legal} onClick={confirm}>{busy?'확인 중…':leather?'가죽 배치 확정':'구매·배치 확정'}</button></div><button className="pw-advance" disabled={!canAct||leather} onClick={()=>void send({type:'ADVANCE'})}><strong>앞으로 이동</strong><span>단추 +{advance.distance}{advance.incomeGain?` · 수입 +${advance.incomeGain}`:''}</span></button></div>}
 {uncertain&&<div className="pw-alert" role="alert">{error}<button disabled={busy||!props.connected} onClick={()=>{const saved=request.current;if(saved)void send(saved.payload);}}>처리 결과 다시 확인</button></div>}{error&&!uncertain&&<p className="pw-alert" role="alert">{error}</p>}
 {finished&&<section className="pw-results"><h3>{g.result.reason==='SCORED'?'마지막 한 땀까지, 수고했어요.':'이번 게임의 퀼트'}</h3><div>{g.playerStates.map(p=>{const score=patchworkScore(p,g.bonusOwner);return <article key={p.playerId}><strong>{name(p.playerId)}</strong><b>{score.total}<small>점</small></b><p>단추 {score.buttons} + 보너스 {score.bonus}<br/>− 빈칸 {score.empty} × 2</p></article>})}</div>{props.snapshot.room.players.find(p=>p.playerId===self)?.isHost&&<button className="pw-primary" onClick={props.onRematch} disabled={props.pending||!props.connected}>같은 방에서 다시 만들기 →</button>}</section>}
 <details className="pw-market-all" open><summary>전체 천 조각 · {g.market.length}개 남음 <span>왼쪽부터 시계 방향 · 앞의 세 조각만 선택</span></summary><div className="pw-market-ribbon">{g.market.map((t,i)=><button key={t.tileId} className={i<3?'available':''} disabled={!canAct||leather||i>=3||me.buttons<patchworkPatch(t.patchId).cost||!fit.get(t.tileId)} onClick={()=>select(t.tileId)} aria-label={`조각 ${t.patchId} · 순서 ${i+1}`}><PatchArt patchId={t.patchId}/><span>{String(t.patchId).padStart(2,'0')}</span><small>{patchworkPatch(t.patchId).cost}단추 / {patchworkPatch(t.patchId).time}시간 · 수입 {patchworkPatch(t.patchId).income}</small></button>)}</div></details>
 <div className="pw-last-action" aria-live="polite">{latest?`${name(latest.playerId)}님 · ${latest.automatic?'시간 초과 · 자동 ':''}${latest.kind==='BUY'?`조각 ${latest.patchId} 구매·배치`:latest.kind==='LEATHER'?'가죽 조각 배치':`${latest.distance}칸 전진`}${latest.income?` · 단추 수입 +${latest.income}`:''}${latest.bonus?' · 7×7 보너스 획득!':''}`:'각자 단추 5개. 첫 번째 천을 골라보세요.'}</div>
 </div>;
}

// Anchor to the received server time; the browser clock only drives the display.
function usePatchworkCountdown(deadline:number|null,serverTime:number){
 const [elapsed,setElapsed]=useState({serverTime,deadline,milliseconds:0});
 useEffect(()=>{
  const start=performance.now();
  setElapsed({serverTime,deadline,milliseconds:0});
  const timer=window.setInterval(()=>setElapsed({serverTime,deadline,milliseconds:performance.now()-start}),250);
  return ()=>window.clearInterval(timer);
 },[serverTime,deadline]);
 const milliseconds=elapsed.serverTime===serverTime&&elapsed.deadline===deadline?elapsed.milliseconds:0;
 return deadline===null?null:Math.max(0,Math.ceil((deadline-serverTime-milliseconds)/1000));
}
