import { useEffect, useRef, useState, type ReactNode } from "react";
import {
  CLUE_BLOCKED_EDGES, CLUE_ROOM_LINKS, CLUE_CELL_PERCENT, CLUE_ENVELOPE_AREA, CLUE_STAIRS_AREA, CLUE_BEDROOM_WING,
  CLUE_BONUS_CELLS, CLUE_BONUS_CARDS, CLUE_BONUS_KINDS,
  CLUE_SUSPECTS, CLUE_WEAPONS, CLUE_ROOMS, CLUE_LABELS, CLUE_ROOM_AREAS, CLUE_CORRIDORS, CLUE_PASSAGES,
  clueCoordinates, isClueRoom, PROTOCOL_VERSION,
  type ClueBonusKind, type ClueAction, type ClueCardKey, type ClueSuspect, type ClueWeapon, type ClueRoom, type ClueProjection, type ClueClientCommand,
} from "@hangul-rummikub/shared";
import type { ClueWebSnapshot } from "../../lib/snapshot-wire-decoder.js";
import { createRequestId } from "../../lib/request-id.js";
import { getGameStartControl } from "../../lib/game-start.js";
import { ClueCommandRejected } from "../../lib/clue-command-error.js";
import { ClueArt, ClueCardFace } from "./art.js";
import { useClueSound, type ClueCue } from "./sound.js";
import { CLUE_COLORS, clueControls, clueKnownOwner, clueNoteStorageKey, parseClueNotes, type ClueNotes } from "./ui.js";

type Props=Readonly<{snapshot:ClueWebSnapshot;connected:boolean;pending:boolean;error:string|null;connectionLabel:string;onCommand(command:ClueClientCommand):Promise<void>;onRematch():void;onStart():void;onLeave():void;onCopy():void}>;
function CluePawn({suspect,mine}:{suspect:ClueSuspect;mine:boolean}){
  return <span className={"cl-pawn cl-portrait-pawn"+(mine?" cl-pawn-mine":"")} style={{borderColor:CLUE_COLORS[suspect]}} title={CLUE_LABELS[suspect]+(mine?" · 내 말":"")} role="img" aria-label={CLUE_LABELS[suspect]+(mine?" · 내 말":"")}><span className="cl-pawn-portrait" aria-hidden="true"><ClueArt card={suspect}/></span><span className="cl-pawn-name" aria-hidden="true">{CLUE_LABELS[suspect]}</span>{mine&&<span className="cl-pawn-self" aria-hidden="true">◆</span>}</span>;
}
function Modal({title,onClose,children}:{title:string;onClose():void;children:ReactNode}){
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>dialog?.close();},[]);
  return <dialog className="cl-modal" ref={ref} aria-label={title} onCancel={onClose}><header><h2>{title}</h2><button type="button" onClick={onClose} aria-label="닫기">×</button></header>{children}</dialog>;
}
export function ClueScreen(props:Props){
  const s=props.snapshot,start=getGameStartControl(s,props.pending||!props.connected);
  const sound = useClueSound(s.game, s.self.playerId, props.connected);
  return <section className="clue-screen" aria-label="클루" onPointerDownCapture={sound.unlock} onKeyDownCapture={event=>{if(event.key===" "||event.key==="Enter")sound.unlock();}}>
    <header className={"cl-header"+(s.game?"":" cl-header-lobby")}><div className="cl-brand"><span className="cl-eyebrow">THE MANOR MYSTERY</span><h1>CLUE <span>클루</span></h1><p>아홉 개의 방. 하나의 진실.</p></div><div className="cl-room-tools"><span>방 {s.room.roomCode}</span><span role="status">{props.connectionLabel}</span><details className="cl-sound"><summary aria-label="효과음 설정">{sound.volume===0?"소리 꺼짐":"소리 켜짐"}</summary><div><label>효과음 {sound.volume}%<input type="range" min="0" max="100" step="5" value={sound.volume} onChange={e=>sound.changeVolume(Number(e.target.value))}/></label><button type="button" onClick={() => sound.toggle()}>{sound.volume>0?"음소거":"소리 켜기"}</button><button type="button" onClick={() => sound.play("TURN")}>소리 들어보기</button></div></details><button type="button" onClick={props.onCopy} disabled={props.pending}>초대하기</button><button type="button" onClick={props.onLeave} disabled={props.pending}>나가기</button></div></header>
    {props.error&&<p className="cl-error" role="alert">{props.error}</p>}
    {s.game?<ClueTable key={s.game.gameId+":"+s.self.playerId} {...props} sound={sound} game={s.game}/>:<div className="cl-lobby"><span className="cl-eyebrow">AN INVITATION TO INVESTIGATE</span><h2>오늘 밤, 저택의 비밀을 밝혀주세요.</h2><p>방을 탐색하고, 비밀 단서를 모으고, 당신만의 추리를 완성하세요.</p><div className="cl-cast">{CLUE_SUSPECTS.map((suspect,i)=>{const p=s.room.players[i];return <div key={suspect} className={p?"":"cl-empty-seat"}><ClueCardFace card={suspect}/><strong>{p?.nickname??"빈 자리"}</strong><small>{p?(p.isHost?"방장 · ":"")+(p.connectionStatus==="CONNECTED"?"접속 중":"재접속 대기"):"초대 기다리는 중"}</small></div>;})}</div><p>{start.guidance}</p><button className="cl-primary" disabled={!start.canStart} onClick={props.onStart}>저택에 입장하기 <span aria-hidden="true">→</span></button><p className="cl-meta">3–6인 · 보너스 카드 17장 · 시간 제한 없음</p></div>}
    <details className="cl-guide"><summary>플레이 가이드 <span>처음 방문한 탐정이라면</span></summary><div><p><b>이동</b> 주사위를 굴린 뒤 빛나는 방이나 복도 칸을 선택하고 이동을 확정하세요. 한 번의 이동으로 눈금을 소모하며 방에 들어가면 멈춥니다. 지도에서 어려우면 목적지 목록을 사용할 수 있습니다.</p><p><b>추리</b> 도착한 방에서 인물과 도구를 고릅니다. 다음 사람부터 반박하며, 첫 번째 카드 보유자가 질문자에게만 한 장을 보여줍니다. 자기 카드도 추리에 넣을 수 있습니다.</p><p><b>비밀통로와 소환</b> 주방↔차고, 침실↔거실 통로는 주사위 대신 사용합니다. 다른 사람에게 불려 다른 방으로 옮겨졌다면 다음 차례에 이동 없이 그 방에서 추리할 수 있습니다.</p><p><b>최종 지목</b> 자기 차례에 어느 방이든 지목할 수 있습니다. 한 번만 가능하며, 틀리면 봉투를 혼자 확인하고 이동·추리에서 제외됩니다. 이후에도 다른 사람에게 반박 카드를 제시해야 합니다.</p><p><b>기록과 연결</b> 내 카드와 직접 본 증거는 자동 표시됩니다. 수동 메모는 이 브라우저에 저장합니다. 연결이 끊기면 기다리며, 나가기 버튼은 이번 판을 중단합니다. 사진을 바탕으로 구성한 보너스 저택 지도입니다. ?칸에 도착하면 보너스 카드 한 장을 뽑습니다. 통과할 때는 뽑지 않습니다.</p></div></details>
  </section>;
}
function ClueTable({game:g,sound,...props}:Props&{game:ClueProjection;sound:ReturnType<typeof useClueSound>}){
  const self=props.snapshot.self.playerId,people=props.snapshot.room.players,controls=clueControls(g,self),me=g.playerStates.find(p=>p.playerId===self)!;
  const name=(id:string)=>people.find(p=>p.playerId===id)?.nickname??"플레이어";
  const [destination,setDestination]=useState<string|null>(null),[suspect,setSuspect]=useState<ClueSuspect|null>(null),[weapon,setWeapon]=useState<ClueWeapon|null>(null),[room,setRoom]=useState<ClueRoom|null>(null);
  const [modal,setModal]=useState<"suspect"|"weapon"|"room"|"accuse"|"evidence"|null>(null),[pickingAccusation,setPickingAccusation]=useState(false);
  const [tab,setTab]=useState<"notes"|"history">("notes"),[mobile,setMobile]=useState<"board"|"notes"|"history">("board"),[zoom,setZoom]=useState(false);
  const [flight,setFlight]=useState(false),[retry,setRetry]=useState<ClueClientCommand|null>(null),[message,setMessage]=useState<string|null>(null);
  const locked=useRef(false),mounted=useRef(true);
  const scope=g.gameId+":"+(g.phase==="FINISHED"?"finished":g.turnId),scopeRef=useRef(scope);scopeRef.current=scope;
  const evidence=g.suggestion?.resolved?g.privateState.evidence.find(e=>e.toPlayerId===self&&e.suggestionId===g.suggestion?.id):undefined;
  const lastEvidence=useRef(evidence?.suggestionId??0);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  useEffect(()=>{setDestination(null);setSuspect(null);setWeapon(null);setRoom(null);setRetry(null);setMessage(null);setModal(null);},[scope]);
  useEffect(()=>{if(evidence&&evidence.suggestionId>lastEvidence.current){lastEvidence.current=evidence.suggestionId;setModal("evidence");}},[evidence?.suggestionId]);
  const disabled=!props.connected||props.pending||flight||retry!==null;
  async function send(command:ClueClientCommand){
    if(locked.current||!props.connected)return;locked.current=true;setFlight(true);setMessage(null);const sentScope=scope;
    try{await props.onCommand(command);if(mounted.current&&scopeRef.current===sentScope){setRetry(null);setModal(null);}}
    catch(error){if(mounted.current&&scopeRef.current===sentScope){if(error instanceof ClueCommandRejected){setRetry(null);setMessage(error.message);}else{setRetry(command);setMessage("응답을 확인하지 못했습니다. 같은 요청의 결과를 다시 확인해주세요.");sound.play("ERROR");}}}
    finally{locked.current=false;if(mounted.current)setFlight(false);}
  }
  function act(payload:ClueAction, cue: ClueCue="SELECT"){if(disabled||g.phase==="FINISHED")return;void send({kind:"clue:act",protocolVersion:PROTOCOL_VERSION,requestId:createRequestId(),gameId:g.gameId,expectedGameRevision:g.gameRevision,turnId:g.turnId,payload});sound.play(cue);}
  function pickDestination(value:string){if(!controls.move||disabled)return;sound.play("SELECT");setDestination(value);}
  function openPicker(kind:"suspect"|"weapon"|"room",accusation=false){setPickingAccusation(accusation);setModal(kind);sound.play("SELECT");}
  function choose(value:ClueCardKey){if(CLUE_SUSPECTS.some(k=>k===value)){const key=CLUE_SUSPECTS.find(k=>k===value);if(key)setSuspect(key);}else if(CLUE_WEAPONS.some(k=>k===value)){const key=CLUE_WEAPONS.find(k=>k===value);if(key)setWeapon(key);}else{const key=CLUE_ROOMS.find(k=>k===value);if(key)setRoom(key);}setModal(pickingAccusation?"accuse":null);sound.play("SELECT");}
  const lastEvent=g.history.at(-1);
  const responder=g.suggestion?.responderPlayerId,acting=g.phase==="PEEK"?g.bonus.peekPlayerIds[0]:g.phase==="BONUS"&&g.bonus.pending?.targetPlayerId?g.bonus.pending.targetPlayerId:g.phase==="RESPOND"?responder:g.turnPlayerId,offline=people.find(p=>p.playerId===acting)?.connectionStatus!=="CONNECTED";
  const headline=g.phase==="FINISHED"?"사건 기록을 공개합니다":controls.respond?"당신의 반박 카드를 골라주세요":g.turnPlayerId===self?"당신의 차례입니다":name(g.turnPlayerId)+"님의 차례";
  return <div className="cl-game">
    <div className="cl-turn"><div><span className="cl-eyebrow">{g.phase==="FINISHED"?"CASE CLOSED":"TURN "+String(g.turnNumber).padStart(2,"0")}</span><strong>{headline}</strong></div><span>{offline&&g.phase!=="FINISHED"?"재접속을 기다리는 중":g.phase==="RESPOND"&&responder?name(responder)+"님이 카드를 고르는 중":"각자의 노트는 비공개입니다"}</span></div>
    <div className="cl-players">{g.playerStates.map(p=><div key={p.playerId} className={"cl-player"+(acting===p.playerId&&g.phase!=="FINISHED"?" cl-player-active":"")+(p.eliminated?" cl-player-out":"")} style={{borderColor:CLUE_COLORS[p.suspect]}}><ClueArt card={p.suspect}/><div><b>{name(p.playerId)}{p.playerId===self?" · 나":""}</b><small>{CLUE_LABELS[p.suspect]} · {p.eliminated?"반박만 참여":p.cardCount+"장"}</small></div><span className="cl-presence" aria-label={people.find(person=>person.playerId===p.playerId)?.connectionStatus==="CONNECTED"?"접속 중":"연결 끊김"}>{people.find(person=>person.playerId===p.playerId)?.connectionStatus==="CONNECTED"?"●":"○"}</span></div>)}</div>
    {g.phase==="FINISHED"&&<section className="cl-result"><span className="cl-eyebrow">{g.result.reason==="SOLVED"?"THE MYSTERY IS SOLVED":"THE INVESTIGATION HAS ENDED"}</span><h2>{g.result.reason==="SOLVED"?name(g.result.winnerPlayerIds[0]!)+"님이 사건을 해결했습니다":g.result.reason==="CANCELLED"?"이번 조사를 중단했습니다":"모든 탐정이 최종 지목에 실패했습니다"}</h2><div className="cl-result-cards">{[g.solution.suspect,g.solution.weapon,g.solution.room].map(card=><ClueCardFace key={card} card={card}/>)}</div><button className="cl-primary" disabled={props.pending||!props.connected||!people.find(p=>p.playerId===self)?.isHost} onClick={props.onRematch}>같은 방에서 다시 준비하기</button><details><summary>모든 사람의 카드 확인</summary>{g.revealedHands.map(p=><div className="cl-revealed-hand" key={p.playerId}><b>{name(p.playerId)}</b><div className="cl-hand">{p.hand.map(c=><ClueCardFace key={c.cardId} card={c.key} small/>)}</div></div>)}</details></section>}
    <nav className="cl-mobile-nav" aria-label="플레이 화면"><button aria-pressed={mobile==="board"} onClick={()=>setMobile("board")}>저택 보드</button><button aria-pressed={mobile==="notes"} onClick={()=>{setMobile("notes");setTab("notes");}}>추리 노트</button><button aria-pressed={mobile==="history"} onClick={()=>{setMobile("history");setTab("history");}}>진행 기록</button></nav>
    <div className={"cl-layout cl-mobile-"+mobile}>
      <div className="cl-map-column"><div className="cl-section-title"><div><span className="cl-eyebrow">THE MANOR</span><h2>저택 탐색</h2></div><button type="button" onClick={()=>setZoom(!zoom)} aria-pressed={zoom}>{zoom?"전체 지도":"지도 확대"}</button></div>
        <div className={"cl-board-scroll"+(zoom?" cl-zoom":"")}><div className="cl-board" aria-label="저택 지도">
          {CLUE_CORRIDORS.map(location=>{const p=clueCoordinates(location)!;const t=g.tokens.find(t=>t.location===location);const bonus=CLUE_BONUS_CELLS.includes(location);const stairs=p.x>=CLUE_STAIRS_AREA.x&&p.x<CLUE_STAIRS_AREA.x+CLUE_STAIRS_AREA.width&&p.y>=CLUE_STAIRS_AREA.y&&p.y<CLUE_STAIRS_AREA.y+CLUE_STAIRS_AREA.height;const reachable=controls.move&&controls.paths.has(location),path=destination?controls.paths.get(destination):null;return <button type="button" key={location} className={"cl-cell"+(stairs?" cl-stair-cell":"")+(bonus?" cl-bonus-cell":"")+(reachable?" cl-reachable":"")+(path?.includes(location)?" cl-path":"")} style={{left:p.x*CLUE_CELL_PERCENT+"%",top:p.y*CLUE_CELL_PERCENT+"%",width:CLUE_CELL_PERCENT+"%",height:CLUE_CELL_PERCENT+"%",backgroundPosition:(p.x%4)*100/3+"% "+(p.y%4)*100/3+"%"}} disabled={!reachable||disabled} aria-label={(bonus?"보너스 ?칸 ":stairs?"계단 ":"복도 ")+(p.x+1)+", "+(p.y+1)+(t?" · "+CLUE_LABELS[t.suspect]:"")} aria-pressed={destination===location} onClick={()=>pickDestination(location)}>{bonus&&<span className="cl-question" aria-hidden="true">?</span>}{t&&<CluePawn suspect={t.suspect} mine={g.playerStates.some(player=>player.playerId===self&&player.suspect===t.suspect)}/>}</button>;})}
          {CLUE_ROOM_AREAS.map(area=>{const reachable=controls.move&&controls.paths.has(area.room),here=controls.location===area.room;return <button type="button" key={area.room} className={"cl-room"+(reachable?" cl-room-reachable":"")+(here?" cl-room-here":"")} style={{left:area.x*CLUE_CELL_PERCENT+"%",top:area.y*CLUE_CELL_PERCENT+"%",width:area.width*CLUE_CELL_PERCENT+"%",height:area.height*CLUE_CELL_PERCENT+"%"}} disabled={!reachable||disabled} aria-label={CLUE_LABELS[area.room]+(here?" · 현재 위치":"")+(reachable?" · 이동 가능":"")} aria-pressed={destination===area.room} onClick={()=>pickDestination(area.room)}><ClueArt card={area.room}/><span className="cl-room-label">{CLUE_LABELS[area.room]}{here&&<small>현재 위치</small>}</span><span className="cl-room-pawns">{g.tokens.filter(t=>t.location===area.room).map(t=><CluePawn key={t.suspect} suspect={t.suspect} mine={g.playerStates.some(player=>player.playerId===self&&player.suspect===t.suspect)}/>)}{g.weapons.filter(w=>w.room===area.room).map(w=><span className="cl-weapon-piece" key={w.weapon} title={CLUE_LABELS[w.weapon]}><ClueArt card={w.weapon}/></span>)}</span>{CLUE_PASSAGES[area.room]&&<span className="cl-passage-mark" aria-hidden="true">↗</span>}</button>;})}
          {CLUE_ROOM_AREAS.flatMap(area=>area.doors.map(door=>{const p=clueCoordinates(door)!;let x=p.x,y=p.y,width=1,height=1;if(p.x<area.x){x=area.x-.12;width=.24;}else if(p.x>=area.x+area.width){x=area.x+area.width-.12;width=.24;}else if(p.y<area.y){y=area.y-.12;height=.24;}else{y=area.y+area.height-.12;height=.24;}return <span key={area.room+door} className="cl-door" style={{left:x*CLUE_CELL_PERCENT+"%",top:y*CLUE_CELL_PERCENT+"%",width:width*CLUE_CELL_PERCENT+"%",height:height*CLUE_CELL_PERCENT+"%"}} aria-hidden="true"/>;}))}
          {CLUE_BLOCKED_EDGES.map(edge=><span key={edge.from+edge.to} className="cl-map-wall" aria-label="계단과 서재 사이 벽 · 통과 불가" style={{left:edge.x*CLUE_CELL_PERCENT+"%",top:(edge.y-.08)*CLUE_CELL_PERCENT+"%",width:edge.width*CLUE_CELL_PERCENT+"%",height:.16*CLUE_CELL_PERCENT+"%"}}/>)}
          {CLUE_ROOM_LINKS.map(link=><span key={link.from+link.to} className="cl-door cl-room-link" aria-label={CLUE_LABELS[link.from]+" ↔ "+CLUE_LABELS[link.to]+" 연결문"} style={{left:link.x*CLUE_CELL_PERCENT+"%",top:(link.y-.12)*CLUE_CELL_PERCENT+"%",width:link.width*CLUE_CELL_PERCENT+"%",height:.24*CLUE_CELL_PERCENT+"%"}}/>)}
          {[{...CLUE_STAIRS_AREA,kind:"stairs",label:"계단 · 한 칸씩 이동"},{...CLUE_BEDROOM_WING,kind:"bedroom-wing",label:"침실 벽 · 이동 불가"}].map(area=><div key={area.kind} className={"cl-map-"+area.kind} aria-label={area.label} style={{left:area.x*CLUE_CELL_PERCENT+"%",top:area.y*CLUE_CELL_PERCENT+"%",width:area.width*CLUE_CELL_PERCENT+"%",height:area.height*CLUE_CELL_PERCENT+"%"}}>{area.kind==="stairs"&&<span>계단</span>}</div>)}
          <div className="cl-envelope" aria-label="비공개 사건 봉투" style={{left:CLUE_ENVELOPE_AREA.x*CLUE_CELL_PERCENT+"%",top:CLUE_ENVELOPE_AREA.y*CLUE_CELL_PERCENT+"%",width:CLUE_ENVELOPE_AREA.width*CLUE_CELL_PERCENT+"%",height:CLUE_ENVELOPE_AREA.height*CLUE_CELL_PERCENT+"%"}}><span>CONFIDENTIAL</span><div className="cl-envelope-paper"><i>?</i></div><b>사건 봉투</b><small>인물 · 도구 · 장소</small></div>
        </div></div>
        <div className="cl-board-legend"><span><i/> 이동 가능한 칸</span><span>황동 표시: 출입문</span><span>↗ 비밀통로</span><span className="cl-bonus-legend">? 도착하면 보너스 카드</span></div>
        {controls.move&&<details className="cl-destinations"><summary>목적지 목록으로 이동하기</summary><div>{[...controls.paths.entries()].map(([location,path])=><button key={location} disabled={disabled} aria-pressed={destination===location} onClick={()=>pickDestination(location)}>{isClueRoom(location)?CLUE_LABELS[location]:(CLUE_BONUS_CELLS.includes(location)?"? 보너스 ":"복도 ")+location.slice(2).replace(":",", ")} · {path.length}칸</button>)}</div></details>}
        <section className="cl-hand-section"><div className="cl-section-title"><div><span className="cl-eyebrow">YOUR EVIDENCE</span><h2>내 카드</h2></div><span>나만 볼 수 있어요</span></div><div className="cl-hand">{g.privateState.hand.map(c=><ClueCardFace key={c.cardId} card={c.key}/>)}</div></section>
      </div>
      <aside className="cl-sidebar">
        {g.phase!=="FINISHED"&&<section className="cl-action-panel" aria-label="현재 행동"><span className="cl-eyebrow">YOUR NEXT MOVE</span>
          {controls.respond&&g.suggestion?<><h2>증거 한 장을 보여주세요</h2><p>{name(g.suggestion.playerId)}님에게만 전달됩니다.</p><div className="cl-response-cards">{g.privateState.hand.filter(c=>g.suggestion&&(c.key===g.suggestion.suspect||c.key===g.suggestion.weapon||c.key===g.suggestion.room)).map(c=><button type="button" disabled={disabled} key={c.cardId} onClick={()=>act({type:"SHOW_CARD",cardId:c.cardId},"RESPOND")}><ClueCardFace card={c.key}/><span>이 카드 제시</span></button>)}</div></>:<>
            <h2>{me.eliminated?"반박으로 조사를 이어가세요":controls.roll?"어느 방으로 가볼까요?":controls.move?"목적지를 골라주세요":controls.bonusSuggest?"원하는 조합으로 추리하세요":g.phase==="BONUS"?"보너스 카드를 해결하세요":g.phase==="PEEK"?"엿보기 선택을 기다립니다":controls.suggest?"이 방에서 무슨 일이?":g.phase==="RESPOND"?"반박을 기다리는 중":g.turnPlayerId===self?"단서를 정리해보세요":"다른 탐정의 차례입니다"}</h2>
            {controls.roll&&<div className="cl-roll-row"><button type="button" className="cl-die-button" onClick={()=>act({type:"ROLL"},"ROLL")} disabled={disabled}><Dice value={g.die??1}/><span>주사위 굴리기</span></button>{controls.passage&&<button type="button" onClick={()=>act({type:"PASSAGE"},"MOVE")} disabled={disabled}>비밀통로<br/><b>{CLUE_LABELS[controls.passage]} ↗</b></button>}</div>}
            {controls.move&&<><div className="cl-movement"><Dice value={Math.min(g.die??1,6)}/><p><b>{g.die}칸</b>까지 이동할 수 있습니다.<small>{destination?(isClueRoom(destination)?CLUE_LABELS[destination]:"선택한 복도")+" · "+controls.paths.get(destination)?.length+"칸":"지도에서 빛나는 목적지를 선택하세요."}</small></p></div><button type="button" className="cl-primary" disabled={disabled||!destination} onClick={()=>destination&&act({type:"MOVE",destination},"MOVE")}>이동 확정</button></>}
            {(controls.suggest||controls.bonusSuggest)&&<><div className="cl-selection-pair"><button type="button" disabled={disabled} onClick={()=>openPicker("suspect")}>{suspect?<ClueCardFace card={suspect}/>:<span className="cl-unknown-card">?<small>인물 고르기</small></span>}</button><button type="button" disabled={disabled} onClick={()=>openPicker("weapon")}>{weapon?<ClueCardFace card={weapon}/>:<span className="cl-unknown-card">?<small>도구 고르기</small></span>}</button></div>{controls.bonusSuggest?<button type="button" disabled={disabled} onClick={()=>openPicker("room")}>{room?CLUE_LABELS[room]:"추리할 장소 고르기"}</button>:<p className="cl-location">장소 · {isClueRoom(controls.location)?CLUE_LABELS[controls.location]:""}</p>}<button className="cl-primary" disabled={disabled||!suspect||!weapon||controls.bonusSuggest&&!room} onClick={()=>{if(suspect&&weapon){if(controls.bonusSuggest&&room)act({type:"BONUS_SUGGEST",suspect,weapon,room},"SUGGEST");else if(controls.suggest)act({type:"SUGGEST",suspect,weapon},"SUGGEST");}}}>추리 발표하기</button></>}
            {g.phase==="RESPOND"&&responder&&<p>{name(responder)}님이 반박할 카드를 고르고 있습니다.{offline?" 연결이 복구되면 계속됩니다.":""}</p>}
            {evidence&&<button type="button" className="cl-evidence-link" onClick={()=>setModal("evidence")}>봉인된 증거 · 받은 카드 보기</button>}
            {controls.end&&<button type="button" className="cl-primary" disabled={disabled} onClick={()=>act({type:"END_TURN"},"TURN")}>턴 마치기 →</button>}
          </>}
          {g.phase==="BONUS"&&g.bonus.pending&&<div className="cl-bonus-resolution">
            <BonusFace kind={g.bonus.pending.kind}/>
            {g.turnPlayerId===self&&g.bonus.pending.kind==="TELEPORT"&&<div className="cl-bonus-rooms">{CLUE_ROOMS.map(r=><button key={r} disabled={disabled} onClick={()=>act({type:"BONUS_MOVE",room:r},"MOVE")}><ClueCardFace card={r} small/></button>)}</div>}
            {g.bonus.pending.kind==="PUBLIC_REVEAL"&&(g.bonus.pending.targetPlayerId===self?<><h3>모두에게 보여줄 카드 선택</h3><div className="cl-response-cards">{g.privateState.hand.map(c=><button key={c.cardId} disabled={disabled} onClick={()=>act({type:"BONUS_REVEAL",cardId:c.cardId},"RESPOND")}><ClueCardFace card={c.key} small/></button>)}</div></>:g.bonus.pending.targetPlayerId?<p>{name(g.bonus.pending.targetPlayerId)}님이 공개할 카드를 고릅니다.</p>:g.turnPlayerId===self?<div className="cl-bonus-targets">{g.playerStates.filter(p=>p.playerId!==self).map(p=><button key={p.playerId} disabled={disabled} onClick={()=>act({type:"BONUS_TARGET",playerId:p.playerId})}><ClueArt card={p.suspect}/>{name(p.playerId)} 지목</button>)}</div>:<p>{name(g.turnPlayerId)}님이 공개할 사람을 고릅니다.</p>)}
          </div>}
          {g.phase==="PEEK"&&<div className="cl-peek-prompt"><h3>카드 엿보기 기회</h3>{controls.peek?<><p>방금 제시된 반박 카드를 함께 보시겠어요?</p><button disabled={disabled} onClick={()=>act({type:"USE_BONUS",kind:"PEEK"},"RESPOND")}>엿보기 카드 사용</button><button disabled={disabled} onClick={()=>act({type:"SKIP_PEEK"})}>이번에는 보관</button></>:<p>{name(g.bonus.peekPlayerIds[0]!)}님이 엿보기 사용 여부를 선택하고 있습니다.</p>}</div>}
          {lastEvent?.type==="BONUS_DRAW"&&lastEvent.playerId===self&&<p className="cl-bonus-notice" role="status">? 보너스 카드를 뽑았습니다. {g.phase==="BONUS"?"지금 효과를 사용하세요.":"내 보관 카드에서 확인하고 사용할 수 있습니다."}</p>}
          <section className="cl-bonus-inventory" aria-label="내 보너스 카드"><div className="cl-section-title"><h3>보너스 카드</h3><span>덱 {g.bonus.deckCount} · 사용 {g.bonus.discardCount}</span></div>
            {g.bonus.extraTurn&&g.turnPlayerId===self&&<p role="status">↻ 이번 턴을 마치면 한 차례 더 진행합니다.</p>}
            {g.privateState.bonusHand.length===0?<p>?칸에 도착해 특별한 기회를 얻으세요.</p>:<details className="cl-held-bonus"><summary>내 보관 카드 {g.privateState.bonusHand.length}장 펼치기</summary><div className="cl-bonus-hand">{CLUE_BONUS_KINDS.filter(k=>g.privateState.bonusHand.includes(k)).map(kind=><div key={kind}><BonusFace kind={kind}/><span className="cl-bonus-count">{g.privateState.bonusHand.filter(k=>k===kind).length}장 보유</span>{(kind==="PLUS_SIX"||kind==="EXTRA_TURN"||kind==="PEEK")&&<button disabled={disabled||!(kind==="PLUS_SIX"?controls.plusSix:kind==="EXTRA_TURN"?controls.extraTurn:controls.peek)} onClick={()=>act({type:"USE_BONUS",kind},"BONUS")}>{kind==="PEEK"?"반박 제시 후 엿보기":"지금 사용"}</button>}</div>)}</div></details>}
            <details><summary>6종 카드 안내 · 총 17장</summary><div className="cl-bonus-catalog">{CLUE_BONUS_KINDS.map(kind=><div key={kind}><BonusFace kind={kind}/><small>{CLUE_BONUS_CARDS[kind].count}장</small></div>)}</div></details>
          </section>
          {g.suggestion&&<div className="cl-latest"><small>{name(g.suggestion.playerId)}님의 추리</small><b>{CLUE_LABELS[g.suggestion.suspect]} · {CLUE_LABELS[g.suggestion.weapon]} · {CLUE_LABELS[g.suggestion.room]}</b><span>{g.suggestion.resolved?(g.suggestion.responderPlayerId?name(g.suggestion.responderPlayerId)+"님이 카드 한 장 제시":"아무도 반박하지 못했습니다"):(responder?name(responder)+"님의 응답 대기":"")}</span></div>}
          {controls.accuse&&<button type="button" className="cl-accuse-button" disabled={disabled} onClick={()=>{sound.play("SELECT");setSuspect(null);setWeapon(null);setRoom(null);setModal("accuse");}}>사건을 해결했나요? 최종 지목</button>}
          {me.eliminated&&g.privateState.caseFile&&<details className="cl-private-solution"><summary>내가 확인한 사건 봉투</summary><div className="cl-triple">{[g.privateState.caseFile.suspect,g.privateState.caseFile.weapon,g.privateState.caseFile.room].map(card=><ClueCardFace key={card} card={card} small/>)}</div><p>다른 탐정에게는 공개되지 않습니다.</p></details>}
          {message&&<p className="cl-error" role="alert">{message}</p>}{retry&&<button type="button" disabled={flight||!props.connected} onClick={()=>void send(retry)}>같은 요청 결과 확인</button>}
          {flight&&<p role="status">서버에서 확인 중…</p>}
        </section>}
        <div className="cl-notebook-panel"><nav className="cl-desktop-tabs" aria-label="탐정 수첩"><button type="button" aria-pressed={tab==="notes"} onClick={()=>setTab("notes")}>추리 노트</button><button type="button" aria-pressed={tab==="history"} onClick={()=>setTab("history")}>진행 기록</button></nav>{tab==="notes"?<Notebook game={g} name={name}/>:<History game={g} name={name}/>}</div>
      </aside>
    </div>
    {controls.move&&destination&&<div className="cl-mobile-confirm"><span>{isClueRoom(destination)?CLUE_LABELS[destination]:"선택한 복도"} · {controls.paths.get(destination)?.length}칸</span><button type="button" className="cl-primary" disabled={disabled} onClick={()=>act({type:"MOVE",destination},"MOVE")}>선택한 곳으로 이동</button></div>}
    {modal==="evidence"&&evidence&&<Modal title="당신에게만 전달된 증거" onClose={()=>setModal(null)}><div className="cl-private-reveal"><span className="cl-eyebrow">PRIVATE EVIDENCE</span><ClueCardFace card={evidence.card.key}/><p>{name(evidence.fromPlayerId)}님이 보여준 카드입니다.<br/>추리 노트에 자동으로 기록했습니다.</p><button type="button" className="cl-primary" onClick={()=>setModal(null)}>확인했습니다</button></div></Modal>}
    {(modal==="suspect"||modal==="weapon"||modal==="room")&&<Modal title={modal==="suspect"?"누가? 용의자 선택":modal==="weapon"?"무엇으로? 도구 선택":"어디서? 장소 선택"} onClose={()=>setModal(pickingAccusation?"accuse":null)}><div className="cl-picker">{(modal==="suspect"?CLUE_SUSPECTS:modal==="weapon"?CLUE_WEAPONS:CLUE_ROOMS).map(card=><button type="button" key={card} disabled={disabled} onClick={()=>choose(card)}><ClueCardFace card={card}/></button>)}</div></Modal>}
    {modal==="accuse"&&controls.accuse&&<Modal title="최종 지목 · 단 한 번의 기회" onClose={()=>setModal(null)}><p>틀리면 봉투를 확인하고 이동·추리에서 제외됩니다. 이후에도 반박 카드는 제시합니다.</p><div className="cl-accusation-fields">{([{kind:"suspect",value:suspect,label:"누가"},{kind:"weapon",value:weapon,label:"무엇으로"},{kind:"room",value:room,label:"어디서"}] as const).map(field=><button type="button" key={field.kind} disabled={disabled} onClick={()=>openPicker(field.kind,true)}>{field.value?<ClueCardFace card={field.value}/>:<span className="cl-unknown-card">?<small>{field.label}</small></span>}</button>)}</div><button type="button" className="cl-danger" disabled={disabled||!suspect||!weapon||!room} onClick={()=>suspect&&weapon&&room&&act({type:"ACCUSE",suspect,weapon,room},"ACCUSE")}>이 조합으로 최종 지목 확정</button></Modal>}
  </div>;
}
export function BonusFace({kind}:{kind:ClueBonusKind}){
  const card=CLUE_BONUS_CARDS[kind];
  return <div className={"cl-bonus-card cl-bonus-"+kind.toLowerCase()}><span className="cl-eyebrow">FORTUNE FAVOURS THE CURIOUS</span><span className="cl-bonus-symbol" aria-hidden="true">{card.symbol}</span><strong>{card.title}</strong><p>{card.description}</p><small>{card.immediate?"지금 사용":"사용할 때까지 보관"}</small></div>;
}
function Dice({value}:{value:number}){
  const spots:Record<number,number[]>={1:[4],2:[0,8],3:[0,4,8],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8]};
  return <span className="cl-die" role="img" aria-label={"주사위 "+value}>{Array.from({length:9},(_,i)=><i className={spots[value]?.includes(i)?"cl-pip":""} key={i}/>)}</span>;
}
function Notebook({game:g,name}:{game:ClueProjection;name(id:string):string}){
  const [category,setCategory]=useState<"suspects"|"weapons"|"rooms">("suspects"),[storageError,setStorageError]=useState(false);
  const key=clueNoteStorageKey(g.gameId,g.privateState.playerId);
  const [notes,setNotes]=useState<ClueNotes>({marks:{},text:""});
  useEffect(()=>{try{const stored=localStorage.getItem(key);const raw:unknown=stored?JSON.parse(stored):null;setNotes(parseClueNotes(raw,g.playerStates.map(p=>p.playerId)));}catch{setStorageError(true);}},[key]);
  function save(next:ClueNotes){setNotes(next);try{localStorage.setItem(key,JSON.stringify(next));setStorageError(false);}catch{setStorageError(true);}}
  const cards=category==="suspects"?CLUE_SUSPECTS:category==="weapons"?CLUE_WEAPONS:CLUE_ROOMS;
  return <div className="cl-notebook"><div className="cl-notebook-heading"><span className="cl-eyebrow">DETECTIVE'S NOTES</span><h2>나만의 추리 수첩</h2></div><nav aria-label="노트 카드 분류">{([{value:"suspects",label:"인물"},{value:"weapons",label:"도구"},{value:"rooms",label:"장소"}] as const).map(c=><button type="button" key={c.value} aria-pressed={category===c.value} onClick={()=>setCategory(c.value)}>{c.label}</button>)}</nav><div className="cl-note-scroll"><table><thead><tr><th>단서</th>{g.playerStates.map(p=><th key={p.playerId} title={name(p.playerId)}>{p.playerId===g.privateState.playerId?"나":name(p.playerId)}</th>)}</tr></thead><tbody>{cards.map(card=>{const owner=clueKnownOwner(g,card);return <tr key={card}><th><ClueArt card={card}/><span>{CLUE_LABELS[card]}</span></th>{g.playerStates.map(p=>{const id=card+":"+p.playerId,known=owner?(owner===p.playerId?"✓":"×"):p.playerId===g.privateState.playerId?"×":null,mark=notes.marks[id]??"·";return <td key={p.playerId}>{known?<span className={known==="✓"?"cl-fact-yes":"cl-fact-no"} aria-label={name(p.playerId)+" · "+CLUE_LABELS[card]+(known==="✓"?" 보유 확인":" 없음 확인")}>{known}</span>:<button type="button" aria-label={name(p.playerId)+" · "+CLUE_LABELS[card]+" 수동 표시 "+mark} onClick={()=>{const marks={...notes.marks};if(mark==="·")marks[id]="?";else if(mark==="?")marks[id]="×";else if(mark==="×")marks[id]="✓";else delete marks[id];save({...notes,marks});}}>{mark}</button>}</td>;})}</tr>;})}</tbody></table></div><p className="cl-note-legend">진한 ✓ ×는 확인한 사실 · 버튼은 나의 추정</p><label className="cl-memo">탐정 메모<textarea maxLength={2000} value={notes.text} onChange={e=>save({...notes,text:e.target.value})} placeholder="확실한 단서와 다음 추리를 적어보세요."/></label><small role="status">{storageError?"이 브라우저에서 메모를 저장하지 못했습니다. 새로고침하면 수동 메모가 사라질 수 있습니다.":"이 브라우저에 자동 저장됩니다."}</small></div>;
}
function History({game:g,name}:{game:ClueProjection;name(id:string):string}){
  return <div className="cl-history"><span className="cl-eyebrow">THE INVESTIGATION</span><h2>조사 기록</h2>{g.history.length===0?<p>첫 번째 탐정이 저택을 탐색하고 있습니다.</p>:[...g.history].reverse().map((event,i)=>{if(event.type==="SUGGEST")return <article key={g.history.length-i}><small>{name(event.suggestion.playerId)}님의 추리</small><div className="cl-history-art">{[event.suggestion.suspect,event.suggestion.weapon,event.suggestion.room].map(c=><ClueCardFace key={c} card={c} small/>)}</div><p>{event.suggestion.responderPlayerId?name(event.suggestion.responderPlayerId)+"님이 카드 한 장을 제시했습니다.":"아무도 반박하지 못했습니다."}</p>{event.suggestion.passedPlayerIds.length>0&&<small>반박 없음: {event.suggestion.passedPlayerIds.map(name).join(", ")}</small>}</article>;if(event.type==="BONUS_DRAW"||event.type==="BONUS_USE")return <article key={g.history.length-i}><p>{name(event.playerId)} · 보너스 카드 {event.type==="BONUS_DRAW"?"획득":"사용"}</p><b>{CLUE_BONUS_CARDS[event.kind].title}</b></article>;
    if(event.type==="PUBLIC_REVEAL")return <article key={g.history.length-i}><p>{name(event.playerId)} · 모두에게 공개한 카드</p><div className="cl-history-art"><ClueCardFace card={event.card.key}/></div></article>;
    return <article key={g.history.length-i}>{event.type==="ROLL"?<p>{name(event.playerId)} · 주사위 <b>{event.value}</b></p>:event.type==="MOVE"?<p>{name(event.playerId)} · {isClueRoom(event.destination)?CLUE_LABELS[event.destination]:"복도"}{event.passage?" 비밀통로로 이동":" 도착"}</p>:<p>{name(event.playerId)} · {CLUE_LABELS[event.suspect]} / {CLUE_LABELS[event.weapon]} / {CLUE_LABELS[event.room]} 최종 지목 <b>{event.correct?"성공":"실패"}</b></p>}</article>;})}</div>;
}
