import {marsPrintedRequirements} from './requirements.js';
import { marsCard, marsCardDescription, MARS_TAG_NAMES, MARS_CARD_RESOURCE_NAMES, type MarsCard, type MarsDefinition } from '@hangul-rummikub/shared';

export const MARS_FEATURED_ART:Readonly<Partial<Record<string,number>>>={Fish:0,Psychrophiles:1,OlympusConference:2,SecurityFleet:3};
export const MARS_ECOLOGY_ART:Readonly<Partial<Record<string,number>>>={Tardigrades:0,Birds:1,SmallAnimals:2,Livestock:3};
export function MarsArt({cell,className='',definitionId}:{cell:number;className?:string;definitionId?:string}){
 const ecology=definitionId?MARS_ECOLOGY_ART[definitionId]:undefined;
 const featured=ecology??(definitionId?MARS_FEATURED_ART[definitionId]:undefined);
 const atlas=ecology===undefined?'featured-cards-v1.webp':'ecology-cards-v1.webp';
 return <span aria-hidden="true" className={'tm-art '+className} style={featured===undefined?{backgroundPosition:`${cell%4*100/3}% ${Math.floor(cell/4)*50}%`}:{backgroundImage:`url("/images/mars/${atlas}")`,backgroundSize:'200% 200%',backgroundPosition:`${featured%2*100}% ${Math.floor(featured/2)*100}%`}}/>;
}
export function marsScoreLabel(d:MarsDefinition){return d.score==='resources'&&d.resourceScore?`${MARS_CARD_RESOURCE_NAMES[d.resource??'']??'자원'} ${d.resourceScore.per}개당 ${d.resourceScore.points} VP`:d.score==='jovian'?'목성 태그당 1 VP':d.score==='cities'?'전체 도시 3개당 1 VP':d.score==='adjacentCities'?'인접 도시당 1 VP':d.score==='capital'?'인접 해양당 1 VP':d.score==='life'?'과학 자원 보유 시 3 VP':d.points?`${d.points} VP`:'';}
export function marsCardActionStatus(card:MarsCard,generation?:number):string|null{
 return generation!==undefined&&marsCard(card.definitionId).actions?(card.usedGeneration===generation?'이번 세대 사용 완료':'이번 세대 행동 미사용'):null;
}
export function MarsCardView({card,selected=false,reason=null,cost,onSelect,disabled=false,generation}:{card:MarsCard;selected?:boolean;reason?:string|null;cost?:number;onSelect():void;disabled?:boolean;generation?:number}){const d=marsCard(card.definitionId),requirements=marsPrintedRequirements(d),actionStatus=marsCardActionStatus(card,generation);return <button className={`tm-card ${d.type} ${selected?'selected':''}`} aria-pressed={selected} disabled={disabled} onClick={onSelect} aria-label={`${d.name} · ${d.type==='prelude'?'프렐류드':`${cost??d.cost} M€`}${requirements?' · 인쇄 조건: '+requirements:''}${d.resource?' · '+MARS_CARD_RESOURCE_NAMES[d.resource]+' '+card.resources+'개':''}${actionStatus?' · '+actionStatus:''}${reason?' · '+reason:''}`}><div className="tm-card-top"><b>{d.type==='prelude'?'P':cost??d.cost}<small>{d.type==='prelude'?'시작':'M€'}</small></b><strong>{d.name}<small className="tm-card-english">{d.englishName}</small></strong></div><MarsArt cell={d.art} definitionId={d.id}/><span className="tm-card-tags">{d.tags.map((t,i)=><span key={i}>{MARS_TAG_NAMES[t]}</span>)}</span>{requirements&&<span className="tm-card-requirements"><b>인쇄 조건</b> {requirements}</span>}<span className="tm-card-description">{marsCardDescription(d)}</span><span className="tm-card-footer"><span>{d.type==='prelude'?'프렐류드':d.type==='event'?'이벤트':d.type==='active'?'지속·행동':'자동화'} · #{d.number}</span><b>{marsScoreLabel(d)}</b></span>{reason&&<span className="tm-card-blocked">{reason}</span>}{d.resource&&<span className="tm-card-counter">{MARS_CARD_RESOURCE_NAMES[d.resource]??'자원'} {card.resources}</span>}</button>;}
