import { useState } from 'react';
import { MARS_RESOURCE_NAMES, marsCard, marsPaymentValue, type MarsProjection, type MarsAction, type MarsPayment } from '@hangul-rummikub/shared';

/** Adjust only M€; material selection remains an explicit player choice. */
export function marsPaymentMoneyTopUp(spend: MarsPayment, info: {cost:number;steelValue:2|3;titaniumValue:3|4|5}, money:number):number|null {
 const amounts=[spend.steel,spend.titanium,spend.heat,spend.microbes??0];
 if(!amounts.every(n=>Number.isSafeInteger(n)&&n>=0))return null;
 const materialValue=marsPaymentValue({...spend,money:0},info);
 if(!Number.isSafeInteger(materialValue))return null;
 return Math.min(money,Math.max(0,info.cost-materialValue));
}

export function MarsPaymentPanel({game:g,busy,onPay}:{game:MarsProjection;busy:boolean;onPay(a:MarsAction):void}){const info=g.privateState.payment!,me=g.playerStates.find(p=>p.playerId===g.privateState.playerId)!,[microbes,setMicrobes]=useState(0),[spend,setSpend]=useState({money:Math.min(info.cost,me.resources.money),steel:0,titanium:0,heat:0}),value=marsPaymentValue({...spend,microbes},info),reservedHeat=(info.cardId?g.privateState.hand.find(c=>c.tileId===info.cardId):null),heatCost=reservedHeat?marsCard(reservedHeat.definitionId).effects.reduce((n,e)=>n+(e.kind==='stock'&&e.resource==='heat'&&e.amount<0?-e.amount:0),0):0,topUp=marsPaymentMoneyTopUp({...spend,microbes},info,me.resources.money),legal=Number.isSafeInteger(microbes)&&microbes>=0&&microbes<=(info.microbes??0)&&spend.heat<=me.resources.heat-heatCost&&value>=info.cost&&(['money','steel','titanium','heat']as const).every(k=>Number.isSafeInteger(spend[k])&&spend[k]>=0&&spend[k]<=me.resources[k]);
 return <div className="tm-payment"><h3>{info.label}</h3><div className="tm-price"><span>필요 비용</span><b>{info.cost}<small> M€</small></b></div>{(['money','steel','titanium','heat']as const).filter(k=>k==='money'||info[k]).map(k=><label key={k}><span>{MARS_RESOURCE_NAMES[k]} <small>{k==='steel'?`×${info.steelValue}`:k==='titanium'?`×${info.titaniumValue}`:'×1'}</small></span><input type="number" inputMode="numeric" min="0" max={k==='heat'?Math.max(0,me.resources.heat-heatCost):me.resources[k]} step="1" value={spend[k]} disabled={busy} onChange={e=>setSpend({...spend,[k]:Number(e.target.value)})}/><small>보유 {me.resources[k]} · 지불 후 {Number.isSafeInteger(spend[k])&&spend[k]>=0&&spend[k]<=me.resources[k]?me.resources[k]-spend[k]:'—'}</small></label>)}{(info.microbes??0)>0&&<label><span>호냉성 미생물 <small>×2 M€</small></span><input aria-label="지불할 미생물" type="number" inputMode="numeric" min="0" max={info.microbes} step="1" value={microbes} disabled={busy} onChange={e=>setMicrobes(Number(e.target.value))}/><small>보유 {info.microbes} · 지불 후 {Number.isSafeInteger(microbes)&&microbes>=0&&microbes<=info.microbes! ? info.microbes!-microbes : '—'} · 식물 태그 카드 전용</small></label>}{heatCost>0&&<p>카드 효과에 열 {heatCost}개를 별도로 사용합니다.</p>}<p className="tm-payment-note">지불 후 수량은 이 비용만 차감한 값입니다. 카드 효과와 배치 보너스는 실행 후 반영됩니다.</p>{(info.steel||info.titanium||info.heat||(info.microbes??0)>0)&&<button type="button" disabled={busy||topUp===null||topUp===spend.money} onClick={()=>{if(topUp!==null)setSpend({...spend,money:topUp});}}>부족분 M€로 맞추기</button>}<p role="status" aria-live="polite" aria-atomic="true">지불 가치 <b>{value} M€</b>{value>info.cost&&<span className="tm-warning"> · 초과 {value-info.cost} M€는 반환되지 않습니다.</span>}{value<info.cost&&<span> · {info.cost-value} M€ 부족</span>}</p><button className="tm-primary" disabled={busy||!legal} onClick={()=>onPay({type:'PAY',payment:{...spend,...(microbes?{microbes}:{})}})}>지불·실행 확정</button></div>;
}
