import assert from 'node:assert/strict';
import test from 'node:test';
import * as v from 'valibot';
import {readFileSync} from 'node:fs';
import {MarsPlayingProjectionSchema, MARS_CARDS, marsCardDescription, marsResources} from '@hangul-rummikub/shared';
import {marsFeedback} from '../features/mars/sound.js';
import {GAME_CATALOG} from '../features/game-catalog/game-catalog.js';
import {WEB_SUPPORTED_GAME_TYPES} from './snapshot-wire-decoder.js';
function game(revision=1){return v.parse(MarsPlayingProjectionSchema,{gameType:'TERRAFORMING_MARS',gameId:'mars-feedback',gameRevision:revision,rulesVersion:'mars-base-v1',generation:1,stage:'ACTION',activePlayerId:'mars-a',startingPlayerId:'mars-a',actionsTaken:0,oxygen:0,temperature:-30,oceans:0,tiles:[],milestones:[],awards:[],history:[],deckCount:137,discardCount:0,phase:'PLAYING',turnId:'mars-turn',playerStates:['mars-a','mars-b'].map(playerId=>({playerId,corporationId:'Beginner',resources:marsResources({money:42}),production:marsResources(),tr:20,handCount:0,played:[],passed:false,ready:true,generationStartTr:20,corporationUsedGeneration:0})),privateState:{playerId:'mars-a',hand:[],research:[],corporations:[],offers:[],payment:null,cardStatus:[]}});}
test('Mars sound and resource feedback ignore initial, duplicated, missed and reconnected snapshots',()=>{const old=game(),next=game(2);next.oceans=1;next.playerStates[0]!.resources.money-=18;assert.deepEqual(marsFeedback(old,next,true),{cue:'WATER',deltas:{money:-18}});for(const [previous,current,continuous] of [[null,next,true],[next,next,true],[old,game(4),true],[old,next,false]]as const)assert.deepEqual(marsFeedback(previous,current,continuous),{cue:null,deltas:{}});next.gameId=old.gameId;next.temperature=-28;next.oceans=0;assert.equal(marsFeedback(old,next,true).cue,'HEAT');next.generation=2;assert.equal(marsFeedback(old,next,true).cue,'PRODUCTION');});
test('Mars catalog, browser capability, original art and all card descriptions are available',()=>{assert.ok(GAME_CATALOG.some(g=>g.gameType==='TERRAFORMING_MARS'));assert.ok(WEB_SUPPORTED_GAME_TYPES.includes('TERRAFORMING_MARS'));for(const file of ['terrain.webp','cards-atlas.webp'])assert.equal(readFileSync(new URL('../../public/images/mars/'+file,import.meta.url)).subarray(8,12).toString(),'WEBP');for(const c of MARS_CARDS){assert.ok(marsCardDescription(c).length>0,c.id);assert.doesNotMatch(marsCardDescription(c),/undefined|NaN/);}});
