import assert from 'node:assert/strict';
import test from 'node:test';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {parse,safeParse} from 'valibot';
import {PANDEMIC_CITIES,PANDEMIC_ROLES,PANDEMIC_ROLE_INFO,PandemicPlayingPlatformSnapshotV2Schema,PandemicLobbyPlatformSnapshotV2Schema,PandemicClientCommandSchema,GameRevisionSchema,TileIdSchema,type PandemicCard} from '@hangul-rummikub/shared';
import {PandemicScreen} from '../features/pandemic/PandemicScreen.js';
import {pandemicFeedback,pandemicMoveOptions} from '../features/pandemic/presentation.js';
import {decodeWebSnapshot,type PandemicWebSnapshot} from './snapshot-wire-decoder.js';
import {resolveRoomSnapshotView} from './room-snapshot-view.js';
const players=[{playerId:'a',nickname:'하비',isHost:true,connectionStatus:'CONNECTED'},{playerId:'b',nickname:'민서',isHost:false,connectionStatus:'CONNECTED'}];
function lobby(){return parse(PandemicLobbyPlatformSnapshotV2Schema,{snapshotVersion:2,versions:{roomRevision:1,presenceVersion:1},serverTime:1000,self:{playerId:'a'},room:{roomId:'pd',roomCode:'ABCDEF',gameType:'PANDEMIC',phase:'LOBBY',players},game:null});}
function playing(){const l=lobby();return parse(PandemicPlayingPlatformSnapshotV2Schema,{...l,room:{...l.room,phase:'PLAYING'},game:{gameType:'PANDEMIC',gameId:'g',gameRevision:1,rulesVersion:'pandemic-base-v1',phase:'ACTIONS',turnId:'t',settings:{epidemics:4,openHands:true},playerStates:players.map((p,i)=>({playerId:p.playerId,role:i?'MEDIC':'SCIENTIST',city:'ATLANTA',handCount:0,hand:[],stored:null})),activePlayerId:'a',actionsLeft:4,round:1,board:PANDEMIC_CITIES.map(city=>({city,cubes:{BLUE:0,YELLOW:0,BLACK:0,RED:0}})),stations:['ATLANTA'],supply:{BLUE:24,YELLOW:24,BLACK:24,RED:24},cures:{BLUE:'ACTIVE',YELLOW:'ACTIVE',BLACK:'ACTIVE',RED:'ACTIVE'},outbreaks:0,rateIndex:0,playerDeckCount:49,infectionDeckCount:39,discard:[],infectionDiscard:[],infectionRemoved:[],lastInfected:null,infectionRemaining:0,epidemicsRemaining:0,quietNight:false,operationsUsed:false,pending:null,continueReady:[],history:[],pings:[],privateState:{playerId:'a',forecast:null}}});}
const render=(snapshot:PandemicWebSnapshot,connected=true)=>renderToStaticMarkup(createElement(PandemicScreen,{snapshot,connected,pending:false,error:null,connectionLabel:'서버 연결됨',onCommand:async()=>{},onRematch(){},onStart(){},onLeave(){},onCopy(){}}));
test('Pandemic UI: lobby and map render actual art, all 48 cities, keyboard actions and sound controls',()=>{for(const s of [lobby(),playing()]){const decoded=decodeWebSnapshot(s);assert.equal(decoded.kind,'COMPATIBLE');if(decoded.kind==='COMPATIBLE')assert.equal(resolveRoomSnapshotView(decoded.value).kind,'PANDEMIC');const html=render(s);assert.match(html,/효과음 음량/);assert.match(html,/배경음악 음량/);}const html=render(playing());assert.equal((html.match(/role="button"/g)??[]).length,48);assert.equal((html.match(/tabindex="0"/g)??[]).length,48);assert.match(html,/images\/pandemic\/world.webp/);assert.match(html,/도시 찾기/);assert.match(html,/확정하세요/);assert.match(render(playing(),false),/연결 복구/);});
test('Pandemic UI: setup renders all 7 role illustrations, difficulty and start affordance',()=>{const s=playing();s.game.phase='SETUP';const html=render(s);for(const role of PANDEMIC_ROLES)assert.ok(html.includes(PANDEMIC_ROLE_INFO[role].name));assert.match(html,/검역 전문가/);assert.match(html,/위기관리자/);assert.match(html,/영웅 · 전염병 6장/);assert.match(html,/작전 시작/);});
test('Pandemic movement preview compares costs and cannot offer dispatcher-only actions to another role',()=>{const g=playing().game,self=g.playerStates[0]!.playerId,other=g.playerStates[1]!.playerId;const c:PandemicCard={kind:'CITY',cardId:parse(TileIdSchema,'paris'),city:'PARIS'};g.playerStates[0]!.hand=[c];g.playerStates[0]!.handCount=1;assert.equal(pandemicMoveOptions(g,self,self,'CHICAGO')[0]?.action.mode,'DRIVE');assert.equal(pandemicMoveOptions(g,self,self,'PARIS')[0]?.action.cardId,c.cardId);assert.deepEqual(pandemicMoveOptions(g,self,other,'CHICAGO'),[]);g.playerStates[0]!.role='DISPATCHER';assert.match(pandemicMoveOptions(g,self,other,'CHICAGO')[0]!.cost,/동료 동의/);});
test('Pandemic cues are silent for initial/resume/skipped/duplicate/old snapshots, distinguish treatment and outbreak',()=>{const a=playing().game,b=structuredClone(a);b.gameRevision=parse(GameRevisionSchema,2);b.history=[{id:1,text:'치료',sound:'TREAT',city:'ATLANTA'},{id:2,text:'발병',sound:'OUTBREAK',city:'CHICAGO'}];assert.deepEqual(pandemicFeedback(null,b),[]);assert.deepEqual(pandemicFeedback(b,b),[]);assert.deepEqual(pandemicFeedback(b,a),[]);assert.deepEqual(pandemicFeedback(a,{...b,gameRevision:parse(GameRevisionSchema,3)}),[]);assert.deepEqual(pandemicFeedback(a,b).map(e=>e.sound),['TREAT','OUTBREAK']);});
test('Pandemic projection rejects wrong viewer, hidden hand leakage, wrong cube supply and injected server deck',()=>{const s=playing();for(const game of [{...s.game,privateState:{playerId:'b',forecast:null}},{...s.game,infectionDeck:[]},{...s.game,supply:{...s.game.supply,BLUE:23}},{...s.game,settings:{epidemics:4,openHands:false}}])assert.equal(safeParse(PandemicPlayingPlatformSnapshotV2Schema,{...s,game}).success,false);const c={protocolVersion:1,kind:'pandemic:act',requestId:'r',gameId:'g',expectedGameRevision:1,turnId:'t',payload:{type:'CONTINUE'}};assert.equal(safeParse(PandemicClientCommandSchema,c).success,true);assert.equal(safeParse(PandemicClientCommandSchema,{...c,payload:{type:'CONTINUE',nextCard:'TOKYO'}}).success,false);});
test('Pandemic UI handles consent, private share selection, forecast and event window',()=>{const s=playing();s.game.phase='DRAW';assert.match(render(s),/이벤트 없이 계속/);s.game.pending={kind:'SHARE_PICK',proposer:s.game.playerStates[1]!.playerId,responder:s.self.playerId};assert.match(render(s),/공유할 도시 카드를 선택/);s.game.pending={kind:'FORECAST',playerId:s.self.playerId};s.game.privateState.forecast=['TOKYO','SEOUL'];assert.match(render(s),/도쿄 위로/);assert.match(render(s),/이 순서로 확정/);});
