import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { parse, safeParse } from 'valibot';
import { PerchPlayingPlatformSnapshotV2Schema, PerchLobbyPlatformSnapshotV2Schema, PerchClientCommandSchema, perchFountainCells, PERCH_LOCATION_INFO, type PerchLocation } from '@hangul-rummikub/shared';
import { PerchScreen } from '../features/perch/PerchScreen.js';
import { perchNewSoundIds } from '../features/perch/sound.js';
import { decodeWebSnapshot, type PerchWebSnapshot } from './snapshot-wire-decoder.js';
import { resolveRoomSnapshotView } from './room-snapshot-view.js';
const players = [{ playerId: 'a', nickname: '하비', isHost: true, connectionStatus: 'CONNECTED' }, { playerId: 'b', nickname: '민서', isHost: false, connectionStatus: 'CONNECTED' }];
function lobby() { return parse(PerchLobbyPlatformSnapshotV2Schema, { snapshotVersion: 2, versions: { roomRevision: 1, presenceVersion: 1 }, serverTime: 1000, self: { playerId: 'a' }, room: { roomId: 'pc', roomCode: 'ABCDEF', gameType: 'PERCH', phase: 'LOBBY', players }, game: null }); }
function playing() { const l = lobby(), defs: PerchLocation[] = ['PINE', 'ASH', 'DOGHOUSE', 'COTTAGE', 'HANGING', 'EARLY', 'ELM', 'HAWK_NEST']; return parse(PerchPlayingPlatformSnapshotV2Schema, { ...l, room: { ...l.room, phase: 'PLAYING' }, game: { gameType: 'PERCH', gameId: 'g', gameRevision: 1, rulesVersion: 'perch-base-v1', phase: 'PERCH', turnId: 't', settings: { randomBoard: false, objectives: true }, playerStates: players.map((p, i) => ({ playerId: p.playerId, flock: i, score: 0, hand: [{ birdId: `bird${i}`, flock: i }], supplyCount: 27, objectiveSelected: true, house: false, lightning: false })), activePlayerId: 'a', round: 1, board: defs.map((definitionId, i) => ({ tileId: `tile${i}`, definitionId, col: i < 3 ? 0 : i < 5 ? 1 : 2, row: i < 3 ? i * 2 : i < 5 ? (i - 3) * 2 + 1 : (i - 5) * 2, removed: false, nests: Array.from({ length: PERCH_LOCATION_INFO[definitionId].nests }, () => true), stacks: [] })), creatures: [], fountain: perchFountainCells(2).map(() => null), plaza: [], bagCount: 0, neutralSupplyCount: 28, turnOrder: ['a', 'b'], placed: false, bonusUsed: false, pending: null, history: [], roundScores: [], privateState: { playerId: 'a', objective: 'HIDDEN', objectiveChoices: [] } } }); }
const render = (snapshot: PerchWebSnapshot, connected = true) => renderToStaticMarkup(createElement(PerchScreen, { snapshot, connected, pending: false, error: null, connectionLabel: '서버 연결됨', onCommand: async () => { }, onRematch() { }, onStart() { }, onLeave() { }, onCopy() { } }));
test('Perch UI: lobby route, illustrated cards, accessible hand actions, fountain and audio volume', () => { for (const s of [lobby(), playing()]) {
    const d = decodeWebSnapshot(s);
    assert.equal(d.kind, 'COMPATIBLE');
    if (d.kind === 'COMPATIBLE')
        assert.equal(resolveRoomSnapshotView(d.value).kind, 'PERCH');
    assert.match(render(s), /퍼치 효과음 음량/);
} const html = render(playing()); assert.match(html, /pc-location-art/); assert.match(readFileSync('src/features/perch/perch.css', 'utf8'), /images\/perch\/locations.png/); assert.match(html, /images\/perch\/fountain.png/); assert.match(html, /내가 배치할 새/); assert.match(html, /aria-pressed/); assert.match(html, /나의 비밀 목표/); assert.match(render(playing(), false), /연결을 복구/); });
test('Perch UI: setup and private choice phases expose meaningful instructions', () => { const s = playing(); s.game.phase = 'SETUP'; assert.match(render(s), /오늘의 숲을 골라주세요/); assert.match(render(s), /무작위 · 전체 24종/); s.game.phase = 'OBJECTIVES'; s.game.privateState.objectiveChoices = ['HIDDEN', 'EGRETS']; s.game.privateState.objective = null; s.game.playerStates[0]!.objectiveSelected = false; const html = render(s); assert.match(html, /두 장 중 한 장/); assert.match(html, /A SECRET AMBITION/); });
test('Perch contracts reject wrong viewer, hidden bag, forged command, unsupported fountain and duplicate birds', () => { const s = playing(); for (const game of [{ ...s.game, privateState: { ...s.game.privateState, playerId: 'b' } }, { ...s.game, bag: [] }, { ...s.game, playerStates: s.game.playerStates.map(p => ({ ...p, hand: [s.game.playerStates[0]!.hand[0]!] })) }, { ...s.game, pending: { actor: 'b', title: 'hidden', kind: 'FOUNTAIN', choices: [{ id: 'x', label: 'private', tileIds: [], birdId: null, slot: 0 }] } }])
    assert.equal(safeParse(PerchPlayingPlatformSnapshotV2Schema, { ...s, game }).success, false); const c = { protocolVersion: 1, kind: 'perch:act', requestId: 'r', gameId: 'g', expectedGameRevision: 1, turnId: 't', payload: { type: 'END_TURN' } }; assert.equal(safeParse(PerchClientCommandSchema, c).success, true); assert.equal(safeParse(PerchClientCommandSchema, { ...c, payload: { type: 'END_TURN', score: 99 } }).success, false); });
test('Perch sounds skip first view, disconnected state, duplicate and old history; new cues are unique', () => { const g = playing().game; g.history = [{ id: 1, text: '배치', sound: 'PLACE', tileId: null }, { id: 2, text: '분수', sound: 'WATER', tileId: null }]; assert.deepEqual(perchNewSoundIds(null, g, true), []); assert.deepEqual(perchNewSoundIds({ gameId: 'different', sequence: 0 }, g, true), []); assert.deepEqual(perchNewSoundIds({ gameId: 'g', sequence: 0 }, g, false), []); assert.deepEqual(perchNewSoundIds({ gameId: 'g', sequence: 2 }, g, true), []); assert.deepEqual(perchNewSoundIds({ gameId: 'g', sequence: 3 }, g, true), []); assert.deepEqual(perchNewSoundIds({ gameId: 'g', sequence: 0 }, g, true), [1, 2]); });
