import assert from 'node:assert/strict';
import test from 'node:test';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { parse, safeParse } from 'valibot';
import { SpiritLobbyPlatformSnapshotV2Schema, SpiritPlayingPlatformSnapshotV2Schema, SPIRIT_BOARD_DATA, SPIRIT_POWERS, spiritBoardLinks, spiritProjectionIsConsistent, SpiritActionSchema } from '@hangul-rummikub/shared';
import { SpiritScreen } from '../features/spirit-island/SpiritScreen.js';
import { spiritTransitionCues } from '../features/spirit-island/sound.js';
const players = [{ playerId: 'a', nickname: '강', isHost: true, connectionStatus: 'CONNECTED' }];
function lobby() { return parse(SpiritLobbyPlatformSnapshotV2Schema, { snapshotVersion: 2, versions: { roomRevision: 1, presenceVersion: 1 }, serverTime: 1000, self: { playerId: 'a' }, room: { roomId: 'spirit-room', roomCode: 'ABCDEF', gameType: 'SPIRIT_ISLAND', phase: 'LOBBY', players }, game: null }); }
function playing() { const s = lobby(), cards = SPIRIT_POWERS.filter(c => c.deck === 'RIVER').map(c => ({ cardId: c.key, key: c.key })), links = spiritBoardLinks(1); return parse(SpiritPlayingPlatformSnapshotV2Schema, { ...s, room: { ...s.room, phase: 'PLAYING' }, game: { gameType: 'SPIRIT_ISLAND', rulesVersion: 'spirit-island-intro-v1', gameId: 'game', gameRevision: 0, phase: 'PLAYING', turnId: 'turn', stage: 'PREPARE', round: 1, lands: SPIRIT_BOARD_DATA.A.terrains.map((terrain, i) => { const id = `A${i + 1}`; return { id, board: 'A', number: i + 1, terrain, coastal: i < 3, adjacent: links.flatMap(([a, b]) => a === id ? [b] : b === id ? [a] : []), pieces: [], presence: i === 4 ? [{ playerId: 'a', count: 1 }] : [], blight: i === 3 ? 1 : 0, defend: 0, skip: false, protectDahan: false, vitality: false, dahanHealth: 0 }; }), playerStates: [{ playerId: 'a', spirit: 'RIVER', board: 'A', energy: 2, energyTrack: 0, cardTrack: 0, destroyedPresence: 0, grown: true, ready: false, hand: cards, played: [], discard: [], resolved: [], elements: [], fastRemaining: 0, repeatRemaining: 0 }], fear: 0, fearPool: 4, terror: 1, fearDeckCount: 9, earnedFearCount: 0, blightPool: 6, ravage: null, build: null, explore: null, invaderDeckCount: 11, pending: null, plans: [], log: [], privateState: { playerId: 'a', hand: cards, powerOptions: [] } } }); }
const handlers = { connected: true, pending: false, error: null, connectionLabel: '연결됨', async onCommand() { }, onRematch() { }, onStart() { }, onLeave() { }, onCopy() { } };
test('Spirit UI: illustrated lobby, solo start, accessible sound, map and cards', () => { const welcome = renderToStaticMarkup(createElement(SpiritScreen, { ...handlers, snapshot: lobby() })); assert.match(welcome, /섬으로 들어가기/); assert.match(welcome, /효과음 음량/); assert.match(welcome, /1–4인/); const s = playing(), html = renderToStaticMarkup(createElement(SpiritScreen, { ...handlers, snapshot: s })); assert.ok(spiritProjectionIsConsistent(s.game)); assert.equal((html.match(/class="si-land si-terrain-/g) ?? []).length, 8); assert.match(html, /강의 풍요/); assert.match(html, /카드 준비 확정/); assert.match(html, /aria-pressed="false"/); assert.match(html, /si-panel-portrait/); assert.match(html, /prefers-reduced-motion|진행 방법과 이번 버전 안내/); });
test('Spirit sounds deduplicate revisions and establish silent initial/reconnect baseline', () => { const a = playing().game, b = structuredClone(a); b.gameRevision = parse(SpiritPlayingPlatformSnapshotV2Schema, { ...playing(), game: { ...b, gameRevision: 1 } }).game.gameRevision; b.log = [{ id: 1, kind: 'DAMAGE', text: '피해', playerId: a.privateState.playerId, landId: 'A1' }]; assert.deepEqual(spiritTransitionCues(null, b), []); assert.deepEqual(spiritTransitionCues(a, b), ['DAMAGE']); assert.deepEqual(spiritTransitionCues(b, b), []); assert.deepEqual(spiritTransitionCues(b, a), []); });
test('Spirit contracts reject unrecognized fields and mismatched self hand', () => { assert.equal(safeParse(SpiritActionSchema, { kind: 'GROW', option: 0, energy: 99 }).success, false); assert.equal(safeParse(SpiritActionSchema, { kind: 'USE_POWER', cardId: 'x', target: 'A1', threshold: 99, fast: true, repeat: false, shadowReach: false }).success, false); const s = playing(); assert.equal(safeParse(SpiritPlayingPlatformSnapshotV2Schema, { ...s, game: { ...s.game, privateState: { ...s.game.privateState, hand: [] } } }).success, false); });
