import * as v from 'valibot';
import {TerrorTraitSchema,TerrorDifficultySchema} from './traits.js';
import {TerrorPlanSchema} from './plans.js';

import { TileIdSchema,GameIdSchema,PlayerIdSchema,TurnIdSchema } from '../../identifiers.js';
import { GameRevisionSchema } from '../../protocol.js';
import { TerrorMapSchema,TerrorHuntTrapSchema,TerrorTrapPlacementSchema,TerrorCharacterSchema,TerrorRoomSchema,TerrorCardSchema,TerrorKillerCardSchema,TerrorKillerSchema } from './actions.js';
export const TerrorSensedSchema=v.variant('kind',[v.strictObject({kind:v.literal('ZONE'),character:TerrorCharacterSchema,zone:v.picklist(['R','B','G'])}),v.strictObject({kind:v.literal('PAIR'),character:TerrorCharacterSchema,rooms:v.pipe(v.array(TerrorRoomSchema),v.minLength(1),v.maxLength(15))}),v.strictObject({kind:v.literal('LOCATION'),character:TerrorCharacterSchema,location:TerrorRoomSchema})]);
export const TerrorCount=v.pipe(v.number(),v.safeInteger(),v.minValue(0));
export const TerrorSurvivorSchema=v.strictObject({character:TerrorCharacterSchema,outcome:v.picklist(['ACTIVE','ESCAPED','DEAD']),playerId:PlayerIdSchema,location:TerrorRoomSchema,fear:v.pipe(TerrorCount,v.maxValue(2)),injuries:v.pipe(TerrorCount,v.maxValue(2)),hand:v.pipe(v.array(TerrorCardSchema),v.maxLength(49)),immobilized:v.optional(v.boolean(),false),acted:v.boolean(),ready:v.boolean()});
export const TerrorEncounterSchema=v.strictObject({location:TerrorRoomSchema,targets:v.array(TerrorCharacterSchema),attacked:v.array(TerrorCharacterSchema),defender:v.nullable(TerrorCharacterSchema),fleePending:v.array(TerrorCharacterSchema)});
export const TerrorLogSchema=v.strictObject({id:TerrorCount,text:v.pipe(v.string(),v.maxLength(240)),sound:v.picklist(['STEP','CARD','NOISE','BLOCK','FEAR','DEFENSE','HURT','TURN','WIN','NONE'])});
export const TerrorResultSchema=v.strictObject({reason:v.picklist(['SEPARATE_WAYS','STRIKE_BACK','ESCAPED','RESCUED','KILLED','EXHAUSTED','CANCELLED']),winnerPlayerIds:v.array(PlayerIdSchema)});
export const TerrorLootSchema=v.strictObject({character:TerrorCharacterSchema,cards:v.pipe(v.array(TerrorCardSchema),v.maxLength(5)),source:v.picklist(['SEARCH','DISCOVER','REWARD'])});
export const TerrorPlanStateSchema=v.strictObject({cards:v.pipe(v.array(TerrorPlanSchema),v.maxLength(2)),active:v.nullable(TerrorPlanSchema),progress:v.pipe(v.number(),v.integer(),v.minValue(0),v.maxValue(4)),complete:v.boolean(),used:v.boolean(),location:v.nullable(TerrorRoomSchema),chooser:v.nullable(TerrorCharacterSchema)});

export const TerrorSurvivorTraitSchema=v.strictObject({character:TerrorCharacterSchema,offered:v.pipe(v.array(TerrorTraitSchema),v.maxLength(2)),chosen:v.nullable(TerrorTraitSchema)});
export const TerrorTeamSchema=v.strictObject({suitcase:v.optional(v.boolean(),false),treasures:v.optional(v.array(TerrorRoomSchema),()=>[]),specialCount:v.optional(TerrorCount,0),survivors:v.pipe(v.array(TerrorSurvivorSchema),v.length(3)),traits:v.array(TerrorSurvivorTraitSchema),usedTraits:v.array(TerrorTraitSchema),plan:TerrorPlanStateSchema,keyOwners:v.array(v.strictObject({cardId:TileIdSchema,character:TerrorCharacterSchema})),keys:TerrorCount,repair:v.pipe(TerrorCount,v.maxValue(5)),repaired:v.boolean(),rescue:v.nullable(TerrorCount),trap:v.nullable(TerrorRoomSchema),searchCount:TerrorCount,discoverCount:TerrorCount,discard:v.array(TerrorCardSchema),loot:v.nullable(TerrorLootSchema),pings:v.pipe(v.array(v.strictObject({room:TerrorRoomSchema,message:v.picklist(['GO','SEARCH','REPAIR','HELP']),playerId:PlayerIdSchema})),v.maxLength(6))});
export const TerrorKillerViewSchema=v.strictObject({traps:v.optional(v.array(TerrorTrapPlacementSchema),()=>[]),trapsReady:v.optional(v.boolean(),false),traitOffer:v.array(TerrorTraitSchema),traitsChosen:v.boolean(),usedTraits:v.array(TerrorTraitSchema),senseTargets:v.array(TerrorCharacterSchema),levelTrait:v.nullable(TerrorTraitSchema),hand:v.pipe(v.array(TerrorKillerCardSchema),v.maxLength(6)),deckCount:TerrorCount,discardCount:TerrorCount,actionsLeft:TerrorCount,slowUsed:v.boolean(),discard:v.array(TerrorKillerCardSchema),fearTarget:v.nullable(TerrorCharacterSchema),levelBlocksRemaining:TerrorCount});
export const TerrorTrapRevealSchema=v.strictObject({sequence:TerrorCount,room:TerrorRoomSchema,trap:TerrorHuntTrapSchema,character:TerrorCharacterSchema});
export const TerrorTrackingSchema=v.strictObject({character:TerrorCharacterSchema,origin:TerrorRoomSchema,distance:TerrorCount});
const Base={setupReady:v.optional(v.array(PlayerIdSchema),()=>[]),killerSelected:v.optional(v.boolean(),false),survivorSelected:v.optional(v.pipe(v.array(v.boolean()),v.length(3)),()=>[false,false,false]),trapsPrepared:v.optional(v.boolean(),false),map:v.optional(TerrorMapSchema,'MANOR'),huntingTrapRooms:v.optional(v.array(TerrorRoomSchema),()=>[]),trapReveal:v.optional(v.nullable(TerrorTrapRevealSchema),null),tracking:v.optional(v.nullable(TerrorTrackingSchema),null),gameType:v.literal('TERRORSCAPE'),gameId:GameIdSchema,gameRevision:GameRevisionSchema,rulesVersion:v.picklist(['terrorscape-base-v2','terrorscape-feral-v2']),playerStates:v.pipe(v.array(v.strictObject({playerId:PlayerIdSchema})),v.minLength(2),v.maxLength(4)),killerPlayerId:PlayerIdSchema,owners:v.pipe(v.array(PlayerIdSchema),v.length(3)),round:TerrorCount,difficulty:TerrorDifficultySchema,killerTraits:v.array(TerrorTraitSchema),groupMove:v.nullable(v.strictObject({targets:v.array(TerrorCharacterSchema),max:TerrorCount})),plansEnabled:v.boolean(),separateWays:v.boolean(),firstDiscover:v.nullable(TerrorCharacterSchema),keys:TerrorCount,killerType:TerrorKillerSchema,killerLocation:v.nullable(TerrorRoomSchema),stealthOrigin:v.nullable(TerrorRoomSchema),level:v.pipe(TerrorCount,v.minValue(1),v.maxValue(5)),strength:TerrorCount,blocks:v.pipe(v.array(v.string()),v.maxLength(7)),noises:v.array(TerrorRoomSchema),firecracker:v.boolean(),conditions:v.pipe(v.array(v.strictObject({character:TerrorCharacterSchema,outcome:v.picklist(['ACTIVE','ESCAPED','DEAD']),keys:TerrorCount,fear:TerrorCount,injuries:TerrorCount,immobilized:v.optional(v.boolean(),false)})),v.length(3)),sensed:v.array(TerrorSensedSchema),encounter:v.nullable(TerrorEncounterSchema),dice:v.array(TerrorCount),defenseTotal:v.nullable(TerrorCount),history:v.pipe(v.array(TerrorLogSchema),v.maxLength(80)),privateState:v.variant('role',[
 v.strictObject({role:v.literal('KILLER'),playerId:PlayerIdSchema,killer:TerrorKillerViewSchema}),
 v.strictObject({role:v.literal('SURVIVOR'),playerId:PlayerIdSchema,team:TerrorTeamSchema}),
])};
export const TerrorscapePlayingProjectionSchema=v.strictObject({...Base,phase:v.picklist(['RESET_TRAPS','TRAIT_DRAFT','KILLER_START','KILLER_END','SENSE_REACTION','LEVEL_TRAIT','TOYING','HEROIC','GROUP_MOVE','SETUP','PLAN','SURVIVORS','LOOT','KILLER','FAST','MAIN','SLOW','RAGE','UNLOCK','WHIZZ','REACTION','REAPPEAR','LEVEL_BLOCK','ATTACK','DEFENDER','DEFEND','FLEE']),turnId:TurnIdSchema});
export const TerrorscapeFinishedProjectionSchema=v.strictObject({...Base,phase:v.literal('FINISHED'),result:TerrorResultSchema});
export type TerrorscapePlayingProjection=v.InferOutput<typeof TerrorscapePlayingProjectionSchema>;
export type TerrorscapeFinishedProjection=v.InferOutput<typeof TerrorscapeFinishedProjectionSchema>;
export type TerrorscapeProjection=TerrorscapePlayingProjection|TerrorscapeFinishedProjection;
export function terrorscapeProjectionIsConsistent(g:TerrorscapeProjection):boolean {const ids=new Set(g.playerStates.map(p=>p.playerId));return new Set(g.setupReady).size===g.setupReady.length&&g.setupReady.every(id=>ids.has(id))&&ids.size===g.playerStates.length&&ids.has(g.killerPlayerId)&&ids.has(g.privateState.playerId)&&g.owners.every(id=>ids.has(id)&&id!==g.killerPlayerId)&&(g.privateState.role==='KILLER')===(g.privateState.playerId===g.killerPlayerId)&&new Set(g.conditions.map(c=>c.character)).size===3;}
